### ISSUE TITLE
Required Fields

### ISSUE THREAD

**Issue by mpjones84** [PiranhaCMS/piranha.core#1001]
How do we make fields required in the manager?

I've tried the data annotations with no luck.

**Comment by filipjansson** [comment]
Hi @mpjones84!

You can use [Hooks](http://piranhacms.org/docs/application/hooks) to validate fields before save.

Here is a example of how I validated a Version type field.
By throwing a ValidationException in the BeforeSave hook will abort the saving and show a notification for the user.

~~~ csharp
// Validate version input string before saving post
App.Hooks.Posts.RegisterOnBeforeSave(post =>
{
    foreach(var release in ((DynamicPost)post).Regions.Releases)
     {
        if (!release.Version.IsValid)
        {
             throw new ValidationException($"{release.Version.Input} is not a valid version format.");
        }
    }
});
~~~

**Comment by tidyui** [comment]
Like @filipjansson wrote there's no built in support for this using attributes, however it looks like a good suggestion. Will add it as a feature request for future development!

**Comment by mpjones84** [comment]
Thank you both.  I love this product, just re writing a website i did in .net core 2.2 in 3.1 and just wanted to make sure I’m following the correct path.
