### ISSUE TITLE
Placeholder in the User/Edit are not localized

### ISSUE THREAD

**Issue by vjacquet** [PiranhaCMS/piranha.core#1014]
I suppose they are in Swedish :smile:.

![image](https://user-images.githubusercontent.com/6363920/73297235-78fad780-420b-11ea-8511-3ba1e63d34bd.png)

**Comment by tidyui** [comment]
Yes of course.. Swedish which nowadays is considered one of the world languages, you know English, German and **Swedish** 😂

Thanks for noticing!
