### ISSUE TITLE
Roslyn analyzers to detect invalid use of e.g, built-in fields

### ISSUE THREAD

**Issue by mikaellindemann** [PiranhaCMS/piranha.core#1017]
### Suggestion
Instead if having to look up the correct usage of fields, i.e. which are intended to be used as single field regions and not, a set of Roslyn analyzers could be created to warn the developer while developing content types.

### Example
According to documentation, the CheckBoxField is primarily intended for complex regions, so we could create an analyzer that detects when the RegionAttribute is applied to a CheckBoxField property and warn the user that this is not supported (or, as per documentation, that this is not the primary use case).

### Scope
I suggest that the scope of this issue (if wanted) is to set up an analyzer project, and to create analyzers that warn for incorrect use of built-in fields.

Other analyzer suggestions can then be tracked in separate issues.

**Comment by tidyui** [comment]
I think this is a great idea **BUT** this is the kind of feature that neither I or @filipjansson will have the time to support or elaborate on. A feature that is not supported or improved is per definition a bad feature, so in order to add this I would either need you to take responsibility for this and maintain it over a long period of time **or** you can create your own repository with this feature and publish it on NuGet as an add-on package for Piranha.

How do you feel about this?

Regards

**Comment by mikaellindemann** [comment]
Thanks for taking the time to read through the issue.

I would very much like to support the analyzers.

I'm not sure if they should belong in the core repository, but I see a benefit of having the analyzers close to the issues of Piranha itself, as these are typically a great source for improving the developer experience.

Furthermore, if the analyzers are packaged in the same pipeline as Piranha, it is easier to make them a dependency of the core, bringing them to more developers. (As an example, this is how xunit bring their analyzers to testers.)

**Comment by tidyui** [comment]
We could do it the way we've done it in the past, setup a new repository under the PiranhaCMS account, create a new user group, add you to that group and set you as an admin of the repository. This way we keep the project here but not as a part of the core repo.

**Comment by mikaellindemann** [comment]
Sounds good to me :-)

**Comment by tidyui** [comment]
Closing as this has now been moved to its own repository.
