### ISSUE TITLE
No error message on login page when used wrong password or username

### ISSUE THREAD

**Issue by AkulovOleg** [PiranhaCMS/piranha.core#1027]
Hi, guys!
As user i would like to see an error message on login page when i use wrong password or username.
Please can you add this functionality.
Also our team want to help you with your project, because we are interested in it. Can we contribute it?

**Comment by tidyui** [comment]
Yes we'll add this to the upcoming release! We appreciate all the help we can, so just contribute where you feel comfortable. If you want 100% coverage of the manager translations please also feel free to take a look at the translation project here:

https://crowdin.com/project/piranhacms

The login error message will pop up there as well when it's implemented :)¨

Best regards
