### ISSUE TITLE
Querystring on Homepage

### ISSUE THREAD

**Issue by monsieurberry** [PiranhaCMS/piranha.core#1028]
Hi,

We currently run some websites through the CMS and have just gone live.

Everything is going very smoothly and our content-editors love the simplicity of the manager - brilliant stuff!

I've noticed a very minor issue in relation to adding querystring parameters onto the end of the homepage URL. This was spotted as we are using a Facebook tracking pixel on our site which passes through a tracking code in the form of a querystring parameter.

What's happening is the URL is being rewritten with an extra '/' on the end and therefore the tracking code is not getting picked up.

This doesn't seem to happen on any of the other pages we have running through the CMS.

I've tested this with the sample project and the same thing happens there as well with any query string parameter

For example if I add `?foo=bar` onto the end of my url `http://www.mysite.com` it gets rewritten as

`http://www.mysite.com/?foo=bar`

instead of 

`http://www.mysite.com?foo=bar`

Is this intentional or am I missing something on the routing setup?

Thanks again!

**Comment by tidyui** [comment]
Hi there, sorry for the late response!

Piranha doesn't rewrite public URL:s to other public URL:s, i.e there's no code that would rewrite an incoming request for `http://www.mysite.com?foo=bar` to `http://www.mysite.com/?foo=bar`. The only rewriting that is done is when internally rewriting the request to the route that should execute the page type that the requested page has.

Best regards

**Comment by monsieurberry** [comment]
Hi Hakan,

No problem on the late response.

This is exactly what I thought - and I had a look through the source code and couldn't see anything that would be rewriting the URL. It's just really weird that it does this on the sample project as well with the homepage.

It also does this with a sample MVC core project (without Piranha).

I'll keep trying to figure this one out but feel free to close this one out

Thanks

Adam
