### ISSUE TITLE
Can’t save block groups containing generic blocks

### ISSUE THREAD

**Issue by r4g-jon** [PiranhaCMS/piranha.core#1041]
When you create a Custom Block and add a list of child blocks, you cannot save or publish the page.

Here's how to recreate the problem:

**Step 1: Create this block:**

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Piranha.Extend;
using Piranha.Extend.Blocks;
using Piranha.Extend.Fields;

namespace RazorWeb.Models.Blocks
{

    [BlockGroupType(Name = "Custom Block", Category = "ATest", Icon = "fas fa-images")]
    [BlockItemType(Type = typeof(ChildBlock))]
    public class CustomBlockTest : BlockGroup
    {
        [Field]
        public StringField BlockTitle { get; set; }
    }

    [BlockType(Name = "Child Block", Category = "ATest", Icon = "fas fa-quote-right", IsGeneric = true)]
    public class ChildBlock : Block
    {
        /// <summary>
        /// Gets/sets the text body.
        /// </summary>
        [Field]
        public StringField ChildText1 { get; set; }

        [Field]
        public StringField ChildText2 { get; set; }

        public override string GetTitle()
        {
            if (string.IsNullOrEmpty(ChildText1))
                return "Nothing entered";
            else
                return ChildText1 + " " + ChildText2;
        }
    }
}

**Step 2: Register the blocks in Startup.cs:**

In the Configure method in Startup.cs file, register the two blocks as follows:

App.Blocks.Register<CustomBlockTest>();
App.Blocks.Register<ChildBlock>();

**Step 3: Add the custom block to a page**

Login to the Piranha manager and add the new custom block to a page. Try to add a child block to the custom block and then click save or publish, nothing happens.

The error message in the browser says:

TypeError: e.style is undefinedpiranha.min.js:1:6447
    push http://localhost:4000/manager/assets/js/piranha.min.js:1

**Comment by tidyui** [comment]
This is now resolved in `master`. Also another tip, if you add the property `IsUnlisted = true` to the `BlockTypeAttribute` of `ChildBlock` it will only be available for block groups explicitly specifying them with the `BlockItemTypeAttribute`.

**Comment by r4g-jon** [comment]
Thank you @tidyui for looking at this so quickly - really appreciate it!
