### ISSUE TITLE
Getting Started and moving from Kentico

### ISSUE THREAD

**Issue by ecnerwal1234** [PiranhaCMS/piranha.core#1063]
This is not an issue, just looking for advice. Please direct me to a better forum if necessary. 
Anyway, I've been working for a company that uses Kentico for years now. I really like all the features of Kentico but, the cost now is outrageous. 

I'm looking to start my own side business and want to find a CMS to start using. So far, Piranha CMS seems to be the closest product out there that appeals to my needs.  Is there much of a community here? I'd love to see what people or working on and start sharing my own projects. 

Do people here use discord, or reddit or any other group to share on or is this the best place? 

I would also love to see some sites that have been built in Piranha to better see how people are using it.

Thanks, Looking forward to using Piranha!

**Comment by tidyui** [comment]
Hi there @ecnerwal1234 and welcome!

GitHub is mostly used for issues and feature requests, for questions and discussion we have a chat on Gitter that you can find here: 

https://gitter.im/PiranhaCMS/Piranha

Regarding what people are doing with Piranha some people on the chat have shared examples, and I of course have some more "private" knowledge from direct email, but in general I'm as curious as you 😀

We have been thinking for a long time about adding a "Showcase" section on our official homepage where people can contribute and showcase their projects and get a link to their company as well if they'd like. I might just post a message about it in the chat!
