### ISSUE TITLE
Redirect to ReturnUrl after login does not work

### ISSUE THREAD

**Issue by nahojd** [PiranhaCMS/piranha.core#1065]
After login you are always sent to the manager, even if there is a ReturnUrl=/something in the querystring. I found an old issue about this (https://github.com/PiranhaCMS/piranha.core/issues/579), and it seems to have been fixed in version 6.1.

However, the fix seems to have disappeared again in the new manager interface from version 7.0, because ReturnUrl does not work at all. And in Login.cshtml there is no ReturnUrl, nor in Login.cshtml.cs.

**Comment by tidyui** [comment]
Hi this was added for the new manager in 8.1, see issue #1019

**Comment by nahojd** [comment]
I don't see that #1019 solves that problem at all. I don't mean an automatic redirect to a certain place inside the manager, I mean a general redirect to a url specified by the querystring parameter ?ReturnUrl=/some/where.

That's the way login pages usually works, you try to access a resource you are not allowed to access, you get redirected to the login page with the original page in the returnurl parameter, and after a successful login you get redirected back to the resource that you were trying to access in the first place. 

And that exact problem seems to have been solved in https://github.com/PiranhaCMS/piranha.core/commit/ffc3997fde17526bd546a1dd1f23898080bfb9cd , but since that part was re-written for 7.0, the functionality is gone. Now, even if you have ?ReturnUrl=/somepage you always end up in the manager.

**Comment by tidyui** [comment]
Hi, you’re right! I misread the issue!
