### ISSUE TITLE
Application/Manager specific model hooks

### ISSUE THREAD

**Issue by goranhell** [PiranhaCMS/piranha.core#1070]
If I have a hook for Page.OnLoad, can I determine if I'm in the manager?
The task for the hook shall not be perfomed while editing.

**Comment by tidyui** [comment]
Not at them moment since hooks are called from the core services!

**Comment by tidyui** [comment]
To give some more info, the standard hooks can not be aware from where they are loaded. We could possible add hooks to the `IModelLoader` which is only used in the client application **and** the manager services loading the models for the manager interface.

**Comment by goranhell** [comment]
I understand. I've solved my case differently. Need to figure out when OnLoad hook can be useful.

**Comment by tidyui** [comment]
Closed in favor of #1767
