### ISSUE TITLE
assets files not available

### ISSUE THREAD

**Issue by ecnerwal1234** [PiranhaCMS/piranha.core#1071]
I'm working on making a custom block and have created the script file and added this

App.Modules.Manager()
        .Scripts.Add("~/assets/js/myscripts.js");

It shows in the admin source code, but the file doesn't seem to be there.

**Comment by ecnerwal1234** [comment]
I just moved it to the wwwroot folder instead.

**Comment by tidyui** [comment]
Hi! Yes all assets referenced from the browser should be inside the wwwroot folder!

Regards
