### ISSUE TITLE
NuGet packages for patch releases

### ISSUE THREAD

**Issue by tfritzke** [PiranhaCMS/piranha.core#1073]
Packages are not available on NuGet for the latest patch release (i.e.: 8.1.1).
Please add this into the release workflow.

**Comment by tidyui** [comment]
When we release a service release (or patch) we do not label it 8.1.1 for example, we label it Service Release X. We clearly specify which packages are affected and only these packages are released.

If you take a look at NuGet all data packages (Piranha.Data...) are available in 8.1.2 but the rest of the packages are 8.1.0

Regards

**Comment by tfritzke** [comment]
Thanks!
