### ISSUE TITLE
Customize Login page and forgot password

### ISSUE THREAD

**Issue by traustitj** [PiranhaCMS/piranha.core#1078]
Is there a way to costumize the login page ?
How does a user handle forgot password ?

**Comment by tidyui** [comment]
Hi there! The manager login-page is not by any means intended to be used as login-page for your web-application, only the manager interface. If you're still looking to customize it you can register custom stylesheets for the manager which will be applied after the standard look-n-feel. You can read more about this here:

http://piranhacms.org/docs/manager-extensions/resources

Best regards
