### ISSUE TITLE
Alternate urls and hreflang

### ISSUE THREAD

**Issue by vjacquet** [PiranhaCMS/piranha.core#1079]
Hi,

I am using the multi-tenant capabilities of Piranha to create a site with localized versions.
I'd like to link the pages to their alternate versions in the other sites.

Is there some properties to help me do that or should I add a field in every page type?

Regards

**Comment by tidyui** [comment]
Hi! There's no specific property for handling this, I suggest creating a base class with a `PageField` or a collection or `PageField` regions depending on how your site structure looks.

Best regards
