### ISSUE TITLE
Can't login into the manager after `dotnet new piranha.web`, keep redirecting to the login page

### ISSUE THREAD

**Issue by ramon-mendes** [PiranhaCMS/piranha.core#1080]
I installed a fresh template with `dotnet new piranha.web`, then I went to `localhost:54444/manager` and inputed `admin` and `password`. It accepts login but redirects me to the login page again:
![image](https://user-images.githubusercontent.com/44581176/75810441-5bb8ac00-5d69-11ea-9913-33f87db174c7.png)

**Comment by tidyui** [comment]
We recommend you to close your web browser completely and start over. Since you’re not getting an error message it’s most likely because you have a stray cookie in your browser from something else on localhost.

Regards

**Comment by ramon-mendes** [comment]
Worked! Thanks
