### ISSUE TITLE
Thumbnails not working

### ISSUE THREAD

**Issue by callebergqvist** [PiranhaCMS/piranha.core#1081]
I have a problem with thumbnails not showing up in the Media library.

`<img src="/manager/api/media/url/04ef56b8-2fcb-4fbe-988b-9674ae7ffcbe/210/160" class="thumbnail-image">`

What I'm I missing or doing wrong?
![thumbnails_failing](https://user-images.githubusercontent.com/34142028/75971025-79a12080-5ed1-11ea-8310-06b2ebf6b3d2.JPG)

**Comment by tidyui** [comment]
Do you get a 500 for all image types? And can you look at the server logs, because a 500 indicates that something goes wrong when resizing the image.

Regards

**Comment by callebergqvist** [comment]
Thanks for quick response! Was trying to find the root cause for quite some time but I ended up setting up a new solution with a fresh DB. Now it works!
