### ISSUE TITLE
Renaming display name of SysAdmin role breaks things

### ISSUE THREAD

**Issue by NogginBox** [PiranhaCMS/piranha.core#1091]
In the admin interface I was allowed to rename the SysAdmin display name. When I did this (for no good reason) I got the following error on several pages:

`SqlException: Cannot insert duplicate key row in object 'dbo.Piranha_Roles' with unique index 'RoleNameIndex'. The duplicate key value is (SYSADMIN).`

I was able to fix by changing the display name back in the database. I was pointed by @tidyui at this code being the issue:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore.Identity/Db.cs#L93

And the following suggestion was made:

> What did you change on the role, the display name? Maybe we could lock down the manager interface so that only certain fields can be changed for this role and that it can't be deleted? And the query in the code above could look at normalized name instead of name.

**Comment by tidyui** [comment]
Another option could be to only seed the default role if there’s no roles available in the database.
