### ISSUE TITLE
Improve manager error messages

### ISSUE THREAD

**Issue by Netclick19** [PiranhaCMS/piranha.core#1095]
I got Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Information: Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ValidationProblemDetails'.

For example this happens if I write 0.5 in a numberfield. There is an error during the validation input but to the manager interface doesn't receive any message error.

Is it possibile to improve the message info for the content editor?

**Comment by tophermurphy** [comment]
Having the same issue with the NumberField. It looks like a Vue issue e.style is undefined is appearing in the web console.

**Comment by tidyui** [comment]
Closing as it's too unspecific. New issues should be opened for respective part that needs improvement.
