### ISSUE TITLE
Markdown and Blog-Template?

### ISSUE THREAD

**Issue by DNF-SaS** [PiranhaCMS/piranha.core#1096]
Hi,
I'm very new to PiranhaCMS - looks really cool! :-)
For content-writing, Markdown is IMO very easy, I use it whenever it's possible.
Unfortunately, Piranha's Blog-Template uses Tiny for editing.
Now my question: is it possible to "switch" to Markdown?

Thanks
Sascha

**Comment by tidyui** [comment]
Hi there! The default post in the blog template uses `Blocks` as it's main content area, blocks are intended for non technical people and for that reason we haven't included a Markdown block. However if you like to just write your posts in Markdown I'd change the included post model to this:

~~~csharp
[PostType(Title = "Blog post", UseBlocks = false)]
public class BlogPost : Post<BlogPost>
{
    [Region(Title = "Main content")]
    public MarkdownField Body { get; set; }

    [Region]
    public Regions.Hero Hero { get; set; }
}
~~~

This will **disable** the block based content area and instead add a new Markdown based body to your posts.

Best regards

Håkan

**Comment by DNF-SaS** [comment]
Hi Håkan,

thanks for the superfast reply! :-)
Looks good so far.
Additionally, I've replaced @Html.DisplayFor(m => m.Blocks) with @this.Html.Raw(this.Model.Body.ToHtml())
Looks good so far, thanks! 👍
