### ISSUE TITLE
Gulpfile.js failed to load after upgrade to Visual Studio 16.5

### ISSUE THREAD

**Issue by vjacquet** [PiranhaCMS/piranha.core#1098]
The error is "ReferenceError: primordials is not defined".

The reason is that Visual studio installs node version v12.13.1 (prior version was v10.16.3), which is not compatible with gulp 3.9.

You can find more on the subject at 
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node/58394828

**Comment by j2ba** [comment]
Just encountered this too. You can get tasks running by updating gulp and gulp-sass to "^4.0.2" in core\Piranha.Manager, core\Piranha.Manager.Summernote, examples\MvcWeb (if using), and examples\RazorWeb (if using). 

Piranha.Manager and Piranha.Manager.Summernote's gulp.js files need a couple tweaks as well. If you are held up, you can reference the commit in my fork here https://github.com/j2ba/piranha.core/commit/3a2b42e7b00958a71c856c9cd4e689c5cc54cd7c. After that you can just build the solution as normal and the tasks will run. RazorWeb and MvcWeb are not bound to any build events so they need to be run manually if applicable.

**Comment by vjacquet** [comment]
Thanks, it helped a lot.
I also had to reorder the location of the external tools to get it to work https://stackoverflow.com/a/41454385

**Comment by tidyui** [comment]
Anyone interested in sending a PR for this?
