### ISSUE TITLE
Question: Why are you not following Microsoft Design Guidelines?

### ISSUE THREAD

**Issue by jgauffin** [PiranhaCMS/piranha.core#110]
I'm thinking about helping out a bit. However, I'm used to code using the standard [Microsoft Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/).

Why do you put the start brace on the same line? 

Another thing that I wonder about is why you don't minimize the amount of branches by exiting if statements early instead of using if/else?

Current:
```csharp
private T Load<T>(Page page) where T : Models.Page<T> {
    var type = api.PageTypes.GetById(page.PageTypeId);

    if (type != null) {
            // a lot of code
        return model;
       }
      return null;
}
```

imho easier to follow:

```csharp
private T Load<T>(Page page) where T : Models.Page<T> 
{
    var type = api.PageTypes.GetById(page.PageTypeId);
    if (type == null) 
	   return null;

	// a lot of code
    return model;
}    
```
In that way you don't have to scan whole methods to find early exists (i.e. not following the main path)

**Comment by tidyui** [comment]
Oh how one could wish that 2017 was the year that this kind of discussion would no longer exist! 

First of I started with C/C++ on UNIX/Solaris back in the days when MS still used their Hungarian notation (oh the horror) and the formatting standard I use is the one I was taught. Secondly I **totally** disagree with **everything** you wrote in your comment. Every line of code you suggested I find harder to follow.

**BUT** I will not judge you by your formatting and I trust you will do the same to me :)

However, if you send a **PR** with that formatting I **will** re-format every single line before accepting it ;)

Regards

Håkan

**Comment by jgauffin** [comment]
I too started with C++ and Hungarian notation 20 years ago. 

But I adopt my style according to the programming language and the design guidelines that exists for the language. Thus I adopt my style depending on if I code Javascript, Go or C#.
