### ISSUE TITLE
Is there the multitenant support?

### ISSUE THREAD

**Issue by biapar** [PiranhaCMS/piranha.core#1101]
Is there the multitenant support?

**Comment by goranhell** [comment]
http://piranhacms.org/docs/tutorials/how-to-use-multitenancy

**Comment by tidyui** [comment]
As @goranhell shows in his tutorial it depends on **how** you're going to use it. Piranha CMS does not have "true" multi tenant support but it supports multiple sites in the same application, which in the end is what many people use multi tenant for.
