### ISSUE TITLE
How to apply migrations in a Azure DevOps pipeline?

### ISSUE THREAD

**Issue by muffadalis** [PiranhaCMS/piranha.core#1106]
My understanding is the currently the migrations are applied at runtime. I would like to apply the migrations as per of my deployment pipeline. Is my understanding correct? If yes, Is there a way to achieve this?

Thanks.

**Comment by tidyui** [comment]
Yes you are correct, the migrations are applied the first time the `DbContext` is created. You could perform the operation in your pipeline by adding the `Design` package to your project with:

    dotnet add package Microsoft.EntityFrameworkCore.Design

and the execute the following in your application directory.

    dotnet ef database update --context Piranha.Data.EF.SQLite.SQLiteDb

Please note that the parameter `--context` needs to be replaced to the actual database package you're using in production.

**Comment by muffadalis** [comment]
Thanks for the prompt response.
