### ISSUE TITLE
Problem when using Postgres Database

### ISSUE THREAD

**Issue by jjferreira** [PiranhaCMS/piranha.core#1108]
Good morning, I wanted to use postgres as my database but on the the seed process it complained about 2 fields not being there

**Excerpt**
and
**PrimaryImageId**

This seems to be around the table Piranha_Posts.

Thank you

**Comment by tidyui** [comment]
Hi. These fields are only available in the `master` branch, which is our development branch. The simple answer to you problem is that we only created migrations for `SQLite` at this point since this is what we use for development.

Best regards
