### ISSUE TITLE
anonymous access to site pages - Using my own custom Identity Service

### ISSUE THREAD

**Issue by singhalak** [PiranhaCMS/piranha.core#1111]
I am new user of Piranha CMS. Able to integrate the CMS with the existing website. However I am having issue with the default behavior of CMS. My regular web pages have anonymous access but CMS is forcing the user to login. Is there setting for anonymous access to the published CMS pages?

My existing pages works fine; however for any page related to CMS, the system is forcing me login. 

Alternate option -- Is there a option to point CMS to Specific folder which I can set up to have anonymous access?

**Comment by tidyui** [comment]
Hi there! That's very interesting, none of the templates we provide in the package `piranha.core.templates` has any kind authorization on them except if you explicitly specify that the users should be logged in when creating them.

The manager interface uses authorization to make sure the user should have access to managing the data. The only thing I can think of is if your web application has default security enabled for **all pages** and you have added the `AllowAnonymousAttribute` to your Pages/Controllers. If this is the case you probably need to add this to the Pages/Controllers that handles the CMS-pages as well.

Best regards

**Comment by singhalak** [comment]
Thanks for quick response. You are right, I have setup an Authorization required for MVC. I guess I can remove it to enable anonymous access.

**Comment by tidyui** [comment]
**Or** you can just add the `AllowAnonymousAttribute` to the pages/controllers that handles data from Piranha. If you add permissions on certain pages in the manager this will result in an `UnauthorizedException` anyway when loading the content **if** you using the `IModelLoader` service so you can handle this manually.
