### ISSUE TITLE
SEED procedure not correctly inserting user data with Identity/SQL Server

### ISSUE THREAD

**Issue by LeadMagnet** [PiranhaCMS/piranha.core#1115]
If I create a new project using the "dotnet new" statements on the main page, the user credentials are inserted into the SQLLite (default) database and I can log into the manager.

Create another project, this time omitting the "dotnet run" command. Then following the documentation change the config/code to use SQL Server and Identity(with seed). Compile the project and run (in VS).

The database is correctly populated with objects. The data to display the default pages is inserted. All dbo.Piranha_User* tables are blank.

Going to the manager page, using "admin / password" gets an "incorrect username/password" error message. Which (of course) happens because these tables are empty.

I've tried to find the "seed" procedure that inserts SQL Server data so I can manually run it, but I cannot find it.

Can you please post the SQL INSERT commands I need to successfully log in?

**Comment by tidyui** [comment]
Hi again @LeadMagnet! @filipjansson just tried the following

* Installed the latest templates (`piranha.templates`)
* Created a new project with `dotnet new piranha.blog`
* Switched packages for the core Db **and** Identity Db to SQL Server
* Switched both connection settings in `Startup.cs`
* Started the application which successfully seeded the database with the default user

We're at a loss here on how to proceed, we're having a hard time recreating your issue.

Regards

**Comment by LeadMagnet** [comment]
whatever version is pulled using "dotnet new piranha.blog.razor"

**Comment by tidyui** [comment]
@LeadMagnet The version used when creating a new project is dependent on the version you have installed of the templates!

**Comment by LeadMagnet** [comment]
OK....well whatever version is installed running "dotnet new -i Piranha.Templates" moments before

**Comment by LeadMagnet** [comment]
Not sure if it matters...but the dev env is:

Windows 10 Enterprise (1809)
Visual Studio 2019 (16.5.3)
SQL Server 2019 (15.0.2070.41)
Windows Server 2019 (1809) IIS v10.0.17763.1

**Comment by tidyui** [comment]
We have tried it with `piranha.blog.razor` as well not without any issues. Maybe we should share our project somewhere for you to look at.

**Comment by filipjansson** [comment]
This is my project file after running `dotnet new piranha.blog.razor` and making the necessary changes changes to use SQL Server.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Piranha" Version="8.1.0" />
    <PackageReference Include="Piranha.AspNetCore" Version="8.1.0" />
    <PackageReference Include="Piranha.AspNetCore.Identity.SQLServer" Version="8.1.0" />
    <PackageReference Include="Piranha.AttributeBuilder" Version="8.1.0" />
    <PackageReference Include="Piranha.Data.EF.SQLServer" Version="8.1.2" />
    <PackageReference Include="Piranha.ImageSharp" Version="8.1.0-rc1" />
    <PackageReference Include="Piranha.Local.FileStorage" Version="8.1.0" />
    <PackageReference Include="Piranha.Manager" Version="8.1.0" />
    <PackageReference Include="Piranha.Manager.TinyMCE" Version="8.1.0" />
  </ItemGroup>

</Project>
```

And updating the startup to use SQL Server

```
using Piranha.AspNetCore.Identity.SQLServer;
using Piranha.Data.EF.SQLServer;
...
services.AddPiranha(options =>
{
    options.AddRazorRuntimeCompilation = true;
    options.UseFileStorage();
    options.UseImageSharp();
    options.UseManager();
    options.UseTinyMCE();
    options.UseMemoryCache();
    options.UseEF<SQLServerDb>(db =>
        db.UseSqlServer(Configuration.GetConnectionString("piranha")));
    options.UseIdentityWithSeed<IdentitySQLServerDb>(db =>
        db.UseSqlServer(Configuration.GetConnectionString("piranha")));
});
```

**Comment by LeadMagnet** [comment]
My project file is identical to yours. 

Your Startup.cs fixed it! User data now getting populated. Thanks!

So the process I followed...

- Open VS...open nuget console...change target to solutions folder

- run dotnet new -i Piranha.Templates

- run dotnet new piranha.blog.razor

- dotnet restore

- open project in VS...open nuget console

- run install-package Piranha.AspNetCore.Identity.SQLServer

- modify Startup.cs to include services.AddPiranhaIdentityWithSeed<IdentitySQLServerDb>(options => ...)

- add "Default Identity Options" from website to above

- run install-package Microsoft.EntityFrameworkCore.SqlServer

- run install-package Piranha.Data.EF.SQLServer

- modify Startup.cs to include options.UseEF<SQLServerDb>(db => db.UseSqlServer(Configuration.GetConnectionString("piranha")));

- modify appsettings.json for SQL Server connection string

- save an compile site.....run (F5)

I used the website "services.AddPiranhaIdentityWithSeed" example instead of including it into the "options.UseIdentityWithSeed" of the existing call.

It's all working now. Thanks a bunch for the help and time.
