### ISSUE TITLE
How is good Piranha as a base of a web tracking application?

### ISSUE THREAD

**Issue by biapar** [PiranhaCMS/piranha.core#1116]
How is good Piranha as a base of a web tracking application?

**Comment by tidyui** [comment]
Hi there @biapar! Piranha is a good fit for any application where you need to work with structured templated data and need to have full control over the application. As Piranha is a fully decoupled CMS there's no restrictions on the application you build on top of it.

Regards

**Comment by biapar** [comment]
Is there a showcase?
