### ISSUE TITLE
Save ImageBlock error

### ISSUE THREAD

**Issue by futsystems** [PiranhaCMS/piranha.core#1117]
Piranha CMS is a great project, we are planing to use it for our blog system.

When we save an ImageBlock in page or post,  there is an error from Json

{"errors":{"blocks[1].model.body.media.properties":["Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.IDictionary`2[System.String,System.String]' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\r\nPath 'blocks[1].model.body.media.properties', line 1, position 1238."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|da6c8724-499ab94159c29f4e."}

i have check it, because the data from  manager/api/media/list  can not be deserialized into  Piranha.Models.Media.

Property1
size,:"xxxx kb" can not convert to size int64
Property2
properties:[] can not convert to dictonary

so please check these error.

**Comment by futsystems** [comment]
the code is from master branch

**Comment by i-love-code** [comment]
The code in the master branch is not representative of the published version of Piranha.  I would suggest using the versioned release branches, or the versions published on Nuget/available through "dotnet new" templates.

**Comment by tidyui** [comment]
Like @i-love-code wrote master is our development branch, nevertheless thanks for pointing out this issue @futsystems! We’ll take a look at it!

Regards

**Comment by eric-wilson** [comment]
I ran into the same issue today while evaluating the product.  The media.size is getting set to a pretty format e.g. 10 KB, but the server-side model needs it as a long and it blows up during evaluation before executing the controller's endpoint.

**Comment by eric-wilson** [comment]
@tidyui - FYI - I hacked a fix in my local build by splitting out a Size and a SizeFormatted in the ViewModel for the MediaListModel.  That fixes the Property1 error reported above.  

The other one has properties = [] that's trying to deserialize back into List<KeyValue<string, string>>.  The quickest hack on my side was to check the count and add null instead of the list.  I don't know the circumstances of how this gets populated, I only know it works when no properties are returned.

`Properties =(m.Properties.Count > 0) ? m.Properties.ToArray().OrderBy(p => p.Key).ToList() : null,`

**Comment by tidyui** [comment]
So I checked and the error is not present in the latest released version `8.2`. We'll try to locate the commit that has changed the behavior.

**Comment by tidyui** [comment]
Thank you for your detailed descriptions. A property accessor for set had changed from `internal` to `public` which cased media object to be deserialized and bound when it wasn't supposed to.
