### ISSUE TITLE
anonymous form submission

### ISSUE THREAD

**Issue by ksahmed** [PiranhaCMS/piranha.core#1122]
when i try to submit the form anonymously to  controller action.. i get the error that authentication token is expired, in pipleline.. I copied the cms controller and added  this action in it.. i dont need to authenticate i this case . how do i get out of this?

here is my action 
 [Route("contactus")]
        [HttpPost]
        public async Task<IActionResult> ContactPage(ContactPage model)
        {
            if (string.IsNullOrEmpty(model.Data.Email) || string.IsNullOrEmpty(model.Data.Name) || string.IsNullOrEmpty(model.Data.Message))
            {
                //send email
                ViewBag.ErrorMessage = "Please fill the form";
                return View(model);
            }

Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[7]
      Identity.Application was not authenticated. Failure message: Ticket expired

**Comment by tidyui** [comment]
Hi there! I don’t really know where that error is coming from unless you’ve maybe configured you application to demand authorization by default in which case you probably need to add an AllowAnonymous attribute to your action.

There’s no built in stuff in Piranha that requires the user to be authenticated in order to perform a post. For example, take a look at this article on how you can add a custom login page to your application.

https://piranhacms.org/docs/tutorials/securing-pages

Regards

**Comment by ksahmed** [comment]
i have added allow anonymous. but still getting the same problem.  this is my configureservices() 

 // Service setup
            services.AddPiranha(options =>
            {
                options.UseFileStorage();
                options.UseImageSharp();
                options.UseManager();
                options.UseTinyMCE();
                options.UseMemoryCache();
                options.UseEF<SQLiteDb>(db =>
                    db.UseSqlite(Configuration.GetConnectionString("piranha")));
                options.UseIdentityWithSeed<IdentitySQLiteDb>(db =>
                    db.UseSqlite(Configuration.GetConnectionString("piranha")));
            });

**Comment by tidyui** [comment]
Hi there. You closed the error, did you manage to resolve your issue?

**Comment by ksahmed** [comment]
yes - i added wrong route in ppost action.. hence i was getting 404
but .. the log in piranha shows ticketexxpired on everycall  to all actions in every controller .. i dont know why ....
but its solved
