### ISSUE TITLE
Need option to Remove GUID from file name in media uploads to Azure Blob Storage

### ISSUE THREAD

**Issue by topanoe** [PiranhaCMS/piranha.core#1124]
Media filenames uploaded to Azure Blob Storage are prepended with GUID.  Using [this answer](https://stackoverflow.com/a/56057920/2207699) from StackOverflow as a suggestion, would it be possible to have an option added to remove the GUID?

**Comment by tidyui** [comment]
As long as there’s another way to ensure uniqueness of the path. Maybe media could be put in a Guid based folder?

**Comment by tidyui** [comment]
Also you have to be aware of that if you would change provider the old files wouldn't be found. The reason for this is that path is not saved in the database, it is resolved by the storage provider.

**Comment by tidyui** [comment]
This needs some modifications in the storage API, we'll add this for a future release!
