### ISSUE TITLE
How to use the correct layout for a manager extension

### ISSUE THREAD

**Issue by ramon-mendes** [PiranhaCMS/piranha.core#1125]
I have followed [this tutorial](https://piranhacms.org/docs/manager-extensions/menu) to add a manager extension, and the icon did appeared correctly:
![image](https://user-images.githubusercontent.com/44581176/80289262-ee474d00-8713-11ea-90e5-ba885ad131bb.png)
When I click the link, it does correctly hits the correct action/route:
![image](https://user-images.githubusercontent.com/44581176/80289316-159e1a00-8714-11ea-918a-d0590bb9d9b1.png)
Problem is, the rendered view has the layout of the site, and NOT the layout of the manager:
![image](https://user-images.githubusercontent.com/44581176/80289375-61e95a00-8714-11ea-9f23-076811e041cf.png)

Maybe I should change the layout in the .cshtml file?
![image](https://user-images.githubusercontent.com/44581176/80289415-abd24000-8714-11ea-8836-d0030982449b.png)

**Comment by tidyui** [comment]
Hi there! You need to add the controller to the “Manager” area for it to render in the correct context!

Best regards

**Comment by ramon-mendes** [comment]
I've your suggestion:
![image](https://user-images.githubusercontent.com/44581176/80294548-52800600-8740-11ea-90df-5ccf976fa26e.png)

Now I get the following error:
![image](https://user-images.githubusercontent.com/44581176/80294558-675c9980-8740-11ea-9df0-6d2f5753d638.png)

Seems the layout being used is wrong... how can I fix that?

**Comment by tidyui** [comment]
If my memory serves me correct you need to add it to the area “Manager”, not “manager”. 

Regards

**Comment by ramon-mendes** [comment]
I tried that, still the same problem...
![image](https://user-images.githubusercontent.com/44581176/80297628-389fec80-875b-11ea-82f9-6400ad00975b.png)

Pretty strange this ??? in the error message

**Comment by tidyui** [comment]
Sorry, I missed one of you initial screenshots. For some reason you have explicitly specified that the Layout **shoud** be "???". Please removed the following line from your view:

    Layout = "???";

Regards

**Comment by ramon-mendes** [comment]
It worked! Thanks
