### ISSUE TITLE
Simple question: how to set the manager language / idiom?

### ISSUE THREAD

**Issue by ramon-mendes** [PiranhaCMS/piranha.core#1129]
How do I set the manager's language?
I have completed the translations at https://crowdin.com/project/piranhacms/pt-BR
Now, how do I set the manager language to Portuguese?

**Comment by ramon-mendes** [comment]
I tried setting the locale through:

```
var cultureInfo = new System.Globalization.CultureInfo("pt-br");
System.Globalization.CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
System.Globalization.CultureInfo.
```

But manager is still in English

**Comment by tidyui** [comment]
If you're using the NuGet-packages the latest translation contributions has not yet been published. I can try to get a new version up for `8.1` today.

**Comment by ramon-mendes** [comment]
You mean, an updated v8.1 with the translation? That would be sweet...

**Comment by tidyui** [comment]
New package is now available at https://www.nuget.org/packages/Piranha.Manager.Localization/

**Comment by arash2021Pro** [comment]
would you please tell me how to use Piranha.Manager.Localization package ? I'm poking around for something to set it up but i can not get hold of anything to use as a documetation
