### ISSUE TITLE
can piranha handle a around 200 sites similar to square space?

### ISSUE THREAD

**Issue by ksahmed** [PiranhaCMS/piranha.core#1131]
considering we have good number of resources, is piranha  ready for multitenancy ?

**Comment by tidyui** [comment]
The current version of Piranha is **not** multi-tenant, it is only multi-site, i.e all users have access to all sites and resources.

**Comment by ksahmed** [comment]
is there any plan to make it multitenant , soon ?

**Comment by biapar** [comment]
+1

**Comment by tidyui** [comment]
We’re looking at a new updated and more flexible content structure. One of the features we’re looking at is true multi-tenant support. This will however not be released until one of the upcoming major releases as it will not be backwards compatible and will require data migration.

Regards

**Comment by biapar** [comment]
You can think a branch multi-tenant only.

**Comment by tidyui** [comment]
@biapar Elaborate, I don’t quite get what you mean.

**Comment by biapar** [comment]
Sorry...I read again what you wrote and I understand that maybe in the next major release will be multi tenant.

**Comment by ksahmed** [comment]
this multitenancy can really open up new horizons for piranha. i assume it will be released later this year ..

**Comment by biapar** [comment]
I think yes...but also if will be more plugins ( like small ecommerce, etc ).

**Comment by tidyui** [comment]
As I wrote we are still evaluating multi-tenancy, so I can't give any promises on **if** or **when** this would be included. If full multi-tenancy is a demand for the application you're currently building I would have to recommend you to investigate other options than Piranha that might support this out-of-the-box.

Best regards

**Comment by r4g-jon** [comment]
If you do decide to add full multi-tenancy, it would be good if this was an option.

At the moment, we host several sites on a single Piranha instance and they all share the same pages, blocks and images. This really suits us having this.

**Comment by tidyui** [comment]
To follow up on what @r4g-jon wrote. Piranha has never been intended to be a multi-tenant framework. It is a single tenant cms where that tenant can administrate one or more sites. These sites can be completely different sites, or different language versions of the same site.

Changing focus into multi-tenancy breaks compatibility and also changes the core usage of the framework. Nevertheless we’re still evaluating it like we evaluate lots of things for the future 😁

**Comment by ksahmed** [comment]
good discussion .. thanks guys
