### ISSUE TITLE
Are reusable blocks available in v8.x?  

### ISSUE THREAD

**Issue by eric-wilson** [PiranhaCMS/piranha.core#1143]
Version 6 mentions reusable blocks.  I can't seem to find/ figure it out in v8.x. Is it available? Thanks!

**Comment by tidyui** [comment]
This issue has been moved around and is still open (#290). When the original block-features were implemented we had a completely different manager interface which didn't really support the modularity we needed to build it in the way we wanted.

At this stage we're looking at the "problem" in much more broader perspective, see issues #1114 & #467 where we're discussing features that could be added on top of Piranha to give it more of the features set of a classic "integrated CMS".

**Comment by tidyui** [comment]
You are more than welcome to join in on the discussion in #1114 and contribute with your thoughts!

Best regards
