### ISSUE TITLE
Finer control on which users can edit which pages in manager

### ISSUE THREAD

**Issue by adautev** [PiranhaCMS/piranha.core#1145]
Hello, 
I need to implement a fine grained control for pages in the manager, such as a group of users that belong to an organization can edit only their own pages. 
I will implement it myself, but I was wondering if there is a guideline for it, or maybe a ready way I have ommited.

**Comment by tidyui** [comment]
Hi there @adautev! As Piranha isn't a multi-tenant platform we don't have any such features available, there's only access control on function level, not entity level.

**Comment by adautev** [comment]
Thanks for the prompt response!
