### ISSUE TITLE
null reference exception on live

### ISSUE THREAD

**Issue by ksahmed** [PiranhaCMS/piranha.core#1146]
so i have my layout page like this 
   @if (WebApp.CurrentPage.TypeId == "StartPage")
    {
        <link rel="stylesheet" href="~/revolution/css/settings.css">
}
it works well locally.. but when  publish on live, it gives null reference exception 
at http://dt1.lwp.hostinguk.org/

i have tried setting and unsetting hostname field forthe site to 
dt1.lwp.hostinguk.org

any idea why ?

**Comment by tidyui** [comment]
Hi there! First, you don’t need to set hostname if you only have one site **or** it’s the default site.

Secondly, the only thing that can cause a null reference exception is if CurrentPage is null. What page/post are you navigating to?

Last, could you include a full stack trace with your error.

Best regards

**Comment by ksahmed** [comment]
if you go here http://dt1.lwp.hostinguk.org/ , you will have stack trace
im checking home page... but it seems to be going to setup controller. dont know why

**Comment by ksahmed** [comment]
crap// its now working.. dont know what has happened between all this time..
