### ISSUE TITLE
Possible Routing Issue

### ISSUE THREAD

**Issue by eric-wilson** [PiranhaCMS/piranha.core#1148]
I'm writing a customizable module for error handling and routing e.g. 404 errors, etc.  I was running into an issue where the page kept blowing up.  

The main issue is with the querystring manipulation in the IntegratedMiddleware.cs

`query.Append("id=");` <- in the IntegratedMiddleware.cs file

Under this use case, when a 404 is detected, I'm trapping it and sending it to a page that I've configured in the CMS tool.  e.g. /errors/404 as a StandardPage type.

When I trap it and push it back into the middleware;  the querystring is already populated from the previous request and the new routing page /errors/404 which is found in the CMS tool as `page` adds the `id` to the current local string builder (which is fine), however the last section of the IntegratedMiddleware will detect a current (but now invalid) query string and append it.

Resulting in something like ?id={guid}&id={guid}...  <- this appears to be the main issue, which makes the page blow up.

```csharp
if (context.Request.QueryString.HasValue)
{
context.Request.QueryString =
new QueryString(context.Request.QueryString.Value + "&" + strQuery);
}
else {
    context.Request.QueryString = new QueryString("?" + strQuery);
}
```

The short term fix is to do this in my ErrorMiddleware before pushing it back into the pipeline
`ctx.Request.QueryString = new QueryString("");`

I'm not sure if this the best long term approach or if the IntegratedMiddle should swap out the duplicated query string params.  To me, it would make sense to replace them (if dups are found).

Full ErrorHandlerExample:

```csharp
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Piranha;

namespace GeekCafe.Piranha.ErrorRouting
{
    public static class ErrorRoutingExtensionMethods
    {
        public static IServiceCollection AddGeekCafeErrorRouting(this IServiceCollection services)
        {
            App.Modules.Register<Module>();

            return services;
        }

        public static IApplicationBuilder UseGeekCafeErrorRouting(this IApplicationBuilder builder)
        {            

            builder.Use(async (ctx, next) =>
            {
                // send the request up the chain
                try
                {
                    await next();

                    // catch the error
                    if (ctx.Response.StatusCode == 404 && !ctx.Response.HasStarted)
                    {

                        
                        string originalPath = ctx.Request.Path.Value;
                        ctx.Items["originalPath"] = originalPath;


                        // todo hit the db for custom settings

                        if (originalPath.StartsWith("/manager/"))
                        {                            
                            ctx.Request.Path = "/manager/errors/404";
                        }
                        else
                        {
                            ctx.Request.Path = "/error/404";

                        }

                        // you must clear this out or there will be issues
                        // if the "id" is there it will create a bunch of problems
                        ctx.Request.QueryString = new QueryString("");

                        // push it back into the middleware
                        // Re-execute the request so the user gets the error page
                        await next();
                        
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            });

            return builder;
        }
    }
}

```

**Comment by filipjansson** [comment]
Hi!

I have an alternative solution using Microsoft own [StatusCodePages ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.statuscodepagesextensions?view=aspnetcore-3.1)middleware.
Looking at your custom middleware i think the method `UseStatusCodePagesWithReExecute` would be the corresponding approach.

We will register the middleware with the `UseStatusCodePagesWithReExecute` so the URL will stay the same. On error the middleware will redirect to our action in our `CmsController`, if we then find an error page with machting slug we use that, else we keep returning the status code to the client.

_Startup.cs_
```csharp
app.UseStatusCodePagesWithReExecute("/Error", "?statusCode={0}");

app.UsePiranha(options => {
    options.UseManager();
    options.UseTinyMCE();
    options.UseIdentity();
});
```

_CmsController.cs_
```csharp
[Route("error")]
public async Task<IActionResult> Error(int statusCode)
{
    var model = await _api.Pages.GetBySlugAsync<Models.StandardPage>(statusCode.ToString());
    if (model != null)
        return View(model);
    else
        return StatusCode(statusCode);
}
```

BR
Filip

**Comment by eric-wilson** [comment]
@filipjansson thanks, I'll test that out but it might be a bit limiting for the end product/module.

**Comment by tidyui** [comment]
@eric-wilson In your use-case I don't think it's a bad thing that you're resetting the query-string since you are actually re-executing the entire middleware pipeline. There's nothing saying that you might add other third-party middleware later that could affect the query-string and then you might want to reset it anyway before starting over.

Personally I prefer to redirect to the error-page when hitting a `404` as I don't like to present valid content on every URL of the site. In my opinion it's better to tell the web browser that the requested URL wasn't found and then redirect the user to a visual error page.

Best regards

**Comment by eric-wilson** [comment]
@tidyui - Ok, cool and good to know.

Yeah, I've had clients on e-commerce sites that prefer specific 404 pages for users under different content sections, which is what I'm basing this idea off of.

For SEO it will still send the correct 404 response.  But for the user, I can tailor it any way they want.

![Screen Shot 2020-05-07 at 2 41 24 PM](https://user-images.githubusercontent.com/3632968/81332629-61848380-9071-11ea-967c-a1db03e62cd8.png)

Ignore the other 404 errors, I'm messing around with injecting blazer into the manager section for my UI pieces.  If I can't get that to work then I'll learn vue 😁
