### ISSUE TITLE
Page Metadata

### ISSUE THREAD

**Issue by CSorel-Catalyte** [PiranhaCMS/piranha.core#1149]
I have a handful of fields that I would like to add into the manager page settings modal. These will be used by our custom search module for indexing and are not needed to be rendered on the front end. I'd prefer not to extend pagebase or the db schema for that but it's not clear if I can add those as per https://piranhacms.org/docs/extensions/fields to a child class? If so, can I specify that they be rendered in the manager settings modal? I am able to customize the modal partial and js to have a new tab and fields and it posts the field values to the api/page/save/draft endpoint but it's not clear how to persist them to Piranha_PageFields.

I can manually persist those in PageService.Save(PageEditModel model, bool draft), or I can just persist the fields to a separate table in the same method, but it seems like I'm missing something simple here.

Am I approaching this correctly?

**Comment by tidyui** [comment]
Hi there! Luckily the solution is very simple:

1. Create a base class for your pages to which you add a **region** with the fields you need. This will make sure that all pages that inherit from this class gets the region.
2. In the RegionAttribute for that region, set the property **Display** to RegionDisplayMode.Setting.

Done!

Regards

**Comment by CSorel-Catalyte** [comment]
I knew it had to be something simple. Thanks!

**Comment by yiqi0110-glitch** [comment]
Hello, I have something related to this.

        [Field(Placeholder = "")]
        public SelectField<Language> Language { get; set; }

These values are currently being generated through an enum and I would like to have them be generated dynamically from an external source when I open the page edit screen in the manager. Is there a simple solution to this?

**Comment by tidyui** [comment]
@yiqi0110-glitch The built in `SelectField` doesn't support this, but I've written a blog article once on how to create this kind of behavior in a custom field that you can take a look at.

https://piranhacms.org/blog/creating-a-custom-tag-field

Regards

**Comment by tidyui** [comment]
However, this is a good idea that I'll add an issue for.

**Comment by yiqi0110-glitch** [comment]
Hello again, I have followed the steps from the blog and I get this issue in the browser console.

piranha-deps-dev.js:16016 [Vue warn]: Unknown custom element: <custom-tag> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Region>
       <Root>

The code that seems to differ from mine to the example is,

> mine (select-field.vue)
`<template>
    <select class="form-control" v-model="model.value" v-on:change="update()">
        <option v-for="(name, value) in meta.options" v-bind:key="value" v-bind:value="value">
            {{ name }}
        </option>
    </select>
</template>

<script>
export default {
    props: ["uid", "model", "meta"],
    methods: {
        update: function () {
            if (this.meta.notifyChange) {
                // Tell parent that value has been updated
                this.$emit('update-field', {
                    uid: this.uid,
                    title: this.meta.options[this.model.value]
                });
            }
        }
    }
}
</script>`

blog's (custom-tag.vue)
`<template>     
    <select class='form-control' :id='uid' v-model='model.value'>
        <option :value='item' v-for='item in model.options'>{{ item }}</option>
    </select>
</template>

<script>
    Vue.component("custom-tag", {
      props: ["uid", "toolbar", "model", "meta"],
      mounted: function () {
        var self = this;

        $("#" + self.uid).select2({
          tags: true,
          selectOnClose: true,
          placeholder: piranha.resources.texts.addTags
        });
        $("#" + self.uid).on("change", function() {
          var item = $(this).find("option:selected").text();
          self.model.value = item;
        });
      }
    });
</script>`

Thanks for your time and support.

**Comment by yiqi0110-glitch** [comment]
`<template>     
    <select class='form-control' :id='uid' v-model='model.value'>
        <option :value='item' v-for='item in model.options'>{{ item }}</option>
    </select>
</template>

<script>
    Vue.component("custom-tag", {
      props: ["uid", "toolbar", "model", "meta"],
      mounted: function () {
        var self = this;

        $("#" + self.uid).select2({
          tags: true,
          selectOnClose: true,
          placeholder: piranha.resources.texts.addTags
        });
        $("#" + self.uid).on("change", function() {
          var item = $(this).find("option:selected").text();
          self.model.value = item;
        });
      }
    });
</script>`

**Comment by tidyui** [comment]
Please open a new issue if you need help instead of adding comments to closed issues.

/ Regards
