### ISSUE TITLE
Excerpt as HTML

### ISSUE THREAD

**Issue by goranhell** [PiranhaCMS/piranha.core#1150]
The new Excerpt part of a post don't use an editor in the manager. It's just a plain text, although the template seed inserts html code.
Also a title for PrimaryImage and Excerprt in the manager would be good...

**Comment by tidyui** [comment]
Hi there! Yes after some internal discussions it was decided that the Excerpt should be in plain text, although maybe we could make it optional. Thanks for noticing the error in the template, as I converted the old pages to the new structure I just changed fields and kept the data without realizing that the content was in HTML 😀

**Comment by goranhell** [comment]
It should be my call, I vote for optional...
