### ISSUE TITLE
[Support] Manager log in not working

### ISSUE THREAD

**Issue by LeadMagnet** [PiranhaCMS/piranha.core#1158]
I have the CMS running in VS2019 using SQL2019 and everything is running fine.

If I run the site (F5) in VS, login using "admin/password" it works fine. Site is on http://localhost:5001

If I publish the site to IIS, using the same SQL database, the site runs (can see all blog entries) but the manager login using "admin/password" fails. Site is on http://localhost

Is there URL hashing of the password or something?
Is there some config entry I need to toggle to get it working in a (fake) production environment?

**Comment by tidyui** [comment]
Did you log out of the manager before navigating to it in IIS? If not, have you restarted your browser?

**Comment by tidyui** [comment]
There has been issues reported before since the manager doesn't Sign out before Signing in. I will add an issue for that related to this one..

**Comment by LeadMagnet** [comment]
@tidyui Yup.....I derped.....cleared browser cache and can log in fine. Sorry, forgot all about this issue when developing!

Thanks for the help guys! :D
