### ISSUE TITLE
How to delete already added content?

### ISSUE THREAD

**Issue by net4u** [PiranhaCMS/piranha.core#1160]
Hi,

I noticed that in RazorWeb example, since a content (any type, excepting Gallery) is added in a page, is no way to delete, move etc.

**Comment by tidyui** [comment]
What do you mean when you say content? Are you referring to Blocks in the main content area? If so, when you hover a block it will be activated and you have the icons for moving and deleting the block in the top right corner. See the attached screenshot.

![Skärmavbild-2020-05-11-kl -21 00 13](https://user-images.githubusercontent.com/781266/81601055-c79f3c80-93ca-11ea-8118-bd570fe24250.jpg)

**Comment by net4u** [comment]
yes, this I mean (text, images, etc.). But for me it behave this way, only for "Gallery" block type.

**Comment by tidyui** [comment]
What web browser and what version of it are you using?

**Comment by tidyui** [comment]
And for Block Groups rendered like the Media Gallery the tools are visible all the time, even when you don't hover the block with the mouse.

**Comment by net4u** [comment]
Sorry. It was browser related. I was by mistake on old Edge. Normally I use new Edge Chromium.

**Comment by tidyui** [comment]
👍
