### ISSUE TITLE
Post comments will not delete

### ISSUE THREAD

**Issue by LeadMagnet** [PiranhaCMS/piranha.core#1161]
Using 8.1 of all modules for Piranha.Blog.Razor running on IISv10 using MSSQL2019. Running the site using Opera68

Can add/edit/delete pages and posts just fine.
Can add comments, with approval enabled/disabled and this works just fine.
I can view Content:Comments no problem, and enable/disable approval.

When I click the Comment delete icon...nothing happens.

There are no errors in IIS or Event Viewer. 
MSSQL Profiler shows no request to delete from [dbo].[Piranha_PostComments] table. The table is not locked.
VS2019 process listener doesn't fire when that icon is clicked.

Any ideas?

**Comment by tidyui** [comment]
There seems to be a mismatch in the api-controller causing a `404` when sending the request for deleting the comment. We'll try to fix it in a service release for `8.2`
