### ISSUE TITLE
Unable to hide pages from sitemap/menu

### ISSUE THREAD

**Issue by net4u** [PiranhaCMS/piranha.core#1170]
Hi

I try make some page(s) to be not visible in menu, but I can't do this:

![2020-05-15](https://user-images.githubusercontent.com/255743/82050898-9459f780-96c1-11ea-8e49-48cac92e18f4.png)
![2020-05-15 (1)](https://user-images.githubusercontent.com/255743/82050909-9b810580-96c1-11ea-8a7e-a0938eda1c4c.png)
I do this wrong?

**Comment by tidyui** [comment]
As we don’t provide any front end components you have to handle it in your view. The SitemapItem will have the property IsHidden=true.

Best regards

**Comment by net4u** [comment]
Solved:
<ul>
    @foreach (var item in sitemap)
    {
        @if (item.IsHidden == false)
        {
            <li class="nav-item @(item.Id == WebApp.PageId ? "active" : "")">
                <a href="@item.Permalink"><span>@item.MenuTitle</span></a>
            </li>
        }
    }
</ul>
