### ISSUE TITLE
Enabling TinyMCE source view

### ISSUE THREAD

**Issue by net4u** [PiranhaCMS/piranha.core#1171]
Hi,

Is possible to togle TinyMCE between Normal and HTML View? (e.g. I need to and an empty div in the middle of some content)

**Comment by tidyui** [comment]
You can configure which Plugins you wish to use in the TinyMCE editor. See documentation here:

https://piranhacms.org/docs/architecture/html-editors/tiny-mce

And on Tiny's official website for available plugins:

https://www.tiny.cloud/docs/

Regards

**Comment by net4u** [comment]
I've tried to add:

"menubar": "file edit view insert format tools table",

into the json, but it does not render the menubar

**Comment by tidyui** [comment]
The supported keywords are the ones you can see here in the docs:

https://piranhacms.org/docs/architecture/html-editors/tiny-mce

You should add HTML to the toolbar.

Regards
