### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by net4u** [PiranhaCMS/piranha.core#1172]
Hi again

Is Piranha.Extend.Blocks the proper place to start implementing a custom component? I want to add a component that I suppose to show in "Blocks" (near gallery, content, video etc.). The only thing that I have now is the model, but I am not sure what else is supossed to have in mind. Also if relevant it will be "form based" (nothing fancy) so I enter data in front-end, not in back-end, and I see data in back-end. The most similar stuff is when we upload media (images etc.) Simply said, I have to enter some text fileds and some blob fields (image and pdf/doc).

Also, where is migration/seed, for adding my stuff? In framework, or in my project?

Regards.

**Comment by net4u** [comment]
Or is more apropriate to use Modules aproach? Any way, what I want to do is:
![2020-05-15 (2)](https://user-images.githubusercontent.com/255743/82091448-0c471280-9700-11ea-934a-a55c61fa0d25.png)

**Comment by tidyui** [comment]
A block sounds right for this. No migrations needed, the framework will take care of storing all properties that derive from IField to the database. The easiest way is to just add the fields you want in you form to your block and don’t specify a custom vue-component. The manager will then automatically render all of the fields in the backend.

https://piranhacms.org/docs/extensions/blocks
