### ISSUE TITLE
Blazor controls

### ISSUE THREAD

**Issue by aprokopyev** [PiranhaCMS/piranha.core#1199]
Hello,

Please let me know, does your CMS allow to create custom pages without coding and place references to custom components on them?

I would like to create a custom data bound Grid component (in Visual Studio) based on Syncfusion Blazor data Grid:

https://blazor.syncfusion.com/demos/datagrid/inline-editing?theme=material

then create general CMS pages and insert some macroses to them which would render grids using my component code.

Like:  
<p> A list of records from Table1:</p>
<% DisplayGrid("View1") %>

CMS would call my custom macros DisplayGird, pass a parameter View1 to it and then macros would call Synfusion Blazor grid to render it in place of the macros. It is possible with your CMS?

Do you have an example of creation of such Blazor bazed macroses?

Thanks

**Comment by tidyui** [comment]
Hi there @aprokopyev!

First of, we don't have any application templates that use Blazor, but as Piranha is totally decoupled you could write your client application using any framework you wish. As for your "macros", Content Types in Piranha are composed of two main pieces, **Fields** (or regions made up of several fields) and **Blocks**. Both of these types of components are totally modular and you could add your own custom components to your application that let's you render anything you like. Whether or not this is the kind of framework support you're looking for is hard for me to tell, but I suggest you read through the documentation on designing content with Piranha:

https://piranhacms.org/docs/content/introduction

Regards
