### ISSUE TITLE
UI components

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#12]
Create UI components for:

* Menu generation
* Breadcrumb generation
* Link generation
* Meda generation
* Meta data generation

For reference, check the existing `UI` helper in the PiranhaCMS repo.

**Comment by TheWolfA2** [comment]
I would say the UI and breadcrumb components should also move to a tag helper syntax to better align with .Net Core MVC standards. Even something like `<piranha-menu />` would be sufficient

**Comment by tidyui** [comment]
As it's very easy to inject an `Api` into a partial view, writing these components is very easy. It would be more logical to for example create an entire module with Bootstrap components for front end applications using this than to force HTML markup from the core package.
