### ISSUE TITLE
Replace EF with nHibernate

### ISSUE THREAD

**Issue by aprokopyev** [PiranhaCMS/piranha.core#1200]
How difficult is it to replace EntityFramework by nHibernate?

I would actually prefer to add even a CSLA layer like this:

CMS -> CSLA -> nHibernate -> Database

Then most likely it would even be possible to make data access library switchable like NH/EF?

https://en.wikipedia.org/wiki/Component-based_Scalable_Logical_Architecture

Is it a good idea? How much of work is it?

Do you already have your own data access layer above EF or all your code refers EF directly from many places?

How does your CMS compare to Orchard?

**Comment by tidyui** [comment]
Hi the @aprokopyev. The architecture already supports this as it's split up into a service layer containing all business logic, and a repository layer that just handles the database communication. The service layer is part of the core package here:

https://github.com/PiranhaCMS/piranha.core/tree/master/core/Piranha/Services

while the repository layer only has interfaces in the core package here:

https://github.com/PiranhaCMS/piranha.core/tree/master/core/Piranha/Repositories

The package `Piranha.Data.EF` contains repository implementations for EntityFramework, so in fact you could create your own `Piranha.Data.NHibernate` if you wanted. 

https://github.com/PiranhaCMS/piranha.core/tree/master/data/Piranha.Data.EF

Regarding how Piranha compares to Orchard I don't really think we try to solve the same thing. Orchard is a modular, complex application framework while Piranha is a content management library that focuses on content editing. Which one you should choose depends on what kind of application you are going to build.

Regards

**Comment by aprokopyev** [comment]
I would like to build control panels for different Linux and OpenBSD services like e-mail, hosting, DNS, etc. Something similar to Linode.com, but much less sophisticated, very specialized for my needs.  It is preferred the system would already have ready login, user/group management, ability to add site pages - it is just what your CMS already has.

I need to extent CMS with my custom grid blocks to allow displaying editable data from different corresponding views.

**Comment by tidyui** [comment]
Hi there, there's an article by Scott Hanselman as well I think about different CMS:s for .NET Core (https://www.hanselman.com/blog/HeadlessCMSAndDecoupledCMSInNETCore.aspx).

As for testing the CMS, it's extremely easy to get a website up and running locally. Just install our project templates:

    dotnet new -I Piranha.Templates

Then create a new project and start it: (remember to create a new folder before running the code below)

    dotnet new piranha.blog.mvc
    dotnet restore
    dotnet run

/ Regards
