### ISSUE TITLE
Authentication failed on docker

### ISSUE THREAD

**Issue by lelongho89** [PiranhaCMS/piranha.core#1206]
Clone new template with command: `dotnet new piranha.web`
Build docker image and start
Navigate to /seed => working
Navigate to /manager => Login screen show => Enter admin/password => Not showing error but redirected to same login page

![image](https://user-images.githubusercontent.com/6689001/83235083-845f0f00-a1bb-11ea-93ca-9ff4f8caabf6.png)
![image](https://user-images.githubusercontent.com/6689001/83235102-8f19a400-a1bb-11ea-9907-2ca3f4c49558.png)

P/S: everything is ok on local with visual studio

**Comment by filipjansson** [comment]
Hi!

Have you tried clearing your browser cache or login via an private tab?
We have a issue with stray cookies (#1159), that have been resolved in the upcoming 8.3 release.

BR

**Comment by lelongho89** [comment]
@filipjansson: use private mode browser and it works. Thanks for your help.
