### ISSUE TITLE
Default Admin Password don't work

### ISSUE THREAD

**Issue by biapar** [PiranhaCMS/piranha.core#1207]
Hi,

I installed the last 8.2 version solution and running. I try to enter to the control panel, but the default admin password don't work.
How solve?

**Comment by tidyui** [comment]
Hi there are many issues on this subject that hopefully will be resolved in 8.3z the current manager doesn’t perform a sign out before sign out which sometimes causes stray cookies to block login. Try logging in in a private tab and if it works clear your browser cache.

Best regards

**Comment by biapar** [comment]
I'm not possible to do because I downloaded the vanialla solution for play with CMS/Blog and think if use it or not for a new blog.
