### ISSUE TITLE
Using Backend for data collection

### ISSUE THREAD

**Issue by biapar** [PiranhaCMS/piranha.core#1215]
Is’t possible to create a set of fields and use them like a set of data collected by an user thought control panel and gived to external application by Webapi?

**Comment by tidyui** [comment]
Hi there! I'm afraid you'll have to explain a bit more!

**Comment by biapar** [comment]
That is... We create a document model with some fields. Then someone put in data in this model trough control panel. So with Api it’s possible to use them ( Crud operations ). See Directus.IO for example.
Thx

**Comment by tidyui** [comment]
Piranha is a decoupled api-based CMS. You can pull out the data any way you want and use it any way you want. All of the interfaces of the service layer can be found here:

https://github.com/PiranhaCMS/piranha.core/tree/master/core/Piranha/Services

Which can be easily accessed trough the application Api:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha/IApi.cs

Best regards

**Comment by biapar** [comment]
I think that an update maybe to create a new type not tight with post or something without URL.

**Comment by tidyui** [comment]
We're looking into introducing a new much more generic content model that can be used for creating both routed content and content that shouldn't be navigated to directly. At the moment we're planning for this to be a part of `9.0` which will be released sometime after the summer.

**Comment by biapar** [comment]
Ok. I mean that.
