### ISSUE TITLE
Improve SEO features

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#1218]
The following fields should be provided out of the box

### Basic
- [x] Meta title - *default value main title*
- [x] Meta keywords
- [x] Meta decription

### Open Graph
- [x] OG Title - *default value meta title, then mail title*
- [x] OG Description - *default value meta description* 
- [x] OG Image - *default value primary image* 

Should there be more fields? If so please comment below

**Comment by biapar** [comment]
TWITTER cards, canonical url

**Comment by jbrozek** [comment]
Alt tag on image blocks

**Comment by tidyui** [comment]
@jbrozek The image block just refers an image in the media library which has a field for alt text (added in 8.1)

Regards

**Comment by danielshue** [comment]
If this hasn’t been done, I’ll be happy to make the change.

**Comment by tidyui** [comment]
Hi @danielshue! No this hasn't been implemented yet! It's basically about adding some fields to Pages & Posts and updating the `Settings` modal for both types of content!

**Comment by tidyui** [comment]
@danielshue We're always happy for contributions, so feel free to join in! Much appreciated

**Comment by danielshue** [comment]
Great! I'll give it a go!

**Comment by danielshue** [comment]
@tidyui 

The Open Graph Protocol - https://ogp.me has a number of supported attributes.  The minimum values appear to be:

```
og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
og:image - An image URL which should represent your object within the graph.
og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".
```

Do we want to support the additional properties available for image such as image:type, image:width, image:alt, and image:height?

If an image isn't provided, it seems like using the Piranha logo seems like a natural choice.

**Comment by tidyui** [comment]
@danielshue Well these were my initial thoughts.

* `og:title` - This should default to the new `MetaTitle`, then `Title` if not set
* `og:description` - This should default to `MetaDescription` if not set
* `og:image` - This should default to `PrimaryImage` if not set

As for `og:type` I haven't really thought about it. Either it could be up to the `Razor Page` / `View` rendering the page/post **or** we could add a property for this. But then maybe there should also be a property available on `PageType` and `PostType` so you can set a default value for this type of content, for example if you create a `ProductPost` you could set it to something relevant to this. 

Regarding meta information about the selected image this can probably be collected from the media object as this will contain all of these fields.

What do you think?

**Comment by tidyui** [comment]
@danielshue And when I wrote that it should default to other fields, I think a good solution is to just show the default values as `placeholder` in the input fields in the manager. Then we can always add helper methods in the package `Piranha.AspNetCore` to help render the meta tags **if** the developer wants to use it.

**Comment by tidyui** [comment]
@danielshue Added first version of helper for rendering meta-tags. See the commit above

**Comment by tidyui** [comment]
@danielshue Just so I know, are you looking at this issue. I'm thinking about starting with #1000 which also requires Db migrations and sometimes it can get a bit messy when trying to merge migrations from several branches.
