### ISSUE TITLE
PrimaryImage & Excerpt

### ISSUE THREAD

**Issue by jbrozek** [PiranhaCMS/piranha.core#1225]
I see from issue #1175 that PrimaryImage & Excerpt where added on 8.3 for each page.  How can we disable or remove this on the manager as we don't use this?

**Comment by tidyui** [comment]
The same concept applies as for Posts, i.e you can disable the fields in the `PageTypeAttribute`, see documentation below:

https://piranhacms.org/docs/content/pages

Regards
