### ISSUE TITLE
Script error causing the Manager Page Editor not to render content

### ISSUE THREAD

**Issue by hedronn** [PiranhaCMS/piranha.core#1227]
Core package for Piranha CMS for .NET Core - Version 8.3.0  (Nuget packages installed)

Script error causing the Manager Page Editor not to render for production release

The following script errors seem to only be the minified versions as non minified .js files work correctly in local debugging.

[Chrome dev console outputs the following script errors]

piranha-deps.min.js:1 ReferenceError: usePrimaryImage is not defined
piranha-deps.min.js:1 TypeError: Cannot read property 'addEventListener' of undefined

**Comment by tidyui** [comment]
Please update to version 8.3.1 of the manager package as there was a bug in the deploy chain for the manager. Make you clear your browser cache so there’s no chance of cached resources and then let us know if the error persists!

Best regards

**Comment by hedronn** [comment]
Thank you for the quick response. Indeed 8.3.1 for the Manager package was the fix for this issue.

Good work on the fast turnaround for the Distributed cache issue too, much appreciated. Keep up the good work guys.

**Comment by tidyui** [comment]
Yes we have now also updated our integration tests so we run all our service layer tests with distributed cache as well so we don’t miss anything in the future!
