### ISSUE TITLE
IsHidden value not changing for subitems without server restart

### ISSUE THREAD

**Issue by Maxoper** [PiranhaCMS/piranha.core#1229]
**IsHidden** isn't working for **Sub**Pages - value is always `false`.

Testcode:
```C#
@foreach (var item in WebApp.Site.Sitemap)
{
     foreach (var subitem in item.Items)
     {
           if(!subitem.IsHidden)
           {
                 //always arrives here
           }
     }
}
```

**Comment by Maxoper** [comment]
Nevermind - somehow it's working now with a clean sqlite DB.

**Comment by Maxoper** [comment]
IsHidden actually works - but changing the hidden state in the manager isn't working properly. 
The new state won't be adjusted on the live server. It always requires a server restart to show the new IsHidden value.

**Comment by tidyui** [comment]
How is your cache set up, which CacheLevel, which Cache Service and how is your application deployed? If you change something in a content block on the pages, is this reflected without restart?

**Comment by Maxoper** [comment]
I had Piranha.Cache.CacheLevel.Basic in my Startup.cs without knowing about that feature.
Guess I should read the docs better next time 🙃

**Comment by tidyui** [comment]
No cache is good and be enabled. The sitemap will be cleared automatically when you save a page BUT you can’t for example use a MemoryCache if your manager is on a different server than the application, then you need a distributed cache.

How is you server setup?

**Comment by Maxoper** [comment]
Honestly: I'm not 100% sure myself. I just bought shared hosting at https://www.ionos.de/hosting/windows-hosting-tarife
I press publish to FTP in VS19 and that's it. I'm still a bloody beginner.
Never touched IIS settings and couldn't find any settings page at all in the admin panel except for setting up the domain. All I know is that I upload the whole project into the root folder of the FTP and that I can shut it down via placing a `app_offline.htm` into the root. This is all surely not the proper way to go but I'm in a hurry to release my page 🙈. If I get your response right everything should work as intended though.

`App.CacheLevel = Piranha.Cache.CacheLevel.Basic;`
or higher results in VS19 Debug- or Release-Mode or on the LiveServer at IONOS with sites not refreshing.
Setting it to `App.CacheLevel = Piranha.Cache.CacheLevel.None;` works for me.
