### ISSUE TITLE
Error after following docs

### ISSUE THREAD

**Issue by peppelorum** [PiranhaCMS/piranha.core#1230]
Followed the quick guide on the start page so ran:

> dotnet new -i Piranha.Templates

and then

> dotnet new piranha.blog
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "ASP.NET Core Blog with Piranha CMS" (piranha.blog) from author "Håkan Edling" in pack Piranha.Blog.CSharp
    To use this template, run the following command and try again:
        dotnet new -i Piranha.Blog.CSharp::6.0.1

**Comment by tidyui** [comment]
The templates have been updated for `8.3` but the quick start on the start page was not updated. I've updated the start page and here is also the link to the full documentation for the new templates:

https://piranhacms.org/docs/basics/project-templates

Hoppas allt rullar på på nya jobbet!!!

**Comment by peppelorum** [comment]
Sweet!!

Jadå, sitter mitt emot Niklas och jobbar så =)
