### ISSUE TITLE
Cannot install based on Official Web page instruction

### ISSUE THREAD

**Issue by vincentvc168** [PiranhaCMS/piranha.core#1241]
C:\Piranha>dotnet restore
  Determining projects to restore...
C:\Piranha\Piranha.csproj : error NU1108: Cycle detected.
C:\Piranha\Piranha.csproj : error NU1108:   Piranha -> Piranha (>= 8.3.0).
  Failed to restore C:\Piranha\Piranha.csproj (in 8.02 sec).

**Comment by tidyui** [comment]
Hi there! You can not have a project with a reference with the same name as the project, that creates a cyclic dependency with NuGet. In other words, you can’t name your project Piranha!

Best regards
