### ISSUE TITLE
How to prevent need to re-seed Pages table

### ISSUE THREAD

**Issue by Markarend** [PiranhaCMS/piranha.core#1242]
We've found that some code modifications cause pages in the dbo.Piranha_Pages table to be deleted (unsure of this process) and re-seeded to defaults (via Seed.RunAsync).  It seems the modifications that cause this to happen are **adding** new **custom page types**, and sometimes **modifying** those types. 

What should we do if we want to begin adding pages via the manager, but there comes a time when we want to deploy a new custom page type, or modify an existing one?  We can't just have the database being wiped out every time this happens.

**Comment by tidyui** [comment]
The only thing that can delete pages is if you remove their page type from the application startup and have the statement DeleteOrphans() in your page type import, see here as an example:

https://github.com/PiranhaCMS/piranha.core.templates/blob/master/src/web/razor/Startup.cs#L96

Page types can be removed for several reasons, for example:

* You change the class name (as this is the PK)
* You have deployed your client & manager to different servers, they both import content types at startup and they are not in sync.

For more concrete suggestions I will need more details on your setup.

Regards

**Comment by Markarend** [comment]
I hate to say it didn't occur to me that DeleteOrphans() was the thing that was doing this. Now I understand orphaned pages are those whose type no longer exists. I can watch for that and correct on my own, and not worry that pages will be deleted when I don't expect it.  Thanks again for your prompt help, it makes a big difference for our success!
