### ISSUE TITLE
Automatically add / for content type routes

### ISSUE THREAD

**Issue by mkarlsson** [PiranhaCMS/piranha.core#1245]
It goes to Page route in CMS controller and not the one I created (for department page). I read the route documentation and understood it like it will pick up the correct page type in the CMSCOntroller if I add the route value and Controller pagetype to the name of the pagetype?

Startup.cs
`  var pageTypeBuilder = new Piranha.AttributeBuilder.PageTypeBuilder(api)
                 .AddType(typeof(Models.DepartmentPage))
                 .AddType(typeof(Models.StandardPage))
                 .AddType(typeof(Models.LanguageSelectorPage));
            pageTypeBuilder.Build()
                .DeleteOrphans();`

CMSController
`[Route("department")]
        public async Task<IActionResult> DepartmentPage(Guid id)
        {
            var model = await _api.Pages.GetByIdAsync<DepartmentPage>(id);

            return View(model);
        }`

DepartmentPage.cs (actually empty...)
`[PageType(Title = "Department page")]
    public class DepartmentPage : Page<DepartmentPage>
    {
        /// <summary>
        /// Gets/sets the available populareCategories
        /// </summary>
        //public IEnumerable<PopulareCategoryModel> PopulareCategories { get; set; } = new List<PopulareCategoryModel>();

    }`

Then I have a DepartmentPage.cshtml in VIews/CMS..

![image](https://user-images.githubusercontent.com/5114880/85342181-43bc9200-b4ea-11ea-968c-bfd0e872fff6.png)

Also, regarding the routing logic its hard to understand how I can create a english page and a Swedish page and use the same route?

**Comment by tidyui** [comment]
Hi there! The route needs to start a forward slash, so `department` should be `/department`. We've talked about fixing this when types are imported as it's easy to forget and easy to fix.

**Comment by magnuskarlssonhm** [comment]
Thanks, quick as usual!

Added it but it still goes to Page route. Using the latest template. 
dotnet new piranha.mvc -s BlobStorage -d SQLServer
Here is the page route in the template, it does not have a forward slash, am I misunderstanding something here?

`[Route("page")]
        public async Task<IActionResult> Page(Guid id, bool draft = false)
        {
            try`

**Comment by tidyui** [comment]
No, the route on the Page Type. I misread you code and thought you'd added one. The route in the controller should probably be without a forward slash. But on each page type that you need to send to a different route you have to add a `PageTypeRouteAttribute`

~~~ csharp
[PageType(Title = "My Page")]
[PageTypeRoute(Title = "Default", Route = "/myroute")]
public MyPage : Page<MyPage>
{
}
~~~

Regards

**Comment by mkarlsson** [comment]
Ah, I see. It did the trick as well, thanks!



Sent from Outlook<http://aka.ms/weboutlook>

________________________________
