### ISSUE TITLE
GenericBlock not updating item title in the manager

### ISSUE THREAD

**Issue by maxpowernz** [PiranhaCMS/piranha.core#1246]
Hi,

not sure if its a bug or I am doing it wrong, but using the code below, the title doesnt show up in the item list until a page refresh, It could be onblur setting in vue? According to the docs: "No specific Vue component is needed to render block groups".

The same thing happens with a region as well, region i have:

```
using Piranha.Extend;
using Piranha.Extend.Blocks;
using Piranha.Extend.Fields;

[BlockGroupType(Name = "PDFFiles", Category = "Media", Icon = "fas fa-images")]
[BlockItemType(Type = typeof(AuthorBlock))]
public class MyBlockGroup : BlockGroup
{

}


[BlockType(Name = "Author", Category = "Media", Icon = "fas fa-fish")]
public class AuthorBlock : Block
{
    public StringField Title { get; set; }

    public HtmlField HtmlField { get; set; }

    public MediaField PdfFile { get; set; }

    public ImageField Image { get; set; }


    public override string GetTitle()
    {
        return Title;
    }
}
```

![image](https://user-images.githubusercontent.com/27950691/85510659-cc9f0f00-b64b-11ea-81ae-fca428d61504.png)

```
    [Region(ListTitle = "Title", ListExpand = false)]
    public IList<MyRegion> PDFFiles { get; set; }
```

![image](https://user-images.githubusercontent.com/27950691/85511755-3a980600-b64d-11ea-87bf-10c72ac81444.png)

**Comment by maxpowernz** [comment]
it was my fault sorry, I needed a custom vue component to handle the blur, closing.

**Comment by tidyui** [comment]
I'll reopen this issue as we should add support for updating list-title on generic block-components.

**Comment by tidyui** [comment]
The `BlockGroupAttribute` needs a `ListTitle` property just like list-regions. `generic-block.vue` should listen to emitted `update-title` events from the specified field and update list title accordingly.

**Comment by mikaellindemann** [comment]
Does this deprecate the `GetTitle()` method on blocks then?

**Comment by tidyui** [comment]
@mikaellindemann `GetTitle()` is currently used for calculating the title from C# when working when the models. It's also included to the UI when loaded from the backend. The different emits flying around is simply for updating the UI dynamically when changing field values in the manager.

**Comment by tidyui** [comment]
And @mikaellindemann I see your point when going through the code **but** `GetTitle()` would still be needed for blocks with custom components, however it might be a good idea to have a default implementation that checks the `ListTitle` property. 

I'll get back to you on that.

**Comment by tidyui** [comment]
@mikaellindemann The class `Piranha.Extend.Block` currently has the default implementation:

~~~ csharp
public virtual string GetTitle()
{
    return "[Not Implemented]";
}
~~~

This implementation could be expanded to check if `ListTitle` is set, and if it is return the title for the specified field. If `ListTitle` are empty the current string "[Not Implemented]" could be returned. And for all blocks overriding this method it wouldn't make any difference.

**Comment by tidyui** [comment]
@mikaellindemann That worked perfectly. So in other words when setting the `ListTitle` property of the `BlockTypeAttribute`, overriding `Block.GetTitle()` is not necessary.
