### ISSUE TITLE
Is it possible to make page sections collapsed by default?

### ISSUE THREAD

**Issue by r4g-jon** [PiranhaCMS/piranha.core#1260]
Hello!

I have a question about whether it is possible to add an option to make pages with child pages collapsed by default. 

The problem I have is that I have 3 websites on one Piranha instance and when the manager loads, it's a bit difficult to find the page I want to edit, so I have to "collapse" the parent pages to make it easier to see where I am. 

If we could have an option to collapse sections it makes viewing the sites and pages much easier to work with. Here's an example of what I would like:

![image](https://user-images.githubusercontent.com/52327054/86014267-03906e80-ba18-11ea-966b-f2f904bdde76.png)

**Comment by tidyui** [comment]
Hi there! Yes, if you go to the config view in the manager you can set the number of expanded levels in the sitemap.

<img width="1412" alt="Skärmavbild 2020-06-29 kl  16 10 21" src="https://user-images.githubusercontent.com/781266/86016504-21af9c00-ba23-11ea-8725-669f41bcf7cd.png">

**Comment by r4g-jon** [comment]
Thanks @tidyui  for letting me know about this! I really appreciate it! :)
