### ISSUE TITLE
NGINX 502 Error with Manager

### ISSUE THREAD

**Issue by mentatpsi** [PiranhaCMS/piranha.core#1265]
I am getting a 502 error upon attempting to login to Manager. Using Ubuntu Linux. I'm using the mostly default configuration of a proxy pass to 5000 port to your application. I've tested this locally on my own system (Windows 10 Pro + Visual Studio 2019 Community) and it works fine. Not sure the issue.

**Comment by tidyui** [comment]
Hi there @mentatpsi! Please check if this is related and could solve your issue: https://github.com/PiranhaCMS/piranha.core.docs/issues/40

**Comment by mentatpsi** [comment]
Hey... I actually did some searching and came across that issue last night. I tried implementing the change but I was still getting that error. It took a bit of doing (I'm a Microsoft Developer Professionally). But the issue from the NGINX error log is that the headers being passed are too large during the login process. So it returns that error. I noticed that when I debug locally through running the app, it never gets to an error on the app... so it was happening during the request. Seems like the right place for it to be happening given this debug process. Let me know. Also, thanks for the extremely quick response.

**Comment by mentatpsi** [comment]
Hey... i thought you sent me a link to another issue that I saw with NGINX that was fixed in version 8.0 (I believe)... should have spent more time reading the whole thread. Ya, this looks to be the issue. I'll try and implement the solution. Thanks!

**Comment by mentatpsi** [comment]
That worked perfectly. Just need to put it behind HTTPS. Thanks for the help!

**Comment by zlightverse** [comment]
Hi, 

I like to share my solution to similar issue.
Upon checking on Nginx log, the error i got was "upstream sent too big header while reading response header from upstream, client"
I solved it by modifying nginx.conf to increase buffer. These are the 4 lines i added：

        proxy_buffer_size 32k;
        proxy_buffers 8 32k;
        proxy_busy_buffers_size 64k;
        large_client_header_buffers 4 32k;
