### ISSUE TITLE
Delete pop-up interferes with uBlock Origin

### ISSUE THREAD

**Issue by lukasan** [PiranhaCMS/piranha.core#1269]
When clicking inside the /manager/pages to delete a page either on the list or in the edit layout, Firefox loads `<div class="modal-backdrop show"></div>` with a few others and it stays darkened unless I reload the page. There's no interactive pop-up to delete/cancel.

With Chromium browsers this doesn't happen. Tested on Edge and Brave.

**Comment by tidyui** [comment]
Which version of Firefox are you using? I’m developing mainly using FF and never seen the issue so it has to be a new issue!

**Comment by tidyui** [comment]
I'm having som trouble reproducing this issue. I'm running FF 78.0.2 on Mac and can see the modals on both pages, see screenshots.

<img width="1448" alt="Skärmavbild 2020-07-12 kl  07 35 01" src="https://user-images.githubusercontent.com/781266/87239693-615a8880-c412-11ea-965e-61c5a46154f3.png">
<img width="1448" alt="Skärmavbild 2020-07-12 kl  07 35 11" src="https://user-images.githubusercontent.com/781266/87239697-6586a600-c412-11ea-82a3-ac5c2761560f.png">
<img width="742" alt="Skärmavbild 2020-07-12 kl  07 35 18" src="https://user-images.githubusercontent.com/781266/87239700-67e90000-c412-11ea-9e7c-85e105774b98.png">

**Comment by lukasan** [comment]
The FF version is the same.
My view on Firefox:
![Firefox](https://user-images.githubusercontent.com/60816397/87292072-efb13600-c508-11ea-99ca-95c65fe37054.png)
On Brave:
![brave](https://user-images.githubusercontent.com/60816397/87292081-f2139000-c508-11ea-9fed-1ac2d27a5d0d.png)

As writing this answer, I thought that **uBlock Origin can interfere**. Turns out it is. If I disable uBlock Origin, it works on Firefox.

**Comment by tidyui** [comment]
@lukasan I'm not really familiar with the extension, and not really sure if we can do anything to bypass it's behavior.
