### ISSUE TITLE
Redirect to http from https on manager

### ISSUE THREAD

**Issue by mentatpsi** [PiranhaCMS/piranha.core#1270]
I notice when I am on https and navigating to https://www.example.com/manager ... it immediately redirects me to the http page. I have to again write https in the beginning for it to get to the secure version. I'm not sure if this is an NGINX thing or something else. Was wondering if it's been encountered before.

**Comment by tidyui** [comment]
My guess here is that nginx isn’t forwarding scheme so when a redirect is performed the application thinks it’s running in http. But it’s just a guess.

**Comment by mentatpsi** [comment]
Thanks! I'll look into it.

**Comment by mentatpsi** [comment]
I oddly was able to get something working by playing around with the NGINX configuration file. I'll close the ticket.

**Comment by mentatpsi** [comment]
Seemed like it was ok when there was a session cached. Reverted back to the same issue. Will require some debugging. I'll do some digging.

**Comment by mentatpsi** [comment]
Actually. just uncovered... it doesn't have the issue when you go directly to /manager/login ... it does have an issue when you go just to /manager

**Comment by tidyui** [comment]
That’s because /manager will redirect to /manager/login

**Comment by mentatpsi** [comment]
yes... but during the redirect... it loses the https for some reason. I'm not sure what would cause that. I mainly work with IIS.

**Comment by tidyui** [comment]
Yes exactly. The cause is often that you access nginx with https but nginx forgets to forward scheme to kestrel which causes the application to think that it’s running http. When a redirect is performed it redirects to http because asp.net core thinks that is the scheme being used.

**Comment by mentatpsi** [comment]
That's really good information! Thank you!

**Comment by mentatpsi** [comment]
I actually decided to just provide a 301 permanent redirect to HTTPS and that did the trick. I think it's best to avoid HTTP if you can handle it easily.

**Comment by mentatpsi** [comment]
If I wanted to fix this the correct way... how would I go about doing that?

I found this... just want to confirm:
https://stackoverflow.com/questions/58124655/net-core-x-forwarded-proto-header-doesnt-pass-to-nginx-properly

**Comment by mentatpsi** [comment]
That seemed to do the trick. Thanks guys!

**Comment by traustitj** [comment]
I just added this bit in the conf file for my host and now sitemaps and everything works

`      proxy_pass      http://127.0.0.1:5002;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection keep-alive;
      proxy_set_header   Host $host;
      proxy_cache_bypass $http_upgrade;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;`
