### ISSUE TITLE
"error NU1108: Cycle detected."

### ISSUE THREAD

**Issue by yooakim** [PiranhaCMS/piranha.core#1271]
Hi,
I'm curious about Piranha and I want to create a super simple test site. I downloaded the template using `dotnet new -i Piranha.Templates` and then I create the app as follows:

![piranha-cycle-detected](https://user-images.githubusercontent.com/862546/87225044-447a7280-c38a-11ea-8187-bfe1a97d977f.gif)

I've never encountered a NuGet error "Cycle detected", anyone here know what I need to do to fix this?

**Comment by tidyui** [comment]
Hi there. This is a limitation in dotnet restore, see #1263 for details

**Comment by yooakim** [comment]
Yes, thanks. Stupid of me to use the same name for the project as for a dependency ;-)

**Comment by tidyui** [comment]
@yooakim Not at all, it’s quite logical actually 😁
