### ISSUE TITLE
IntegratedMiddleware throws when Piranha is hosted in a Virtual Directory

### ISSUE THREAD

**Issue by eloekset** [PiranhaCMS/piranha.core#1273]
Like mentioned in #372, Piranha is not tested when hosted in a Virtual Directory.

There may be more unexpected behavior, but at least I've tracked down one bug, which I know how to fix.

![image](https://user-images.githubusercontent.com/791721/87871320-a69d2e00-c9af-11ea-9605-a8256bb3b331.png)
![image](https://user-images.githubusercontent.com/791721/87871324-ab61e200-c9af-11ea-80c8-1619577e6608.png)

It starts after adding support for empty `url` at line 53, so I can send a PR for that.

**Comment by eloekset** [comment]
I just wanted to update this issue with the results after building my own fork and trying to use it in a site hosted as a Virtual Directory within an Azure App Service.

The site starts up, but routing doesn't work as it should. At least I've confirmed that the `/seed` route defined in the `SetupController` doesn't work.

The error message that I find in the event log is:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\home\site\<virtual-directory-name>\seed'.
```

I'm not sure what this indicates, but it seems like Azure App Service tries to navigate to a folder, while instead ASP.NET Core should use this as a route. I will link to a new issue and send another PR if I find the solution to this.

**Comment by tidyui** [comment]
Hi! This error looks like you’ve published but haven’t included the seed folder in the published files! This is needed if you want to run the seed after deploy.

Best regards

**Comment by eloekset** [comment]
Thanks! You're absolutely right. The manager works fine, so there's obviously no routing issues.
