### ISSUE TITLE
Unable to create a new Page type in 8.3.0

### ISSUE THREAD

**Issue by jonaslorander** [PiranhaCMS/piranha.core#1275]
Hi,

I've just started playing around with Piranha CMS, which seems lika a rellay great CMS tool that I would like to use.
After reading the docs I wanted to get a feeling of what it is like to use Piranha as a programmer and the first thing I wanted to try was to create a new Page type. But I am unable to get it to work!

I'm using the latest NuGet packages (8.3.0) and created a project using the piranha.razor template (after installing it with `dotnet new -i Piranha.Templates` as per the docs. I then made a copy of Models\StandardPage.cs and renamed the file to TestPage.cs:

```
using Piranha.AttributeBuilder;
using Piranha.Models;

namespace jonasblog.Models
{
    [PageType(Title = "Test page")]
    public class TestPage  : Page<TestPage>
    {
    }
}
```

I run in debug with Visual Studio 2019, add seed data and login in to the manager. In the manager I can select "Test page" when adding a new page. I add a title to the page and some blocks, saves and publishes. When I then go to the front page of the site I can see the newly created page in the menu, but when I click the link I get a 404 error. The URL matches the slug in the page settings URL segment.

If I do the same thing, but use Standard Page Type instead of my Test Page it works just fine!

In the docs it says that when creating a new page type, it should be added in the Configure method of the startup class using the PageTypeBuilder, but it also says that one could use the  ContentTypeBuilder (`new ContentTypeBuilder(api).AddAssembly(typeof(Startup).Assembly).Build().DeleteOrphans();`) which is specified in the template. Is this not true, are the docs out of date? Is it possible to use both PageTypeBuilder and ContentTypeBuilder to get around this issue? If so, what order should the be added in? 

I'm probably doing something wrong, but what? Since I can see the Page Type in the manager I'm guessing that the page type is added correctly, so I can't be that far off.

Thanks in advance, and I hope this is the correct place to post this kind of question!

Hälsningar,
Jonas

**Comment by tidyui** [comment]
Hi there @jonaslorander! There's nothing wrong with the page type itself, but you haven't configured any `routing` for your new type. When a page matching the current request url is found by the middleware is found it's routed to mvc/razor pages. The default route for pages is `/page`, but as you see by taking a look at `~/Pages/Page.cshtml` (https://github.com/PiranhaCMS/piranha.core.templates/blob/master/src/web/razor/Pages/Page.cshtml) this expects a `StandardPage` as it's model. 

To fix this you need to send all requests to pages of your new type to another `.cshtml` page. This is done by adding the `PageTypeRouteAttribute` to your type, for example:

~~~ cshtml
[PageType(Title = "Test page")]
[PageTypeRoute(Title = "Default", Route = "/test")]
public class TestPage  : Page<TestPage>
{
}
~~~

Then to serve the request you would add a page at `~/Pages/Test.cshtml`. You can make a copy of `~/Pages/Page.cshtml`, but remember to change the model type at the second line.

You can find more information about routing on the page under "Page Routing" https://piranhacms.org/docs/content/pages

**Comment by jonaslorander** [comment]
That was it! It works great now! And, I got a better understanding of Piranha as well!

Tack så mycket!

**Comment by dinukasal** [comment]
I created the Model class like this,

```
using Piranha.AttributeBuilder;
using Piranha.Models;
using Piranha.Extend;

namespace RazorWeb.Models
{
    [PageType(Title = "Contact Page")]
    [PageTypeRoute(Title = "Default", Route = "/contactpage")]
    public class ContactPage: Page<ContactPage>
    {
    }
}

```

And cshtml file like this,

```
@page
@model SinglePage<ContactPage>
@{ ViewData["Title"] = Model.Data.Title; }
@section head
{
    @WebApp.MetaTags(Model.Data)
}

@*@Html.DisplayFor(m => m.Data.Hero)*@

<div class="container body-container">
    <div class="row justify-content-center">
        <div class="col-md-10 col-xs-12">
            @Html.DisplayFor(m => m.Data.Blocks)
        </div>
    </div>
</div>

```
When navigating to the created page under this new page type it gives a 404.

**Comment by tidyui** [comment]
@dinukasal I don't see anything obviously wrong with your page type. I am assuming you had no problem locating the `Contact Page` page type in the manager when creating the page. Also, did you publish the page and not just save it? If none of these issues are your problem, could you check the application output to see if it finds the requested permalink, if it does then the error is most likely that it can't find the Razor Page you are referring to in your route. Is the `.cshtml` located in `~/Pages/ContactPage.cshtml`.

Regards

**Comment by dinukasal** [comment]
@tidyui it was because my view filename was Contact.cshtml, when renamed to ContactPage.cshtml it workd.
Thanks!
