### ISSUE TITLE
Routes are incorrect when hosted in Virtual Directory

### ISSUE THREAD

**Issue by eloekset** [PiranhaCMS/piranha.core#1282]
Related to #1273. The application starts after the fix done to `IntegratedMiddleware` but routes are incorrect, so navigating to any page except the default site page fails - or even the main page URL is incorrect when clicked in the menu.

`HttpContext.Request.PathBase` contains the Virtual Directory path, so I've tried to do some changes to make use of that value, but I haven't found the correct place(s) to modify. It looks like route handling is correct, so the pages are found and rendered correctly if the browser URL points to the `<host>/<virtual-directory>/<page>`, however the menu items don't include the `<virtual-directory>` segment.

![image](https://user-images.githubusercontent.com/791721/88489774-d2637980-cf96-11ea-86dc-dcd9d0bebf58.png)

I've just modified the MvcWeb application in the examples folder to debug this:
![image](https://user-images.githubusercontent.com/791721/88489798-fde66400-cf96-11ea-9b0b-853e955c4c1a.png)

**Comment by eloekset** [comment]
Maybe this is the correct place, if `IApplicationService.Request` gets a new property `PathBase` that somehow gets set to the value that `HttpContent.Request.PathBase` has when a request is handled. Don't know if that value is available where necessary when the `IRequestHelper` is instantiated, though. 
![image](https://user-images.githubusercontent.com/791721/88490605-05a90700-cf9d-11ea-8197-ade89074266f.png)

**Comment by tidyui** [comment]
My guess is the menu can be fixed easily in the project. The templates render the menu like this:

https://github.com/PiranhaCMS/piranha.core.templates/blob/master/src/web/razor/Pages/_Layout.cshtml#L25

Where permalink will start with a forward slash. By adding a “~” before permalink and wrapping it inside @Url.Content() asp.net should resolve the links correctly.

We’re adding some helpers for link generation in 8.4, we’ll try to test for this case as well.

Regards

**Comment by tidyui** [comment]
Yes your second comment would be the correct place to add the code in master (8.4). Like you say RequestHelper needs to be updated to store the value.

**Comment by eloekset** [comment]
This PR documents the changes I've done to my fork to support Virtual Directories: https://github.com/eloekset/piranha.core/pull/6 It works as far as I've tested with or without a Virtual Directory.

If you want, I can create a PR that's based on **origin/master** to contribute the changes back here. 

**Disclamer:** I haven't tested on a multi-site Piranha application, and the MCV template needs an update as described in my PR. And I've just started using Piranha, so I'm not aware of all implications this may cause yet.

**Comment by eloekset** [comment]
Menu items is not the only thing that needs to be updated in the template to make use of the changes. I've already discovered that the **PostBlock.cshtml** file's **Read more** button has the same issue. There's probably a lot of places where relative URLs are rendered without calling the `WebApp.Url(...)` method. Hopefully the changes to the central component is the only change that is needed to the framework, and the rest is to make use of it all around the template.

**Comment by tidyui** [comment]
Yes we are fully aware of this, but as the templates are in a separate repository we won’t update them until we have packages to build against.

**Comment by eloekset** [comment]
Should I send a PR targeted master for the changes I've done to core?

**Comment by tidyui** [comment]
I added a comment to your PR!

**Comment by eloekset** [comment]
One thing to keep note of when hosting Piranha in Virtual Directories: https://medium.com/@rene.sackers/hosting-multiple-asp-net-core-instances-on-a-single-azure-web-app-eb5552ce00f6

In short, edit the web application's csproj file like this:
```
<PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
</PropertyGroup>
```

To resolve this error in all but the first virtual directory:
*HTTP Error 500.35 - ANCM Multiple In-Process Applications in same Process
Common solutions to this issue:
Select a different application pool to create another in-process application.*

**Comment by tidyui** [comment]
This has been merged by issue was still open. Closing.
