### ISSUE TITLE
HTTP header configuration

### ISSUE THREAD

**Issue by lukasan** [PiranhaCMS/piranha.core#1284]
I think that a default field like 'File' should be a core feature. A File field works like any other media input, but it uploads any type of file. And on a page it links to a download of that file.

This would probably need an additional section on the manager under 'content'

Use case for me:
I need a 'Downloads' page with a few files that I want to host on Azure Blob Storage. These files ideally should be easily added or removed through the manager by a non-programmer.

In the meanwhile, how could I set up file uploading myself with the api, or is it strictly media-only and I need to find a solution outside Piranha?

**Comment by r4g-jon** [comment]
Hi @lukasan 

You can set up Piranha to use Azure Blob storage, if you take a look in the documentation there's a good example on how to do it. You can then use code similar to this to upload to Azure:

                    using (var stream = System.IO.File.OpenRead("image.jpg"))
                    {
                        await api.Media.SaveAsync(new Piranha.Models.StreamMediaContent()
                        {
                            Id = image.id,
                            Filename = "image.jpg",
                            Data = stream
                        });
                    }

You can also use the Piranha API to find files too by name etc.

I think Piranha by default allows you to upload PDFs etc but if you want to be able to upload other types of images, there is a an option that allows you to do that. For example, if you wanted to be able to upload SVGs add this line to your Configure method in Startup.cs:

App.MediaTypes.Images.Add(".svg", "image/svg+xml", false);

I hope this helps!

**Comment by lukasan** [comment]
@r4g-jon 
Yes I already am using Blob Storage and I have .svg files configured.

What I'm asking is I want to upload .zip files and other text/code files solely for downloading from a website. And I'm unsure if the api.Media can handle

**Comment by r4g-jon** [comment]
Ah - I see what you mean.

You should be able to upload zip files by adding this into you Configure method:

App.MediaTypes.Images.Add(".zip", "application/zip", false);

**Comment by lukasan** [comment]
And that is the point

If a non-programmer wants to add another different file, say, .exe, I would need to add it inside Startup.cs and re-initialise the project for it to register. Which defeats the purpose of easy file adding inside the manager

Thus I'm proposing that another category for 'files' should be created, that you can't just put inside an ImageField. And I wouldn't need to add each type of non-image files inside Startup.cs.

**Comment by r4g-jon** [comment]
I see what you mean! I can certainly see it from your perspective :)

However, from a security perspective, it's probably better than the developers explicity allow which file types can be uploaded. A non-technical user could end up uploading files that have not been virus checked for example?

**Comment by lukasan** [comment]
Okay, then if I added .zip files, what's stopping other site admins from uploading viruses inside the .zip? PDFs can have viruses inside them, why Piranha lets them through by default then?

My solution will probably be to upload files manually to Azure, then retrieve the link of the file from the Blob Storage and use that manually wherever I need, probably inside a custom-made block.
But that is far from ideal

By the way, thanks for the quick responses!

**Comment by r4g-jon** [comment]
Yes, I totally understand! It's definitely a tricky area. 

No problem on the responses @lukasan - I hope you can resolve your problem quickly!

**Comment by tidyui** [comment]
Hi there @lukasan We allow a limited set of file types by default because these types usually work across most devices. Like @r4g-jon mentioned you can configure any types of files you want, but as a developer you still have to tell Piranha **what** types should be allowed, and **how** they should be classified (document, image, resource or video). 

We have a MediaField which allows any type of file from the media library, and uploading it through the api is easy as long as the file type is configured.

Best regards

**Comment by lukasan** [comment]
Hey, @tidyui. Sorry, but I have probably misunderstood a lot about what I was trying to achieve here.
I think all I need is to have a **HTTP/1.1 header** 'content-disposition: attachment' set when uploading a file to the blob storage (or when requesting a download from the blob?). How can I achieve that within Piranha's BlobStorage extension? I can't find anything regarding headers in the docs.

Ideally, I register a .zip file in the configuration, then set all uploaded .zip files to have a 'content-disposition: attachment' header.

**Comment by tidyui** [comment]
There’s no included API endpoint for the application for uploading images as this feature would probably need to be restricted for authenticated users in the client application.

Maybe this is something that could be created as a small add-on package

**Comment by lukasan** [comment]
> could be created as a small add-on package

I'd love to see that happen, thanks for the replies.
