### ISSUE TITLE
Labelling the manager ui

### ISSUE THREAD

**Issue by jkulubya** [PiranhaCMS/piranha.core#1285]
Hi,
Is it possible to label the editors in the manager UI? I'd like to make the admin area as foolproof as possible, but its a bit difficult as it is currently. For example, the screen below has a few editors that are only described by icons.

<img width="1061" alt="Screenshot 2020-07-31 at 17 00 31" src="https://user-images.githubusercontent.com/7911793/89048098-a148c780-d34f-11ea-9552-27e9ce75502a.png">

Thanks

**Comment by tidyui** [comment]
Hi there. If I’m not mistaken the labels doesn’t appear until you hover the components. We’ll take a look at how it could be clarified.

**Comment by tidyui** [comment]
This will be release in `9.0` and is a part of #1290
