### ISSUE TITLE
PrimaryImage & Excerpt taking too much space

### ISSUE THREAD

**Issue by i-love-code** [PiranhaCMS/piranha.core#1290]
![image](https://user-images.githubusercontent.com/1737733/89324294-af972c00-d64c-11ea-9afb-c71c2c8e0aa5.png)

While I love most features I've seen recently, the addition of the image/lead-in text on _all_ page types wasn't one I expected. While I get the intent, having an image and some text on every page can help build a more functional site OOTB and have an image field for meta tags, I really dislike how much of the visual real estate the UI takes up on the page especially when I don't believe every page needs an image/excerpt if it's just a legal terms of service/privacy/standard content page.

![image](https://user-images.githubusercontent.com/1737733/89324427-e2d9bb00-d64c-11ea-9f4f-ebd0b33755ad.png)

Is there any way to hide/remove them from the UI?

**Comment by tidyui** [comment]
Hi there! Yes can remove the fields on the Page Types! https://piranhacms.org/docs/content/pages

Regards

**Comment by tidyui** [comment]
We've decided to review the layout of the `PrimaryImage` & `Excerpt` in a way that it doesn't take as much space in the editor. Page/post settings will be changed from a **modal** to a side **panel** and these two fields will be moved there (see provided screenshot).

![Skärmavbild 2020-09-04 kl  08 51 26](https://user-images.githubusercontent.com/781266/92208617-dcc53d00-ee8b-11ea-90e0-fe203d2cad79.png)
