### ISSUE TITLE
Cannot add Video Block

### ISSUE THREAD

**Issue by mgkoko** [PiranhaCMS/piranha.core#1292]
I am getting 400 bad request error, when I try to add a video block. Am I missing something? The preview works fine.

![image](https://user-images.githubusercontent.com/6714930/89490779-a4bad380-d7d3-11ea-85d2-e7610eeb9e8d.png)

**Comment by tidyui** [comment]
Hi there! We had this issue previously in the ImageBlock, but unfortunately it looks like it was missed in the video & audio block. We’ll fix this for the 8.4 release which is just around the corner!

**Comment by mgkoko** [comment]
cool, thank you!
