### ISSUE TITLE
Is this cms supports CKEditor

### ISSUE THREAD

**Issue by SAISUDHEERREDDY** [PiranhaCMS/piranha.core#1294]
Is this cms supports CKEditor?

**Comment by lukasan** [comment]
No, not automatically through packages. You'd have to implement it yourself, I presume.
https://piranhacms.org/docs/architecture/html-editors
> At the moment Piranha has packages for two different editors, TinyMCE and Summernote.

**Comment by tidyui** [comment]
You can inject any editor into the manager by overriding the methods `piranha.editor.addInline` and `piranha.editor.remove`. Take a look at the summernote package for reference. https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.Summernote/assets/src/piranha.editor.js#L45
