### ISSUE TITLE
TinyMCE expanded toolbar overflows above the content

### ISSUE THREAD

**Issue by lukasan** [PiranhaCMS/piranha.core#1295]
Hello again,
I expanded the editor to include more editing options. The extra toolbar row overflows the first line of the content.
![Untitled](https://user-images.githubusercontent.com/60816397/89635720-18321300-d8b0-11ea-9fbc-84f7410cd4a4.png)

Is there a setting I missed to overcome this? There's no way to add ```"toolbar_mode": "sliding"``` to at least make it work ok.

**Comment by tidyui** [comment]
Hi there! You should add a custom JavaScript resource to your manager and change the top margin offset as needed.

See the docs here for how to add resources to the manager:

https://piranhacms.org/docs/manager-extensions/resources

Regards
