### ISSUE TITLE
ColorField

### ISSUE THREAD

**Issue by lukasan** [PiranhaCMS/piranha.core#1302]
What happened to #31? Is there any way to have colour picker functionality inside the manager?

All I can do is just use a StringField and use its input as a hex value in .cshtml. This is really hacky.

**Comment by tidyui** [comment]
As the core package is content oriented we have tried to stay clear of fields that are not content focused. However we have talked about creating an add-on package with more web-oriented fields, like color pickers, YouTube media and so on.

**Comment by govi2010** [comment]
Hello @tidyui ,

I have made some progress on this. 
I have used `vue-color` package and made some progress.

I have pushed my code my master branch(forked repo). If you can review and suggest some changes. 



![Kapture 2020-09-19 at 20 50 23](https://user-images.githubusercontent.com/8776031/93670550-cd640780-fab9-11ea-95d5-b6715b1fc4a6.gif)

**Comment by govi2010** [comment]
Doing CSS improvement this weekend.
