### ISSUE TITLE
Issue upgrading Piranha Nuget packages from v8.3.0  -->  v8.4.0 (still investigating)

### ISSUE THREAD

**Issue by hedronn** [PiranhaCMS/piranha.core#1313]
I am seeing an Issue upgrading Piranha Nuget packages from v8.3.0  -->  v8.4.0

Created a copy of the my Piranha CMS sql database (v8.3.0) and a new branch of my site code before updating the Piranha CMS Nuget packages.

However after upgrading I am seeing the following exception for v8.4.0.

Exception triggered in CreateHostBuilder(args).Build().Run();

System.Exception: 'Could not resolve a service of type 'Piranha.IApi' for the parameter 'api' of method 'Configure' 
SqlException: Cannot find the object "Piranha_Sites" because it does not exist or you do not have permissions.

Code with nuget packages updated - v8.3.0  -->  v8.4.0

[From]

PackageReference Include="Piranha" Version="8.3.0"
PackageReference Include="Piranha.AspNetCore" Version="8.3.0"
PackageReference Include="Piranha.AttributeBuilder" Version="8.3.0"
PackageReference Include="Piranha.Azure.BlobStorage" Version="8.3.0"
PackageReference Include="Piranha.Data.EF.SQLServer" Version="8.3.0"
PackageReference Include="Piranha.ImageSharp" Version="8.2.0-rc1"
PackageReference Include="Piranha.Manager.TinyMCE" Version="8.3.0"
PackageReference Include="Piranha.WebApi" Version="8.3.0"

[To]

PackageReference Include="Piranha" Version="8.4.2"
PackageReference Include="Piranha.AspNetCore" Version="8.4.1"
PackageReference Include="Piranha.AttributeBuilder" Version="8.4.0"
PackageReference Include="Piranha.Azure.BlobStorage" Version="8.4.0"
PackageReference Include="Piranha.Data.EF.SQLServer" Version="8.4.0"
PackageReference Include="Piranha.ImageSharp" Version="8.4.0"
PackageReference Include="Piranha.Manager.TinyMCE" Version="8.4.0"
PackageReference Include="Piranha.WebApi" Version="8.4.0"

Weirdly if i use the old branch (v8.3.0) and target the new copy of Piranha CMS sql database its working fine. I have verified the 'Piranha_Sites' table exists (assuming that is what its unable to locate) and the credentials used have all necessary permissions.

It appear the permissions exception error is NOT the issue from what i can establish, but have been unable as yet to determine why this exception is triggering.

Heads up I am still investigating if this is something unique to my implementation but would like to hear from the community if anyone else has experienced any issues upgrading Piranha nuget packages from v8.3.0  -->  v8.4.0?

Please close this issue if this is NOT relevant to the project, as i mentioned i am still investigating but wanted to report early in case anyone else is experiencing this issue.

**Comment by hedronn** [comment]
Hi Håkan thank you for your prompt reply. 

You are correct it was permissions! I suddenly realised that after a security audit the SQL credentials had been replaced with a least privilege account and this is indeed the issue on i am seeing with the upgrade. I should learn to trust the exception messages!

I will assign the original permissions to allow the Piranha CMS upgrade to do its work and then revert to the least privilege account. Many thanks for helping me realise this issue and get it resolved in a timely manner.

One question i am sure they exist but i could not locate any release notes for the v8.4x upgrade. Can you please point me in the right direction? Thanks again and good work on the project it’s awesome!

Closing this issue.

**Comment by tidyui** [comment]
Great! All of our release notes can be found under "Releases" here at the GitHub repo: https://github.com/PiranhaCMS/piranha.core/releases

**Comment by hedronn** [comment]
Excellent thank you again
