### ISSUE TITLE
Specify allowed blocks by content type

### ISSUE THREAD

**Issue by StatusDigitalGists** [PiranhaCMS/piranha.core#1318]
At the moment, when useBlocks is set to true in the page model, all the blocks are available to add.
This could be confusing to the CMS user if we have only built in styles for certain custom blocks, so It would be great if we could limit the blocks available you can add per page, similar to how a BlockGroup can have certain block types enabled.

**Comment by CrossBound** [comment]
I agree this is important... When building application-specific page templates it would be very helpful to have only applicable blocks available. This makes the user experience better because it's less confusing for the editor.
