### ISSUE TITLE
Update package dependencies

### ISSUE THREAD

**Issue by Paw261** [PiranhaCMS/piranha.core#1319]
![image](https://user-images.githubusercontent.com/47861091/91443317-76309580-e873-11ea-8494-be7e26d549a1.png)

Is my only option to downgrade to automapper 9 or has anyone figured this out? :)

**Comment by tidyui** [comment]
`Piranha.Data` is built with `AutoMapper 9.0` so downgrading will solve your problem. Apparently the new version of AutoMapper is not backwards compatible which causes the application to crash.

**Comment by adjdred** [comment]
How hard would it be to upgrade it to 10?

**Comment by tidyui** [comment]
We usually don't update dependencies on minor release for backwards compatibility. We will upgrade it for version `9.0`
