### ISSUE TITLE
Integration to current ASP.NET core web application with Identity

### ISSUE THREAD

**Issue by rmeshksar** [PiranhaCMS/piranha.core#1320]
Hi,
I really like the Piranha CMS and the features it provides. Thank you.

Trying to add Piranha CMS to my current ASP.NET Core application with ASP.NET Identity and Identity Server 4 with Single Sign On feature.

I would like to have all authentication and authorizations to be handled by the current system including all Piranha roles and claims and having hard time to set up services with proper seeding of data.

If I have both my setup for Identity and also use UseIdentityWithSeed of Piranha I am getting the following error:

System.InvalidOperationException: Scheme already exists: Identity.Application

Is there any instruction on how to integrate the CMS to an existing application.

Thanks.

**Comment by hedronn** [comment]
https://stackoverflow.com/questions/61486742/net-core-user-identity-for-both-website-and-cms-authentication

**Comment by tidyui** [comment]
Hi there @rmeshksar! If your application already have authentication setup I don’t think you should use Piranha’s packages at all. Instead just implement your own ISecurity service that validates against the current setup and make sure you give admin users the correct claims!

https://piranhacms.org/docs/architecture/authentication
https://piranhacms.org/docs/extensions/authentication
