### ISSUE TITLE
RouteCreationException

### ISSUE THREAD

**Issue by Paw261** [PiranhaCMS/piranha.core#1324]
![image](https://user-images.githubusercontent.com/47861091/91942810-d56f2980-ecfb-11ea-8ee5-1e29add1291e.png)

I am having a bit of trouble getting piranha up and running. Im using Piranha 8.4.2, in a .net core 3.1 application.

Im hoping you can help

**Comment by tidyui** [comment]
Hi there. Can you specify exactly what runtime of .NET Core you are using as we can't reproduce this issue!

**Comment by Paw261** [comment]
I am using .NET Core 3.1.6

**Comment by tidyui** [comment]
I will start by updating to the latest version `3.1.7` as I'm running `3.1.4`

**Comment by tidyui** [comment]
Sorry I mistook the numbers. I'm testing with sdk `3.1.401` which uses runtime `3.1.7` with out issues. Can you give me some further specs about your setup, i.e operating system and stuff like that!

**Comment by Paw261** [comment]
Windows 10 Home edition

We are trying to intergrate Piranha into an existing project.

Here is what I have done in the Startup file.

ConfigureServices:
![image](https://user-images.githubusercontent.com/47861091/91967990-4ae6f400-ed14-11ea-8b79-869651a9d255.png)

Configure:
![image](https://user-images.githubusercontent.com/47861091/91968009-4faba800-ed14-11ea-9537-b7839ccae163.png)

I have tried using a custom login, so it is compatible with the existing system, by using the ISecurity interface

Hope this helps

**Comment by tidyui** [comment]
My guess is that the MVC route config for the rest of your application isn’t working with the manager as it seems that the keyword action has been reserved by asp.net core.

The simple solution would be for us to just rename the parameter for these pages.

**Comment by tidyui** [comment]
After upgrading `master` to `.NET 5` we still can't recreate this issue, nevertheless we will change the name of the parameter to **page edit** and **post edit** to rule out the possibility of naming conflicts.
