### ISSUE TITLE
Editorconfig.json missing in MVC example

### ISSUE THREAD

**Issue by mrccarvalho** [PiranhaCMS/piranha.core#1337]
Hi,

I cloned the app and had this error:
Application startup exception: Editor config editorconfig.json not found!

I think that is the same issue mentioned here [[#842](https://github.com/PiranhaCMS/piranha.core/issues/842)]

Thanks.
Best regards.
Roger

**Comment by tidyui** [comment]
Which repository did you clone and which project did in the repository did you start?

Regards

**Comment by mrccarvalho** [comment]
Hi,
i cloned the repository master (the latest) and i used the mvc project template. 
The razor template project seems to be good.

thanks,
regards

**Comment by tidyui** [comment]
We'll take a look at it! Please note that the `master` branch is our development branch for version `9.0`. If you want the source code that resembles the currently release version, please use https://github.com/PiranhaCMS/piranha.core/tree/version/v8.4
