### ISSUE TITLE
PageField in a custom Block is not rendered in the manager

### ISSUE THREAD

**Issue by gitvadim** [PiranhaCMS/piranha.core#1343]
### Repro steps

1. Spin up a new project using the Razor template
2. Create a new Block with one PageField

```
    [BlockType(Name = "Tag List", Category = "Content", Icon = "fas fa-use")]
    public class TagListBlock : Block
    {
        public PageField Body { get; set; }

        public override string GetTitle()
        {
            if (Body != null && Body.Page != null)
            {
                return Body.Page.Title;
            }
            return "No page selected";
        }
    }
```
3. Register the Block in the app
4. Try to add the block to the page
5. The Body field will not have its editor rendered.

Can someone please point me to where I should be looking for the cause of the problem? I'd very much like to use this feature in my project, but I don't know where to start looking.

### What I've tried

1. Change the component to 'page-block' but it gives this error in the console:

`Error in render: "TypeError: Cannot read property 'primaryImage' of undefined"`

2. Further debugging showed that the model is null for this component in the manager, which does not happen for the page-block.

**Comment by tidyui** [comment]
I have copied your code to the `RazorWeb` test project and it renders as expected in the manager, see screenshot below:

![Skärmavbild 2020-10-12 kl  09 29 33](https://user-images.githubusercontent.com/781266/95717681-983c7680-0c6d-11eb-817e-7f6e6c34c8f6.png)

**Comment by dinukasal** [comment]
@tidyui is it mandatory to add fields of a custom block to be added as Vue components?
and do we need to add fields in the custom block in the Vue component as well?
