### ISSUE TITLE
Specify the number of columns in ColumnBlock

### ISSUE THREAD

**Issue by pauldbentley** [PiranhaCMS/piranha.core#1344]
Is there a way to specify the number of columns in the column block?

I note that each column has a class of `col-md` so it will render as many columns as added.

I have a requirement where some columns need to be 2, 3, or 4.

Is this possible?

**Comment by pauldbentley** [comment]
I suppose I could add multiple column blocks?

**Comment by tidyui** [comment]
Hi there, this is not possible atm and it all boils down to the fact that there's no support for field/block specific configuration. Here are a couple of other issues discussing the same thing but for regions #486, #386. The problem with blocks however are a bit different. On regions & fields you could add configuration values with attributes on the properties as these are defined in the model classes. On blocks however (as they are added by the editor), how would this configuration work. Would the number of columns be application-wide, i.e affecting all column blocks in the entire site, or just for specific page/post types?

**Comment by pauldbentley** [comment]
From an editor point of view, I could visualise the editor adding a column block then accessing some form of configuration panel just for that block.  This panel could contain options such as the column breaking e.g:

- Extra small: 
- Small: 2
- Medium: 3
- Large: 4
- Extra large: 

Then when the block is rendered in the CMS (and maybe the manager as well?) it would look at this configuration and add a class along the lines of `col-sm-2 col-md-3 col-lg-4`

**Comment by tidyui** [comment]
I totally see your use-case, however it's hard for us to provide these kind of functions out-of-the-box as we are not dependent on any css-framework for the client application. It's very hard for us to know what kind of features the website will provide, and giving the content editor too many specific choices can easily lead to the content not at all being translated to the website in the way they think it would be.

**Comment by pauldbentley** [comment]
Yes completely agree about not being dependent on the css-framework.  From a developer point of view, is there a solution where I can extend ColumnBlock and provide this functionality myself?

**Comment by tidyui** [comment]
Closing this as it's not possible to add item specific configuration to blocks. This will be available for regions in `9.0` however.
