### ISSUE TITLE
Pirahna_RoleClaims id field needs to have Identity Specification set to yes

### ISSUE THREAD

**Issue by zoinkydoink** [PiranhaCMS/piranha.core#1350]
1. Create a dummy razor cms site
2. Set it up to use SQL Server
3. Launch then go to /manager, getting an error that says cannot insert nulls into 'Id' field, after further inspection it seems that this field is not to be auto incremented on the generated tables, simply setting Identity Specification to Yes fixes this problem

**Comment by tidyui** [comment]
Did you change the identity package to SQLServer as well?

**Comment by zoinkydoink** [comment]
Yes I did

**Comment by tidyui** [comment]
The migrations for SQL Server clearly specifies that column as being an identity column (https://github.com/PiranhaCMS/piranha.core/blob/master/identity/Piranha.AspNetCore.Identity.SQLServer/Migrations/20180516203540_InitialCreate.cs#L56). However the migration is database specific so if a package for another database is used you would run into the problem you’re describing

**Comment by tidyui** [comment]
I'm closing this as not reproducible. If you can reproduce the issue, please open a new one and clearly provide a step-by-step process of how to reproduce it, on what operating system you are running Piranha and what database you are using.

Best regards
