### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by msavara** [PiranhaCMS/piranha.core#1353]
I published to azure from the latest version from releases tab. But it doesn't work. I didn't change anything. Only download source code, open in visual studio. Create publish on RazorWeb to azure and nothing more
does it work for someone? does anyone know how to solve this? https://piranhacms.azurewebsites.net/

**Comment by r4g-jon** [comment]
Hi @msavara 

Here's a couple of things to check:

1. On the error page, you should have a link to the Azure event viewer - that will tell you specifically what the error is.

2. Have you checked your connection strings are correct? Is the database server behind a firewall? Have you added the IP to the firewall?

3. Are you using a Redis cache to cache data? If so, check the connection strings and firewall.

Hope this helps!

**Comment by tidyui** [comment]
The `RazorWeb` is a test-project for development purposes, it's not intended as a starting template for your projects. For this we have our template package `Piranha.Templates` which is available on `NuGet`.

Apart from this, the error you're getting can be related to that the test-projects tries to seed some test data in `Startup`, but the files used in the seed is most likely not included when you publish the project. This means it will fail and the entire application will crash before starting.

Best regards

**Comment by msavara** [comment]
> The `RazorWeb` is a test-project for development purposes, it's not intended as a starting template for your projects. For this we have our template package `Piranha.Templates` which is available on `NuGet`.
> 
> Apart from this, the error you're getting can be related to that the test-projects tries to seed some test data in `Startup`, but the files used in the seed is most likely not included when you publish the project. This means it will fail and the entire application will crash before starting.
> 
> Best regards

Perfect, thank you very much for quick response :) 
I tried to go with empty template. with "dotnet new piranha.mvc" , i opened it in visual studio. and message was : 
![image](https://user-images.githubusercontent.com/34938369/94689244-edec5700-032e-11eb-8d85-4489ce32361e.png)

**Comment by tidyui** [comment]
@msavara Hi there! You can't give your project the same name as a NuGet package you're referencing. It's a limitation in `NuGet.exe`.

**Comment by msavara** [comment]
> @msavara Hi there! You can't give your project the same name as a NuGet package you're referencing. It's a limitation in `NuGet.exe`.

Sorry, thank you. now i'm feeling like idiot :D hehe. thanks.

**Comment by tidyui** [comment]
Don't :) 

#981 #1241 #1263 #1271 #1296

/Håkan
