### ISSUE TITLE
Feature request: Enable config option to minify css+html and compress output (Brotli, GZip)

### ISSUE THREAD

**Issue by shapeh** [PiranhaCMS/piranha.core#1358]
For SEO purposes it would be nice with config options to Minify output (css, html and possibly js).

We are using WebMarkupmin, ResponseCaching and ResponseCompression  in many of our other projects to improve rankings on search engines.

**startup.cs**

        public void ConfigureServices(IServiceCollection services)
        {
           .....

            // response caching 
            services.AddResponseCaching();

           // minification
            services.AddWebMarkupMin(options =>
            {
                options.AllowMinificationInDevelopmentEnvironment = true;
                options.AllowCompressionInDevelopmentEnvironment = true;
                options.DisablePoweredByHttpHeaders = true;
            })
            .AddHtmlMinification(options => options.MinificationSettings.RemoveRedundantAttributes = true)
            .AddHttpCompression();

            // compress the response to browsers to enable speedier delivery of the website content to browsers:
            services.AddResponseCompression(options =>
            {
                options.Providers.Add<BrotliCompressionProvider>();
                options.Providers.Add<GzipCompressionProvider>();
            });

            }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
          ....

                // minify html on output
                //https://github.com/Taritsyn/WebMarkupMin 
                app.UseWebMarkupMin();

                app.UseResponseCompression();
                app.UseResponseCaching();
        }

**Comment by tidyui** [comment]
As Piranha is headless / decoupled we don't include features that are specific to the client application. However, since Piranha in essence is just added into the `ASP.NET` as middleware components it shouldn't be an issue for you to use these components together with Piranha in your application.

Regards

**Comment by shapeh** [comment]
@tidyui - okay, well understood.
