### ISSUE TITLE
ability to add html block

### ISSUE THREAD

**Issue by codesoroush** [PiranhaCMS/piranha.core#1371]
i can't add html text in blocks , please put this ability
when we want change website template it's necessary to can add html manually

**Comment by tidyui** [comment]
We provide a lot of different blocks for building content, HTML is one of them. https://piranhacms.org/docs/content/blocks

Please clarify exactly what you’re trying to do that you feel isn’t working, what version of Piranha you’re using and how you have created your project.

Regards

**Comment by codesoroush** [comment]
i dont know  am i doing this wrong or not ?
 when want  add some html to page ,
1.  i click on plus ( + ) button
2. choose "Content"  block
but when i choose "Content" i face with text editor (POWERED BY TINY)
and in this area i can't add plain html
(html rendered as text)

**Comment by tidyui** [comment]
We do not have the source editor plugin enabled by default. You can read here how to adjust the settings of the tiny editor in piranha.

https://piranhacms.org/docs/architecture/html-editors/tiny-mce

Best regards

**Comment by codesoroush** [comment]
again thanks for your  favorand response ,
my idea was , add another block with html name , 
for editor we can use textarea and it's enough.
i already did that for myself
and wish u do that officially.

ok i got my answer 

best regards

**Comment by codesoroush** [comment]
Hello and best regards
It's really annoying that you can't inject html code directly into the page

I used the tiny mce "html editor" as your guide, but my problem now is that tiny mce automatically deletes empty tags (like font awesome tags).

It took me a lot of time to figure out the problem and how to solve it

Please put a simple editor which we can put HTML on the page without tiny mce.

accourding to link in below
https://stackoverflow.com/questions/26732501/configure-tinymce-for-use-of-font-awesome-icons-in-composite-c1
for each empty tag we must set  &nbsp in empty tag to tiny mce find out shoulnt remove tag 

 like <span class="fa fa-bus">&nbsp;</span>.

i cant do this for every tag, and i changed all configuration and didnt find out how to fully solve this problem.


plz if its ok , just add a simple editor that can accept html

**Comment by tidyui** [comment]
@codesoroush Do you mean add a WYSISYG editor with better code editing features, or do you just mean a simple text block that you can add custom HTML into without preview in the manager UI?

**Comment by codesoroush** [comment]
simple text editro that we can add custom html , yes i want this
