### ISSUE TITLE
User permission

### ISSUE THREAD

**Issue by GuilhermeNovaes233** [PiranhaCMS/piranha.core#1374]
How to remove SysAdmin from the managing user when the user is of lower level? I would like the user to be allowed to create other users but following the same rules

**Comment by tidyui** [comment]
There's no such rule atm. If the logged in user has permissions to **delete users** he can delete every user. There's no hierarchical grouping on what user roles are "higher" and which are lower.

**Comment by GuilhermeNovaes233** [comment]
Hello, thanks for your reply! User permissions solved my problem. I didn't even need to use hierarchy or something
