### ISSUE TITLE
Indesired elements with TinyMCE 5.0.3

### ISSUE THREAD

**Issue by axunonb** [PiranhaCMS/piranha.core#1379]
Excerpt contains single ```<br>``` even if left empty in manager
```cs
StandardPage.SinglePage<StandardPage>.Data.Excerpt
StandardPost.SinglePost<StandardPost>.Data.Excerpt
```
This way it cannot simply be checked with ```string.IsNullOrEmpty```.

**Comment by axunonb** [comment]
PiranhaCms is shipping with TinyMCE Version: 5.0.3 (2019-03-19) 
This version of the editor has some bugs, which were obviously fixed in later releases.
One the bugs are:
* ```<br>``` tags are inserted into HTML posted to the server, where they shouldn't (see my original issue)
* ```<br mce_bogus="1">``` are inserted into HTML posted to the server, where they shouldn't (see [this issue](http://archive.tinymce.com/forum/viewtopic.php?pid=94022) in the TinyMCE forum.
There may be a good reason for not deploying the most recent version. Is there any?

**Comment by tidyui** [comment]
There's no particular reason other than that it hasn't been upgraded. The current version is `5.6.2`, so we'll just have to double check compatibility to the custom plugins we have developed for Piranha for Link and Media Library integration.

**Comment by tidyui** [comment]
Now this could absolutely be done as a service release for `8.4` for the package `Piranha.Manager.TinyMCE` but we don't have the time to look at it straight away. If you want it released for `8.4` you could update the javascript files in the repository and send a PR, but make sure you work off the `versions/v8.4` branch and send a PR back to that branch!

Best regards

**Comment by axunonb** [comment]
PR https://github.com/PiranhaCMS/piranha.core/pull/1427 for TinyMCE 5.6.2

**Comment by axunonb** [comment]
Even with TinyMCE 5.6.2 the [issues](https://github.com/PiranhaCMS/piranha.core/issues/1379#issuecomment-744400935) exist. What I understand from TinyMCE, editor's content should be retrieved using the API
```tinyMCE.get('some_area').getContent()  // some_area is the ID of the TinyMCE Textarea```
instead of reading the content with jQuery
```$(#some_area).contents().html()```
With the latter, the TinyMCE "internal" elements (not displayed in the editor) like ```<br mce_bogus="1">``` are included, while they are not using the API. 
I can definitely confirm, that always exactly the "internal" content of the element with class "mce-content-body" is stored in the database. Unfortunately I couldn't figure out how content is retrieved with Piranha. Still hope this gives a hint into the right direction.

**Comment by filipjansson** [comment]
Thanks!

I did some testing and couldn´t reproduce this behavior on the [html-field](https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/assets/src/js/components/fields/html-field.vue#L17), the field uses the `getContent()` method as describe above, and when inspecting it looks good.

But the `html-block` do get the extra markup (`<p><br data-mce-bogus=\"1\"></p>`) when it´s empty and saved.
And as you describe, [the block don´t use the getContent() method](https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/assets/src/js/components/blocks/html-block.vue#L17).

**Comment by tidyui** [comment]
@filipjansson Yes I see that the two blocks retrieve their data differently, this is probably the case with the excerpt as well as this is probably based off the `html-block` component. We should try to just replace `e.target.innerHTML` with `tinyMCE.activeEditor.getContent()` and see if it solves the problem.

**Comment by tidyui** [comment]
@filipjansson Do you have the time to test this?

**Comment by filipjansson** [comment]
@tidyui I have tried it and it seems to solve the problem.

**Comment by axunonb** [comment]
Thanks, awesome!

**Comment by tidyui** [comment]
Version `8.4.2` of `Piranha.Manager` & version `8.4.1` of `Piranha.Manager.TinyMCE` is now available on NuGet.
