### ISSUE TITLE
.NET 5

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#1400]
Hello!

It's been a while since my last ticket, but this one will be quick. As I have recently read more and more about .NET 5, being the successor of .NET Core 3.1 do you have any plans on using it in Piranha CMS?

Ref:
https://docs.microsoft.com/en-us/dotnet/core/dotnet-five

Regards,
Chris

**Comment by filipjansson** [comment]
Hi!

Yes, we have already upgraded Piranha to .NET 5, but we have moved the development to a version branch, [version/9.0](https://github.com/PiranhaCMS/piranha.core/tree/version/v9.0).

We have talked about using this type of structure in the future, so the master branch will always be in sync with the latest NuGet packages.

BR
Filip

**Comment by tidyui** [comment]
We will merge into master as soon as `AppVeyor` and `Travis` supports building on `.NET 5`

**Comment by tidyui** [comment]
I'm adding this to the `9.0` release as it's a part of this.
