### ISSUE TITLE
Hidden page still appearing in sitemap.xml

### ISSUE THREAD

**Issue by emleder** [PiranhaCMS/piranha.core#1403]
If a page is unpublished, then it will not appear in the sitemap.xml, but if a page is published but marked IsHidden it will still be listed.

**Comment by tidyui** [comment]
Hi there! This is a duplicate of #1000 which will be released in `9.0`. The `IsHidden` was never intended to affect the generation of `Sitemap.xml`, it was intended to be used for visually hiding pages when rendering the application menu. However in `9.0` we're adding a bunch of new features for SEO and Sitemap generation.

**Comment by emleder** [comment]
Awesome thanks for the update. I tried searching for an open issue but couldn't find it. Keep up the great work
