### ISSUE TITLE
Issues during adding Video or Audio Blocks.

### ISSUE THREAD

**Issue by MehranDHN** [PiranhaCMS/piranha.core#1405]
I'm using Piranha 8.3.0 and I got error message in console when I'm clicking Save or Publish button to save Videos (MP4) or Audios(MP3) content.
Am I missing something in configuration?
Thanks.

![image](https://user-images.githubusercontent.com/9722881/99394969-07545d00-28f5-11eb-8d75-1dfb662c26c1.png)

**Comment by tidyui** [comment]
Hi there! This is a bug, it was fixed and release in `8.4`, see #1292
