### ISSUE TITLE
Allow limit Post Type use for a Archive Type

### ISSUE THREAD

**Issue by gioxoay** [PiranhaCMS/piranha.core#1410]
Hi everyone,
I created `IntroPost` and `IntroArchive` model, from `IntroArchive` can limit only create post type `IntroPost` by attribute `[PageTypeArchiveItem(typeof(IntroPost))]`. BUT from other archive type such `StandardArchive`, it's can create both `IntroPost` & `StandardPost`, then can we have way limit only can create `IntroPost` from `IntroArchive` only?

**Comment by tidyui** [comment]
Hi there! You achieve this by adding a PageTypeArchiveAttribute to StandardArchive as well that only allows post of the type StandardPost!

Regards

**Comment by gioxoay** [comment]
Thank you for help!

I updated:
```
[PageTypeArchiveItem(typeof(StandardPost))]
```
