### ISSUE TITLE
Unable to locate the right view for the custom pagetype

### ISSUE THREAD

**Issue by ronsplinter** [PiranhaCMS/piranha.core#1414]
I added a new page type to the Models folder.

![image](https://user-images.githubusercontent.com/8985712/100463669-7e93a900-30cc-11eb-9f94-acee14906656.png)

I also added a ProductPage.cshtml to the /Views/Cms folder for the new page model

![image](https://user-images.githubusercontent.com/8985712/100463775-ab47c080-30cc-11eb-9b13-11ad601197b8.png)

I added the page type to the configure method in the startup.cs

![image](https://user-images.githubusercontent.com/8985712/100464418-dda5ed80-30cd-11eb-9365-4ce6af1106bc.png)

Now when I add a ProductPage and preview it, I get the following error:

![image](https://user-images.githubusercontent.com/8985712/100464178-696b4a00-30cd-11eb-956f-fdfa5c1e9d6b.png)

Somehow my view for the custom product page is not located. Why is this? What am I doing wrong?

**Comment by tidyui** [comment]
Hi there, you need to add a PageTypeRoute attribute and specify which route (or view if you use MVC) should be used, otherwise the default route /page will be used. You can find more details here:

https://piranhacms.org/docs/content/pages

Regards

**Comment by filipjansson** [comment]
Hi!

Also, I notice in your screenshot that `ProductPage` inherit `Page<StandardPage>`, should it not be `Page<ProductPage>`?
Because it looks like the error is thrown in the `StandardPage` view.

BR
Filip

**Comment by ronsplinter** [comment]
Hi!

thanks for your help! It was a combination of Page<ProductPage> and adding the PageTypeRoute attribute. Thanks for your help guys!
