### ISSUE TITLE
Request: Add support for templates to TinyMCE

### ISSUE THREAD

**Issue by Nauvran** [PiranhaCMS/piranha.core#1430]
Currently there is no way to add custom templates to TinyMCE. 
Therefore there is no way for users to add buttons, FaQ dropdowns and other magical stuff inside the text area.

**Comment by tidyui** [comment]
Hi there @Nauvran. With 15 years of experience building CMS-platforms I **truly** believe this is not a good way to use a WYSIWYG editor. Inserting too advanced HTML-components usually ends up with the unknowing content manager messing some HTML up along the way corrupting the rendering of the public website. This is also why we have lots of other ways to build content in Piranha, such as `Block Groups`, `Regions` and `Fields`. This also means I'm a little bit reluctant to add this as a simple JSON parameter into the `editorconfig`.

However, you can customize your TinyMCE initialization any way you want simply by overriding the method `piranha.editor.addInline(...)` in a custom js-file and adding it to the editor.

### Default TinyMCE implementation of addInline()

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.TinyMCE/assets/piranha.editor.js#L8

### Documentation on how to add custom manager resources

https://piranhacms.org/docs/manager-extensions/resources

Best regards

**Comment by Nauvran** [comment]
Thats a fair point
I'll try and see if I can't get it working within the existing systems

Thanks for the help!
