### ISSUE TITLE
Error When using RTL Languages in Taxonomies

### ISSUE THREAD

**Issue by MehranDHN** [PiranhaCMS/piranha.core#1439]
I'm using Piranha 8.4.0 and it seems it's not possible to use RTL languages in taxonomies. Am I missing something?
![image](https://user-images.githubusercontent.com/9722881/103033120-fc858b80-4576-11eb-9a84-a3c3ed6b9340.png)

**Comment by tidyui** [comment]
Piranha uses the same method to generate slugs for taxonomies as for pages, posts, so if you’ve overridden the GenerateSlug method it **should** apply to taxonomies as well.

**Comment by codesoroush** [comment]
@MehranDHN  go to Piranha > Utils.cs  and change line 83 with this >>>


            slug = Regex.Replace(slug, @"[^a-z\u0600-\u06FF0-9-/ ]", "").Replace("--", "-");

**Comment by tidyui** [comment]
@codesoroush I'm no expert in how these characters should be translated into url-safe characters, but the line you provided only seem to **remove** characters between a certain interval. This would mean that if all characters are "special characters" the generated slug will be empty. @MehranDHN is there some kind of mapping available of what characters should be substituted with what to provide URL safe strings?

**Comment by codesoroush** [comment]
@tidyui  this regex is persian and arabic alphabet range (\u0600-\u06FF0)

**Comment by tidyui** [comment]
Adding this to `9.0`. Setting you as assignee @codesoroush as you provided the solution, I will however push the changes to the repo.
