### ISSUE TITLE
Upgrade TinyMCE Please

### ISSUE THREAD

**Issue by ddavisfw** [PiranhaCMS/piranha.core#1443]
TinyMCE Version 5.0.3 is a really strange version of TinyMCE. Version 5.0.4. is very different and actually works with things like CodeMirror. Can we upgrade this for PiranhaCMS 9.0 please? There is so much that simply doesn't work right because that version of TinyMCE is kind of a black hole.

**Comment by tidyui** [comment]
The latest version of Piranha.Manager.TinyMCE (8.4.1) is already updated to version 5.6.2.
