### ISSUE TITLE
Add year and month in URL?

### ISSUE THREAD

**Issue by asim-rehman** [PiranhaCMS/piranha.core#1444]
Hi,

For the blog section is it possible to organise the URLs to follow a structure such as /blog/year/month/post ? 

I can see currently without rewriting any code, I could either change each slug for posts or add sub blogs under blog to get this affect. Although this is inefficient.

It would be nice to be able to have placeholders in the slug e.g. {year}/{month} for parent pages which are automatically populated for child pages.

**Comment by tidyui** [comment]
You could use the hook OnGenerateSlug to override the default slug generation and create your own!

https://piranhacms.org/docs/application/hooks

Regards
