### ISSUE TITLE
Any Advise Deploying Piranha in Azure App Service

### ISSUE THREAD

**Issue by MehranDHN** [PiranhaCMS/piranha.core#1446]
Hi There, Any advise deploying Piranha 8.4.0 with SQLLite DB on Azure App Service?
I'm using default connection string with piranha.mvc template. When I test locally everything is fine but it seems Azure doesn't see Piranha.db and redirects to initial Default page with Seed data.
Thanks.

  "ConnectionStrings": {
     "piranha": "Filename=./**piranha.db**"
  }

**Comment by tidyui** [comment]
If you want to include your local SQLite database in your deploy, make sure you’ve added the db file to you csproj!

https://stackoverflow.com/questions/54762744/net-core-include-folder-in-publish/54762901

Regards

**Comment by tidyui** [comment]
But as always we generally advice against using SQLite as production database, especially if you expect a lot of traffic. As soon as you need to scale up your application so it runs in a cluster, having a disk based database is not 100% reliable. Azure has cheap entry level plans for other database such as SQLServer as well!

Regards

**Comment by MehranDHN** [comment]
Thank you very much.
