### ISSUE TITLE
Is there the support of JWT login flow?

### ISSUE THREAD

**Issue by biapar** [PiranhaCMS/piranha.core#1455]
Is there the support of JWT login flow?

**Comment by tidyui** [comment]
We (the core team) uses plain identity with cookies in 99% of the applications we deploy. This is the reason why this is the only module we provide for authentication.

However, authentication is totally pluggable and you can login any way you like. The manager interface only looks at claims, not how they got assigned to the current user.

Best regards

**Comment by biapar** [comment]
To use Piranha as headless cms to retreive data for react front end and mobile app.

**Comment by tidyui** [comment]
We always recommend writing your own api controller for these purposes which can authenticate incoming requests any way you want. The basic provided `WebApi` packages provide rather simple functionality and exposes the entire backend models, in many cases you'll want to tailor the models to your application.

**Comment by biapar** [comment]
Is there some axamples?
