### ISSUE TITLE
Bug: collapsing a generic block doesn't work

### ISSUE THREAD

**Issue by horacioj** [PiranhaCMS/piranha.core#1456]
Hi,

A block defined like this cannot be collapsed in the Manager when editing a page.

`[BlockType(Name = "A block", Category = "A category", Icon = "fas fa-columns", Component = "a-block", IsGeneric = true)]`

The title is updated as if it was collapsed, but the block isn't collapsed.

Thanks

**Comment by tidyui** [comment]
I can't reproduce since I don't have access to your `Vue.js` component `a-block`. However, creating a pure generic block like this doesn't introduce any problems with collapsing:

~~~ csharp
using Piranha.Extend;
using Piranha.Extend.Fields;

namespace RazorWeb.Models.Blocks
{
    [BlockType(Name = "Generic Block", Category = "My Category", Icon = "fas fa-fish", IsGeneric = true, ListTitle = "Title")]
    public class MyGenericBlock : Block
    {
        public StringField Title { get; set; }
        public TextField Body { get; set; }
    }
}
~~~

<img width="980" alt="Skärmavbild 2021-01-07 kl  06 56 37" src="https://user-images.githubusercontent.com/781266/103856798-8e33e380-50b5-11eb-9705-b488a6fa575e.png">

<img width="984" alt="Skärmavbild 2021-01-07 kl  06 56 53" src="https://user-images.githubusercontent.com/781266/103856823-97bd4b80-50b5-11eb-9e4c-66a87c23f08f.png">

**Comment by horacioj** [comment]
Sorry, I thought it would be easier to reproduce.
Adding a Vue component you can see the behavior.
Example:


**Model**

 
```
[BlockType(Name = "Generic Block", Category = "My Category", Icon = "fas fa-fish", IsGeneric = true, Component = "generic-block" )]
    public class MyGenericBlock : Block
    {
        public StringField Title { get; set; }
        public TextField Body { get; set; }
    }
```


**generic-block.vue:**


```
<template>
<div>  
   <string-field v-bind:uid="uid + StringField .meta.id" v-bind:meta="StringField .meta" v-bind:model="StringField .model" ></string-field>
   <text-field v-bind:uid="uid + TextField .meta.id" v-bind:meta="TextField .meta" v-bind:model="TextField .model" ></text-field>
</div>    
</template>

<script>
export default {
    props: ["uid", "model", "meta"],
    computed: {
        StringField () {
            return this.model.find(element => element.meta.id === 'StringField ');
        },
        TextField () {
            return this.model.find(element => element.meta.id === 'TextField ');
        }     
    }
}
</script>
```

**Comment by tidyui** [comment]
I found the issue. The root element of the template needs to have the class `block-body`. When a block is collapsed the element with the class `block-body` is hidden.

**Comment by tidyui** [comment]
I'll update the documentation in https://github.com/PiranhaCMS/piranha.core.docs/blob/master/src/06.%20Extensions/02.%20Blocks.md to reflect this.

**Comment by tidyui** [comment]
Documentation has been updated. https://piranhacms.org/docs/v8/extensions/blocks

**Comment by horacioj** [comment]
Thanks, you rock!

**Comment by tidyui** [comment]
As a side note you can't actually use the name `generic-block` for any custom block as this name is already used by the internal generic block rendering component. Took me a little while to realize why nothing happened when I used your example :)

**Comment by horacioj** [comment]
Oops sorry, it wasn't a real component, just the simplest example I could think of to write it here...
