### ISSUE TITLE
[Bug] Paging is broken in Examples

### ISSUE THREAD

**Issue by MikeBairdRocks** [PiranhaCMS/piranha.core#1463]
I haven't investigated too far but I was using the latest stable version and also tried the latest 9 beta RazorWeb example and paging seems to not be working in an archive. The same posts are shown when navigating to page/2 route.

![image](https://user-images.githubusercontent.com/240362/104026572-c0b01000-518b-11eb-9716-8dc78291c717.png)

**Comment by tidyui** [comment]
It appears the query parameter `page=`used in the routing,  in some version of `.NET Core` turned into a reserved keyword so the parameter got lost. Thanks for noticing!
