### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by airfanBG** [PiranhaCMS/piranha.core#1472]
Hi! I have a strange problem with login. When I run my project in debug I can login with "admin" and "password". When I deploy my project to IIS and try the same login it returns me to url "/manager/login?ReturnUrl=%2Fmanager". Where is the problem. Greetings!

**Comment by tidyui** [comment]
Given that this is not a general issue in Piranha it would have to do with how your IIS is configured. Since the manager uses cookie based authorization by default, are cookies discarded, how is the security features configured in your IIS?

**Comment by airfanBG** [comment]
Oh thank you so much. Of course cookies, this was the problem. Sorry for my stupid question :)

**Comment by tidyui** [comment]
No problem! Glad you sorted it out!
