### ISSUE TITLE
Separate wwwroot to another server

### ISSUE THREAD

**Issue by kttary** [PiranhaCMS/piranha.core#1477]
Is it possible to separate wwwroot folder to another server?

**Comment by tidyui** [comment]
Could you please elaborate on your question.

**Comment by kttary** [comment]
wwwroot is hosting static files such as uploaded images, css and so on. It can be very large depend on the website content but don't need as good as application server specification. If we able to separate statics file with application, we have 3 layer which database, app and static files. if our cms very busy, we can load balancing cms server only (assume we store database on powerful postgre server). Statics file remains on the single server and all cms server accessing one static file server.

**Comment by tidyui** [comment]
Hi there, sorry for not responding. As you totally control the HTML-markup of your web application you can load all static assets from anywhere you like, including another server. As for media assets uploaded through the manager, we provide functionality for storing these either in the web applications `wwwroot` **or** in `Azure Blob Storage`. Community packages also exists for using `AWS S3 Storage` and you could also write your own implementation to store uploaded files anywhere you like.
