### ISSUE TITLE
Implementing authentication for the User pages and the Manager pages.

### ISSUE THREAD

**Issue by bthirumanyam** [PiranhaCMS/piranha.core#1481]
Hi @tidyui , 
We have created an MVC project with Piranha CMS. We are trying to have AAD authentication for user as well as Manager. We were able to authenticate the user using AAD but for the manager we are not able to do . 

So we are trying to use the existing manager interface with admin and password as credentials. This is also not working.

Could you please let us know if it is possible to have Piranha CMS manager interface as it is and authenticate the user with AAD or would you suggest any other way ?

**Comment by tidyui** [comment]
I am no expert in running different identification methods for different parts of the same website. However, one last resort is always to publish the manager to another URL than the public website. Just remember to use distributed cache as the applications won't share the same memory area.
