### ISSUE TITLE
"Excerpt" is always null when saving a post

### ISSUE THREAD

**Issue by acastaner** [PiranhaCMS/piranha.core#1484]
I'm running into an issue where I can't make head or tails. Whenever I save a post's draft, the "excerpt" value is "null." If I had other blocks to the post, then those blocks are used instead.

See the image below where you can see I typed something in the "excerpt" field of the post, but when I save (ie: send a HTTP POST) the "excerpt" value is set to "null." I tried with both Firefox and Chrome. I'm using Piranha Manager 8.4.2 and Piranha.Manager.TinyMCE. Everything has been built using the dotnet razor template.

This shows the problem: https://imgur.com/a/BZZHkQa

Is there any way for me to fix this? I'm really struggling to understand what's happening, it seems to have started behaving like this when I updated the Manager to 8.4.2 (from 8.4.1) and TinyMCE to 8.4.1 (from 8.4.0). Now even downgrading doesn't seem to fix the problem anymore, like I said I can't make heads or tails of this problem.

**Comment by tidyui** [comment]
TinyMCE is a real pain when it comes to caching it's resources in the web browser. When you upgrade **or** downgrade, remember to clear all browser cache to make sure that not old parts of Tiny MCE are present in the cache.

**Comment by tidyui** [comment]
Now there was an update how HTML-excerpts were extracted from the DOM in version `8.4.2` (https://github.com/PiranhaCMS/piranha.core/commit/0c8c68fe1a5eced0dd018465e4070931d87b6f38) This service release also included an update to the Tiny MCE editor.

**Comment by tidyui** [comment]
@acastaner Did you manage to solve this issue?

**Comment by acastaner** [comment]
Nope. I tried every permutation, cleared cache, etc., never got it to work unfortunately.

**Comment by tidyui** [comment]
`Piranha.Manager 8.4.3` has been submitted to NuGet.
