### ISSUE TITLE
Localization of Manager UI

### ISSUE THREAD

**Issue by mbogomolsky** [PiranhaCMS/piranha.core#1487]
Hi,
I understand that there is Piranha.Manager.Localization library that would allows us to show to end user localized manager UI 

Can someone please point me to some example how this library needs to be used or configured?

Thanks in advance!!!

**Comment by tidyui** [comment]
Hi there! You set the culture of the application, either in your `Startup.cs` or by using a middleware component. For example.

~~~ csharp
var cultureInfo = new System.Globalization.CultureInfo("en-US");
System.Globalization.CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
~~~

**Comment by mbogomolsky** [comment]
HI,
thank you for answer. 

I am still a bit confused by the answer. I have made changes you suggested and expected to see Manager in French but it is still loading in English

![image](https://user-images.githubusercontent.com/72209242/106302777-6274cb00-6227-11eb-9236-029fd0bd7798.png)

**Comment by mikaellindemann** [comment]
If you by any chance run dotnet in alpine-based docker images, additional languages should be installed in the image.

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS runtime

# Install cultures (same approach as Alpine SDK image)
RUN apk add --no-cache icu-libs

# Disable the invariant mode (set in base image)
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```

**Comment by mbogomolsky** [comment]
Thank you for your answer!!

I am just running it as regular asp.net core app in Visual studio, no container
