### ISSUE TITLE
Request to support AWS S3 storage

### ISSUE THREAD

**Issue by yang-xiaodong** [PiranhaCMS/piranha.core#1509]
Hello there,

This is a great cms library for .NET and has a great design.

I see that you alreay support Azure Blob as the storage, do you have any plan to support AWS S3 as storage or accept PR?

Thanks

**Comment by tidyui** [comment]
As we (the core team) don’t use AWS and therefore have limited knowledge we won’t provide packages for it.

There are however already two packages available for S3 storage for Piranha developed by other members of the community!

https://www.nuget.org/packages/Flagscript.PiranhaCms.Aws.S3Storage/

https://www.nuget.org/packages/Amberglass.PiranhaCMS.AWSS3/

Regards
