### ISSUE TITLE
Add hooks for content

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#1511]
The classic hooks (`OnLoad`, `OnBeforeSave`, `OnAfterSave`, `OnBeforeDelete`, `OnAfterDelete`) should be available for content.

**Comment by jensbrak** [comment]
Does the content hooks work (or rather should they work) the same as for pages, posts and comments? If so, I might have a go on this one if no one beats me to it (I'm messing around with similar stuff anyway). 
I'll add a heads up if I do so and if I don't I haven't done anything either. :)

**Comment by tidyui** [comment]
As we're not changing the implementation at this point they should work **exactly** the same as for pages & posts!

**Comment by jensbrak** [comment]
I'm picking this one up now. Is the base class for the content supposed to be ContentBase or GenericContent?

**Comment by tidyui** [comment]
The base class for content is `GenericContent`. `ContentBase` is the base for all content (Content/Pages/Posts/SiteContent)

**Comment by tidyui** [comment]
It was all very clear until we introduced a top level model with `Content` in its name :P

**Comment by jensbrak** [comment]
Ah, kinda suspected that but good to know. 
Work done (not much code I know) but I'm adding a couple of test cases too and running some manual tests in addition.

**Comment by jensbrak** [comment]
In  `core/Runtime/HookManager.cs` add a property for `GenericContent` hook:

``` csharp
        /// <summary>
        /// Gets the hooks available for generic content.
        /// </summary>
        public ServiceHooks<GenericContent> GenericContent { get; } = new ServiceHooks<GenericContent>();
```
