### ISSUE TITLE
Excerpt text overwritten by text from HTML fields

### ISSUE THREAD

**Issue by SamBray** [PiranhaCMS/piranha.core#1516]
Hi, after updating the manager package from 8.4.1 to 8.4.2 and TinyMCE package from 8.4.0 to 8.4.1 I am having an issue with contents items' excerpts that I was hoping to see if you can reproduce.

Setup: Page with excerpt and blocks sections, using TinyMCE as the WYSIWIG editor for the manager with the default configuration and everything running off of the package versions specified above.

Steps (performed in Chrome with Disable Cache active in devtools):
1. Create a page
2. Add text to the excerpt
3. Add the built-in Content/HTML block and add some different text
4. Click into and out of the excerpt field

Result: The text from the HTML block replaces the text in the excerpt field. If you continue to click the excerpt and HTML fields (whether these be in the Content block, a custom block with an Html Field, a region, etc.), whenever the excerpt loses focus the text is always replaced with the text from the last HTML field clicked.

**Comment by eric-wilson** [comment]
This is happening to me too.  It's a real pain. 😔

**Comment by tidyui** [comment]
`Piranha.Manager 8.4.3` has been submitted to NuGet.

**Comment by tidyui** [comment]
Make sure to shift-reload the page & post edit views in the manager after upgrading so you don’t have any cached assets.
