### ISSUE TITLE
CultureInfo with Chinese

### ISSUE THREAD

**Issue by AllPIM** [PiranhaCMS/piranha.core#1519]
In the Chinese language family, Traditional Chinese and Simplified Chinese are distinguished. Currently, it is found that you specify "zh" as Traditional Chinese.

"Some CultureInfo objects differ depending on the underlying platform. In particular, "zh-CN", or Chinese (Simplified, China) and "zh-TW", or Chinese (Traditional, Taiwan), are available cultures on Windows systems."

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-5.0

**Comment by tidyui** [comment]
This is beyond my knowledge. We use the site **Crowdin** for managing languages where we have added both Traditional & Simplified Chinese (see screenshot).

<img width="1197" alt="Skärmavbild 2021-02-25 kl  15 43 25" src="https://user-images.githubusercontent.com/781266/109169746-6ccfa980-7780-11eb-8b79-0257571d33ee.png">

This platform is then responsible for creating the resource files with the correct culture specification. These are all of the available Chinese variants in the Crowdin platform.

<img width="254" alt="Skärmavbild 2021-02-25 kl  15 46 21" src="https://user-images.githubusercontent.com/781266/109169954-a0aacf00-7780-11eb-91fe-ad297185f2c0.png">

If there's something wrong with this setup, then an issue has to be opened with the people maintaining the translation platform.

Best regards

**Comment by AllPIM** [comment]
Thank you for your response.

I translated Traditional Chinese and Simplified Chinese on Crowdin, and tested it on Piranha Manager UI, but I saw that the Piranha.Manager.Localization project references different language sources, maybe you can check again.

Content.zh.resx.   New translations Content.resx (Chinese Simplified)
Module.zh.resx.    New translations Module.resx (Chinese Traditional) (#1501)

In another case maybe can use different files like Menu.zh-TW.resx and Menu.zh-CN.resx.

**Comment by tidyui** [comment]
After you save your translations in Crowdin the platform will send a PR back to this repository. This PR will then have to be merged in order for the translations to be available in the source code.
