### ISSUE TITLE
Published issue

### ISSUE THREAD

**Issue by ademsenel** [PiranhaCMS/piranha.core#1529]
Hi dear
i have finished project and i tried on my machine everything is working as ecepted 
but when i published the hosting provider it is not shoving web site
the host provider is myasp.net
piranha version : 8.4.2
what is the problem or tricky
thank you

**Comment by ademsenel** [comment]
also does it possible to select authentication  individial user accaunt 
the provider needs individual user accaunt authentication

**Comment by r4g-jon** [comment]
Hi @ademsenel 

Can you share the error message you are seeing on your website? If so, we might be able to help.

Thanks

**Comment by tidyui** [comment]
@ademsenel If you’ve used SQLite for development and want to include the database you have to add it to your csproj. By default it is not included in the publish

**Comment by ademsenel** [comment]
i solved that problem 
Web deploy doesnt transfer SQLite database i transfer it with ftp then issue was gone
Thank you
