### ISSUE TITLE
About meta tag keyword and description shows 

### ISSUE THREAD

**Issue by ademsenel** [PiranhaCMS/piranha.core#1533]
Hi dear;
i create custom page content 
But when i create page in  manager, it doesnt show meta keywords and description except og: meta tags;
but which one provide by cms template is standart page is shows what required
pls check www.bymecnun.com/ana-sayfa (home page by standardpage model) www.bymecnun.com/mobilya-katalog (my custom model)
What is problem or missing  

    [PageType(Title = "Katalog Sayfası", UseBlocks = false)]
    [PageTypeRoute(Title = "Default", Route = "/katalog")]
    public class CatalogPage : Page<CatalogPage>
    {
    }
    public class CatalogController : CmsBase
    {
        public CatalogController(IApi api, IModelLoader loader) : base(api, loader)
        {
        }

        [Route("katalog-kategori")]
        public async Task<IActionResult> Category(Guid id)
        {
            var model = await _api.Pages.GetByIdAsync<Models.CategoryPage>(id).ConfigureAwait(false);
            return View(model);
        }

        [Route("katalog")]
        public async Task<IActionResult> Catalog(Guid id)
        {
            var catalog = await _api.Pages.GetByIdAsync<CatalogPage>(id);
            var model = new CatalogViewModels
            {
                CatalogPage = catalog,
                Categories = (await _api.Sites.GetSitemapAsync())
                .Where(item => item.Id == catalog.Id)
                .SelectMany(item => item.Items)
                .Select(item =>
                {
                    var page = _api.Pages.GetByIdAsync<CategoryPage>(item.Id).Result;
                    return new CategoryItem
                    {
                        Title = page.Title,
                        Description = page.CategoryDetails.Description,
                        PageUrl = page.Permalink,
                        ImageUrl = page.CategoryDetails.CategoryImage.Resize(_api, 200)
                    };
                })
            };
            return View(model);
        }

        [Route("contact")]
        public async Task<IActionResult> Contact(Guid id)
        {
            var contactPage = await _api.Pages.GetByIdAsync<ContactPage>(id);
            var model = new ContactViewModels
            {
                ContactPage = contactPage,
                Contact = (await _api.Sites.GetSitemapAsync())
                .Where(x => x.Id == contactPage.Id)
                .Select(x =>
                {
                    var contact = _api.Pages.GetByIdAsync<ContactPage>(x.Id).Result;
                    return new ContactItem
                    {
                        Title = contactPage.Title,
                        ContactName = contact.Contact.ContactName,
                        PhoneNumber1 = contact.Contact.PhoneNumber1,
                        PhoneNumber2 = contact.Contact.PhoneNumber2,
                        FaxNumber = contact.Contact.FaxNumber,
                        Email = contact.Contact.Email,
                        AddressLine1 = contact.Contact.AddressLine1,
                        AddressLine2 = contact.Contact.AddressLine2,
                        AddressLine3 = contact.Contact.AddressLine3,
                        District = contact.Contact.District,
                        City = contact.Contact.City,
                        PostCode = contact.Contact.PostCode,
                        GoogleApiKey = contact.Contact.GoogleApiKey
                    };
                }).FirstOrDefault()
            };
            return View(model);
        }
    }

thank you

**Comment by tidyui** [comment]
Meta-information has nothing to do with your model, they are all default fields available on all pages. You do however need to add some relevant content into the fields in the `Settings` modal under `SEO` (see provided screenshot).

<img width="1484" alt="Skärmavbild 2021-03-04 kl  09 18 32" src="https://user-images.githubusercontent.com/781266/109932699-d4c74800-7cca-11eb-965a-4ab269686b70.png">

**Comment by ademsenel** [comment]
i filled all of them but not showing 
if you need i can share manager password

**Comment by tidyui** [comment]
As Piranha is decoupled it’s up to you what you do with the meta-tags. This is the line in the standard page that renders the meta-tags if you’ve used our template to create your project:

https://github.com/PiranhaCMS/piranha.core.templates/blob/master/src/web/razor/Pages/Page.cshtml#L8

This uses a html-helper we’ve added that renders all of the tags, but you could just as well just render them like any property on your page model, it’s up to you.

As meta-tags are being rendered on the default page it’s highly unlikely that there’s some kind of bug in the framework.

Regards

**Comment by tidyui** [comment]
I see you’re using MVC. This is the equivalent line from the MVC template:

https://github.com/PiranhaCMS/piranha.core.templates/blob/master/src/web/mvc/Views/Cms/Page.cshtml#L7

**Comment by ademsenel** [comment]
The Model is refering view model how can i handle metatags
