### ISSUE TITLE
Logo images doesnt show in web page

### ISSUE THREAD

**Issue by ademsenel** [PiranhaCMS/piranha.core#1534]
i add logo in site but it doesn't show in page 
i try to show in attached images
everything seems be good looking

![Screenshot 2021-03-05 111615](https://user-images.githubusercontent.com/7110715/110087616-ed0b9580-7da4-11eb-9c34-66d45b4b636b.png)
![Screenshot 2021-03-05 111548](https://user-images.githubusercontent.com/7110715/110087673-ff85cf00-7da4-11eb-836f-ec87cbb5181c.png)
![Screenshot 2021-03-05 111745](https://user-images.githubusercontent.com/7110715/110087697-06acdd00-7da5-11eb-8c64-36b8ee2f2970.png)

**Comment by tidyui** [comment]
Hi there! Can you specify which version you're running and what template you've created your project with.

**Comment by ademsenel** [comment]
Hi Hakan ofcourse
The versin is 8.4.2

**Comment by tidyui** [comment]
Well our templates doesn't include any `.cshtml` code that actually renders the logo field. But if I add an image to the site, just like you've done and add the following at the start of my `_Layout.cshtml`.

~~~
@{
    var site = await WebApp.Api.Sites.GetDefaultAsync();
}
~~~

And then the following in the toolbar:

~~~
<img src="@Url.Content(site.Logo)" alt="The Logo">
~~~

The image is rendered without issues.

**Comment by ademsenel** [comment]
yes this is it
thank you very much
take care pls
