### ISSUE TITLE
Custom Editors doesn't work for Posts.

### ISSUE THREAD

**Issue by horacioj** [PiranhaCMS/piranha.core#1546]
This works fine. I.e. in the Manager the content can be edited.

```
    [ContentTypeEditor(Title = "Location", Component = "location-region", Icon = "fas fa-map-marker-alt")]
    public class LocationPage : Page<LocationPage>
    {
        ...
        ...

        [Region(Display = RegionDisplayMode.Hidden)]
        public Regions.LocationRegion Location { get; set; }

        ...
        ...
```

The same, in a `Post`, doesn't work. 

```
    [ContentTypeEditor(Title = "Location", Component = "location-region", Icon = "fas fa-map-marker-alt")]
    public class LocationPage : Post<LocationPage>
    {
        ...
        ...

        [Region(Display = RegionDisplayMode.Hidden)]
        public Regions.LocationRegion Location { get; set; }

        ...
        ...
```

In the JS console you get:

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'typeId' of undefined"

found in

---> <LocationRegion> at src/js/components/location-region.vue
       <Root>

TypeError: Cannot read property 'typeId' of undefined
    at Proxy.render (agentcards-region.vue?6b0c:22)
    at VueComponent.Vue._render (piranha-deps-dev.js:21574)
    at VueComponent.updateComponent (piranha-deps-dev.js:22090)
    at Watcher.get (piranha-deps-dev.js:22501)
    at new Watcher (piranha-deps-dev.js:22490)
    at mountComponent (piranha-deps-dev.js:22097)
    at VueComponent.Vue.$mount (piranha-deps-dev.js:27067)
    at VueComponent.Vue.$mount (piranha-deps-dev.js:29952)
    at init (piranha-deps-dev.js:21154)
    at createComponent (piranha-deps-dev.js:23996)
```

**Comment by tidyui** [comment]
I can't find any error in custom errors on posts in general. I've tested with the simplest example like so:

~~~ js
Vue.component("location-region", {
    props: ["uid", "id"],
    template: "<div><h1>This is custom editor</h1></div>"
});
~~~

And the editor loads just fine for posts. If you in the vue component are accessing your regions, for example with `piranha.pageedit.regions...`, please remember that when attached to a post `piranha.pageedit` **will be null** as you're editing a post and not a page.

**Comment by horacioj** [comment]
Ah... 

So for a `post` instead of referencing `piranha.pageedit.regions`, or `piranha.pageedit.typeId` I should reference `piranha.postedit.regions`, and `piranha.postedit.typeId`.

For regular regions, I see there is a `content:"post"` (or, for pages and generic content `content:"page"`) property.
However for custom regions, `props: ["uid", "id"]` are the only available properties.
If I add `content` to the list (`props: ["uid", "id", "content"]`), it will be `undefined`. 

How can I know, from within the .vue component if it is being referenced by a page, post, or content?
Is there a better way than checking which of `piranha.pageedit` or `piranha.postedit` isn't `undefined`?

**Comment by tidyui** [comment]
Not at the moment. The intention was that the components should operate on model given to them and not the entire page/post model. I actually don't even remember why regions get this property exported :)

**Comment by tidyui** [comment]
In the future our goal is to consolidate all of this to **one** server model in the manager. See #1224

**Comment by horacioj** [comment]
Nice, thanks! 
If it helps, I'm ok with breaking backwards compatibility for the greater good :)

**Comment by tidyui** [comment]
:) For us it's more of a self preservation thing to make upgrading as smooth as possible, since we don't have the manpower to support several versions :-D
