### ISSUE TITLE
Site Edit not showing errors from content save

### ISSUE THREAD

**Issue by FelipePergher** [PiranhaCMS/piranha.core#1553]
I am using the hooks to validate custom blocks/regions when going to save pages and it's working nice, but when I tried to use the same ideia to site hooks, the site is saved ignoring the validationException. 

This is the code por the block validation in page
```
App.Hooks.Pages.RegisterOnBeforeSave(x =>
{
    var messages = string.Empty;
    foreach (var block in ((DynamicPage)x).Blocks)
    {
        if (block is ContactBlock contactBlock)
        {
            if (string.IsNullOrEmpty(contactBlock.Title.Value))
            {
                messages += "Titulo é obrigatório. </br>";
            }

            if (string.IsNullOrEmpty(contactBlock.SuccessMessage.Value))
            {
                messages += "Mensagem de sucesso é obrigatório. </br>";
            }

            if (string.IsNullOrEmpty(contactBlock.ErrorMessage.Value))
            {
                messages += "Mensagem de erro é obrigatório. </br>";
            }
        }
    }

    if (!string.IsNullOrEmpty(messages))
    {
        throw new ValidationException(messages);
    }
});
```

This is the code I tried use to site hook to validate a custom block
```
App.Hooks.Site.RegisterOnBeforeSave(async x =>
{
    var messages = string.Empty;
    BaseSite currentSite = await api.Sites.GetContentByIdAsync<BaseSite>(x.Id);
    if (currentSite != null && currentSite.FooterLinks.Any())
    {
        foreach (var footerLink in currentSite.FooterLinks)
        {
            if (string.IsNullOrEmpty(footerLink.Text.Value))
            {
                messages += "Texto é obrigatório. </br>";
            }
            if (string.IsNullOrEmpty(footerLink.Url.Value))
            {
                messages += "Url é obrigatória. </br>";
            }
        }
    }
    if (!string.IsNullOrEmpty(messages))
    {
        throw new ValidationException(messages);
    }
});
```
Looks like the hooks of site don't follow the same way of hooks of page, is possible to add the same way to we can show to user a message of validation when something is wrong instead saving?

**Comment by tidyui** [comment]
Hi there! I think I've found your issue. The site is split into two different save operations, one for saving the basic fields (title, hostname and so on) and one for saving global site content. The hook you're using is for saving the static site content, the hook you're looking for is:

~~~ csharp
App.Hooks.SiteContent.RegisterOnBeforeSave(x => 
{
   ...
});
~~~

The model you are receiving will is a `SiteContentBase`, but when saving from the manager interface you will in fact get a `DynamicSiteContent` model because this is what the manager uses. However you have to check the type of `x` since if you're doing a save directly on the `Api` with your CLR model, you will get this model type into the hook.

**Comment by FelipePergher** [comment]
@tidyui  Interesting, I saw have the two hooks, because I don't know the difference I used the site one, I will try with the site content, hopefully will work 🤞

**Comment by FelipePergher** [comment]
I updated the code to use the SiteContent hook, but this hook is ignoring the exception, I used debug mode, and the useful message appear on manager UI before the hook is processed. On the page hook the message just appear after the hook finish.

Current code:
```

 App.Hooks.SiteContent.RegisterOnBeforeSave(x =>
  {
      var messages = string.Empty;

      foreach (var footerLink in ((DynamicSiteContent)x).Regions.FooterLinks)
      {
          if (string.IsNullOrEmpty(footerLink.Text.Value))
          {
              messages += "Texto é obrigatório. </br>";
          }

          if (string.IsNullOrEmpty(footerLink.Url.Value))
          {
              messages += "Url é obrigatória. </br>";
          }
      }

      if (!string.IsNullOrEmpty(messages))
      {
          throw new ValidationException(messages);
      }
  });
```

**Comment by FelipePergher** [comment]
Just an update, using this code the UI show is saved, but on real the config not are being saved, só I think the only thing that need adjust here is the return message to the user with the message of exception.

**Comment by tidyui** [comment]
That is correct. I can see that the `Vue` application performs two save operations, one for the regular site information and one for the "content", however only the status message from the first operation is shown in the manager.
