### ISSUE TITLE
WebApp.CurrentPage  is null for /some-page?draft=true being some-page unpublished

### ISSUE THREAD

**Issue by horacioj** [PiranhaCMS/piranha.core#1565]
WebApp.CurrentPage  is null for /some-page?draft=true being some-page unpublished (never published).

Is this the expected behavior?

Notice var currentPage = await WebApp.Api.Pages.GetByIdAsync<PageType>(WebApp.PageId) isn't null

**Comment by tidyui** [comment]
This is obviously by design, see:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore/PiranhaMiddleware.cs#L202
https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore/PiranhaMiddleware.cs#L231

Since the code was written a while back I can't remember **exactly** why the choice was made, I'll have to dig around a bit.

Regards

**Comment by horacioj** [comment]
Ah... I see...
Some context (why I asked): 

- The site has CMS and non-CMS pages. 
- There are many types of CMS pages.
- All pages (CMS, all types) and non-CMS pages share the same footer (implemented in a partial _Footer).
- I implemented the shared footer information in the site's settings (similar to https://piranhacms.org/docs/master/tutorials/how-to-create-a-footer)
- One of the CMS page types, can have a custom footer. In this page type, there are some regions that allow overriding the default footer. 
- Problem: When a user is creating a new page of this particular type, defining custom data for the footer, the user cannot preview how the footer will look like because the page wasn't yet published (WebApp.CurrentPage is null ). Workaround: I'm doing `await WebApp.Api.Pages.GetByIdAsync(WebApp.PageId)` , but I wanted to avoid this extra call in every page (all CMS page types + non CMS pages)

**Comment by tidyui** [comment]
Yes I understand your use case, however we can’t change the current implementation without first investigating what consequences it has as it was clearly a decision made at some point 🙂 

A better workaround would probably be to check if it is a draft, and if so just assign the current model to CurrentPage in your Controller action or Razor Page, then your Layout won’t have to perform anything additional.

**Comment by horacioj** [comment]
> A better workaround 

Yes, much better!

I'm using Razor pages, and added this to the somepage.cshtml:

```
    if (!Model.Data.IsPublished)
    {
        WebApp.CurrentPage = Model.Data;        
    }
```

Is this what you meant? 
It seems to be working fine.
Thanks!

**Comment by tidyui** [comment]
Yes! Exactly. As the page is executed before the Layout page it won't even notice the difference.
