### ISSUE TITLE
Can't access the manager

### ISSUE THREAD

**Issue by ramon-mendes** [PiranhaCMS/piranha.core#1609]
I just installed it in Azure using SQLServer as database, getting this error: https://ramonmendes.com.br/manager
![image](https://user-images.githubusercontent.com/44581176/116563625-93be6f00-a8da-11eb-9e20-f9f4e925a7e3.png)

Here is my ConfigureService:
![image](https://user-images.githubusercontent.com/44581176/116563855-cff1cf80-a8da-11eb-8963-eecc56790fc0.png)

**Comment by tidyui** [comment]
Since you have left out the part of `ConfigureService` where you specify the connection string for `Asp.Net Identity` and add the Identity package, can you verify this is done correctly?.

Regards

**Comment by ramon-mendes** [comment]
Fixed it by inserting: 
![image](https://user-images.githubusercontent.com/44581176/116571271-4eea0680-a8e1-11eb-9f4e-668a0cc7e664.png)
And adding Nuget Piranha.AspNetCore.Identity.SQLServer

Problem is, documentation doesn't state that it must be done: https://piranhacms.org/docs/master/architecture/databases/sql-server

**Comment by mikaellindemann** [comment]
It is here under the Authentication/Identity documentation: https://piranhacms.org/docs/master/architecture/authentication/identity

Best regards!
