### ISSUE TITLE
PostInfo Excerpt is null

### ISSUE THREAD

**Issue by ramon-mendes** [PiranhaCMS/piranha.core#1612]
Hi, after updating to 9.0 I have a problem.

In piranha.mvc template Archive.cshtml has the following line:
![image](https://user-images.githubusercontent.com/44581176/116762213-12590080-a9f0-11eb-98f7-e2cf8200130b.png)

It does shows the Excerpt. But in my site `item.Excerpt` is null.
Where does it gets this value from?

**Comment by ramon-mendes** [comment]
Lately I had a custom function that extracted the Excerpt from the Blocks:
`@Html.DisplayFor(m => item.Blocks).Excerpt()`
But now PostInfo doesn't carry the Blocks anymore

**Comment by tidyui** [comment]
PostInfo has never included blocks OR regions, this is the sole purpose of the PostInfo class.

**Comment by tidyui** [comment]
And the answer to the first question which I missed was, in the newer versions there's a dedicated `Excerpt` field on Pages and Posts that can be used. Depending on which version you upgraded from this field wasn't available before.

Best regards
