### ISSUE TITLE
Use external Identity service (OAuth2 etc)

### ISSUE THREAD

**Issue by tedvanderveen** [PiranhaCMS/piranha.core#1622]
We have a customer requirement to refer to an external account/identity service for authentication against a Piranha environment. In such a way that -for example- the Piranha Manager should authorize using a JWT/access token provided by this external OAuth identity store. User/account signup en management is handled outside Piranha. Piranha shall never get "in touch" with those user credentials. It "only" needs to properly accept/handle OAuth/JWT tokens for authorization.

When trying to implement this in Piranha, I noticed that the `ISecurity` interface plays a vital role. But it has a `SignIn` method that requires a username and password. Whilst in our use case, users provide their credentials via the OAuth redirect to the external identity service login page.

In this specific use case, we try to get the `Microsoft.Identity.Web` and `Microsoft.Identity.Web.UI` Nuget packages working properly with Piranha, but are stuck.
https://www.nuget.org/packages/Microsoft.Identity.Web
https://www.nuget.org/packages/Microsoft.Identity.Web.UI

Is there a recommended approach for externalizing Piranha user accounts and auth?

**Comment by tidyui** [comment]
Hi there! The ISecurity service is only used when you login to the manager. My suggestion is that you override the default login view with your own (place a local copy in your project in the same location). Then implement ISecurity to handle when the user wants to logout from the manager!

Regards

**Comment by tidyui** [comment]
Updated to support this better has now been pushed to master and will be included in `9.1`
