### ISSUE TITLE
BlockGroup SelectField value not set in manager

### ISSUE THREAD

**Issue by jason-petit** [PiranhaCMS/piranha.core#1626]
Hi, I have a custom BlockGroup with a SelectField field on it: 

    [BlockGroupType(Name = "Custom Column", Category = "Content", Icon = "fas fa-columns", Display = BlockDisplayMode.Horizontal)]
    public class CustomColumnBlock : BlockGroup, ISearchable
    {
        [Field(Title = "Layout (Extra columns will be ignored)")]
        public SelectField<ColumnLayout> Layout { get; set; }
    }

    public enum ColumnLayout
    {
        [Display(Description = "5 | 7")]
        FiveSeven = 0,

        [Display(Description = "7 | 5")]
        SevenFive = 1
    }

Adding this block group to a page and setting the dropdown value, then rendering the content on the front end (not in the manager) works as expected. However, in the manager, after leaving and going back to edit the page, the dropdown for this field is not set to the correct value. 

I see this in the json response from the manager API when the page loads:

![image](https://user-images.githubusercontent.com/29665883/117984520-87380e80-b2fd-11eb-9708-595893b2dc80.png)

which of course renders like this:

![image](https://user-images.githubusercontent.com/29665883/117985305-3379f500-b2fe-11eb-8eaf-65637c40a585.png)

which doesn't match up with the `value` of `FiveSeven`. Am I missing something? How can I get around this? Thank you!

**Comment by tidyui** [comment]
I don’t think I’ve ever tried it with enums with explicit values, I.e you setting them to 0 and 1.

What happens if you remove this from the enum declaration?

Regards

**Comment by jason-petit** [comment]
Thanks for the reply. Same result without explicit values.

It looks like the `option` values are being forced to `int` here:

https://github.com/PiranhaCMS/piranha.core/blob/5ee127643de0d5535246e101a02e99563b3d5554/core/Piranha.Manager/Services/PageService.cs#L634-L640

**Comment by jason-petit** [comment]
I will note that if I load the page editor, the dropdown is blank, like the first option isn't selected, it's just blank. If I save the page without touching the dropdown, the previous value is not overwritten in the database. So that's not as big a deal as I previously thought - even as it is now, users won't have to remember to re-set that value every time they edit the page.

**Comment by tidyui** [comment]
What database are you using? We have the exact same setup in our public website and do not have same issues (note that it hasn't been upgraded yet and is running version `8.4`). The difference is that in the JSON I get from our site when editing the page contains the integer value of the enum and not the `ToString` value like your JSON data does.

**Comment by tidyui** [comment]
I've created a new project from the current templates targeting the latest production packages and can't reproduce. I have added a custom block group with a select field as a global field which works perfectly when loading it into the manager.

~~~ csharp
[BlockGroupType(Name = "My Group", Category = "Custom", Icon = "fas fa-fish", Display = BlockDisplayMode.Horizontal)]
public class MyGroup  : BlockGroup
{
    public enum MyStyle
    {
        [Display(Description = "It's so narrow")]
        Narrow = 0,
        [Display(Description = "It's quite normal")]
        Normal = 1,
        [Display(Description = "It's really wide")]
        Wide = 2
    }

    public SelectField<MyStyle> Style { get; set; }
}
~~~

<img width="993" alt="Skärmavbild 2021-05-24 kl  12 05 47" src="https://user-images.githubusercontent.com/781266/119332244-9e291a00-bc88-11eb-92e3-fa8af5665f5a.png">

**Comment by jason-petit** [comment]
Ah, I found my problem...

````csharp
services.AddControllersWithViews()
    .AddNewtonsoftJson(opts =>
    {
        opts.SerializerSettings.TypeNameHandling = Newtonsoft.Json.TypeNameHandling.None;
        opts.SerializerSettings.Converters.Add(new StringEnumConverter());
        opts.SerializerSettings.ContractResolver = new DefaultContractResolver
        {
            NamingStrategy = new CamelCaseNamingStrategy()
        };

    });

services.AddRazorPages()
    .AddPiranhaManagerOptions();
````

I forgot I had done that. I moved this functionality to a base controller so it doesn't affect Piranha and everything is working as expected now. Thanks for your time.
