### ISSUE TITLE
Is there any documentation/resources for how to add a custom block?

### ISSUE THREAD

**Issue by RobRukavina** [PiranhaCMS/piranha.core#1635]
Trying to create a custom block that I can use with an option while in CMS web app to view source code of said block. Is there any documentation that may help me with this task? Any help would be greatly appreciated!

**Comment by tidyui** [comment]
We have documentation or our website for creating custom blocks and block groups.

* https://piranhacms.org/docs/master/extensions/blocks
* https://piranhacms.org/docs/master/extensions/block-groups

Best regards

**Comment by RobRukavina** [comment]
thanks!

**Comment by RobRukavina** [comment]
I've created several custom blocks now and they work great, thanks for the help with the link to docs! Problem now is that I've got custom block group that is modeled after the ImageGalleryBlock but instead of using images it uses documents. I've created at RegulatoryCardBlock.cs which inherits from BlockGroup and a RegulatoryDocumentBlock.cs that does what ImageBlock does in ImageGalleryBlock.cs. On the Manager side it works fine and I can select multiple documents and save and publish but when I get to the public facing side, I get a json error on page load even though I've done my CleanResponse as shown here: 
`.Replace("Sabio.Web.CMS.Models.RegulatoryCardBlock, Sabio.Web.CMS", "Piranha.Models.RegulatoryCardBlock, Vertex.Data");`
Not sure what's going on. At first I thought maybe I needed a Component/template but then I read in docs that is not necessary for BlockGroup components... Any suggestions? Thanks in advance

**Comment by RobRukavina** [comment]
`namespace Piranha.Extend.Blocks
{
    [BlockGroupType(Name = "Regulatory Document Gallery", Category = "Content", Icon = "fas fa-file")]
    [BlockItemType(Type = typeof(RegulatoryDocumentBlock))]
    public class RegulatoryCardBlock : BlockGroup
    {
    }
}`

**Comment by RobRukavina** [comment]
'Error resolving type specified in JSON 'Piranha.Models.RegulatoryCardBlock, Vertex.Data'. Path 'blocks[0].$type', line 1, position 1388.'

**Comment by tidyui** [comment]
Hi there, I see you closed the issue again but you shouldn’t replace any namespaces in the response going out. This will most likely break everything when you try to send the data back or add an item to the block group.

Best regards
