### ISSUE TITLE
Question: is it possible to add a sitemap property for example navigation location

### ISSUE THREAD

**Issue by AndreSteenbergen** [PiranhaCMS/piranha.core#1657]
For example:

TopNavigation
FooterLeftColumn
FooterRightColumn

And to be able to use checkboxes to 

This
``` @foreach (var item in (await WebApp.Site.Sitemap.ForUserAsync(User, Auth)).Where(i => !i.IsHidden)) ```

could be:

``` @foreach (var item in (await WebApp.Site.Sitemap.ForUserAsync(User, Auth)).Where(i => i.TopNavigation)) ```

etc.

**Comment by tidyui** [comment]
Hi there! This is not possible, **BUT** you could do the following instead:

1. Create a Site Type for your site as outlined in https://piranhacms.org/docs/master/content/sites
2. On your content type add a region with two `PageFields`, One for `FooterLeftRoot` and `FooterRightRoot`.
3. Select your pages from the site map in the two fields.

When rendering your Layout (or where you will be rendering the menus) retrieve the Sitemap as usual, then call `GetPartial` with the selected `Id` your added in step `3`, this will then give you the Sitemap from this page downwards.

Best regards
