### ISSUE TITLE
Please check this project using SonarQube

### ISSUE THREAD

**Issue by PolywickStudio** [PiranhaCMS/piranha.core#1660]
I added CI integration into my project using PiranaCMS. Here's some of the SonarQube results I get:

Example:
\piranha.core-master\core\Piranha\Services\PageService.cs(426,17): warning S4201: Remove this unnecessary null check; 'is' returns false for nulls. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\PageService.cs(595,28): warning S3776: Refactor this method to reduce its Cognitive Complexity from 35 to the 15 allowed. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\PageService.cs(726,41): warning S1155: Use '.Any()' to test whether this 'IEnumerable<System.Guid>' is empty or not. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\PageService.cs(967,28): warning S3776: Refactor this method to reduce its Cognitive Complexity from 28 to the 15 allowed. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\MediaService.cs(256,21): warning S3247: Replace this type-check-and-cast sequence with an 'as' and a null check. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\MediaService.cs(277,21): warning S3247: Replace this type-check-and-cast sequence with an 'as' and a null check. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\MediaService.cs(285,26): warning S3247: Replace this type-check-and-cast sequence with an 'as' and a null check. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\MediaService.cs(200,27): warning S3776: Refactor this method to reduce its Cognitive Complexity from 19 to the 15 allowed. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\MediaService.cs(370,35): warning S3776: Refactor this method to reduce its Cognitive Complexity from 16 to the 15 allowed. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\ContentTypeService.cs(159,42): warning S1155: Use '.Any()' to test whether this 'IEnumerable<Piranha.Models.ContentType>' is empty or not. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\ContentService.cs(136,13): warning S3923: Remove this conditional structure or edit its code blocks so that they're not all the same. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\ContentService.cs(168,17): warning S4201: Remove this unnecessary null check; 'is' returns false for nulls. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\ContentService.cs(159,17): warning S2589: Change this condition so that it does not always evaluate to 'true'. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\ContentService.cs(146,17): warning S2583: Change this condition so that it does not always evaluate to 'false'; some subsequent code is never executed. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\ContentService.cs(161,52): warning S3655: 'languageId' is null on at least one execution path. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\ContentService.cs(243,17): warning S1066: Merge this if statement with the enclosing one. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\ContentService.cs(251,37): warning S3655: 'languageId' is null on at least one execution path. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Services\ContentFactory.cs(73,24): warning S4586: Do not return null from this method, instead return 'Task.FromResult<T>(null)', 'Task.CompletedTask' or 'Task.Delay(0)'. [\piranha.core-master\core\Piranha\Piranha.csproj]

\piranha.core-master\core\Piranha\Api.cs(107,19): warning S107: Constructor has 19 parameters, which is greater than the 7 authorized. [\piranha.core-master\core\Piranha\Piranha.csproj]

(And so on...)

**Comment by tidyui** [comment]
As with all code analyzers some warnings are good and others and others are just “opinions”. We use several other analyzers for the code base and do changes when we get the time and chance!

Best regards!
