### ISSUE TITLE
I am looking to change the value of menu from false to piranha.editorconfig.menu

### ISSUE THREAD

**Issue by RobRukavina** [PiranhaCMS/piranha.core#1663]
https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.TinyMCE/assets/piranha.editor.js
on the above component you can see that this is set to false. I would like to enable the menu bar so I can see the menu buttons and be able to select the source code option. Is there already a workaround for this?

**Comment by tidyui** [comment]
Hi there! You don’t need the menu bar to enable the source code option, you can add this into the toolbar using the menu config.

https://piranhacms.org/docs/master/architecture/html-editors/tiny-mce

**Comment by RobRukavina** [comment]
Thank you, I was trying to add the menu and menubar to the config.json but I never tried to add code to the toolbar props

**Comment by RobRukavina** [comment]
So this is kind of a different issue but it still relates to configuring tinymce... I am trying to set valid_elements: "style" and/or custom_elements: "sabioStyle", and/or extended_valid_elements: "style". I've also tried: "*[*]" according to tiny's docs but it seems to have no effect on anything. I see that the init function Piranha uses sets extended_valid_elements: piranha.editorconfig.extended_valid_elements but my dev tools are not showing the value that I type in editorconfig.json... in short, their docs are failing me. Any suggestions would be great! I'm just trying to be able to add <style>// custom css here</style> into the tiny mce editor but currently it deletes the style tags and anything in between them on save. Thanks

**Comment by tidyui** [comment]
The editor config is by no means a mirror of the complete tiny mice configuration, we only support a subset of the options tiny does. I’ve update the docs with the correct syntax for extended valid elements, you can find it here:

https://piranhacms.org/docs/master/architecture/html-editors/tiny-mce

The reason why we only support a subset of the available options is simple. We believe that you **shouldn’t** do complex stuff in an html-area, it should only be used for formatting text. As soon as you start adding complex html into a wysiwyg editor you will in most cases make it much harder to render it properly in a responsive application. Instead, advanced components should be handled by custom blocks and/or block groups.

Best regards

**Comment by RobRukavina** [comment]
I appreciate the quick response. I'm trying to make this easy for someone who doesn't know how to code to be able to just past some valid html and css into the editor, save it and then I can handle the output on our site that we've built piranha into. I really need the advanced features. Or at least a <style> tag :)

**Comment by RobRukavina** [comment]
Do you know if it's in the invalid_elements list?

**Comment by tidyui** [comment]
We haven’t added anything custom into invalid_elements. You can clearly see the code that renders the editor script here:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.TinyMCE/assets/piranha.editor.js

**Comment by RobRukavina** [comment]
ok, thanks again

**Comment by RobRukavina** [comment]
> The editor config is by no means a mirror of the complete tiny mce configuration, we only support a subset of the options tiny does. I’ve update the docs with the correct syntax for extended valid elements, you can find it here:
> 
> https://piranhacms.org/docs/master/architecture/html-editors/tiny-mce
> 
> The reason why we only support a subset of the available options is simple. We believe that you **shouldn’t** do complex stuff in an html-area, it should only be used for formatting text. As soon as you start adding complex html into a wysiwyg editor you will in most cases make it much harder to render it properly in a responsive application. Instead, advanced components should be handled by custom blocks and/or block groups.
> 
> Best regards


isn't this the correct syntax? extended_valid_elements

I got this from:
https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.TinyMCE/assets/piranha.editor.js
 extended_valid_elements: piranha.editorconfig.extended_valid_elements,

**Comment by tidyui** [comment]
No. That is the name in the JavaScript object that has been bound to the config values. See here:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Areas/Manager/Shared/Partial/_EditorConfig.cshtml

The correct syntax is stated in the docs here:

https://piranhacms.org/docs/master/architecture/html-editors/tiny-mce
