### ISSUE TITLE
Working with pages

### ISSUE THREAD

**Issue by traustitj** [PiranhaCMS/piranha.core#1664]
![Screen Shot 2021-07-21 at 18 26 22](https://user-images.githubusercontent.com/232880/126540531-94f789c8-fa7d-4bcc-b222-c58799a0c64f.png)

The indented page does not show up in the sitemap. I get this.
But is there a way to make new pages of MYPageType be like that by default when I create it?
Also. Is there an API to find indented pages? Like can Welcome to My world page find the Indented page because it is below it self?

Hope I am making myself understood

**Comment by tidyui** [comment]
Hi @traustitj I don’t really understand what you mean. Given the screenshot the “Indented page” is not a child of “My world”, it’s a sibling. The page “Another page” is a child of “My world”.

**Comment by traustitj** [comment]
Sorry for not explaining better.

The idea was that Indented page would be of MyPage type and not standard, and be like the one above.
Can I, from Welcome to my page, find the Another page?

How can MyPage which is Indented page always be indented, at least when created

**Comment by tidyui** [comment]
I still don't follow what you want to achieve. The "Idented page?" will be a part of the sitemap and will be the next sibling to the start page. The sitemap provides the id of the pages from which you can load any page from the `IApi`

**Comment by traustitj** [comment]
Ok, then this is clearly a case where I am misunderstanding.

Can you explain the indented page? What makes it different? And can I create a page that is indented by default?

Can a top page query indented pages under it? As can Welcome to my world page know that "Another page" is under it? This is like so I can create a menu on the "Welcome to my world" that displays a link to all its sub pages?

Again, I could be misunderstanding this badly.

**Comment by tidyui** [comment]
Ok, let’s forget about your “Indented page” as the screenshot clearly shows it’s not a child page but on the same level as the start page. 

If you want to get the pages below the current page, simply get the full site map, then call GetPartial with the id of your current page as the parameter. This will get a partial site map with the given I’d as the root node.

Best regards
