### ISSUE TITLE
Diacritics normalization in Slug

### ISSUE THREAD

**Issue by hrvoje-grabusic** [PiranhaCMS/piranha.core#1666]
Hi,

I noticed in the source code that you only normalize some diacritics and remove all the rest.
` // Convert culture specific characters
            slug = slug
                .Replace("å", "a")
                .Replace("ä", "a")
                .Replace("á", "a")
                .Replace("à", "a")
                .Replace("ã", "a")
                .Replace("â", "a")
                .Replace("ö", "o")
                .Replace("ó", "o")
                .Replace("ò", "o")
                .Replace("ô", "o")
                .Replace("õ", "o")
                .Replace("é", "e")
                .Replace("è", "e")
                .Replace("ê", "e")
                .Replace("í", "i")
                .Replace("ì", "i")
                .Replace("ú", "u")
                .Replace("ž", "z")
                .Replace("š", "s")
                .Replace("č", "c")
                .Replace("ç", "c");`

There is a function on stackoverflow that will do it for all cultures.
[https://stackoverflow.com/questions/9565360/how-to-convert-utf-8-characters-to-ascii-for-use-in-a-url/9628594#9628594](https://stackoverflow.com/questions/9565360/how-to-convert-utf-8-characters-to-ascii-for-use-in-a-url/9628594#9628594)

**Comment by tidyui** [comment]
Great, we'll take a look at it! Currently it is possible to override the default slug generation by using the appropriate application `hook`, but it's always nice if the default behavior can be improved!

**Comment by tidyui** [comment]
See #1922
