### ISSUE TITLE
MySQL packages name consistence

### ISSUE THREAD

**Issue by successgo** [PiranhaCMS/piranha.core#1669]
There are 2 packages: `Piranha.Data.MySql` and `Piranha.AspNetCore.Identity.MySQL`.

Maybe we need to change `Piranha.Data.MySql` to `Piranha.Data.MySQL`.

**Comment by tidyui** [comment]
One package was named by us, one was named by a contributor. Not sure what the impact will be on Linux/Mac as file system is case sensitive. Having multiple versions with the same symbols will effectively break the applications after upgrade. On windows it should sort itself out, and NuGet is case insensitive

**Comment by successgo** [comment]
It does not work on MacOS and linux when **the case** not match.

It is a little strange with the 2 packages, but it works perfectly for now.

Maybe we can fix that in the next major release.

**Comment by tidyui** [comment]
Yes, the difference as I wrote was that they were named by different contributors. Unfortunately we missed it before releasing the packages

**Comment by tidyui** [comment]
Almost all of the packages for data providers have casing issues, but since nuget package names seems to be case sensitive we won't fix this now.
