### ISSUE TITLE
HtmlColumnBlock obsolete?

### ISSUE THREAD

**Issue by LukeOwlclaw** [PiranhaCMS/piranha.core#1684]
I just found `Piranha.Extend.Blocks.HtmlColumnBlock` which has two columns. I assume that it got replaced by ``ColumnBlock`` which takes any number of columns. Is that correct? Can I safely remove ``HtmlColumnBlock.cshtml`` from ``DisplayTemplates``?

Second, slightly related question: What prevents `BlockGroup`s to be nested within ``BlockGroup``s?

Thanks!

**Comment by tidyui** [comment]
Yes, HtmlColumnBlock is obsolete and only kept for backward compatibility so you can safely remove it.

Neither the data transformation or the manager UI supports block groups inside of block groups.

best regards

**Comment by LukeOwlclaw** [comment]
Thanks for the clarifications, @tidyui!

BTW, Piranha is *awesome*! 👍  Thank you so much for this great project!
