### ISSUE TITLE
Add support for aliyun oss storage

### ISSUE THREAD

**Issue by successgo** [PiranhaCMS/piranha.core#1686]

**Comment by tidyui** [comment]
We only provide tools for hosting applications locally or on Azure as these are the environments we know and use. However we encourage you to create your own module for this and publish it as a NuGet package so others can benefit from it. Much like there are packages on NuGet for using AWS S3 Storage with Piranha.

Best regards

Håkan

**Comment by successgo** [comment]
@tidyui Hi, thanks for your feedback.

I will have a try to make a standalone nuget package called `Success.Piranha.Aliyun.OssStorage`. 

Thanks for your hard work for the beautiful project and I have learnt a lot from **Piranha CMS** as a `.NET` beginner.
