### ISSUE TITLE
How to get site culture?

### ISSUE THREAD

**Issue by PaddySe** [PiranhaCMS/piranha.core#1690]
Hi,

Not sure if this is a bug, or if it is a setup issue on my end…

I'm running Piranha 9.1.1. I have configured the site (a new site and not the default site) to use the culture _sv-SE_. However, I'm not able to retrieve the site culture from code. `WebApp.Site.Culture` is always null in the views, and if I get the site using `_api.Sites.GetByIdAsync(model.SiteId)` (_model_ is the current page) in the controller, the resulting site object also has Culture set to null.

I have tried setting the culture of the site in the manager to only have a single culture, and have tried keeping the _en-US_ culture there, and having either of them set to default, but the Culture property is always null.

Am I doing something wrong? Is there a different way of getting the culture setting? I guess I could check directly with the database, but that just feels wrong... :)

**Comment by PaddySe** [comment]
Never mind, I figured out how to load the language for the site.

What I was trying to do, was to set the lang attribute on the html tag to the language of the site, but since it is a bit of a hassle to load the language every time anything is rendered, I'm just going to hard code it into the layout.

**Comment by tidyui** [comment]
@PaddySe The culture property on Site is an obsolete remainder that should have been removed. In the more recent versions you select a language for a site, and that language has a culture assigned to it. The language culture should be mapped to the WebApp service per request, but I definitely have to check to see if the docs are up to date!

Regards
