### ISSUE TITLE
Blazor and database

### ISSUE THREAD

**Issue by AdamJachocki** [PiranhaCMS/piranha.core#1694]
Hi, I have two questions:
1. Can nowadays Piranha be used in Blazor WebAssembly? If not are there any plans?
2. Piranha can use Sqlite database. Does it mean I can host it wherever I want? (like Blazor WebAssembly?)

**Comment by tidyui** [comment]
Hi there! We unfortunately have no experience in using Blazor WebAssembly, so we can't really answer your question. My suggestion is you try the gitter chat, maybe some other users have tried something similar!

https://gitter.im/PiranhaCMS/Piranha

Regards
