### ISSUE TITLE
How to find Media by Folder Name instead of ID? Or is there a better approach?

### ISSUE THREAD

**Issue by sander1095** [PiranhaCMS/piranha.core#1695]
Hello!

I am looking around in your (Great looking) CMS and I am wondering how I would retrieve media in a sane way.

Let's say I have a media folder called "tech images" filled with images of tech logos a company uses. I want to show this on the home page.
Your `IMediaService` only has a way to retrieve a folder's media by ID, and I do not have the ID; the ID seems to be a randomly created GUID. 

I can think of 2 things:

- Somehow change the ID in the database for each environmento to be the same (local, test, prod) and hardcode it in my codebase so we can use `GetAllByFolderIdAsync(id)`.
  - This seems pretty ugly, I don't like hardcoded Id's in my codebase everywhere cuz they don't say anything, and having to manually change the database keys for each environment seems way too hacky.
- Write my own `GetMediaByFolderNameAsync(name) like this:

```c#
public static async Task<IEnumerable<Media>> GetAllByFolderNameAsync(this IMediaService mediaService, string name)
{
    if (string.IsNullOrWhiteSpace(name))
    {
        throw new ArgumentException($"'{nameof(name)}' cannot be null or whitespace.", nameof(name));
    }

    // Inefficient!
    // We use Ordinal instead of OrdinalIgnoreCase to prevent lazy code that contains typo's.
    var folder = (await mediaService.GetAllFoldersAsync()).FirstOrDefault(x => x.Name.Equals(name, StringComparison.Ordinal));

    if (folder == null)
    {
        throw new Exception($"Folder {name} could not be found!");
    }

    var media = await mediaService.GetAllByFolderIdAsync(folder.Id);

    return media;
}
```

This seems ugly as well because now I can't change my folder name without also changing my code (or I have my blocks contain a "folder name" field so we can use that, but that also is some custom work), but it seems a bit better than hardcoded GUID's in my codebase.

I am wondering if I am misunderstanding something, or if my "findbyname" is the best approach for my situation

Thank you very much!

**Comment by tidyui** [comment]
I would create my own add-on service which I would register in `Startup.cs` that performs the necessary filters and searches directly on the `DbContext` and then use the `Api` to get the media models. Here's an example:

~~~csharp
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Piranha;
using Piranha.Models;

namespace MyNamespace
{
    public class MyMediaService
    {
        private IApi _api;
        private IDb _db;

        public MyMediaService(IApi api, IDb db)
        {
            _api = api;
            _db = db;
        }

        public async Task<IEnumerable<Media>> GetByFolderName(string name)
        {
            var folder = await _db.MediaFolders
                .AsNoTracking()
                .Where(f => f.Name == name)
                .OrderBy(f => f.Name)
                .FirstOrDefaultAsync()
                .ConfigureAwait(false);

            if (folder != null)
            {
                return await _api.Media.GetAllByFolderIdAsync(folder.Id)
                    .ConfigureAwait(false);
            }
            return new List<Media>();
        }
    }
}
~~~

Best regards

**Comment by sander1095** [comment]
I found a better solution. The dev should not use folders by name. Instead, the dev should let the cms user select the folder or media so the user is free to change the cms however they want and are not limited to hardcoded paths

**Comment by sander1095** [comment]
Created #1706.
