### ISSUE TITLE
How to get languageId ?

### ISSUE THREAD

**Issue by hrvoje-grabusic** [PiranhaCMS/piranha.core#1703]
Hi,

How do i get the languageId of the current site ?
I expected it would be something like this since the languageId is in the Sites table but its missing from the sitehelper object.
`WebApp.Site.LanguageId`

**Comment by hrvoje-grabusic** [comment]
This works:
```csharp
var site = await WebApp.Api.Sites.GetByIdAsync(WebApp.Site.Id);
<p>@site.LanguageId</p>
```

**Comment by tidyui** [comment]
Yes it works, but it would be better if `LanguageId` was included in the site helper!
