### ISSUE TITLE
Timeout when uploading large media files

### ISSUE THREAD

**Issue by esandstedt** [PiranhaCMS/piranha.core#1704]
We've experienced the media component cancelling uploads after 30 seconds, which sets an implicit limit on file sizes.

After googling a bit, I found this issue which is quite similar.
https://github.com/flagscript/Flagscript.PiranhaCms.Aws.S3Storage/issues/28

I think it might have to do with the default `timeout` configuration option in Dropzone.js. It is 30 seconds.
https://www.dropzonejs.com/#configuration-options

**Comment by esandstedt** [comment]
I discovered another issue with large files. The media upload endpoint uses the default max request body size of 30MB. 
https://github.com/aspnet/Announcements/issues/267

I worked around the issue by increasing the limit globally.

**Comment by tidyui** [comment]
Hi there. The first one we could add a config setting for. The second one is by design as Piranha is a framework and can’t demand any specific max upload size by the application.

Regards

**Comment by tidyui** [comment]
This can now be configured by setting the following in your `Startup.cs`:

~~~csharp
Config.ManagerXhrTimeout = 60; // This sets the timeout to 60 seconds
~~~

**Comment by dmdmaasz6** [comment]
Good Morning All, do we have the solution in a dotnet core 6 project documented anywhere. I am having major issues with file uploads bigger than 10MB timing out, and I have tried it all but cannot seem to find the solution. Please let me know if there is a documented example of how to set the timeout in Program.cs of a dotnet core 6 or 7 solution with no startup.cs. Your assistance in this regard will be highly appreciated.

**Comment by tidyui** [comment]
Hi there! The same applies in Program.cs, but as there’s no Configure() where you can get the Config injected you need to construct it yourself providing the IApi you have available.

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha/Config.cs#L229

Regards
