### ISSUE TITLE
EmailConfirmed is not handled in User create or edit

### ISSUE THREAD

**Issue by wilmarmacosta** [PiranhaCMS/piranha.core#1708]
The user confirmed his email, however, if you  edit the user in the cms manager, the emailconfirm value becomes false, the user then cannot login and asked to confirm his email again. This is

**Comment by tidyui** [comment]
I can’t see that we’ve ever set EmailConfirmed in our code, so I’m assuming you have a custom registration page for your users?

**Comment by wilmarmacosta** [comment]
Yes, I do have a custom registration page which includes the user confirms
his email address, all works fine.

However, when the admin edits the user with confirmed email address in the
cms manager and save, the emailconfirmed field is back to false.

I already solved this for me by retaining the emailconfirmed value on
model.Save method within Identity class.

**Comment by tidyui** [comment]
Updated title as this has nothing to do with version `9.1.1`

**Comment by tidyui** [comment]
Fixed in master, see PR #1779
