### ISSUE TITLE
Custom Page: Where I find the field out the custom region?

### ISSUE THREAD

**Issue by biapar** [PiranhaCMS/piranha.core#1714]
I create a demo page and insert a field DemoPageTitle out of custom region. 

- I don't find the field into the admin panel. Why?
- Is't a must to inherit from Page?

~~~csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Piranha.AttributeBuilder;
using Piranha.Models;
using Piranha.Extend;
using Piranha.Extend.Fields;

namespace PiranhaCMS9.Models
{
    [PageType(Title = "DemoPage")]
    public class DemoPage : Page<DemoPage>
    {
        public class HeroRegion
        {
            [Field]
            public StringField Title { get; set; }
            [Field]
            public ImageField Image { get; set; }
            [Field]
            public TextField Body { get; set; }
        }

        [Region]
        public HeroRegion Hero { get; set; }

        [Field]
        public StringField DemoPageTitle { get; set; }
    }
}
~~~

**Comment by tidyui** [comment]
Hi there! A page/post/site model doesn't handle properties marked with the `FieldAttribute`, they only look at `RegionAttribute`. To create a single field region you must therefor use the following syntax.

~~~csharp
public class DemoPage : Page<DemoPage>
{
   ...

   [Region]
   public StringField DemoPageTitle { get; set; }
}
~~~

For more information, take a look at the documentation here under "Single Field Regions":

https://piranhacms.org/docs/master/content/regions

**Comment by biapar** [comment]
Thanks.
Is't a must to inherit from Page?

**Comment by tidyui** [comment]
Yes, all pages must inherit from Page<T>
