### ISSUE TITLE
Contact | Security Issue

### ISSUE THREAD

**Issue by hagaiwech** [PiranhaCMS/piranha.core#1724]
Hi @tidyui and PiranhaCMS team,

I've tried to contact you privately through hakan@tidyui.com, but didn't get a reply. 
Please get back to me at hagai.wechsler@whitesourcesoftware.com.
It's about security issues found in your project.

Thanks
Hagai

**Comment by tidyui** [comment]
We have responded to your email. As both of these issues are extremely minor and needs very small changes in the code we suggest you open two issues or even better send two pull requests with your suggested changes.

Best regards

**Comment by tidyui** [comment]
Both issues resolved, see #1725 #1726. Closing issue
