### ISSUE TITLE
Post category slug don't save

### ISSUE THREAD

**Issue by Gigagom** [PiranhaCMS/piranha.core#1757]
Hi! When I try to save post with category name in Russian, category slug don't save, and then if I try to save another one category in Russian I've got an error:
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Piranha_Categories.BlogId, Piranha_Categories.Slug'
I guess that, category slug is saved only if the category name is written in English

**Comment by tidyui** [comment]
Hi there! You need to override to slug generation to suit your needs. This can be done with the available hooks!

https://piranhacms.org/docs/master/application/hooks
