### ISSUE TITLE
Addd vue component like page list

### ISSUE THREAD

**Issue by traustitj** [PiranhaCMS/piranha.core#1758]
I have a page on my module in the manager area. The page loads.
But I want to add a vue component without using the whole vue-cli monster. I want to add a vue component like https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/assets/src/js/piranha.pagelist.js
I use the gulpfile from the manager to compile my component.
My component looks like this (source)
```
<template>
    <div>vue component</div>
</template>

<script>
export default {
    el: "#mylist",
    data () {
        return {
            loading: true,
        }
    },
    created() {
        this.load();
        console.log('Hello world');
    },
    methods: {
        load: function () {
            var self = this;
            setTimeout(() => {
                self.loading = false;
            }, 3000);
        }
    }
}
</script>

```

the compiled version looks like this

```
Vue.component("my-list", {
  el: "#mylist",

  data() {
    return {
      loading: true
    };
  },

  created() {
    this.load();
    console.log('Hello world');
  },

  methods: {
    load: function () {
      var self = this;
      setTimeout(() => {
        self.loading = false;
      }, 3000);
    }
  },
  template: "\n<div>vue component</div>\n"
});
```

my index.cshtml located in /Areas/Manager/MyModule/index.cshtml

```
@page "~/manager/MyModule"

@{
    ViewBag.Title = "My lists";
}

<div id="mylist">
    <div class="top">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Settings</li>
                <li class="breadcrumb-item active" aria-current="page">My List</li>
            </ol>
        </nav>

        
    </div>

    <div class="container-fluid app2" :class="{ ready: !loading }">
        <div class="row">
            <div class="col">
                <h3>Here might be some lists</h3>
            </div>
        </div>
    </div>
</div>

```

Inside startup.cs I add this

````
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IApi api)
....
App.Modules.Manager()
                .Scripts.Add("/js/trausti.components.js");
````

This is not the complete code. I have modules, permissions and you name it. The manager works. Just the Vue component does not appear. I can see that my javascript file is being downloaded.
I don't see the console.log being displayed.

The only thing I can see that it is there is this warning in the console. 
````
piranha-deps-dev.js:18663 [Vue warn]: option "el" can only be used during instance creation with the `new` keyword.
````
This is as far as I have been able to reach.
Using Piranha 9.0.0

**Comment by tidyui** [comment]
Sorry for the late response! Try including your vue component script from your cshtml page in the script section, this is how the other pages do it. As an example:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Areas/Manager/Pages/AliasEdit.cshtml#L9

Chances are your component is added now before any dependencies.

regards
