### ISSUE TITLE
10.0 PostgreSql InvalidCastException with DateTime 

### ISSUE THREAD

**Issue by DjeeBay** [PiranhaCMS/piranha.core#1762]
I encountered the following error when trying to launch a brand new project with v10.0 and PostgreSql :

InvalidCastException : Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. 

To resolve it I needed to add the following line of code in the ConfigureServices method :
`System.AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);`

I don't know if it's a good way to resolve this but at least it work's for now.

Resources I've found about it :
https://github.com/npgsql/efcore.pg/issues/2000
https://www.npgsql.org/efcore/release-notes/6.0.html

Hope it helps.

**Comment by tidyui** [comment]
Ping @junderhill

**Comment by tidyui** [comment]
We’ll take a look if we can add default configuration in our extension methods to avoid this problem!

**Comment by PoisnFang** [comment]
@tidyui FYI this [commit ](https://github.com/PiranhaCMS/piranha.core/commit/a25be57442f96ca016c0cc84c32dbd0395295785) did not fix the error for me. I still had to modify my `Program.cs` file (I have not migrated to a flat file)
```csharp
        public static void Main(string[] args)
        {
            var test = CreateHostBuilder(args).Build();
            AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
            test.Run();
        }
```

**Comment by tidyui** [comment]
This is unfortunate as the solution was taken from the `Npsql` homepage:

> To do this and revert to the legacy timestamp behavior, add the following to your context's constructor, before any Npgsql or EF Core operations are invoked:
>
> `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);`

**Comment by tzaorski** [comment]
I had a similar problem. After upgrading the CMS to the latest version and adding the above workaround, the home page does not work (HTTP ERROR 404). The manager works without a problem.

**Comment by gyfke** [comment]
> This is unfortunate as the solution was taken from the `Npsql` homepage:
I had the same problem on empty database.
Before legacy timestamp behavior applied `: base(options)` is called
And the base class constructor seeds the default data and throws the exception
![image](https://user-images.githubusercontent.com/15141774/200222063-523ceab1-c92b-4976-9853-48ae57ea5e3d.png)
