### ISSUE TITLE
Copying pages between sites doesn't work from the "Add page" button

### ISSUE THREAD

**Issue by ddavisfw** [PiranhaCMS/piranha.core#1766]
It would be helpful to have the ability to copy or clone a page from one site to another. It would be nice to have new guids assigned to each element so it operates independently from the old page, blocks, etc. This could serve as a "starting point" for when you create a new site and just want to make tweaks to the new page instead of building it from scratch.

**Comment by tidyui** [comment]
Hi there! You can already do this by first creating a copy of a page and then detaching it from the original. All of this can be performed from the admin UI.

**Comment by ddavisfw** [comment]
It doesn't seem to allow you to move that detached copy over to another site though.

**Comment by tidyui** [comment]
There seems to be an issue when creating a copy from the "Add page" button between sites. If you use the buttons in the sitemap to add a copy at a certain position it works just fine. I'll add an issue for this.
