### ISSUE TITLE
SiteService doesn't work

### ISSUE THREAD

**Issue by HusseinKhodadadi** [PiranhaCMS/piranha.core#1768]
Hi. I inject Piranha.AspNetCore.Services.IApplicationService WebApp in `\piranha.cms\core\Piranha.Manager\Areas\Manager\Pages\Partial\_PageSettings.cshtml` and I add some codes:

```
<div class="form-group">
    <label>@Localizer.General["Slug"]</label>
    <div class="input-group">
        <input v-model="slug" type="text" maxlength="128" class="form-control">
        <div class="input-group-append">
            <div class="input-group-text text-muted farsiNum">
                {{ piranha.utils.strLength(slug) + "/128" }}
            </div>
        </div>
    </div>
    <span class="field-description small text-muted slugDescription">
        @{
===>        var site = await WebApp.Api.Sites.GetByIdAsync(WebApp.Site.Id);
            var hostname = site.Hostnames != "" ? site.Hostnames : "Hostname";
         }
            https://@hostname/<span v-text="slug"></span>
    </span>
</div>
```
in v9.2 site variable  is not null and code works fine. but v10 site is allways null.

**Comment by tidyui** [comment]
The service `Piranha.AspNetCore.Services.IApplicationService` was never intended to be used in the manager, it is a helper service for building client applications. As a part of cleaning up the request pipeline in `10.0` we made sure none of the client-side tools are executed inside the manager, thus resulting in the service not being initialized inside of the manager.

Also, for the above use case the page settings would always should the hostname of the current request, and not neccessary the correct hostname if you have multiple sites setup in your application. Instead I would suggest you get the site that the page belongs to using the `SiteService` within `IApi` and use that information.

Best regards
