### ISSUE TITLE
x-xsrf-token doesn't exist.

### ISSUE THREAD

**Issue by HusseinKhodadadi** [PiranhaCMS/piranha.core#1770]
Hi. I add login and logout pages in MvcWeb project and change login/out path to them:
![Untitled1](https://user-images.githubusercontent.com/80600729/143311622-b8d11067-c1b4-4076-9107-4352e7a01558.jpg)
after login , when I want to save configs, i get error message:
![Untitled2](https://user-images.githubusercontent.com/80600729/143312121-3b4b5d0e-aa11-4563-a0f8-fb16ecac61aa.jpg)
x-xsrf-token doesn't exist in cookies.
this Scenario works fine in v9.2.
thanks.

**Comment by tidyui** [comment]
Hi there! After successful login you need to redirect to “manager/login/auth” for the anti forgery to be set up correctly.
