### ISSUE TITLE
returnUrl is null

### ISSUE THREAD

**Issue by HusseinKhodadadi** [PiranhaCMS/piranha.core#1771]
Hi. Requested authorized page url will not return after login. instead manager page returned always.
in v9.2 its work correctly
![Untitled3](https://user-images.githubusercontent.com/80600729/143417055-360456bc-4ba1-4f76-8125-4145ad5f00d6.jpg)
![Untitled4](https://user-images.githubusercontent.com/80600729/143417059-5eb9b95f-7f19-411d-8b8e-877de2c047c4.jpg)
.

**Comment by tidyui** [comment]
Confirmed
