### ISSUE TITLE
Piranha.Azure.Search

### ISSUE THREAD

**Issue by martijntakken** [PiranhaCMS/piranha.core#1773]
What happened to Piranha.Azure.Search (https://github.com/PiranhaCMS/piranha.core/tree/master/core/Piranha.Azure.Search)? It is not available as nuget package and I think it is also not in the core. Is it still valid? I'm looking for a solution to implement Azure Search.

**Comment by tidyui** [comment]
As we have limited resources we never had the time to finish it, but it should be valid and we keep the code as a boilerplate for anyone who wants to write their own search implementation.

if you’d like to collaborate on getting it finished that would of course be much appreciated.

Best regards

**Comment by martijntakken** [comment]
thanks for clarifying, we will discuss with the team what to do with this.
