### ISSUE TITLE
Excel upload

### ISSUE THREAD

**Issue by RSStudios** [PiranhaCMS/piranha.core#1778]
Hello,

I'm in the process of writing a CMS web site for an archery club, where, at present, they upload different results as PDFs to their old site, which look awful.

What I would like to do is allow them to upload Excel files with all of the different results & then I will open the file, read it and create a HTML table to display the results, so I'm writing a custom block.  

However, I'm very confused as to what type of Field to use?  Should I be using DocumentField?  I don't understand what Media refers to?  Do you define media to mean sound files, videos...?  Or does media refer to any type of file, e.g. .xlsx, .docx, .txt...?

In addition, I don't know if I need any custom VueJS.

I would be very grateful for some pointers.

Thanks very much.

Robert

**Comment by tidyui** [comment]
Hi there! `Media` is everything uploaded in the system, in retrospect `Assets` would have been a better name, but what is done is done :) Media is divided into the types `Audio`, `Document`, `Image`, `Resource` and `Video`. The different fields available are simply for filtering out the available content in the management UI. What category you place `.xls` in (as it's not included by default) is totally up to you. You can read more about this here: 

https://piranhacms.org/docs/master/content/media

If you don't specify any specific `vue` component for your block the management UI will use the default component which will render the available fields in the block, much like a region.

Best regards
