### ISSUE TITLE
Should not be able to delete SYSADMIN role

### ISSUE THREAD

**Issue by SuccessGo** [PiranhaCMS/piranha.core#1786]
Hi, I have noticed that SYSADMIN normalized name can not be changed to others, so if that means it's not better to delete the SYSADMIN role?

![image](https://user-images.githubusercontent.com/13791720/146338810-a20de2dd-b2b4-42cc-b434-287707ca42f8.png)

**Comment by tidyui** [comment]
The `SYSADMIN` role will be checked on initialization, and if not present it will be created. In other words it can't be deleted, and it's rather a bug in the UI/API:s if it allows you to delete it.
