### ISSUE TITLE
Can I ask for a basic question on how does this code segment to submit the form ?

### ISSUE THREAD

**Issue by SuccessGo** [PiranhaCMS/piranha.core#1790]
![image](https://user-images.githubusercontent.com/13791720/146745254-504ef06b-cbce-4c03-98df-aae730a776e1.png)

Hi, sorry to bother you to ask the question, I'm reading your perfect code and design.

Many thanks.

**Comment by tidyui** [comment]
I highly doubt the code is perfect 🙂 It’s a regular form post that posts the Id to the endpoint responsible for deleting a role. This part of the code has never been converted from MVC to Vue.
