### ISSUE TITLE
Media folder image compression

### ISSUE THREAD

**Issue by JSvanVeen** [PiranhaCMS/piranha.core#1797]
One of the requirements of a website I am currently working on is the automatic compression of images when uploaded to the CMS. After going through the documentation and issues on Github I struggled to find a way to compress images when uploaded to the media folder. Is there currently a feature to do so?

**Comment by tidyui** [comment]
The original image is never compressed, however you could possibly register your own IStorage service which adds compression before saving the binary data.

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha/IStorageSession.cs
