### ISSUE TITLE
Can not call api keep getting null reference

### ISSUE THREAD

**Issue by spurpura12** [PiranhaCMS/piranha.core#1798]
I call api.Pages.GetPageById and I keep getting null reference error. See attachment. 

![83EFC410-200F-4D4B-9507-29214D84E805](https://user-images.githubusercontent.com/96312540/147373197-582fef2f-66ae-4f10-a2d4-526f0d21a5f6.png)

**Comment by tidyui** [comment]
How was the page created in the database? If there's a null reference exception some data must be invalid when transforming the page.

**Comment by spurpura12** [comment]
I found the issue it was related to media storage I had to use azure blob storage.
