### ISSUE TITLE
The antiforgery token could not be decrypted

### ISSUE THREAD

**Issue by mdressel** [PiranhaCMS/piranha.core#1803]
We are in the process of upgrading Piranha that has been embedded into a custom application from a very old version (6.1 to the latest version). We have everything working with the exception of creating/saving changes to pages. When we create/save pages we get 400 response and the error is 
> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.

After looking into it the request being sent has a `X-XSRF-TOKEN` header but no value. 

![image](https://user-images.githubusercontent.com/30449770/148475469-ff1f0a2a-9338-454a-8dee-5e4ce5a4cac2.png)

It also doesn't have a cookie that matches `XSRF-REQUEST-TOKEN`.

![image](https://user-images.githubusercontent.com/30449770/148475632-4d4ce718-d14b-4768-8b90-a5e1691defba.png)

It does have a "standard" AspNet antiforgery token (though we don't explicitly add/configure this token).

I have tried to explicitly configure the options in Pirahna, but the error still happens. Any ideas on what is going on or how to resolve this? I believe the issue is that no matter what I do the XSRF header is never populated.

**Comment by tidyui** [comment]
In v10 another step was added when logging into the manager that takes care of setting up the anti forgery tokens. This means that if you have custom authentication set up, this must redirect to this route after successful login:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Controllers/AuthController.cs#L41

This process can also be interrupted depending on how you configure the cookie middleware pipeline with for example cookie consent as this can block the cookie from being stored.

Regards

**Comment by mdressel** [comment]
@tidyui thanks for the quick response. I figured out our issues, the main problem is that our settings for cookies would not allow the cookie to be saved by the browser.

Why wouldn't you consider this cookie "essential" so that it bypasses the consent requirement? Or at least add that as an CookieOption so a user could decide.
