### ISSUE TITLE
Media delete error in host

### ISSUE THREAD

**Issue by HusseinKhodadadi** [PiranhaCMS/piranha.core#1804]
Hi. uploading and deleting media in localhost works fine. but in real host i can not delete media.
![Untitled1](https://user-images.githubusercontent.com/80600729/148659903-e28a673a-3ef8-493c-97cb-16a777569dbf.jpg)

**Comment by tidyui** [comment]
Have you upgraded your project to 10.0 from a previous version? Could it be related to #1803?

**Comment by HusseinKhodadadi** [comment]
I used piranha mvc example by latest version without any change. The antiforgery token has value.

**Comment by HusseinKhodadadi** [comment]
Removing folder also has error. In MediaApiController, changing HttpDelete Attributes to HttpPost and delete methods to post in piranha.media.js solve problem.

**Comment by HusseinKhodadadi** [comment]
I finally solve this problem. This error is caused because the WebDAV module intercepted the request.
Inserting the following in the web.config file solve problem:

```
<system.webServer>    
  <modules>        
    <remove name="WebDAVModule" />    
  </modules>    
  <handlers>        
    <remove name="WebDAV" />    
  </handlers>
</system.webServer>
```
