### ISSUE TITLE
Manager login does not obey return url

### ISSUE THREAD

**Issue by traustitj** [PiranhaCMS/piranha.core#1808]
When your session is expired and you are redirected to http://localhost:5000/manager/login?ReturnUrl=%2Fmanager%2Fmedia
as an example.

It always goes back to http://localhost:5000/manager/pages

**Comment by tidyui** [comment]
Which version are you using? A fix for this was released in 10.0.1 https://github.com/PiranhaCMS/piranha.core/releases/tag/v10.0.1

Regards

**Comment by traustitj** [comment]
I was using 10.0.0. I can verify that this is not an issue in 10.0.1
