### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [PiranhaCMS/piranha.core#1810]
Hey there!

I belong to an open source security research community, and a member (@satanon2k1) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by tidyui** [comment]
We will look into how a security policy should best be setup for the project as we wasn’t aware of this standard. In the meantime please report anything suspicious to info@piranhacms.org

Best regards

**Comment by JamieSlome** [comment]
@tidyui - thank you for your reply! ❤️ 

You should've received an e-mail to that address yesterday. You can view the report directly here as well:

https://huntr.dev/bounties/6e5d2c36-75d3-4ee1-b7ac-bc9bafdac445/

**Comment by tidyui** [comment]
Added in commit 55753b9a5ba2cc52ae6757fd9a78b019bed89309
