### ISSUE TITLE
How to use Persian or Arabic Language And rtl theme

### ISSUE THREAD

**Issue by Mos80** [PiranhaCMS/piranha.core#1820]

**Comment by tidyui** [comment]
Translations for the manger area are handled here:

https://crowdin.com/project/piranhacms

Looks like no one has contributed to the Persian translations yet, and the Arabic is only at 55%

**Comment by Mos80** [comment]
Thank you,
How to use rtl theme manager ?

**Comment by Mos80** [comment]
And how to change language Piranha CMS ?
thanks for help me

**Comment by tidyui** [comment]
The language used is determined from the culture of the current thread as regular asp.net localization. This can be set through code or from a number of middleware’s available from Microsoft, depending on the solution you want.

**Comment by Mos80** [comment]
Hi  tidyui
Persian translation is completed now how i can use it?

**Comment by tidyui** [comment]
Everything except the config translations you made in the last PR has been released in 10.0.2 which is available on NuGet. We thought all of the translations were done with the first PR
