### ISSUE TITLE
XsrfCookie not set as essential

### ISSUE THREAD

**Issue by LukeOwlclaw** [PiranhaCMS/piranha.core#1829]
In [``SetAuthCookie``](https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Controllers/AuthController.cs#L41) we have:

    Response.Cookies.Append(_options.XsrfCookieName, tokens.RequestToken, new CookieOptions
    {
        HttpOnly = false,
    });

What is missing here:

    IsEssential = true,

Without making it essential, the cookie will only be set if [``CheckConsentNeeded``](https://stackoverflow.com/a/52461278) option is ``false``. However, the auth cookie is essential according to [GDPR](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1).

**Comment by vjacquet** [comment]
The fix works on Firefox but I am still having the issue on Edge (Version 100.0.1185.50 (Version officielle) (64 bits)). I believe the same site option should also be set.

I used the following workaround to set the SameSite to SameSiteMode.Strict, as it is done for the [antiforgery cookie](https://github.com/dotnet/aspnetcore/blob/321ec912eaa8ce3c4515f61fdf7e224f7f7349c4/src/Antiforgery/src/AntiforgeryOptions.cs#L20).
```c#
// HACK: Piranha does not set the SameSite options, resulting in missing cookie on edge.
builder.Services.AddOptions<CookiePolicyOptions>().Configure<IOptions<ManagerOptions>>((options, manager) =>
{
    options.OnAppendCookie = context =>
    {
        if (context.CookieName == manager.Value.XsrfCookieName)
        {
            context.CookieOptions.SameSite = SameSiteMode.Strict;
        }
    };
});
```

**Comment by muench-develops** [comment]
I can't get into the breakpoint, as it doesn't have xsrf cookies set either. However, I thought that the cookie was once set since I had seen this in the DevTools.
