### ISSUE TITLE
Question: Multiple language sites

### ISSUE THREAD

**Issue by alexvasiu** [PiranhaCMS/piranha.core#1832]
I've started working with Piranha CMS for a while, but I have a new requirement to make the site available in 2 languages. I saw that this is possible by adding 2 different sites, but I have some issues (difficulties):

1. I don't have any languages available in the site language dropdown. How is this configurable?
2. I saw that in order for the second site to work I have to add it in the hostnames field, but I'm not sure what this means and how. 
Can you provide an example?

**Comment by blakepell** [comment]
- In the manager, click on the site.
- Under `Language` click on the settings icon.
- Add a new language, click `Save`
- Now, you'll need to close out that slide out panel and go back into it to see it populated.  It appears that after you save it doesn't re-populate the drop down until the panels is reloaded.

![image](https://user-images.githubusercontent.com/5958430/156795402-0cf66ef1-fb7c-4265-bf27-b8a95149c317.png)

![image](https://user-images.githubusercontent.com/5958430/156795417-2ba5fcd8-d06f-4c62-9840-3b5e80a9ea65.png)
