### ISSUE TITLE
Piranha + Mysql + Linux

### ISSUE THREAD

**Issue by mrccarvalho** [PiranhaCMS/piranha.core#1834]
Hi,

**I ran Piranha on a Windows machine:**
Piranha 10.0.2  

**Remote Database:**
Mysql server 8.0.26 installed on a Production Linux Server (Rocky Linux 8)
Everything Works fine.  

But when i Publish Piranha to the same Linux Server, where the mysql database is installed, it gives an error with mysql connection.

` MySqlConnector.MySqlException (0x80004005): Access denied for user ''@'localhost' (using password: NO)
         at MySqlConnector.Core.ServerSession.SendClearPasswordAsync(String password, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line`

Thanks,

**Comment by tidyui** [comment]
The error message clearly indicates that there’s something wrong with the connection string as there’s an access denied exception for the user.

have you tried logging the configurated credentials in your startup to make sure the config is read properly?

**Comment by mrccarvalho** [comment]
Thanks @tidyui .

I will try logging the configurated credentials.

**Comment by mrccarvalho** [comment]
Hi!

Solved.
Permission denied to appsettings.json. Now the connection string can be reached and read.

It's working. 

Thanks you!

**Comment by tidyui** [comment]
Great!
