### ISSUE TITLE
Is changing the text of toolbar buttons possible in Piranha 9.0?

### ISSUE THREAD

**Issue by slpaz** [PiranhaCMS/piranha.core#1838]
The TinyMCE editor can be configured in the editorconfig.json file in 9.0. Is it possible to change the toolbar titles? For example, the formatselect and the styleselect both show Paragraph, is there a way to assign a title for those dropdowns?

![image](https://user-images.githubusercontent.com/102210848/159641218-af3a5bf7-5646-496a-88e3-1567520cc2b1.png)

```
{
  "plugins": "autoresize autolink code hr paste lists piranhalink piranhaimage",
  "toolbar": "bold italic underline | fontsizeselect | bullist numlist hr | alignleft aligncenter alignright | formatselect styleselect | piranhalink piranhaimage | forecolor backcolor",
  "blockformats": "Paragraph=p;Header 1=h1;Header 2=h2;Header 3=h3;Header 4=h4;Header 5=h5;Code=pre;Quote=blockquote",
  "styleformats": [
    { "title": "Small", "tag": "small", "type": "inline" }
  ]
}
```

**Comment by tidyui** [comment]
This has been discussed in Gitter. Bigger customizations of the editor is done by adding a custom Init method for the editors where the full set of configuration options from Tiny cam be used.
