### ISSUE TITLE
Add asp-append-version to script/link tags

### ISSUE THREAD

**Issue by monsieurberry** [PiranhaCMS/piranha.core#1840]
Hi!

We have just successfully updated to v10 - it was a breeze so thank you.

For just one of our employees, they saw a blank screen when logging into the manager and the following message in the console...

![image](https://user-images.githubusercontent.com/706856/159931014-32103898-31b9-4cda-827a-5354a8a078d8.png)

After a bit of investigation I realised the piranha-deps.min.js was cached in their browser, and doing a hard refresh saved the day. This got me wondering if adding `asp-append-version="true" ` to the manager layouts would help mitigate this kind of error in future releases?

Thanks again for all the great work
Adam

**Comment by tidyui** [comment]
Given how we've embedded the resources in the manager `asp-append-version` doesn't seem to work, but we can append a hash of the current assembly version to the resources.
