### ISSUE TITLE
Read Language.Culture in ApplicationService.Initialize

### ISSUE THREAD

**Issue by Urreman** [PiranhaCMS/piranha.core#1845]
When site is saved, the culture is set from it's previous value (which is allways null since there is no input field for site culture).
Instead it should be stored from it's connected language culture.

Possible solution:
https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Services/SiteService.cs
public async Task Save(SiteEditModel model){ 
    ... 
    var language = await _api.Languages.GetByIdAsync(model.LanguageId);
            if (language != null) {
                site.Culture = language.Culture;
            }
    ...
}

**Comment by tidyui** [comment]
So to clarify, there *was* a culture field on the site edit UI but it was removed. The problem is that the property is still there in the model.

**Comment by tidyui** [comment]
Should be added here: https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore/Services/ApplicationService.cs#L127

**Comment by Urreman** [comment]
Yeah, it's been a while, hope all is well :)

Also in the corresponding functionality in the RoutingMiddleware when
current culture is set from the site culture, it should be fetched from the
selected language instead.

Den mån 4 apr. 2022 kl 14:21 skrev Håkan Edling ***@***.***>:
