### ISSUE TITLE
Angular Website

### ISSUE THREAD

**Issue by smohammedyasin** [PiranhaCMS/piranha.core#1852]
Is this new version work with the angular template? I didn't find any doc for using with angular.
Please guide me.

Thank you

**Comment by tidyui** [comment]
Hi there! We don’t provide an Angular template, what template are you referring to?

Regards

**Comment by smohammedyasin** [comment]
Hi,
I found post on old version with angular template [https://libraries.io/github/PiranhaCMS/piranha.core.angular](https://libraries.io/github/PiranhaCMS/piranha.core.angular)

but I'm not sure this will work with new version.

**Comment by tidyui** [comment]
This package was contributed by an external user who took over control over the repo. Unfortunately I think he lost interest of it, didn't update it, and eventually removed it from his profile.

Regards
