### ISSUE TITLE
MS SQL Connection string 

### ISSUE THREAD

**Issue by smohammedyasin** [PiranhaCMS/piranha.core#1854]
Hi , 
I'm trying to use SQL Server connection string in appsettings.json file with 
`"ConnectionStrings": {
    "piranha": "Data Source=localhost ;Initial Catalog=PiranaCMS;User Id=sa;Password=mypassword;MultipleActiveResultSets=True;",
    "blobstorage": "DefaultEndpointsProtocol=https;AccountName=;AccountKey=;EndpointSuffix="
  }`

and I got below exception

` **System.ArgumentException:** 'Connection string keyword 'initial catalog' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.

This exception was originally thrown at this call stack:
    [External Code]
    Piranha.Db<T>.Db(Microsoft.EntityFrameworkCore.DbContextOptions<T>) in Db.cs
    Piranha.Data.EF.SQLServer.SQLServerDb.SQLServerDb(Microsoft.EntityFrameworkCore.DbContextOptions<Piranha.Data.EF.SQLServer.SQLServerDb>) in SQLServerDb.cs
    [External Code]
    PiranhaHostingExtensions.UsePiranha(Microsoft.AspNetCore.Builder.WebApplication, System.Action<Piranha.AspNetCore.PiranhaApplication>) in PiranhaHostingExtensions.cs
    Program.<Main>$(string[]) in Program.cs
`
**Program.cs**

`using Microsoft.EntityFrameworkCore;
using Piranha;
using Piranha.AspNetCore.Identity.SQLServer;
using Piranha.AttributeBuilder;
using Piranha.Data.EF.SQLServer;
using Piranha.Manager.Editor;

var builder = WebApplication.CreateBuilder(args);

builder.AddPiranha(options =>
{
    /**
     * This will enable automatic reload of .cshtml
     * without restarting the application. However since
     * this adds a slight overhead it should not be
     * enabled in production.
     */
    options.AddRazorRuntimeCompilation = true;

    options.UseCms();
    options.UseManager();

    options.UseFileStorage(naming: Piranha.Local.FileStorageNaming.UniqueFolderNames);
    options.UseImageSharp();
    options.UseTinyMCE();
    options.UseMemoryCache();

    var connectionString = builder.Configuration.GetConnectionString("piranha");
    options.UseEF<SQLServerDb>(db => db.UseSqlite(connectionString));
    options.UseIdentityWithSeed<IdentitySQLServerDb>(db => db.UseSqlite(connectionString));

    /**
     * Here you can configure the different permissions
     * that you want to use for securing content in the
     * application.
    options.UseSecurity(o =>
    {
        o.UsePermission("WebUser", "Web User");
    });
     */

    /**
     * Here you can specify the login url for the front end
     * application. This does not affect the login url of
     * the manager interface.
    options.LoginUrl = "login";
     */
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UsePiranha(options =>
{
    // Initialize Piranha
    App.Init(options.Api);

    // Build content types
    new ContentTypeBuilder(options.Api)
        .AddAssembly(typeof(Program).Assembly)
        .Build()
        .DeleteOrphans();

    // Configure Tiny MCE
    EditorConfig.FromFile("editorconfig.json");

    options.UseManager();
    options.UseTinyMCE();
    options.UseIdentity();
});

app.Run();`

Please suggest, Thank you

**Comment by tidyui** [comment]
The issue is that you're still using `UseSqlite(connectionString)` when you're trying to connect to a SqlServer.
