### ISSUE TITLE
Custom implementation of ISecurity leads to nowhere

### ISSUE THREAD

**Issue by Danonovsky** [PiranhaCMS/piranha.core#1855]
Hi,
so as I was following this tutorial:
https://piranhacms.org/docs/master/extensions/authentication
I've tried to add custom authentication for our app. However, I've always ended up with nothing, either redirect to "Account/Login" which was 404, redirect to login screen, even if my custom implementation of ISecurity went through. Is there anything more to add, besides what's in the tutorial above?
Anyways, I think it'll be good to update this, since ISecurity isn't the same anymore.

Thanks in advance!

**Comment by tidyui** [comment]
If you're trying to authenticate a user for the manager interface the user needs to have the appropriate claim after authentication. You can find all of the claims used in Piranha here: https://piranhacms.org/docs/master/architecture/authentication

**Comment by Danonovsky** [comment]
So, so far as I understand, claim "PiranhaAdmin" should be enough and I should've seen the manager interface? Or should I also set some role, etc?
I'll add some code snippet later, maybe I've done something wrong
