### ISSUE TITLE
Add native comment system

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#186]
Even though many external services exists for commenting, having custom functionality for it is good when building internal applications where you don't want to use any of these systems.

**Comment by LucGosso** [comment]
FYI, i used the comment repository in manager for storing form submissions data. 
http://www.lindovilla.se/om-foreningen/arsmote-2018

The form, is saved in a custom field, in this case the form string is: 
"Namn;input;Fullständigt namn;required|Epost;email;Fyll i email;required|Meddelande;textarea;Eventuellt meddelande till Lindö Villaägareförening, antal personer, matallergier m.m.|Mat;checkbox;Jag anmäler mig till buffén;|Medlem;checkbox;Jag är medlem;|VillBliMedlem;checkbox;Jag vill bli medlem;|Skicka;submit;"

**Comment by tidyui** [comment]
That's quite clever :) It shouldn't be that difficult to make a form builder field that allows you to setup custom forms and track responses to it. The only question is if it's a core feature or something that should be available as an add-on

**Comment by zareiramin** [comment]
Hi,
Any updates about this?

**Comment by tidyui** [comment]
Hi there! We will get around to do this sooner or later but is currently focusing on framework updates for `7.0`. If you want to contribute my suggestions would be to build this as a separate module that can be opted in.

## Entities and services
Store the comments in their own tables and provide services for loading/saving/deleting. The hooks available can be used as a foreign key constraint to remove comments if the post is deleted.

## Adding custom interface
In `7.0` you will be able to add a custom component on content type basis, this is how the archive view is added to Archive Pages. This way a view for comments could be added to posts, and another summary view could be added to Archive Pages as well to see the latest comments for all posts in an archive.

**Comment by jensbrak** [comment]
Excellent news adding this to 8.1, I would love to use it!
Let me know if you need help in some way, like testning or so.
This feature will, no matter how basic it will be in first release, add much value to Piranha - being a CMS and all.
