### ISSUE TITLE
Ability to have a code element

### ISSUE THREAD

**Issue by rjcarneiro** [PiranhaCMS/piranha.core#1872]
Hi all, 

I would love to use PiranhaCMS as my (future) blog but recently I hit a wall while adding content as code: it doesn't look good, it doesn't show nor the language, nor the numbers and not even a different styling to easy readability. 

The same way you guys have it on the docs, why don't have a component "code" to do that?

![image](https://user-images.githubusercontent.com/1188674/168489817-7a345df4-6db9-45b2-a0f2-2e2bb003cafd.png)

**Comment by tidyui** [comment]
Since Piranha is a decoupled CMS we can't provide any front end components. The docs pages on our main site are just markdown converted to html and the styling in your screenshot is a result of a javascript-component (https://prismjs.com) together with some additional css styling.

**Comment by rjcarneiro** [comment]
Thanks @tidyui for clarifying. Let's say I wanna add a new block type called "Code", like on the screenshot. What it does, is adding you a new block where you can add code and specify the programming language from a select list. It will save this as any other existing block type.

![image](https://user-images.githubusercontent.com/1188674/168647920-97aaf249-ea0b-47c0-bd92-2a819e103945.png)

On the frontend, it will render a div with a certain class `block-of-code` and I'll add your recommendation (prismjs) to transform all classes `block-of-code` with that styline.

My first question is, is there a easy way to do this? Can you please guide and/or point me in the right direction?

**Comment by tidyui** [comment]
Please take a look at this old issue. https://github.com/PiranhaCMS/piranha.core/issues/1412

**Comment by rjcarneiro** [comment]
Thanks @tidyui for pointing in the right direction.

**Comment by tidyui** [comment]
This is totally expected as the rendering application/website has no idea what to do with your block unless you tell it 🙂

If you look in the DisplayTemplates folder in your views-folder there’s an .cshtml file there for all of the basic blocks. Simply add a new one with the same name as your block and render it as you want.
