### ISSUE TITLE
Page move sort order. Incorrect behavior

### ISSUE THREAD

**Issue by anvarjonruziev** [PiranhaCMS/piranha.core#1876]
Steps to reproduce:

1. Open manager
2. Click to Pages menu
3. Try to change SortOrder up by drag and drop 
![image](https://user-images.githubusercontent.com/37145986/169094211-98e96561-2655-4eea-a65f-cac37a433743.png)

Current behavior:
Related pages SortOrder  not changes, In order changes to take effect you need to restart web server

Expected behavior
Related pages SortOrder  should be changed.

**Comment by tidyui** [comment]
Closing as issue has fix has been merged.
