### ISSUE TITLE
Piranha.Manager customisation

### ISSUE THREAD

**Issue by ilukjan** [PiranhaCMS/piranha.core#1880]
Hi! have a few questions according to Piranha.Manager customisation

1.  How can i set the Manager Icon ?
I tried to use it with **App.Modules.Manager().IconUrl** but it's readonly, so pretty much sure it should be passed in a properties or smth like that..
logo here i mean:
![изображение](https://user-images.githubusercontent.com/91224191/170685754-afc78cc0-5e76-4abd-b927-6772af79ce28.png) ![изображение](https://user-images.githubusercontent.com/91224191/170685821-d2d4a639-945d-4bc3-87c3-72df8f3bdd24.png)

2. How can i set the Manager localisation ?
Saw the related post here (https://github.com/PiranhaCMS/piranha.core/issues/1129), 
got the Manager.Localisation 10.1 nuget, but can't find where to set the value for language

var cultureInfo = new System.Globalization.CultureInfo("pt-br");
System.Globalization.CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
System.Globalization.CultureInfo.

but the manager still has English

Thank you a lot in advance!

**Comment by tidyui** [comment]
You need to inject your own custom css-file into the manager and override the icon with your custom styles.

Regarding translations, first check our Crowdin project where you can find the different translations available that has been contributed by users. Secondly there are many different ways to set the thread culture which are documented in Microsoft’s docs

**Comment by ilukjan** [comment]
Thank you @tidyui for reply!
so i'm trying to inject the own .css file like following:

```
App.Init(api);            
App.Modules.Manager()
                .Styles.Add("~/assets/css/MyStyles.css");
```
but result is that .css file itself is not loaded and content is empty:

![изображение](https://user-images.githubusercontent.com/91224191/171384797-7c6f2cdf-30eb-4c7f-b677-093f88fe0c4e.png)

in <head> it's initialized also
![изображение](https://user-images.githubusercontent.com/91224191/171385122-28ec70ec-e960-4d7e-bbea-1b2bdaf9c48d.png)

in solution structure looks like this, so path should be fine:
![изображение](https://user-images.githubusercontent.com/91224191/171385436-ad5a9678-726f-4ecc-a17f-5a28741811c4.png)

i'm using Piranha.Manager Nuget pack, so maybe should i set smth specific or put the file in different location or smth else ?
Thank you a lot!

**Comment by tidyui** [comment]
Assets needs to be positioned within the wwwroot folder which is not visible from your screenshot

**Comment by ilukjan** [comment]
@tidyui , Thank you a lot! it worked :)
for any other, who have such issue:
1. Pls put the .css in "wwwroot/assets/xxxx.css"
![изображение](https://user-images.githubusercontent.com/91224191/173005426-4b75f63c-c536-43f7-bd08-419440511baa.png)
2. Add custom .css to the Piranha.App
![изображение](https://user-images.githubusercontent.com/91224191/173005642-3ad06729-1203-4ebc-95c2-598d73e89885.png)
