### ISSUE TITLE
Infinite call to Block.Init(...) from Manager

### ISSUE THREAD

**Issue by axunonb** [PiranhaCMS/piranha.core#1881]
```CSharp
public class SampleBlock : Piranha.Extend.Block
{
    public async Task Init(IApi api)
    {
        // This call leads to an immediate infinite loop when trying to edit a page in Manager 
        // that contains SampleBlock
        var sa = await api.Pages.GetAllAsync<StandardArchive>()

        // more code
    }
}
```
Evidence: This resolves the issue
```CSharp
public class SampleBlock : Piranha.Extend.Block
{
    private bool _initRunning = false;

    public async Task Init(IApi api)
    {
        // Breaks the infinite loop
        if (_initRunning) return;
        
        _initRunning = true;
        var sa = await api.Pages.GetAllAsync<StandardArchive>()

        // more code
    }
}
```
Finally I used `api.Pages.GetByIdAsync<StandardArchive>(blogId)`.
Is the call `api.Pages.GetAllAsync<StandardArchive>()` just not allowed here?

**Comment by tidyui** [comment]
When loading a page, even if the page is in cache, init() will be called for all blocks, therefore it is only natural that If you load the parent page from a block it will result in an endless loop.

If you need to check the parent page my strong suggestion is that you load it as a PageInfo model, this will exclude all regions and blocks from the model preventing issues like this.

**Comment by axunonb** [comment]
Great, thanks for the hint which `PageInfo`, which is much better here
