### ISSUE TITLE
Media file size limit ?

### ISSUE THREAD

**Issue by ilukjan** [PiranhaCMS/piranha.core#1882]
Good day!
Guys, have an issue with loading media > 25 Mb size
![изображение](https://user-images.githubusercontent.com/91224191/171435606-97680089-4ea3-4196-bdd2-f4c05f9a8e5c.png)

Thought it was a problem of Timeout, 
and i set it as:
`config.ManagerXhrTimeout = 120; // 2 minutes`

but seems not... Can you pls tip me smth ?

Thank you a lot in advance!

**Comment by tidyui** [comment]
Hi there! The maximum upload size is controled by ASP.NET **and** the hosting environment and is nothing we can control. https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-6.0

Best regards

**Comment by ilukjan** [comment]
Thank you @tidyui !
