### ISSUE TITLE
How can I modify an existing editor plugin or install a new one?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [PiranhaCMS/piranha.core#1885]
I want to give the user the ability to create different types of links by applying a class or inserting an image into a link when created in the editor (TinyMCE).

I see from the template project `editorconfig.json` that the `add link` button on the editor toolbar is a Piranha provided plugin. But I don't see how I can modify this as it is checked into the codebase in [minified form](https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.TinyMCE/assets/tinymce/plugins/link/plugin.min.js)

So then I considered creating my own TinyMCE plugin, but I don't see any way to install it.

1. I don't see any way to copy a plugin to the TinyMCE editor plugin location since those routes seem to be handled by Piranha's own middleware.
2. Registering an external plugin using `external_plugins` in `editorconfig.json` doesn't work.
3. And I don't see anything in the documentation that would enable me to install a `setup` hook.

Can someone point me in the right direction please?

**Comment by tidyui** [comment]
Applying classes and images can easily be done with the built in tolls without adding plugins. Files on disk should loaded in favor of embedded once, simply place the files locally in the same position in wwwroot as they are requested by the browser.

You can also override the TinyMCE package, place your own version in the wwwroot of your project, and after calling UseTinyMCE, override the paths specifying where it should be loaded from.

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.TinyMCE/TinyMCEExtensions.cs#L43
