### ISSUE TITLE
How to deal with hierarchical dynamic content

### ISSUE THREAD

**Issue by bartdevriendt** [PiranhaCMS/piranha.core#1894]
I would like to achieve the following: 

- A page containing a list of product categories
- When you click on one of the categories a new page opens with a list of products in that category
- When you click on a product you go to the details page of that product

I already managed to add custom models and edit forms to the manager part to create the categories and products.  I'm a bit stuck on what would be the best approach to handle this in the frontend.

I thought I could create a custom block to show the categories, which works.  Then I added a controller with a route for the detail page, but when I navigate I loose the layout of the site.

Any ideas on how to approach this ?

**Comment by tidyui** [comment]
For the routing part, if you navigate directly to your controller route navigation will be lost as you're not accessing a page in the sitemap. However you can prepend the action name to the permalink of the page instance you're navigating/posting to and that action will be execute when the request is rewritten. Please refer to:

https://piranhacms.org/docs/master/application/routing
https://piranhacms.org/docs/master/application/advanced-routing

Regards
