### ISSUE TITLE
Deploy with dockerfile

### ISSUE THREAD

**Issue by Spec86** [PiranhaCMS/piranha.core#1895]
Hello! Do you have dockerfile for deploy Piranha CMS on Linux, with MySQL, Nginx, HTTPS ? Step by step procedure of deploy on production?

**Comment by tidyui** [comment]
Sorry, we do not provide. If you ask around in our chat on Gitter https://gitter.im/PiranhaCMS/Piranha I'm guessing someone there could help you out with this.
