### ISSUE TITLE
About coding in core codes.

### ISSUE THREAD

**Issue by mzuvin** [PiranhaCMS/piranha.core#1903]
Hello, I want to add something to both frontend and backend code on Prinha.Manager. I want to see what I want to add, but it takes a long time when I try to reopen the project and recompile javascript files with gulp. How can I do it faster? Platform: Linux Rider.

**Comment by mzuvin** [comment]
Coding in ready-made components is extremely simple and easy. but it takes a lot of time when I want to add something myself. It takes a lot of time to see and fix bugs while developing.

**Comment by tidyui** [comment]
We don't have any dev tools doing this at the moment. This could be something to look into if we at some point look at upgrading the manager UI to `Vue.js` 3
