### ISSUE TITLE
Unpublished pages throws 500 error

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#1916]
### Discussed in https://github.com/PiranhaCMS/piranha.core/discussions/1915

<div type='discussions-op-text'>

<sup>Originally posted by **vindhya124** August  2, 2022</sup>
Is there a way we can throw 404 (Not found) instead of 500 error when application is trying to access an unpublished page? 

Thanks in advance</div>

**Comment by vindhya124** [comment]
Awesome. Thank you
