### ISSUE TITLE
Feature: Simplify adding arbitrary properties and data to a page 

### ISSUE THREAD

**Issue by brianbv** [PiranhaCMS/piranha.core#1920]
Presently, I am using the sitemap to render the top navigation on my site.  This was quick and easy to set up, but now I would like to keep the sitemap and show some of the items in the footer and some of the items in the top navigation.  

One option is to build out my own code for rendering the menus the other way I describe, but it would be nice if I could just use SiteMap.  One way would be adding a text/json field to the Piranha_Pages table.  With this approach,  the developer of the site would have a good deal of flexibility on what could be stored there.  The default editor could be a key/value list.  The editor could easily be swapped out for something more customized, if needed.  There are probably be future applications besides menus for this data as well.

**Comment by tidyui** [comment]
Hi there! There are several ways you could do this with the current application:

## 1. Hidden page in the sitemap

One option is to add a Page in the bottom of your site, let's call it "Footer"  and set that page to `Hidden` in the page settings. If you look at the hidden option while rendering your standard menu you can exlude the structure there. Next you could add copies of the pages you want to include in your footer below this page and use this part of the structure when rendering the footer.

## 2. Adding a site region

Another option would be to add a content type to your site with a region of the type `IList<PageField>`. Given that the footer is a flat list links the user could then select in the "Edit site" dialog the pages that should be included in the footer and sort them in the desired order.

## 3. Separate sitemap

A third option would be to just create a second site that isn't the default site and has no hostname binding, this means the site won't be accessible by any routing. Then you could just add copies of the desired pages into this sitemap like in the first solution and render this sitemap in the footer.

Best regards
