### ISSUE TITLE
How to disable SQL query spam to log?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [PiranhaCMS/piranha.core#1921]
How do I disable all the SQL query spam that gets written to the logs please?

**Comment by tidyui** [comment]
All of those logs are from Entity Framework. You can easily configure different log levels for different namespaces in your app settings.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging

**Comment by Neutrino-Sunset** [comment]
Yeah sorry. I'm an idiot.

    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.AspNetCore": "Warning",
        "Microsoft.EntityFrameworkCore.Database": "Warning"
      }
    },
