### ISSUE TITLE
Users & Roles menu not shown when integrating login with openid

### ISSUE THREAD

**Issue by kttary** [PiranhaCMS/piranha.core#1930]
I'm trying to integrating keycloak with piranha cms. It works but at manager menu i dont see users and roles from System menu.  I guess i miss claims or required role. Anyone can share?
![image](https://user-images.githubusercontent.com/39557649/189248378-e6a736e0-d674-4d8e-ab28-10bc5a5221b1.png)

**Comment by adonisadipos** [comment]
Would you please so kind and tell what the solution was.
I struggle with an similar Problem
