### ISSUE TITLE
Upgrade ImageSharp to support wepb

### ISSUE THREAD

**Issue by NilssonMalin** [PiranhaCMS/piranha.core#1935]
ImageSharp support webp since v2. 
"What's new since V1 #
Some major features!
WebP support - People have been after this for a while! We provide comprehensive support for decoding and encoding WebP images."

Piranha is on ImageSharp 1.0.4 at the moment.

**Comment by tidyui** [comment]
@NilssonMalin Absolutely, just send a PR with the changes! However as it is a major version upgrade of a dependency it will probably not be released until the next major is released.

We’re dragging a bit behind, so we will most likely cut things out of the next release, but if you need the support quickly you can build your own ImageSharp package from source code and use. I recommend creating a local alpha version so you don’t run into issues when the official version is released.

Regards

**Comment by NilssonMalin** [comment]
@tidyui Added PR #1936

**Comment by NilssonMalin** [comment]
@tidyui do you have a timeplan or at least a guess on when we can count on having the next major released?

**Comment by tidyui** [comment]
@NilssonMalin Moved this fix into `10.2` which will be released today.
