### ISSUE TITLE
Regions in my SiteContent don't show up in the settings editors

### ISSUE THREAD

**Issue by hadrian625** [PiranhaCMS/piranha.core#1959]
I have a SiteContent customized with a couple of regions.
For the main site I already have created they are showing up in editor
![image](https://user-images.githubusercontent.com/37671580/201873530-aa4f3cb8-64ce-4c8c-b269-67c6ad1ba86c.png)

But if I try to add a new site, those regions are not showing up at all in editor.
![image](https://user-images.githubusercontent.com/37671580/201874191-be706664-e99f-42de-bf09-adfa2be30450.png)

If I first access the default site that is showing those regions, then add a new site the regions are showing up, but they are filled in with the data from the default site. After saving the site and going back to edit it, those regions are gone again and I see a 404 error for endpoint on "/manager/api/site/content/<SITE_GUID_HERE>". Also in console there is logged the text "No HTML editor registered." and "Setting regions to empty array"

I hope I added enough information.
We are in the process of using multiple sites with our CMS to hold separate content for different tenants.

**Comment by hadrian625** [comment]
On further investigation I found by looking in database that all sites I create with 'Add Site' button have their 'SiteTypeId' set to null and not to my custom sitetype. 
Most probably this is the cause of this issue. So the question is now why the  'SiteTypeId' is set to null for newly created sites and not having the same site type id as the default site I already have

**Comment by tidyui** [comment]
Hi there! All newly created sites default to not having a content type selected. The reason for this is that you could very well have different content types for different sites. After creating a new site you need to:

1. Edit the site
2. Select the desired site type
3. Save the site
4. Close and re-open the site in edit mode

Regards

**Comment by hadrian625** [comment]
Hi,
Thanks for the quick reply.
But I can't see a way to change the site type at edit time. I can only see this:
![image](https://user-images.githubusercontent.com/37671580/201902787-d35c352e-52fa-4b32-912a-23fd447d98b6.png)

What am I missing?

**Comment by hadrian625** [comment]
Found how I can change the type of the site. It was the field 'Content type' in UI. Closing the issue as it is no longer valid
