### ISSUE TITLE
Accessing IDb instance from model class

### ISSUE THREAD

**Issue by albjerto** [PiranhaCMS/piranha.core#1987]
Piranha version: 10.0.2
.NET 6

I have a Model class for a page in Piranha:
```csharp
public class MyPage : Page<MyPage>
{

    //...

    [Region]
    public IList<String> Roles { get; set; }
}
```

The `Roles` region should contain all the names of the user roles defined in the manager.
In order to obtain this list, I should make use of the static `RolesListModel.Get()` method, which requires a `Piranha.AspNetCore.Identity.IDb`.

How do I access the IDb instance from the page model? I managed to do the same with a controller leveraging Dependency Injection, but I cannot do it with the model class.

**Comment by skunal012** [comment]
Hi, I need more info.

**Comment by tidyui** [comment]
Hi there! There is no constructor invocation that allows for dependency injection supported in Piranha atm, so you need to load the related data "on the side" like you did with the controller.

Regards
