### ISSUE TITLE
Post.IsPublished is false even when post has been published.

### ISSUE THREAD

**Issue by RobRukavina** [PiranhaCMS/piranha.core#1994]
I have some posts that were not published and left as drafts for several weeks. now when going to publish them, I have a check on my front end that checks against Post.IsPublished. Even though Post.Published has a date, Post.IsPublished = false. I can't find anywhere in Piranha that set's that value. Also, it's worth noting that the posts I published last year have a value of true. Was there a change to Piranha that could be causing this?

<img width="623" alt="image" src="https://user-images.githubusercontent.com/65525430/234423498-439f1e3e-5032-4d1f-997f-03f601ed1a50.png">

**Comment by tidyui** [comment]
Hi there! As you can see in the code here (https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha/Models/RoutedContentBase.cs#L145) `IsPublished` is not a value, but rather just calculated from the `DateTime` value available in `Post.Published`. Could there be a misalignment between timezones in different environments causing the published date to be interpreted as being "in the future" when your code is running?

Best regards

**Comment by tidyui** [comment]
@RobRukavina Do you have any update on this?

**Comment by RobRukavina** [comment]
Sorry for the delayed response @tidyui . I can see how it might be a timezone difference possibly, but I think the issue would have surfaced before now if that was the case. Prior to this we have had posts that were made as drafts and then published at a later date and did not have this issue. I refactored our code to run off the Published date instead of that post.IsPublished bool. It would be nice to figure out why that bool is not getting set on them now when it was in the past though.

**Comment by tidyui** [comment]
Like I mentioned earlier, `IsPublished` can't be set, it's a calculated read-only property. So the only reason it could return the "wrong" value is if the system time doesn't match the databas time.

~~~csharp
public bool IsPublished => Published.HasValue && Published.Value <= DateTime.Now;
~~~
