### ISSUE TITLE
Search only works for root level pages in Page dialog

### ISSUE THREAD

**Issue by zoinkydoink** [PiranhaCMS/piranha.core#2000]
I have about 40-60 pages created, they link to each other so when I go to make some text a link to another page, when the selection for page lists comes, and  if i type anything in the search, nothing ever comes up, no matter what i type, blank results are the list. (this is for sub pages), if i type 'b' then blog comes up as the first level, but nothing after first level ever shows up

I also opened this issue on SO but havent gotten a response https://stackoverflow.com/questions/76197066/piranha-cms-anchor-link-and-sitemap-question

**Comment by tidyui** [comment]
Confirmed. Will fix this for the next upcoming minor release

**Comment by zacpwhite** [comment]
@tidyui I will gladly work on resolving this issue. 

- What is the expected output of the page search when nested pages exist? 
- Should the search return the filtered results as a flat list or should it continue to display the parent / child hierarchy? 

i.e. When the hierarchy About > Contact exists, when searching with the term 'con', should the result be returned as

* About
    * Contact

OR

* Contact

**Comment by tidyui** [comment]
@zacpwhite Sorry, I didn't have time to respond earlier. I'll take a look at the PR and we can take it from there!

Regards

**Comment by zacpwhite** [comment]
@tidyui no worries! Thanks!
