### ISSUE TITLE
Change to a more efficient mapper?

### ISSUE THREAD

**Issue by steveski** [PiranhaCMS/piranha.core#2012]
Just wondering if you could replace Automapper with Mapperly due to its vastly better performance using source generators?

**Comment by tidyui** [comment]
Mapping is only performed when models are transformed from the database entities, in other words when the requested model is not present in the cache. In this scenario, the model transformation using auto mapper will be the least thing affecting performance as the actual database queries will take more time, so I'm not sure I see how changing the mapper would have any effect in a production scenario.

Best regards
