### ISSUE TITLE
HtmlField TinyMCE editor not working in custom region

### ISSUE THREAD

**Issue by adrian-crisan625** [PiranhaCMS/piranha.core#2045]
We have a custom region defined for the custom Site we have. That region has 3 fields of type HtmlField. We are seeing very often that the TinyMCE editor is not loading, thus the fields are unusable.

![image](https://github.com/PiranhaCMS/piranha.core/assets/65900944/56f61c46-9866-403d-aec7-ecc5a74728d6)

We are seeing in console info texts "No HTML editor registered."

I looked in the source code for the HtmlField and it uses the html-field.vue component. There, in the mount, it calls piranha.editor.addInline(this.uid, this.toolbar, this.onChange);
But if I got to the piranha.editor.addInline function the only line of code I see is "console.log("No HTML editor registered.")"

Are we missing something here or there is a bug with the HtmlField component?

I have to mention that the TinyMCE editor work just fine in content blocks.

![image](https://github.com/PiranhaCMS/piranha.core/assets/65900944/3592f7e6-6b06-47f8-8a7a-f15a411c6152)

**Comment by tidyui** [comment]
When using the package `Piranha.Manager.TinyMCE` and calling `options.UseTinyMCE()` in your application startup, the method `piranha.editor.addInline` is overridden by the TinyMCE package:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.TinyMCE/assets/piranha.editor.js#L8

If what you mention happens, the only logical reason would be that the scripts are executed in the wrong order. When you see the error, could you verify in the console how `piranha.editor.addInline` is actually defined, so we can find out if either the default implementation overwrites the tinymce one, *or* if the site edit modal executes before the tinymce has registered it's method.

**Comment by adrian-crisan625** [comment]
I will try to look on the. Unfortunately, this happens quite random and after things dtart working fine, then I can no longer reproduce the issue.
I looked on the order of the scripts and it makes total sense what you are saying.
The  piranha.editor.addInline function with "console.log("No HTML editor registered.")" is in the "/manager/assets/js/piranha.min.js" script.
The  piranha.editor.addInline function with tinymce init is in "/manager/tiny/piranha.editor.js".
The html-field.vue component is in "/manager/assets/js/piranha.components.min.js"
The order of the 3 scripts is as shown above, so it would be quite weird indeed that the piranha.editor.addInline call from html-field.vue component still uses the addInline from "/manager/assets/js/piranha.min.js" script.
I will keep an eye out for this, next time I can reproduce this issue.


![image](https://github.com/PiranhaCMS/piranha.core/assets/65900944/2ac31be2-645c-4bd5-b916-f3a6b086fe05)

**Comment by adrian-crisan625** [comment]
I was able to catch the issue again and I can say it is not the fault of Piranha. 
In our project, the previous team has added a custom page list, which override the default page list of Piranha, but looked exactly the same. There the scripts included were not correct, as the piranha.min.js was loaded twice, once before "/manager/tiny/piranha.editor.js" and once after that. This way the error is normal to occur. The fact that they replaced the default page list with a custom one with a different url, caused the confusion in replicating the issue, since you would start on the custom page list, but if you go to edit a page, you would be returned on the default page list of Piranha, which was correctly loading the scripts.

So a lesson learned: also look at the url being loaded and cut down on custom pages. Is better to customize things by our own scripts and don't interfere on how Piranha's scripts are loaded.

Sorry for the misleading issue.
I will close the bug.
