### ISSUE TITLE
Can't upload images after v11 upgrade

### ISSUE THREAD

**Issue by patrick-alpcot** [PiranhaCMS/piranha.core#2068]
We recently upgraded to .net8 and upgraded Piranha to v11. After the upgrade we were no longer able to upload images in the CMS.

![image](https://github.com/PiranhaCMS/piranha.core/assets/164901587/fd90ef82-4d04-46d3-ab9e-146a53efb431)

We have now rolled back the upgrade, and image upload works again.

**Comment by tidyui** [comment]
I can't reproduce the error when creating a new site using the `v11` version of the templates. Are you sure you updated the package `Piranha.ImageSharp` as well to `11` since the external ImageSharp library was updated for this version?

**Comment by patrick-alpcot** [comment]
Hey! Thanks for the quick reply, I was told that we did, but I'll check with my team and get back to you.

**Comment by patrick-alpcot** [comment]
We did update the ImageSharp package, and we updated our `SixLabors.ImageSharp` dependency to 3.1.4... Which is the highest version of 'SixLabors.ImageSharp' we can use?

**Comment by tidyui** [comment]
Piranha.ImageSharp is compiled using 2.1.3

https://www.nuget.org/packages/Piranha.ImageSharp#dependencies-body-tab

Upgrading the external dependency to 3.x will most likely break.

**Comment by tidyui** [comment]
Please also remember that if you consume `SixLabors.ImageSharp 3.x` as a direct dependency in your application you might  need to purchase a commercial license. This is also why we choose not to update our ImageSharp package to `3.x`, to avoid confusion for consumers of the Piranha packages.

**Comment by patrick-alpcot** [comment]
Thanks for the info! Good to know about the license too!
