### ISSUE TITLE
UseIdentityWithSeed does not add the user sysadmin.

### ISSUE THREAD

**Issue by HusseinKhodadadi** [PiranhaCMS/piranha.core#2079]
Create a piranha mvc project with a SQL Server database using Visual Studio Piranha template. Change the login page path from the default path to a custom path. On the first login, the user sysadmin is not created, and the users table is empty.

Program.cs :
![image](https://github.com/PiranhaCMS/piranha.core/assets/80600729/1c424cf7-dae6-473f-a1a0-e4b82045ec1d)
![image](https://github.com/PiranhaCMS/piranha.core/assets/80600729/a784d7b2-7b9b-4847-ae88-f3276d1d100c)
LoginController :
![image](https://github.com/PiranhaCMS/piranha.core/assets/80600729/a4725b08-53af-4034-8836-c14dcf877e8b)

**Comment by tidyui** [comment]
Hi there! Yes the plan is to replace this with an extension method that prompts the user with a view the first time it’s started where you setup your own username/password. The existing method is basically there to get the templates up and running without having to do any code modifications.
