### ISSUE TITLE
Global tags

### ISSUE THREAD

**Issue by vladver** [PiranhaCMS/piranha.core#2091]
Hi!
Is there any easy way to make tags global, and not just linked to the posts of the archive page?
I understand that I can create my own tables and organize all the logic of the work, but maybe there is an easier way?

**Comment by tidyui** [comment]
There currently no support for global tags/categories as they are scoped per archive. If you want a shared set of categories/tags, one way would be to keep all posts in the same archive, hide that page in the site, and instead create another page type where you configure the filter you want to use when retrieving posts. That way you could have 3 different pages on your site all fetching data from the same archive, using the same categories and tags.
