### ISSUE TITLE
Add Async Method Support to ICache Interface

### ISSUE THREAD

**Issue by petriceko** [PiranhaCMS/piranha.core#2095]
While implementing a custom ICache interface for use with Piranha, I noticed that the current ICache interface lacks support for asynchronous methods. Adding async support would be highly beneficial, especially for scenarios involving remote caches or databases, where non-blocking operations are crucial for maintaining performance and scalability.

**Proposal:**

I propose adding the following async methods to the ICache interface:

    Task<T?> GetAsync<T>(string key, CancellationToken cancellationToken = default);
    Task SetAsync<T>(string key, T value, CancellationToken cancellationToken = default);
    Task RemoveAsync(string key, CancellationToken cancellationToken = default);

These methods would complement the existing synchronous methods, providing a non-blocking alternative for consumers.

**Comment by tidyui** [comment]
As this is a breaking change this will be scheduled for the next major release.

**Comment by Vilemcok** [comment]
Hello, I also need this change. @tidyui are you able to specify when is going to be next release?

**Comment by vikrantingole** [comment]
Hello, I also expect this proposal ASAP. Please help.

**Comment by tidyui** [comment]
It all depends on implementation. I have an idea how it could be implemented in a non breaking manner which would mean it could be released sooner.

**Comment by gasperini** [comment]
It would be really helpful to have this improvement as soon as possible.

**Comment by peterlacko** [comment]
Hello, I also need this to be implemented due to performance issues in our app, thanks.

**Comment by Vito2502** [comment]
Hi @tidyui keep me updated if you can on this fix because it is important for my project.
I would like to understand when the release containing this fix could be released.
