### ISSUE TITLE
Dependencies versioning

### ISSUE THREAD

**Issue by psijkof** [PiranhaCMS/piranha.core#220]
When I follow the instructions from the README file, I get the following

source\repos\piranha.core\piranha.core\core\Piranha.Manager\piranha.core> **dotnet restore**
The specified SDK version [2.0.0] from global.json source\repos\piranha.core\piranha.core\core\Piranha.Manager\piranha.core\global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

**Comment by tidyui** [comment]
Well the error message clearly states you don't have the SDK for `NetStandard 2.0` which is the target framework. You can download it from the link you referenced above. Worth noting is that the instructions in the `README` are the **cross-platform** CLI way to do it. If you're using Windows and have the latest (or fairly new) version of **VS2017** you can just open up the solution in Visual Studio and it will do everything for you :)

**Comment by psijkof** [comment]
I installed a fresh machine. https://www.microsoft.com/net/learn/get-started/windows (SDK 2.1.100)
Opens fine in VS Code or VS 2017 CE, but can´t do CLI development (i.e. dotnet restore does not run).
Perhaps there is a way to fix this?

**Comment by tidyui** [comment]
Well the latest released version is for `2.0`, so unless you've installed `2.1-preview` you should have the correct version. I primarily work in VS Code on Mac OS X where I don't have any issues, but I also work in VS2017 on Windows to ensure that it works on both operating systems. I tried to perform the .NET CLI commands on my Windows machine without any problems so it's obviously something with your installation.

However, I have no idea how to get to the bottom with this to help you. The best thing is probably to ask the ASP.NET team for some support, as you have the repo forked here on GitHub it's easy to see how it's set up in `global.json`.

Regards

**Comment by tidyui** [comment]
As a final test, if you type the following in your command prompt:

    > dotnet --version

What version does it say you have? And have you installed both the **sdk**, because I know there is a download available for just the **runtime**.

**Comment by tidyui** [comment]
Also, you wrote earlier that you installed SDK `2.1.100`, but when I go to their website the current version seems to be `2.1.4` for the SDK (see attached image):

![skarmavbild 2018-03-13 kl 15 24 12](https://user-images.githubusercontent.com/781266/37347724-c8ab5ee0-26d2-11e8-99e9-61a7f7b3745e.png)

Where did you get the version number `2.1.100` from?

**Comment by psijkof** [comment]
According to what I picked up in a recent .NET community standup, the runtime version and the SDK version are not equal (in the same release). As a reference: [Making sense of the different versions of .NET Core (runtime and SDK)](https://jonhilton.net/2017/04/17/making-sense-of-the-different-versions-of-net-core-runtime-and-sdk/)

Also note (as mentioned in the article), global.json is replaced by yoursolution.sln. dontnet migrate is supposed to convert the json into a sln file.

I have the project running in VS2017, but it would be great to be able to also support CLI with the same repo.

HTH

**Comment by psijkof** [comment]
I have the latest versions, of both!

[All Downloads](https://www.microsoft.com/net/download/all)

**Comment by tidyui** [comment]
Well that is probably the issue! The project is built for the stable 2.0, so when you compile it can’t find the specified version. Visual Studio however ships with the stable version, that’s why it works there.

My suggestion is that you install the current stable release as well. You can still have the latest version activated as default as long as you have the correct version installed as well.

Regards

**Comment by psijkof** [comment]
I'm pretty sure my runtime is stable. And as I downloaded from the official link, if the SDK is already 2.1.100, the project should still run fine.
global.json is no longer supported/preferred, and dotnet migrate should help that issue. 
It is what stopped me, and anyone who wants to run from CLI.
[announced of move to [.csproj / MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/)

**Comment by tidyui** [comment]
I've reproduced your issue by uninstalling all sdk's but the latest preview on my old Mac. Running `dotnet restore` produces the same error as you get. I have also verified that `global.json` is not really needed anymore and removed it from the repository. If you **sync your fork** you should be good to go without the old SDK installed.

**Comment by psijkof** [comment]
Thank you. First thing tomorrow morning!
