### ISSUE TITLE
Several Razor errors

### ISSUE THREAD

**Issue by Eonasdan** [PiranhaCMS/piranha.core#221]
You have razor errors in Archive.cshtml and Start.cshtml

In both files the if under PrimaryImage needs to have curly braces. Razor doesn't support single line ifs

In Archive you have two dangling parentheses in the links.

e.g. `<h2><a href="@post.Permalink")">@post.Title</a></h2>` should be `<h2><a href="@post.Permalink">@post.Title</a></h2>`

**Comment by tidyui** [comment]
Thanks for noticing! Did you receive an error when running the template, because it worked on both Mac & Windows for me, that's why I didn't notice.

**Comment by Eonasdan** [comment]
Resharper pointed them out. Usually you won't get View errors unless you're building in release mode
