### ISSUE TITLE
Add source code dialog to TinyMCE

### ISSUE THREAD

**Issue by wiruzman** [PiranhaCMS/piranha.core#227]
Right now the configuration is like:

```javascript
...
toolbar: "bold italic underline | bullist numlist hr | alignleft aligncenter alignright | formatselect removeformat | piranhalink piranhaimage"
...
```

Could you add 'code' to that line so that it is easier to see what will be rendered when we publish? Sometimes we need to add some more html code to support the content.

If not, is there any chance to override your init clause?

**Comment by wiruzman** [comment]
I just added my own _Editor.cshtml and override it. But it is not really a solution. Is there any possibility to add a sort of a configuration for TinyMCE?

**Comment by tidyui** [comment]
We could do this, but since the only thing present in the .cshtml file you override was the TinyMCE config, what’s the difference? I’d love suggestions on what should be configurable and how!

**Comment by wiruzman** [comment]
I had some troubles to override the view with the path, but in the end i got it.
Actually you are right, it is the only thing that needs to be done, maybe a guideline in the wiki could ease it.

Or it should be overridden in my own javascript files, so it nullifies the one in your view.

**Comment by tidyui** [comment]
I'm closing this issue and adding a new one for included a source code edit for the Editor. However I'm not overly fond of the built-in source code dialog in `TinyMCE`. It would be more fun to provide a text editor with syntax highlighting for HTML ;)

**Comment by tidyui** [comment]
Hi there! This has changed since this issue was closed, and we're currently working on rewriting the documentation completely to make it complete and easy to follow. The view should be:

    ~/Areas/Manager/Views/Shared/Partial/_EditorSetup.cshtml

You can find the original view here for reference: https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Areas/Manager/Views/Shared/Partial/_EditorSetup.cshtml

Best regards

**Comment by layinka** [comment]
Thanks that works perfectly
