### ISSUE TITLE
Use manager only?

### ISSUE THREAD

**Issue by wiruzman** [PiranhaCMS/piranha.core#228]
Is it possible to use manager only for content management and use any framework as frontend, such as react js? When I create a startpage or a page in the root, then the root of web answer on that page instead of HomeController.

It can be I have missed something, but could you explain what possiblities I have?

**Comment by tidyui** [comment]
Yes! If you look at the wiki page about [middleware](https://github.com/PiranhaCMS/piranha.core/wiki/Middleware) you can see the default pipeline that is registered by the call `app.UsePiranha()`. Just remove this call and add the specific middleware you want for you project!

Regards
