### ISSUE TITLE
Add WebApi module for accessing the IApi.

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#229]
Add a module with a completely headless `Api` for building javascript applications consuming the data.

**Comment by tidyui** [comment]
This should be created as a separate project `Piranha.WebApi` in the `core` folder. It should preferable be kept in this repository so that releases can be synced with the main core packages to ensure that the Api covers all repository functionality.

**Comment by gyretech** [comment]
Still want this?
