### ISSUE TITLE
Add checkbox field

### ISSUE THREAD

**Issue by wiruzman** [PiranhaCMS/piranha.core#230]
Is there any plan to add checkout field? It should not be that hard i think?

And again, can I make it my self in a easy way?

**Comment by tidyui** [comment]
Like you say it will be very easy, it just haven’t been added yet! And yes you can totally add it in your own project with just as little effort. I’ll try to get the wiki for “Custom fields” written!

**Comment by tidyui** [comment]
Here! Take a look at the new Wiki page and let me know if it's unclear in any way!

https://github.com/PiranhaCMS/piranha.core/wiki/Custom-Fields

I can still add a default field implementation for `Checkboxes` in the next release though.

**Comment by wiruzman** [comment]
Thank you for the update on the docs, I really appreciate.

I have used it and it works like a charm and easy to setup.

**Comment by tidyui** [comment]
Awesome! Feel free to contribute a CheckBox fields to the core manager for the 4.4 version!

Regards

**Comment by tidyui** [comment]
I can add the `CheckBoxField` for the `4.4` release as it will only take me a couple of minutes :)

**Comment by wiruzman** [comment]
I just added it, hope I didnt forget something.
