### ISSUE TITLE
Api.Sites.GetSitemap() - Always gets default sitemap

### ISSUE THREAD

**Issue by AndreSteenbergen** [PiranhaCMS/piranha.core#233]
Would be more intuitive to retrieve sitemap for the current Site.

**Comment by tidyui** [comment]
As the api is decoupled from webapplication it doesn’t know what the active site is, however we could create a AspNetCore helper that wraps the api call. This helper could be aware of the current site.

**Comment by AndreSteenbergen** [comment]
Would be great.

**Comment by tidyui** [comment]
I'm closing this issue as this functionality is now provided through the `Application Service`.

https://github.com/PiranhaCMS/piranha.core/wiki/Application-Service
