### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by Eonasdan** [PiranhaCMS/piranha.core#235]
There needs to be pre-post, client side validation on all the manager pages. Check for Title and other required fields and verify the slug is available rather then just throwing an error.

Creating a blog archive page for instance has the Add Post button enabled without a Title and the page has to be saved before you can add posts.

**Comment by tidyui** [comment]
Yes! This has been on my list for a while! This shouldn’t be to complicated to add!

Regards

**Comment by tidyui** [comment]
Like a wrote this is a very interesting issue that needs to be a part of the `4.4` release. So far I've only tried to focus on the backend validation, which isn't 100% accurate either from time to time. Do you have experience in using the client side validation libraries with Asp.NET Core @Eonasdan, and if so would you be willing to contribute on this issue?

**Comment by tidyui** [comment]
The only thing important here is that `no attributes` that adds a dependency to any `AspNetCore` package can be added to the core parts of **Piranha**. The core libraries should not have any dependencies on the web libraries.

**Comment by Eonasdan** [comment]
There are no dependencies on [System.ComponentModel.Annotations](https://www.nuget.org/packages/System.ComponentModel.Annotations/4.5.0-preview1-26216-02) so you could easily add `[Required]` to your models.

For client side validation I'd recommend `jquery validate unobtrusive` and its dependency `jquery validate`. It makes it very easy to validate.

I noticed that the manager site wasn't a .Net Core site. That might need to be one of the first steps is to migration that project. Secondly, I think I would change all (most) of your http posts to the javascript fetch api instead of a form action. This would allow you to validate, post, server side validate, return success or fail (and error messages)

**Comment by Eonasdan** [comment]
Gotcha, I just didn't see the typical wwwroot and the use of editor templates and no tag helpers just looked like a non-core mvc site.
