### ISSUE TITLE
Gif files are unsupported

### ISSUE THREAD

**Issue by Eonasdan** [PiranhaCMS/piranha.core#237]
I was trying to upload a gif file and when I clicked Done nothing happen. I looked at the console and saw a 500 error, upon inspecting that I see that the 500 `Filetype not supported`.

Two things, 1) why are gif files supported? (this is a breaking feature for me) 2) this ties into #235 where there is no validation or indication that it failed at all

**Comment by tidyui** [comment]
Hi there! This is configurable, but the documentation is a bit lacking. In your `Configure`, after `App.Init()` add the following line:

    App.MediaTypes.Images.Add(".gif", "image/gif");

Regards

**Comment by Eonasdan** [comment]
Ah, yes that did allow me to upload the image. However the image resizer outputs jpg instead of the original format, which also leads to png images lose their transparency. :(

**Comment by tidyui** [comment]
This is a work around since all cross platform image libraries produce HUGE files (except for jpg). This means resized png files are almost always bigger than the original even if half the size

**Comment by tidyui** [comment]
However, if needed I can make it configurable whether to always save versions as .jpg or go with the format of the original file. Hopefully performance of the third-party image libraries will improve over time.
