### ISSUE TITLE
Can you have a root slug?

### ISSUE THREAD

**Issue by wiruzman** [PiranhaCMS/piranha.core#239]
Is it possible to have a root slug? Every page I create on root level have a slug name equals title name.

I want leveling as - 

* root (/)
  * page1 (/page1)
    * subpage1 (/page1/subpage1)
  * page2 (/page2)
    * subpage1 (/page2/subpage1)
    * subpage2 (/page2/subpage2)
* root1 (/root1)

**Comment by tidyui** [comment]
Well slug can’t be empty, and it looks like the slug of **root** is empty

**Comment by wiruzman** [comment]
I can browse the root without slug because it is the startpage, but pages underlying is using the startpage slug in the url.

**Comment by wiruzman** [comment]
You are right, I can manually edit the slug, but thats not what I wanted. I wanted to keep things in a normal tree structure. I think I will play around with it. Thank you for answers.

**Comment by tidyui** [comment]
Closing this in favor of issue #243
