### ISSUE TITLE
How to register own auth provider?

### ISSUE THREAD

**Issue by wiruzman** [PiranhaCMS/piranha.core#240]
I have read Authentication section in wiki.

UPDATE: Where can I define default auth scheme for Piranha? I have multiple auth providers on my solution.

**Comment by tidyui** [comment]
You have to clarify exactly what you want to achieve. The manager **only** calls the current `ISecurity` service to authenticate admin users, after that the standard Policy/Claims security of Asp.Net core is used. Apart from that there's nothing in the framework that relies on security.

If you want an example you can look at @gyretech implementation of Asp.Net Identity for Piranha here:

https://github.com/gyretech/PiranhaCore-Identity-EF-Module
https://github.com/gyretech/PiranhaCore-Identity-EF-Manager-Module

Regards

**Comment by wiruzman** [comment]
I wanted to use external provider, like Facebook, with claim policies to narrow down the access. Right now I have that implemented on my existing solution. I provided the scheme on the controller it self, but for Piranha, I dont have access to the controller to use it. 

In the log of the application, I can see it is authenticating with success with Facebook, but still redirected to Access Denied page.

**Comment by tidyui** [comment]
Do you want to use facebook login for the manager interface? In such case, these are the claims that the Admin interface uses:

https://github.com/PiranhaCMS/piranha.core/wiki/Security

You can see how the Policies are setup here:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Manager/ManagerModuleExtensions.cs#L44

**Comment by wiruzman** [comment]
Yes I have found a solution.
