### ISSUE TITLE
UseSqlServer error on OS X

### ISSUE THREAD

**Issue by TheWolfA2** [PiranhaCMS/piranha.core#25]
Piranha.Manager's `StartUp.cs` uses `options.UseSqlServer()` which causes an error on OS X environments.

Not sure what the best solution for this is.  Perhaps provide an override method or setup separate extension methods for `UseSqlServer` and `UseSqlite`

**Comment by tidyui** [comment]
The startup.cs in the manager is only used when debugging the manager directly from that project, when it's included into another project that projects startup chooses the database.

For example you can look at the Blog example which uses SQLite and the manager.

However, we should still change the debug connection string in the manager!

Regards

**Comment by TheWolfA2** [comment]
Makes sense! Thanks for the clarification!
