### ISSUE TITLE
Custom TinyMCE

### ISSUE THREAD

**Issue by Asadlerpwcom** [PiranhaCMS/piranha.core#256]
Is there an easy way to add / remove buttons from the built in tinymce editor?

**Comment by tidyui** [comment]
Absolutely! Every `.cshtml` in the Admin UI can be overridden by placing your own version of it in your project. Simply copy the following file:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Areas/Manager/Views/Shared/Partial/_Editor.cshtml

And place it in the same position in your application, i.e `~/Areas/Manager/Views/Shared/Partial/`.

Best regards

Håkan

**Comment by Asadlerpwcom** [comment]
Ok perfect

Thanks!
