### ISSUE TITLE
MySQL as Database Provider

### ISSUE THREAD

**Issue by aatmmr** [PiranhaCMS/piranha.core#269]
I wanted to open this issue in order to help any user who is searching for a solution how to use Piranha Core with MySQL as database provider. It can be simply done through adding MySQL capabilities to EF Core.

A short tutorial including a sample project can be found at [this GitHub repository](https://github.com/aatmmr/piranha-core-mysql). Feel free to use and comment it.

Enjoy!

**Comment by aatmmr** [comment]
@tidyui I guess the issue can be closed or do you like to keep it open?

**Comment by tidyui** [comment]
I think we should keep it open so people see it! Or maybe add a new page to the Wiki about it

**Comment by tidyui** [comment]
I'm guessing we'll need to add some database related info. If you take a look at the current master branch there are atm three packages for AspNetCore Identity as Microsoft has implemented it in a way that the Migrations are database dependent. If MySql should be supported for Identity I'm guessing another version will be needed as well.

**Comment by aatmmr** [comment]
Yes - good point having separate versions depending on the database. I will have a look into it once I have some reasonable spare time.

Regarding closing the issue - Moving it to the wiki might be the better option as it is more a solution than an issue :) I will try to write something for the wiki - so let's keep it open until there is an article.
