### ISSUE TITLE
Add custom styles & scripts to the manager

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#273]
Open up the possibility to register custom styles & scripts in the manager UI.

**Comment by tidyui** [comment]
This can now be added in the application `Configure` method **after** `Piranha.App.Init()` with the following statements:

    Piranha.App.Modules.Get<Piranha.Manager.Module>().Styles.Add("...");
    Piranha.App.Modules.Get<Piranha.Manager.Module>().Scripts.Add("...");

Provided paths with be translated with `@Url.Content()` so app local urls like `~/assets/css/test.css` are preferable.

**Comment by w0ns88** [comment]
@tidyui where would I add my `test.css` file withing the file structure if I were to add a stylesheet?
bear in mind I am using the nuget packages so I do not have the full project cloned.
