### ISSUE TITLE
Add functionality for Block Groups

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#291]
A special type of `BlockType` should be introduced a level of grouping in the Block editor. A `Carousel` could for example be a block group that could contain other blocks.

**Comment by alperencaliskan** [comment]
This means i can add my custom row block then add 3-col and 9-col blocks in it which can contain html and image blocks?

**Comment by tidyui** [comment]
Yes it would! However there won't be any functionality in the first iteration for you to actually limit the amount of blocks the user adds into a row, so it would be hard to make sure only a total of 12 column units are added in each row.

**Comment by alperencaliskan** [comment]
Calculating column sizes and limiting is a luxury for now for me. Multiple blocks in block will be enough to increase usability of the cms greatly. Thank you for your hard work.

**Comment by rengert** [comment]
@tidyui you may want to check out the block concept of episerver. i like it, but it is dangerous ;) blocks could contains blocks and ... you can create many fancy stuff, carrousel is one thing. and when you make a block reusable one block could be used as artical AND content of carrousel. It is just rendered a bit different.

What i dont like is the UX, you have to think about how to manage nested blocks in nested blocks etc.

Other ideads are:
- layout blocks
- overlay blocks containing normal contain
- tabs

**Comment by tidyui** [comment]
You can see a screenshot in the bottom of this issue showing how we’re implementing it!

https://github.com/PiranhaCMS/piranha.core/issues/310
