### ISSUE TITLE
Ability to Clone Block

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#300]
Add the ability to clone a block

**Comment by tidyui** [comment]
There will be an option to **detach** a reusable block, ie cloning it into a page specify block once reusable blocks are implemented. This might be sufficient to cover this as well.

**Comment by CastleSoft** [comment]
Perfect..

**Comment by tidyui** [comment]
Closing this issue in favor of #1335 which will provide functionality for reusable components between pages & posts,
