### ISSUE TITLE
Mobile Friendly Hamburger menu 

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#302]
Change the menu to be mobile friendly / hamburger menu

**Comment by tidyui** [comment]
Hi there! I need more information about what part of the system you're referring to

Best regards

Håkan

**Comment by tidyui** [comment]
Aha.. Good call.. The example project is really just for manually testing functionality during development. 

The template projects you mention `Piranha.BasicWeb.CSharp` & `Piranha.Blog.CSharp` both have responsive menus. Nevertheless it would be good to add it to the example.

Regards
