### ISSUE TITLE
Table / Source support in HTML Editor

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#305]
Enable Table support in HTML editor along with Source mode (to allow tweaking margins/layouts).

**Comment by tidyui** [comment]
There's already an issue for HTML editor here #262. Table support will not be added into the default editor setup as we strongly believe that Table data should be handled differently for a smoother management experience, either by a **custom list region** or a **custom block**. 

If you want to add the table editor in TinyMCE you can easily override how the editors are initialized by copying the following file:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Areas/Manager/Views/Shared/Partial/_EditorSetup.cshtml

and placing it in you local project at the same position, i.e

    /Areas/Manager/Views/Shared/Partial/

Best regards

**Comment by CastleSoft** [comment]
Thanks.. Happy to go with the custom list region or custom block for better management.
Just after a clean way to show table style data.

**Comment by mherrema** [comment]
A year later I'm looking to do the same thing, but it seems the file to override has moved (404 on the link above). I can't find where it moved to, can someone point me in the right direction? Or is overriding the `TinyMCE` plugin done differently now?

**Comment by tidyui** [comment]
Hi there, the comment above is correct for version 6.x, but in order to find the file you have to look in that version branch as master is the development branch for the upcoming 7.0 version.

In 7.0 the approach is a bit different and the docs will be updated after release 

Regards

**Comment by mherrema** [comment]
Great, thanks for the insight. 

Updated link here for anyone else that finds this down the road: https://github.com/PiranhaCMS/piranha.core/blob/v6.0/manager/core/Piranha.Manager/Areas/Manager/Views/Shared/Partial/_EditorSetup.cshtml

**Comment by zoinkydoink** [comment]
all links in this issue seem dead, I would like to be able to customize the tinymce's toolbar to show source and other advanced features

**Comment by tidyui** [comment]
Hi there! This can easily be configured in the json efitorconfig. 

https://piranhacms.org/docs/architecture/html-editors/tiny-mce
