### ISSUE TITLE
One Column / Two Column visual column indication

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#307]
In design mode it would be nice to see a dotted / dashed line showing the column boundaries.
Currently when you create a 2-column its not obvious there are 2 columns until you tab.
Maybe a simple css style applied when editing ?

**Comment by tidyui** [comment]
Another thing we've been talking about is to add placeholder images for HTML-editors in the `One Column` and `Two Column` blocks that are only visible when the columns are empty. Kind of like when the Facebook app is loading the feed it shows an abstracted text flow image. This also glues nicely together with how the Image Block is displayed when no image is selected.
