### ISSUE TITLE
Culture / Language Support

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#308]
Please add a culture selection to the settings as default culture and let the developers overwrite it on website level and page level. (i am not sure if it is needed on post level as well)

The managing part should stay always as it is.

**Comment by tidyui** [comment]
Can you please elaborate. Are you talking about setting `Culture` & `UICulture` from `System.Globalization` or are you talking about multi-lingual support? If you're talking about setting culture I'm assuming you want to create different `Sites` for different languages and route them like:

    http://www.mysite.com
    http://www.mysite.com/lang

And then have different cultures set depending on the request?

**Comment by rengert** [comment]
Well, the default setup does not support to set the culture at all. So i implemented it in my own startup file by setting it to my prefered (de-DE). I am developing the website on both mac and windows, and it seems default culture is different ... or i didn't noticed that the dates were not correct ("may" instead of german "mai").

As I think setting it in startup is may not a good idea, because the culture is may set for the cms as well and this is maybe affecting a lot of features.

Regarding your question. The idea behind my question is to start a multilangual website as a support website for a product. In this case orginal language (german) and english is requested. Most of the stuff is content, so no big deal but we want to show the publish date in the a nice format (dd. MMMM yyyy).

Thats why we noticed it. 

I added to myoriginal request, that for sure the cms/manager should not be affected at all.

**Comment by tidyui** [comment]
Ok! I totally understand setting the culture on the Site. Can you describe in what scenario it would be useful to override the Site culture on content level (Page/Post).

**Comment by rengert** [comment]
My understanding of a site is, that the hostname(s) should be unique. So all pages belonging to one package / hostname is one site. A site could have more than one language / user can switch url and there are different urls and content. so the page should have its culture / language as well.

I know some scenarios on content level / block too, but this is to complex fore now, because it meens to introduce the user groups. (not logged in user).

For now, it would be greate to define the culture without affecting internal feature or the managing stuff.

**Comment by tidyui** [comment]
You can actually have the same host name on multiple sites as long as you add a unique suffix, ie:

    www.mysite.com
    www.mysite.com/de

Regards

**Comment by rengert** [comment]
Well. not the best approach from my seo expertise view ;) but i can go with it for now. For me it is just important for now to remove the dirty work around withing know, whats the effect is on the manager.

**Comment by tidyui** [comment]
You can also do

    www.mysite.com
    de.mysite.com

if that feels better :)

**Comment by tidyui** [comment]
I'm removing this from `5.1` due to time constraints. You **can** however create this feature in your own project with the **Site Content** feature in `5.1`.

You can now create content types for sites that hold all global site content, for example header & footer information, but also a field for culture. You can then add a middleware component that checks the request, gets the site content for the requested site & sets the specified culture on the request.

Regards

**Comment by rengert** [comment]
What i did (and registered in startup), the drop down to select the type is visible and the custom site is selected. But i still no way to change the fields. In repro i found examples in test to do it like this.

`	[SiteType(Title = "Custom Site")]
	public class CustomSite : SiteContent<CustomSite>
	{
		[Region(Title = "Google Analytics")]
		public StringField GoogleAnalyticsIdentifier { get; set; }

		[Region(Title="Meta Data")]
		public MetaData MetaData { get; set; }
	}`

Any advice would be great.

**Comment by tidyui** [comment]
Like @filipjansson wrote you need to add the type just like with Pages & Posts. After that is done you open the site in the manager (Settings > Sites) and select the **Site Type** your want for the selected site.

After you've done that you will get an "Edit site" button in the Sitemap at (Content > Pages).

And yes, after `5.1` is released my primary focus will be updating and adding new documentation to the Wiki. 

Regards

**Comment by rengert** [comment]
Okay got it. The code was fine but i searched for the feature in Sites and noch in Content - Pages ;) My bad, works as expected! Thanks @filipjansson & @tidyui

**Comment by tidyui** [comment]
Well there’s no documentation at all about it since 5.1 hasn’t been released yet 😁 So it was impossible to find any info about it
