### ISSUE TITLE
Blog template is using incorrect meta declaration

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#309]
THe blog template for the cms is using the meta declaration with a mix of "key", "name" and "property". This needs to be reviewed and fixed.

Reference for open graph (would be same for dublin core etc.)
http://ogp.me/

Summary
"Normal" meta like description, keywords etc with name="" content=""
"Special" meta like OpenGraph, Dublin Core etc. with property="" value=""

**Comment by tidyui** [comment]
Hi there! Can you please open this issue again at the appropriate repository as it's hard to keep track of changes otherwise!

https://github.com/PiranhaCMS/piranha.core.blog

Best regards

Håkan
