### ISSUE TITLE
ColorField editor template

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#31]
Add editor template in the manager for the `ColorField` with a color picker.

**Comment by govi2010** [comment]
@tidyui  I would like to pick this card. I want to contribute to this project. I found this project really  handy and really cool.

Let me know how can I contribute my code. What are coding standard and Rule for contribution.

**Comment by tidyui** [comment]
Hi there @govi2010 That’s awesome. The currently open issue scheduled for 9.0 is #1302, this one has been closed for ages.

To fully implement the feature it needs a C# class for the field, that the field is registered in App.cs and a Vue.js component for the manager UI!

If you feel you can’t complete all of these that’s fine as well as long as you state what you’ve implemented in your PR.

Best regards

**Comment by govi2010** [comment]
Starting this today ,

**Comment by govi2010** [comment]
Hello @tidyui ,

I have made some progress on this. 
I have used `vue-color` package and made some progress.

I have pushed my code my master branch(forked repo). If you can review and suggest some changes. 



![Kapture 2020-09-19 at 20 50 23](https://user-images.githubusercontent.com/8776031/93670550-cd640780-fab9-11ea-95d5-b6715b1fc4a6.gif)
