### ISSUE TITLE
Multiple Blocks per row 

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#310]
Are you looking at allowing multiple blocks on a row ?
And if so, then allowing dragging blocks between rows ?
For example Divi (wordpress uses this style/method):

![shot1](https://user-images.githubusercontent.com/740215/41647438-ba66501c-74b9-11e8-9720-a4e22049e09b.png)

![shot2](https://user-images.githubusercontent.com/740215/41647461-cefcd460-74b9-11e8-92bb-b6b0cc81faa9.png)

**Comment by tidyui** [comment]
No, we are not actively looking to support column layouts for random blocks as the data model is completely separated from the application rendering it. Giving generic support for columns would mean forcing the web application using the content to implement its grid in the same way.

**BUT** we're working on `Block Groups` (#291) which will be released in `5.1`. A Block Group is a special kind of block that can have child blocks, for example a Carousel with items inside it, or a Row with columns within it. Here's a screenshot of the current state of development.

![skarmavbild 2018-06-20 kl 10 51 24](https://user-images.githubusercontent.com/781266/41648017-0f89091e-7478-11e8-8153-08ac898ea429.png)

**Comment by CastleSoft** [comment]
Perfect.. That works for me....  I can do what I need with Block Groups.
