### ISSUE TITLE
Adding Piranha 5.0 To an Existing DOT.NET Core 2.1 App

### ISSUE THREAD

**Issue by webzest** [PiranhaCMS/piranha.core#311]
Hi,

I have a working DOT.NET Core 2.1 App with --auth individual and an Existing SQL Server. I installed the latest Piranha Stable Nuget, version 5 without errors and would like to start a blog from my existing App.

How do I proceed with the integration from that installation?

Do you have instructions that I can follow to integrate your wonderful Piranha App with my App and avoid having to build a new separate BLOG?

Thank you for your support.

**Comment by tidyui** [comment]
Hi there!

First off, if you running .NET Core `2.1` I strongly suggest you try the `5.1.0-alpha1` packages for Piranha as **some** components in `5.0` isn't compatible with .NET Core `2.1`.

For application startup, please refer to:

https://github.com/PiranhaCMS/piranha.core/wiki/Project-Setup

However, instead of running `app.UsePiranha()` which enables all middleware, you might want to run:

    app.UsePiranhaSites();
    app.UsePiranhaPosts();
    app.UsePiranhaArchives();

This will enable the middleware need for **just** running a blog archive & post details. Even though you can do your own archive route (and skip `UsePiranhaArchive`) my advice is using the default routing as it's quite powerful.

As far as adding controller code and views for your archive & posts I suggest you create a new project from the **blog** project template just for reference while implementing your custom application. Download & usage instructions for the template is available on it's NuGet page:

https://www.nuget.org/packages/Piranha.Blog.CSharp

Best regards

Håkan

**Comment by webzest** [comment]
Hey Hakan,,

I added the 5.1 pre-release to my existing app as well as added the three app. That you recommended below.  However, when I ran the app, I get the following error:
InvalidOperationException: Unable to resolve service for type 'Piranha.IApi' while attempting to Invoke middleware 'Piranha.AspNetCore.SiteMiddleware'.



Best regards,

Johnny
--------------------------------------------------------
Dr. Johnny Sandaire PhD
Information Technology / Commercial Photography
570 South Ave East Bldg. G, Suite F
Cranford, NJ 07016
---------------------------------------------
WebZest, LLC<https://webzest.com>
Johnny Sandaire Commercial Photography Studio<https://www.johnnysandaire.com>
Interactive Panorama Photography<https://jspano.com>
Voice: 1.888.490.0609
Text: 1.908-377-3627

________________________________

**Comment by KevinSheck** [comment]
I too would be interested in a recipe to add blog functionality to an ASP.NET Core 2.1 project.

**Comment by webzest** [comment]
Hi Hakan,

Thank you for your willingness and Support to get this done.  I am a quick learner and have some experience with building apps, but not enough to figure out every step on my own.  So, I think with your guidance and instructions, I can get the integration done accurately.
Here is the list of my App Settings:


  1.  Front-End Framework is Bootstrap V.3.3.7
  2.  .NET Core 2.1
  3.    <ItemGroup>
  4.      <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />
  5.    </ItemGroup>
  6.  SQLServer Database Back-End
  7.  Identity
  8.  Authentication

I would like to integrate a Blog into the App that uses my existing Identity Framework (registrations and login, etc.) to publish some behind the scene stories, and photos, of my work.  I would also like to allow comments for authenticated users or with Facebook Comments.  Social Media sharing would also be good and useful.


Best regards,

Johnny
--------------------------------------------------------
Dr. Johnny Sandaire PhD
Information Technology / Commercial Photography
570 South Ave East Bldg. G, Suite F
Cranford, NJ 07016
---------------------------------------------
WebZest, LLC<https://webzest.com>
Johnny Sandaire Commercial Photography Studio<https://www.johnnysandaire.com>
Interactive Panorama Photography<https://jspano.com>
Voice: 1.888.490.0609
Text: 1.908-377-3627

________________________________

**Comment by tidyui** [comment]
I will create a new project from the blog template, which uses BS 4, throw away everything except the blog archive & post detail and add a standard MVC controller that handles the start page, that should be enough to get the idea!

Regards

**Comment by webzest** [comment]
😊

I tried that too, and added all my other controllers and classes; however, Since my app started with a the Default MVC  individual auth, I had trouble getting it to work with my existing database and Identity infrastructure.
Maybe you know a nice way to merge your code with the default MVC with individual auth, v2.1.



Best regards,

Johnny
--------------------------------------------------------
Dr. Johnny Sandaire PhD
Information Technology / Commercial Photography
570 South Ave East Bldg. G, Suite F
Cranford, NJ 07016
---------------------------------------------
WebZest, LLC<https://webzest.com>
Johnny Sandaire Commercial Photography Studio<https://www.johnnysandaire.com>
Interactive Panorama Photography<https://jspano.com>
Voice: 1.888.490.0609
Text: 1.908-377-3627

________________________________

**Comment by tidyui** [comment]
In the end you will have to make your own custom implementation for Piranha.ISecurity and register in the DI. Piranha.AspNetCore.Identity has its own DbContext and won’t work with your security

**Comment by webzest** [comment]
I think so…  BTW, where are the User classes and Login View?  Is there a registration Class and Controller?


Best regards,

Johnny
--------------------------------------------------------
Dr. Johnny Sandaire PhD
Information Technology / Commercial Photography
570 South Ave East Bldg. G, Suite F
Cranford, NJ 07016
---------------------------------------------
WebZest, LLC<https://webzest.com>
Johnny Sandaire Commercial Photography Studio<https://www.johnnysandaire.com>
Interactive Panorama Photography<https://jspano.com>
Voice: 1.888.490.0609
Text: 1.908-377-3627

________________________________

**Comment by tidyui** [comment]
There are no user classes in the core library, neither Piranha or the Manager cares about user or where they are stored. The manager validates that the current user has the claims needed to perform the currently selected action. You can find a list of the claims used here:

https://github.com/PiranhaCMS/piranha.core/wiki/Security

To integrate the Piranha Manager with your current security implementation you need to register a service implementing `Piranha.ISecurity`. You can read about the authentication here:

https://github.com/PiranhaCMS/piranha.core/wiki/Authentication

There are currently two implementations available for Piranha that you can look at the for reference, `Piranha.AspNetCore.SimpleSecurity` and `Piranha.AspNetCore.Identity`, the last one probably suits your use case best:

https://github.com/PiranhaCMS/piranha.core/tree/master/core/Piranha.AspNetCore.SimpleSecurity
https://github.com/PiranhaCMS/piranha.core/tree/master/core/Piranha.AspNetCore.Identity

**Comment by tidyui** [comment]
Here, I have created an example repository here. If you have further questions, please open an issue in the example repository! I hope it gets you going!

Best regards

Håkan
