### ISSUE TITLE
Changing text color is not possible using the rich text editor.

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#312]
I see it's Tinymce, but adding color picking would require changing the partial in Piranha core.

What's the recommended way to adding changes like that? I could fork the repo or clone from GitHub, but I'm worried a bit about keeping my version up to date with your changes. Seems like a big price just for adding a color picker.

Is there any workaround? Could I somehow allow the users to enter HTML, but using an editor with some assistance, like closing and highlighting tags?

**Comment by tidyui** [comment]
You can override every view in the manager by placing a local in your project so there’s no need to fork!

Regards

Håkan

**Comment by mfronczyk** [comment]
Thanks. I've also figured out that I can use MarkdownField which gives more flexibility than the HtmlField.
