### ISSUE TITLE
Published manager not working

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#314]
After publishing the application, the website itself is running well.
But the manager cannot be reached, the event viewer shows nothing, but after enabling the .net core logging i saw the following issue;

InvalidOperationException: Cannot find compilation library location for package ‘Microsoft.Win32.Registry’

As i said, the frontend is working very well.

Someone else face this issue?

After reading a tons of articles the answer coming up most is, that this has something to do with the embedded views.

The solution should be to set the follow setting, so the refs folder is still in the output.

`<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`

https://neelbhatt.com/2018/02/25/solution-for-the-error-cannot-find-compilation-library-location-for-package-microsoft-win32-registry-net-core-errors-part-ii/

**Comment by tidyui** [comment]
Yes that is correct. I still haven’t figured out why some people get this error and some don’t, but if you get it it’s the correct solution. I will make sure all of the templates contain this line by default.
