### ISSUE TITLE
A way to render fields from Razor and put dynamic content

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#316]
I want to use Piranha to let admins to change parts of bigger pages that are rendered by our MVC project, like some notes etc. I was wondering what's the best way to do that and I came up with defining specific Page classes for every page that needs to be customisable from the CMS. For example this will be used to customise the checkout page:

```
PageType(Title = "Checkout page")]
public class CheckoutPage  : Page<CheckoutPage>
{
    [Region(Title = "US shipping note", SortOrder = 0)]
    public MarkdownField UsShippingNote { get; set; }
}
```
Then admins will be told to create a page of this type with a specific slug in the manager and the code will find the page by slug and render its fields on the view.

Is it the right approach? Are there any tag helpers that will help with that, process markdown etc? In #202, there was "RenderPiranha" mentioned, but it seems it hasn't been implemented.

Are there also any guidelines about how to enter dynamic parts into field values? For example, let's say that the admin would like to print the current time in the middle of the text. Do I need to come up with my own special dynamic tag syntax and process it when rendering the text, or are there any already established practices? Is it possible to embed any asp.net tag helpers while entering text using Piranha manager?

**Comment by tidyui** [comment]
### Page Structure

I think your approach sounds like something that would be hard to maintain in the long run, and require a lot of models. If it was my choice I would:

1. Define PageTypes from the different content scenarios available, not the amount of pages.
2. Create the entire site structure in the manager with the correct page types.
3. Create a new group for the content administrators and **remove** the following claims for them:
   * PiranhaPagesAdd
   * PiranhaPagesDelete
   * PiranhaPagesPublish

This would mean the content admins would not be able to add, delete or unpublish any pages **but** they could edit & save the content for the pages you'd already created for them. Then it's just a matter of loading the models from your code.

### Rendering fields

Almost all of the fields have implicit operators converting them to strings. In the case of `MarkdownField` this means returning the field as a HTML string, for an image it returns the url of the image. This means you can simple write the following in your view (based on your CheckoutPage) model.

    @Html.Raw(Model.UsShippingNote)

### Dynamic parts in pages

There's currently no transformation of special values built in for either `HTML` or `Markdown` fields. But you could always add your own RegEx method that processes the output before rendering it.

Best regards

**Comment by mfronczyk** [comment]
Thanks a lot! In regards to the page structure, I think I meant the same, to create page types like CheckoutPage, SalePage etc, with fields that should be editable by the content editors. However, I didn't think about limiting the permissions - good idea!
