### ISSUE TITLE
2nd archive page type / blog type in the project

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#322]
What is the preferred way to do it.

What i did already is, i defined the models and registered them. In the manager everything seems to be working. I can create my archive page and i can create my post with the new fields.

In frontend a run in trouble. I checked out the cms controller and see the different action methods. But what i have to do to call my own controller or another action. And the same for the views?

The issue is, i don't want to replace the models in the blog template, at the end i want to use both.

I think the similar question i will have, if i create a new customer page.

Well, in the controller i already change to code, to check first if it is a normal blog and then load the other one. But i think this is not a good idea? 

Background story
I want to handle 2 projects within the content management system and one is a classic blog, so the blog template is great. thx for that. The second one is a location review system. It is a blog to, but i need to define some more fields (address, email, bla bla).

**Comment by tidyui** [comment]
Hi there! You can specify which route is executed for which Page Type by setting the `PageTypeRoute` attribute on your Page Type. For reference, check here:

https://github.com/PiranhaCMS/piranha.core/wiki/Page-Types

As you can see in the documentation you can also specify multiple routes for the same Page Type if you want to reuse types & models.

Let me know if I missed anything or you need more help.

**Comment by rengert** [comment]
Great, many thanks. I only checked for an attribute in PageType attribute. My bad.
