### ISSUE TITLE
Angular Example?

### ISSUE THREAD

**Issue by jcphlux** [PiranhaCMS/piranha.core#325]
I am trying to figure out if this is a fit for my project. Client is wanting to add CMS like features to there site that is built with asp core back end Angular front end.  Wanted to know if there is a sample project or a tutorial on how to use piranha with Angular?

**Comment by jcphlux** [comment]
I have looked in on This project from time to time but have not had a chance to learn to use it. I would not mind helping out if I can find the time. I would need to weigh the time it would take to make these changes vs creating a custom solution to meet my clients needs.

**Comment by tidyui** [comment]
What methods do you need in the api besides Sitemap & Page? I’m guessing the following is needed:

* Get archive with filter
* Get archive by category with filter
* Get archive by tag with filter
* Get post

It would be easy to incorporate preview of unpublished pages & posts depending on the claims of the current user. 

Other than that I’m assuming it’s read only and the manager is used for editing.

**Comment by jcphlux** [comment]
Yeah that would probably handle most of what I need. I am sure once I get into it and know how to use it better I could help figure out any nuances that would make it better.

**Comment by jcphlux** [comment]
Let me build a test site with Piranha today before I play with this. I need a baseline to compare too.

**Comment by jcphlux** [comment]
ok I have been playing with the code and I think I have an understanding on how it works. 
I almost want to see if I could rebuild the manager and the test site with Angular.

**Comment by tidyui** [comment]
Rebuilding the test site is a nice the starting point. I don’t recommend rebuilding the manager as it relies a lot on resolving views based on CLR type and custom model binders, plus the fact that it would be extremely specific for your project and probably would make upgrading harder. However if you have a fixed application where you want to incorporate Piranha data in your admin it’s always an idea, we’ve actually done that in a project as well.

**Comment by jcphlux** [comment]
I am about half way though recreating an exact copy of the the test site using angular 6 I have created a test site that sits in the in the examples folder and works with the current master branch not the API branch.  Is this something you would be interesting in merging in once I get it completed?

**Comment by jcphlux** [comment]
@tidyui I have the Angular 6 example site about 95% done at this point.  I have a few things I would like to work with you on to get all the info I need to display blocks correctly and I think there is a better way to get the image Urls then the way I am handling it. Is there a better way we could communicate to tackle these last few issues I am having?

**Comment by jcphlux** [comment]
@tidyui I think I figured out all my issues. I am creating a pull request after I run through some testing and update the readme for the angular site on steps to get it working.
