### ISSUE TITLE
MarkdownField editor template

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#33]
Add editor template in the manager for the `MarkdownField`. The user should edit the content in plain text but there should be a preview mode which renders the entered markdown as HTML for the user. The rendered HTML should not be editable.

**Comment by TheWolfA2** [comment]
What markdown editor is used for handling the markdown conversion/preview, out of curiosity? Is this a custom module or is another library used for this?

**Comment by tidyui** [comment]
At this point nothing has been decided, neither for editor **or** for markdown > html translator, so it's up for discussion!

**Comment by tidyui** [comment]
I used this package for now for server-side conversion of markdown to html.

https://www.nuget.org/packages/Markdown

Regarding the manager editing view I'm up for suggestions. Of course I love the side-by-side editor in Ghost, and that kind of interface could work when the editor is used in a single field region, like this:

![skarmavbild 2016-11-26 kl 22 35 10](https://cloud.githubusercontent.com/assets/781266/20644056/f9b5354c-b428-11e6-9421-c68425911a27.png)

On the other hand a simple edit/preview mode might be better when the field is part of a complex region. If we would decide on the side-by-side view I'm a bit torn on whether to convert to html to markdown in javascript (which would need a second redundant markdown converter) or make ajax-calls to the server for conversion.

**Comment by TheWolfA2** [comment]
I personally have only used [MarkdownDeep](http://www.toptensoftware.com/markdowndeep/) which has both server-side and client-side support and does side by side live markdown conversion. However, I always found it to be awkward to use client side. The other issue is it hasn't been changed much and doesn't support .Net Core. This can be circumvented by taking the core C# code and making a custom Net Core class library which I did for another project of mine.

**Comment by TheWolfA2** [comment]
I should better qualify it being awkward client side and say that when you deal with Ajax with it it gets awkward. If you're just doing post backs and not injecting new editors it's pretty straightforward

**Comment by tidyui** [comment]
I'm getting there with the markdown editor :)

![skarmavbild 2016-12-01 kl 21 35 00](https://cloud.githubusercontent.com/assets/781266/20811551/6e4e75f6-b80e-11e6-932b-fcdc878d41e3.png)

**Comment by tidyui** [comment]
And for smaller screen resolutions I'll do edit/preview in a tab bar.

![skarmavbild 2016-12-01 kl 22 23 30](https://cloud.githubusercontent.com/assets/781266/20813343/81a02c6a-b815-11e6-818f-4a4887e7a77b.png)

All that's left is live-update of the preview window, right now it's only rendered when the page is loaded in the manager and setting up the tab bar behaviour.

**Comment by TheWolfA2** [comment]
That's awesome! Loving the design of it.

How modular is the markdown tool? Could it be abstracted into a `HtmlHelper` extension or .Net Core tag helper so that Piranha users could make use of the editor in their own app for user uploaded content, for example?

Just a thought that could go towards a future version!

**Comment by tidyui** [comment]
I really like the idea, have to refactor a bit when it's done as it changes behavior depending on screen resolution and context it's used in the manager. All of this would need to be exposed as settings for it to be a good reusable component.
