### ISSUE TITLE
default user password for the manager

### ISSUE THREAD

**Issue by treping** [PiranhaCMS/piranha.core#336]
what is the default user/pass to get into the manager ?
http://localhost:5000/manager/login

**Comment by tgondar** [comment]
what's the user/pass combination? or how can I access some "piranha cms configuration page"

**Comment by natepaxton** [comment]
@treping Did you resolve this issue somehow?

**Comment by tidyui** [comment]
Hi there! It’s user/password 😁

Regards

**Comment by kikkoi** [comment]
@tidyui when I started there wasn't documentation that default user and password in manager. Documentation is so important to will help.
