### ISSUE TITLE
Image size in Manager.

### ISSUE THREAD

**Issue by jcphlux** [PiranhaCMS/piranha.core#339]
I see that in the Example site you do an image resize for the teasers. It would be nice to have an image size in the manager when you add an image to a page.

**Comment by tidyui** [comment]
Do you mean an image preview by the Image Field?

**Comment by jcphlux** [comment]
I got the idea when I was looking through the example there is the resize on the teasers in the chtml page.

**Comment by jcphlux** [comment]
I have created Custom Size image Field and Block in my angular project.  I am about to create a pull request to add my Angular Example site so you can see how I implemented it.
