### ISSUE TITLE
AutoMapper dependency.....

### ISSUE THREAD

**Issue by natiki** [PiranhaCMS/piranha.core#34]
Hi,

I want to pull in the entity models into a DBContext and although the docs say it is built on AutoMapper 5.1.1 the constraint is for AutoMapper (>= 3.3.1 && < 3.4.0)' when I pull in PiranhaCMS.Core.2.2.5.

Before I go and duplicate code here is there any chance of an updated NuGet package?

**Comment by tidyui** [comment]
Hi there! The NuGet packages available are for the version (2.2.6) and the code located in the **Piranha** repository. Piranha for dotnet core will be available as nuget packages once we get a little closer to release!

Regards

**Comment by natiki** [comment]
Hi,

Oops looks like I posted in the wrong repo. Any chance of the current code for MVC getting a bump in terms of AutoMapper. At present I want to access the underlying entities (https://piranhacms.org/docs/api-reference/entities) and am currently recreating the models locally using https://github.com/PiranhaCMS/piranha.core/tree/master/src/data/Piranha.EF/Data.

Any other work around?

**Comment by tidyui** [comment]
If you're willing to go for the beta on NuGet it's updated to version 4.1.1, but we will release a new beta shortly. I could upgrade the master branch to the latest version of `AutoMapper` without any problems.

**Comment by natiki** [comment]
Hi,

Thanks heaps for the beta. I tried with PiranhaCMS.Core.2.2.6-beta6 and got the later 4.x version of AutoMapper. However there is a problem now pulling in LINQ as follows:

> Failed to add reference. The package 'PiranhaCMS.Core' tried to add a framework reference to 'System.Linq' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

I tried with System.Linq 4.0, 4.1 and 4.3.

So I understand where things are heading from a roadmap point of view:

1) Will you still be providing a MVC version going forward? ie something that is **not** .NET Core?
2) Will the MVC version ultimately upgrade to AutoMapper 5.x?

**Comment by tidyui** [comment]
This new version is MVC only, but MVC 6 for aspnet core. Once it's done it is highly unlikely that new features will be added to the MVC 5 version, but I will still accept pull requests and deploy new versions if needed.

Regarding .NET & Automapper versions I'll respond in the other issue in the PiranhaCMS repo!

Regards

**Comment by natiki** [comment]
Thats a pity there will be no continued support for MVC 5. .Core is not ready yet for prime time IMHO until at least it reaches netstandard 2.0. Its great for smaller non enterprise projects at this point.

**Comment by tidyui** [comment]
That depends on how you look at it :) I doubt that everything is up to speed in `piranha.core` **before** dotnet core is stable, effective and production ready. With that in mind MVC 5 will most likely be the version available and supported on NuGet until dotnet core is ready. 

In regards to dropping support for older versions. Since I started the project in 2011 I've only had a handful contributions made by other people. Supporting multiple target frameworks imposes a lot more work which would be too much for me to handle alone. With more community support I'd have **no problem** with support for a wider range of versions & targets.

Regards

**Comment by natiki** [comment]
Hi,

Thanks for that. I totally understand the need for help from the community. I will make sure that anything I change locally gets a PR for your consideration.
