### ISSUE TITLE
Cannot add hyperlink to any image

### ISSUE THREAD

**Issue by em88lou** [PiranhaCMS/piranha.core#343]
Unable to add a hyperlink to an image within the content region/the image region.

**Comment by tidyui** [comment]
Hi there! Just to clarify, are you talking about the **ImageBlock**, or creating a hyperlink with image content in an **HTML Block**?

Regards

**Comment by em88lou** [comment]
Hi, The issue is both within the Image Block and Html Blocks. I have a banner image within a content block and adding a link to the image seems to remove the image completely. Only seem to be able to add a link to text. 
The image block only seems to allow me to add an image with no other functionality. 

Thanks!

**Comment by tidyui** [comment]
I would consider not being able to create an image link within the HTML editor a bug. The `ImageField` however is just supposed to be an Image per design, however it's easy to create your own `BannerBlock` in your project that could create an image, a link and additional information you want.
