### ISSUE TITLE
Managing email templates

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#344]
We'd like to author emails using Piranha and I thought about creating Pages for each email type. However, it sounds like a hack and I'm worried that we might have problems with our email templates appearing in the navigation, sitemap etc (however, we don't use these now). Is that true?

Is using pages a good workaround for editing emails? Or should we rather create a custom module?

**Comment by tidyui** [comment]
You **could** always add a second site for your email templates that isn’t bound to any hostname. This way you could use Pages but they won’t clutter your website structure.

Regards

/Håkan

**Comment by mfronczyk** [comment]
We went so far with creating regions in pages that cause these emails to be sent, but your idea is great! Thanks.
