### ISSUE TITLE
Unique slug should be site based

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#347]
I have multiple site setup and need to setup some pages you need in all sites (imprint, data protection ...).

**Comment by tidyui** [comment]
I'm not sure what error you're receiving. The page slug is unique per site, and I've just tested adding pages with the same slug in different sites.

**Comment by rengert** [comment]
I can confirm, indeed i have also one page with same slug as a page in another site.
The error i received, was not in ui. I checked the response from server and the log file on server. And it was a uniique contraint exception saying slug should be unique. 

I am not sure if it has something to do with: https://github.com/PiranhaCMS/piranha.core/issues/346

Let me see, if i can reproduce the scenario.

**Comment by tidyui** [comment]
I have managed to reproduce an issue when adding a page with the below links on multiple sites. 

When you change site with the drop down you reach the Sitemap with an alternate route. When that route is active these links doesn’t seem to work. However, clicking pages in the left menu you will get the same Sitemap (as it’s stored with a cookie) and then the links work.

I’ll try to get find the issue and solve it!

**Comment by tidyui** [comment]
Ok, it's a bit more complicated. Depending on the how the manager has been routed to the current sitemap the UI looses track of the currently selected `SiteId` which can cause pages to be misplaced when running multiple sites
