### ISSUE TITLE
Page Title should be optional

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#348]
When creating a page, a Title is mandatory.
Not all pages need the page title displayed. A on/off slider to display Title would be a nice feature.

**Comment by tidyui** [comment]
Hi there! All pages are supposed to be routable which means they have a unique mandatory `slug`. The slug is generated from the `title` and therefor the title is mandatory as well. How and what are you using pages for in the scenario, maybe a Page is not the best entity?

**Comment by CastleSoft** [comment]
Sorry.. I'll clarify.
The routable path / slug etc are all good/required as you say.
Sometimes on a page I don't need the Title displayed in a fixed position, as I may override it with different content. Or not need the title displayed at all.
So a mandatory title is all good.. Its the option to display / not display on a page I am after.  

`<div class="row justify-content-center">
        <div class="col-sm-10">
            <h1>About Me</h1>
        </div>
    </div>`

ie. Hide the block above based on a toggle in the settings ?? 

![example2](https://user-images.githubusercontent.com/740215/42997075-d040f598-8c58-11e8-8d28-498d42aabd9f.jpg)
![example2-editing](https://user-images.githubusercontent.com/740215/42997081-d5956290-8c58-11e8-8250-2db1ca934498.png)
![example2-settings](https://user-images.githubusercontent.com/740215/42997088-d87c66ca-8c58-11e8-974e-9bf8902cac52.jpg)

**Comment by CastleSoft** [comment]
For example sometimes, the menu and slug might be "Contact", but a map/carousel/other content might be above the page content. And the page name might be slightly different to the menu (ie. Contact Us). Having the ability to hide the page title, and just use a Block to display it is handy.

![example-contact](https://user-images.githubusercontent.com/740215/43000844-65c794de-8c66-11e8-9210-da341307eb20.png)

**Comment by tidyui** [comment]
Aha, I get it. Well my suggestion is that you create your own custom `SettingsRegion` which can hold all of the different custom settings you want for your pages. For example:

    public class SettingsRegion
    {
        [Field(Title = "Hide Title")]
        public CheckBoxField HideTitle { get; set; }

        ...
    }

Then add this to your pages.

    public class MyPage : Page<MyPage>
    {
        [Region]
        public SettingsRegion Settings { get; set; }

        ...
    }

You will most likely run into more setting you'll want to tweak for the pages in your site!

Regards

**Comment by CastleSoft** [comment]
Thanks.. Is this what you mean ? Do I need anything else ? Do I need to register anything ?

`================================================
       Models/StandardPageHideTitle.cs
================================================

using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;
using Piranha.Models;

namespace BasicWeb.Models
{
    [PageType(Title = "Standard Page Hide Title")]
    public class StandardPageHideTitle  : Page<StandardPageHideTitle>
    {
    		[Region]
    		public Regions.Settings Settings { get; set; }
    }
}

================================================
       Models/Regions/StandardPageHideTitle.cs
================================================

using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;
using Piranha.Models;

namespace BasicWeb.Models.Regions
{
    public class Settings
    {
        [Field(Title = "Hide Title")]
        public CheckBoxField HideTitle { get; set; }        
    }
}

================================================
       Views/Cms/PageHideTitle.cshtml
================================================

@model BasicWeb.Models.StandardPage
@{
    ViewBag.Title = Model.Title;
}

<div class="main">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 page-body">
			 @if (Model.Settings.HideTitle) {
		                <h1>@Model.Title</h1>
			 }
                @DisplayFor(m => m.Blocks)
            </div>
        </div>
    </div>
</div>
`

**Comment by tidyui** [comment]
You need something to load your model and send it to the correct view. You do this by registering a route to your page type, like so:

    [PageType(Title = "Standard Page with Hide Title")]
    [PageTypeRoute(Title = "Default", Route = "/hidetitlepage")]
    public class StandardPageWithHideTitle  : Page
    {
        [Region]
        public Regions.Settings Settings { get; set; }
        }
    }

Then you add an Action for this is any controller.

    public CmsController : Controller
    {
        private readonly IApi _api;

        public CmsController(IApi api)
        {
            _api = api;
        }

        [Route("hidetitlepage")]
        public IActionResult PageWithHideTitle(Guid id)
        {
                return View(_api.Pages.GetById<StandardPageWithHideTitle>(id));
        }
    }

When it comes to the label not rendering for the CheckBoxField it's because regions containing a **single field** are rendered in a different way, usually these regions are for main content fields. There's currently no way to bypass this behavior, but if you had more fields in your Settings region the problem would of course solve itself.

**Comment by CastleSoft** [comment]
Thanks I'll give it a run.  I'll add a dummy called TAG to the settings region and see how things go.
I'm assuming 

.AddType(typeof(Models.StandardPageWithHideTitle)) // ADDED - StandardPageWithHideTitle

Was correct.

**Comment by CastleSoft** [comment]
Hmmm.. Very close.. I get the following error when I try to display HiddenTitle page:

System.ArgumentException: Object of type 'Piranha.Extend.Fields.CheckBoxField' cannot be converted to type 'cms.Models.Regions.Settings'. 

[pir-extended-hidetitle.zip](https://github.com/PiranhaCMS/piranha.core/files/2217977/pir-extended-hidetitle.zip)

The steps so far are:

1) Modify Startup.cs (added line 57)

     .AddType(typeof(Models.StandardPageWithHideTitle))

2) Modify CmsController.cs (added in around line 54)

        // AJT 2018-07-23
        /// <summary>
	/// Gets the PageWithHideTitle with the given id.
	/// </summary>
        /// <param name="id">The unique page id</param>
        [Route("hidetitlepage")]
	public IActionResult PageWithHideTitle(Guid id)
        {
           var model = api.Pages.GetById<Models.StandardPageWithHideTitle>(id);
           
	   return View(model);
    	}

3) Created Models/StandardPageWithHideTitle.cs

using Piranha.AttributeBuilder;
using Piranha.Models;
using Piranha.Extend.Fields;
using System.Collections.Generic;

namespace cms.Models
{
    [PageType(Title = "Standard Page with Hide Title")]
    [PageTypeRoute(Title = "Default", Route = "/hidetitlepage")]
    public class StandardPageWithHideTitle  : Page<StandardPageWithHideTitle>
    {
    	[Region]
    	public Regions.Settings Settings { get; set; }
    }
}

4) Created Models/Regions/Settings.cs

using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;
using Piranha.Models;

namespace cms.Models.Regions
{
    public class Settings
    {
        [Field(Title = "Hide Title")]
        public CheckBoxField HideTitle { get; set; }        
    }
}

5) Created Views/Cms/PageWithHideTitle.cshtml

@model cms.Models.StandardPageWithHideTitle
@{
    ViewBag.Title = Model.Title;
}

<div class="main">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 page-body">
		@if (!Model.Settings.HideTitle) {            
                <h1>@Model.Title</h1>
                }

                @Html.DisplayFor(m => m.Blocks)
            </div>
        </div>
    </div>
</div>

Not sure if the Region Settings / Checkbox stuff is right ? Or I missed other bits ?

**Comment by rengert** [comment]
Did you changed the type of the settings property?
The type is persisted in the db and it is hard to change it afterwards. I had similar issue.

**Comment by CastleSoft** [comment]
No changes.. Also just deleted the DB file. Reseeded the system with clean test data.
Created the page and fails when I try to view.
pir-extended-hidetitle.zip - contains the dotnet run ready version I'm testing (above)

**Comment by tidyui** [comment]
Hi there! If region contain only **one** field that field is returned. So when the model is being built it is assuming that your page model looks like this:

    namespace cms.Models
    {
        [PageType(Title = "Standard Page with Hide Title")]
        [PageTypeRoute(Title = "Default", Route = "/hidetitlepage")]
        public class StandardPageWithHideTitle  : Page
        {
            [Region]
            public CheckBoxField HideTitle { get; set; }
        }
    }

They way the Content Types are represented in the database the model factory can't tell the difference between the above model and your model.

**Comment by CastleSoft** [comment]
Ahh.. that make perfect sense. I was thinking.. I defined Settings but getting CheckBoxField.

So for 1 field define [Region] public CheckBoxField etc etc..
And for 2 or more fields, the [Region] public Regions.Settings Settings { get; set; } is correct.

Will tweak and give it a run. Thanks again.

**Comment by CastleSoft** [comment]
![working](https://user-images.githubusercontent.com/740215/43067253-2f0be760-8eaa-11e8-9cc4-40b1e25f437c.png)

PERFECT.. WORKING 100% 

Added a generic TAG property to the page, to use the Model over just a CheckBoxField and the Display is correct and model passes ok.

Thank you for your help.  Now time to think about what extra settings I want on a custom page. And do some renaming (StandardPageWithHideTitle) was a prototype / test name.

Again thank you.
