### ISSUE TITLE
Missing content type

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#350]
It seems piranha is not providing content type in response.

In general maybe no big issue, but if you run the application with the following security header:
`<add` name="X-Content-Type-Options" value="nosniff" />

The browsers (or other applications) are ask to ignore file extensions or guessing using the content. 

What is the result or the problem:
You can see it very easily using the sitemap, the sitemap is displayed in the browser as plaintext, not as xml where you can collapse the nodes etc.
Another application i am using for seo analysis thinks the sitemap is a normal page and gave me the advice to add description, headline etc. 

I have no idea what the result is for a crawler or so.

So my request is: Please add the content type header depending on the resource (xml for the sitemap ;) )

I did a quick check, the mvc is working correcty, if i request the response from the controller directly i see the correct content type (for example json)
`public IActionResult Details()
		{
			return Json("");
		}`

**Comment by tidyui** [comment]
Just to clarify, I assume this error only exists for the Sitemap middleware as everything else is standard MVC?

**Comment by rengert** [comment]
Well, additional comment. I think you can ignore the cms part. The content type is only missing in case of response type "304". I guess this is fine, i checked with other website and there the content type is also included in "304" case. But as i said, i see no error case. So fixing the sitemap.xml would be enough and great.

Sorry for the confusion. Thanks.

**Comment by tidyui** [comment]
I've checked pages coming from the CMS and they return `text/html; charset=utf-8` both on **localhost** and from **azure**. Like you say, for `304` I don't see any problem with it, but I'll make sure to add `application/xml; charset=utf-8` for the sitemap

**Comment by tidyui** [comment]
This has now been released and is available in `Piranha.AspNetCore` 5.1.2
