### ISSUE TITLE
Ef Migration gives error on npgsql.

### ISSUE THREAD

**Issue by alperencaliskan** [PiranhaCMS/piranha.core#352]
Upgrading from 5.0.0 to 5.1.1,

Ef migration fails because of raw query, postgresql is case insensitive for object names. Needs quotation marks.

https://github.com/PiranhaCMS/piranha.core/blob/131e23f491bcea3499eeb3813d47af4fe351c205/core/Piranha/Migrations/20180531092411_AddMediaVersionExtension.cs#L17

```UPDATE "Piranha_MediaVersions" SET "FileExtension"='.jpg' WHERE "FileExtension" IS NULL```

**Comment by tidyui** [comment]
This has now been released and is available in `Piranha` 5.1.2
