### ISSUE TITLE
Field notes

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#355]
It'd be great to be able to provide field comments that are shown to the content editors. It would be handy to strike the editors with important notes before they edit the field. For example, quickly note where the given field is used.

**Comment by tidyui** [comment]
This will be implemented by a combination of:

* Adding placeholder texts to fields (#370)
* Adding information text for a region

It's more interesting to add information on the region level as a field is more likely a component in the region context.

**Comment by mfronczyk** [comment]
This makes perfect sense. Thanks!
