### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by amh2013** [PiranhaCMS/piranha.core#356]
It would be a good idea to enable HTML input on editor for pages to copy existing HTML when converting sites to Piranha.

**Comment by amh2013** [comment]
Sorry that was just me in a hurry.  Basically when creating a new page with admin interface I notice the default editor (tinyMCE) does not allow HTML input, so if we have HTML data it would be nice to input the HTML direct into the editor. in HTML view.
![pcmssnip](https://user-images.githubusercontent.com/6211491/43633943-b17676b0-9702-11e8-8fe2-60ac2fee85bc.PNG)

**Comment by tidyui** [comment]
Allwright, now I’m on the same page :) There is an already open feature request for this so I will close this issue as a duplicate! In the meantime you can override the TinyMCE setup in your project to include the default html editor, look at the comments in #305 for reference.

Regards
