### ISSUE TITLE
Content links

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#357]
I'd like to allow editors to define content links in the CMS. For example, we'd like to be able to define a global list of service type pages and then to select services that should be available on the given site. So when a user visits a site, he sees an index containing just the services selected in the cms and can read more about these services. It should be linked as a reference, so when the service page changes, it's reflected on all sites offering that service.

Is it possible to achieve currently in Piranha? I looked at the Wiki, but I'm not sure how to model that.

**Comment by tidyui** [comment]
Just to clarify, do you want to have **one** instance of the service pages and just display links on the referencing pages, or do you want to load the linked content and display it on the different pages referencing it?

Regards

**Comment by mfronczyk** [comment]
The latter - be able to load the linked content and display it on different pages.

**Comment by mfronczyk** [comment]
Do you think it’s possible now or it’d require a new feature?

**Comment by tidyui** [comment]
Well you can use the `PageField` or `PostField` in a **ListRegion** on you page model, this way you can reference other pages and load their content into the page model. The only downside is that you can specify specific page/post types that should be visible in these fields, so the content editor will be able to choose from any page/post

**Comment by tidyui** [comment]
Yes you can add a specific issue for that and we'll close this one. It has to be some kind of generic way of supplying parameters to fields as all fields in Piranha are implemented in the same way as you would with a custom field. On the other hand it's a great feature that gives you a lot of options.
