### ISSUE TITLE
Future Enchancement: More request handler hooks

### ISSUE THREAD

**Issue by TheWolfA2** [PiranhaCMS/piranha.core#36]
First, I fully acknowledge this is a rather niche use-case so if this feature were to be skipped I completely understand.

I am currently working on a project at work which we are planning to integrate PiranhaCMS 2.2.5 into.  One of the features we are working on is restricting documents and media based on a user's group/permissions so that only certain documents can reach certain users. We plan to accomplish this with document categories that map to access permissions since media files don't support having permissions directly on them.

In the process of writing a custom `IRequestHandler` implementation, I found that in order to check a user's permissions the request needs to have passed the `HttpApplication.AcquireRequestState` event since user profile information is stored in the current session. It may be a nice addition to update the `IRequestHandler` to include more events similar to what the [`HttpApplication`](https://web.archive.org/web/20071223170129/http://articles.techrepublic.com.com/5100-10878_11-5771721.html) event sequence is.

Since it seems most of the 2.2.x handlers only need the BeginRequest method, the standard handlers could all derive from a base `RequestHandlerBase` class which implements all the `IRequestHandler` methods as virtual members so that all the methods are present in the actual handler but they can still be overridden if necessary. And this would also allow for easier coding of those handlers if this feature were to be implemented

**Comment by tidyui** [comment]
I think this is a totally valid case, it only exposes existing behaviour in a few more places! However this is in the wrong repo as it should've been posted in https://github.com/PiranhaCMS/Piranha. Open an issue for it in that repo and send a PR for it and I'll include it in the next package release!

**Comment by TheWolfA2** [comment]
Oh I was thinking this would be included in the piranha.core implementation instead of 2.2.x since it still needs to be written for 4.0 (or at least it looks like it does). but I could make a PR on Piranha as well so that it ends up in both versions

**Comment by tidyui** [comment]
Oh I see! There was so much references to old code I just assumed you were talking about the 2.x version :)

In piranha.core everything is implemented as middleware, so the easiest way would probably be to:

1. Add a new table for mapping media to groups
2. Add a new middleware that checks incoming media requests and returns unauthorized when applicable.

The overall architecture of piranha.core is cleaner and more open for modification so solutions for the two versions will probably be quite different.

Regards

**Comment by TheWolfA2** [comment]
Yeah, sorry about that! I made reference to the 2.x code since it was the only frame of reference I have, and since I have done much research regarding Piranha's request "interception" mechanisms both in the 2.x and Core versions.

But yeah, if we can implement some middleware to handle this case, I could see some individuals finding use for this type of security/authorization support!
