### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by haeberle** [PiranhaCMS/piranha.core#368]
Dear community

I implemented my own block and when I'm using it, the page save or update function fails with an error with the following message : "The server encountered an error processing the request".

in the VS output I can only see (next to several SQL statements) the two lines:

> BWeb> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
> MBWeb>       Route matched with {area = "Manager", action = "Save", controller = "Page"}. Executing action Piranha.Areas.Manager.Controllers.PageController.Save (Piranha.Manager)
> MBWeb> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
> MBWeb>       Authorization was successful.

then a longer time no output.... ~30 secs

Executing action method Piranha.Areas.Manager.Controllers.PageController.Save (Piranha.Manager) with arguments (Piranha.Areas.Manager.Models.PageEditModel) - Validation state: Unvalidated

Maybe I implemented a too complex Block. Do you have experience on that  ?

Below my Block
```javascript
 [BlockType(Name = "Product", Category = "Mueli Braeu", Icon = "fas fa-beer")]
    public class ProductBlock : Block
    {
        public TextField Title { get; set; }
        public HtmlField Content { get; set; }
        public ImageField Image { get; set; }
        public ImageField LogoImage { get; set; }
        public CheckBoxField EnableProductTeaser { get; set; }
        public HtmlField TeaserContent { get; set; }

    }
```

**Comment by tidyui** [comment]
No, and we've implemented some pretty weird blocks :) Have you tried adding a block to a page through the `Api` so we can pinpoint if the problem is in the manager interface or in the data transformation?

You can look at the example project here which seeds some pages with blocks  on startup.

https://github.com/PiranhaCMS/piranha.core/blob/master/examples/CoreWeb/Startup.cs#L169

Best regards

**Comment by haeberle** [comment]
Thanks Hakan for the hint. The issues was that I had the 
```javascript
@Html.HiddenFor(m => m.TeaserContent .Value, "")
````
in the <div id="Editor....> tag. That blows the value in the hidden tag up.

So my issues is resolved.

Thanks for you great work!

**Comment by tidyui** [comment]
Great!
