### ISSUE TITLE
Defining Alt Text in Image Field

### ISSUE THREAD

**Issue by wzowee** [PiranhaCMS/piranha.core#371]
Are there any plans to offer the ability to set Alt Text on an Image Field or directly on an Image in the Media Library?

Migrating a site from an old version of Orchard CMS to Piranha with a significant number of images and would Ideally like to migrate and render the alt text with these images

**Comment by tidyui** [comment]
Well there's no problem adding another fields to the database and setting it through the api when importing images, however the manager interface currently doesn't have any view where you can edit meta-data about an uploaded file. I'll have to think about a good solution for it!

Regards

**Comment by tidyui** [comment]
Just got an idea on how you can deal with this until more meta fields are added to media. If you're planning on importing the media from Orchard to Piranha, when looping through them you can just set the current Alt text as filename (plus the current extension).

**Comment by pauldbentley** [comment]
I'd be interested in this.

I am looking a migrating from a legacy in-house built CMS to Piranha.  In this CMS each image as a Name field which is separate to the filename.  When an image is selcted in TinyMCE the Name is set as the alt tag on the image which is quite nice.

**Comment by vjacquet** [comment]
Isn't "Added support for media meta information" in version 8.1 fixing this?

**Comment by tidyui** [comment]
Yes indeed. This issue was just so old I didn't see it :)
