### ISSUE TITLE
Raw SQL in migration breaks in mysql

### ISSUE THREAD

**Issue by wzowee** [PiranhaCMS/piranha.core#375]
This raw sql migration breaks in mysql as it's not valid.

https://github.com/PiranhaCMS/piranha.core/blob/f05b715245073eddda13689956b61d8ed73276aa/core/Piranha/Migrations/20180531092411_AddMediaVersionExtension.cs#L17

`UPDATE Piranha_MediaVersions SET FileExtension='.jpg' WHERE FileExtension IS NULL`

Which was previously in this migration does work.

**Comment by tidyui** [comment]
Hi! This is fixed in version 5.1.2 
https://github.com/PiranhaCMS/piranha.core/milestone/12?closed=1

Upgrading should fix your problems!

Regards

**Comment by wzowee** [comment]
The fix in Version 5.1.2 is unfortunately what has broken the migration for mysql. 

mysql doesn't appear to support double quotes around identifiers, instead it prefers backticks `

Actually looks like I may be able to configure mysql to support double quotes around identifiers via configuration but it doesn't look like it supports it by default.
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes

**Comment by tidyui** [comment]
Hmmm, ok.. Just out of curiosity, if you downgrade to `5.1.0` and run the migration from that version, can you get it to work? After the migration is done it should be safe to upgrade to `5.1.2` as the migration won't be executed again
