### ISSUE TITLE
Add more standard blocks

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#376]
For example

* Content
  * Video

* Embed
  * YouTube
  * Twitter
  * Soundcloud
  * Instagram

**Comment by SchipperStash** [comment]
Suggestion: If adding standard blocks, please make them an optional component.

**Comment by stamminator** [comment]
@tidyui In your opinion, where should more advanced blocks (such as the carousel mentioned above) be created if we want them to be reusable? If those should not be contributed to the core project, do you have a preference for where we might submit them?

**Comment by tidyui** [comment]
Good question @stamminator and sorry for being unclear. My intention is to create a new project with a Bootstrap based template with blocks and fields for all components available in bootstrap. I’m even thinking about throwing in an admin view with setting where you for example could install and select child themes for the template. Would this be interesting to collaborate on?
