### ISSUE TITLE
Data Transfer from .db file

### ISSUE THREAD

**Issue by amh2013** [PiranhaCMS/piranha.core#379]
Does anyone know how to transfer the data from .db file to sql server.  I have done the site in the local file. I now wish to use with SQL Server.

**Comment by tidyui** [comment]
Hi there! This is really out of the scope of Piranha, but doing a google search on `migrate sqlite to sql server` I found the following (rather old article):

https://stackoverflow.com/questions/163079/exporting-from-sqlite-to-sql-server

There also seems to be lots of different data migration tools available for this as well to simplify the process, so I guess it all depends on which tools you have available.

Best regards.
