### ISSUE TITLE
Text blocks are not working properly.

### ISSUE THREAD

**Issue by tjscience** [PiranhaCMS/piranha.core#380]
When I add a text block to a page, it does not render. It just shows this:

![image](https://user-images.githubusercontent.com/3706870/45257355-07e72580-b373-11e8-9b77-58a4d5b940eb.png)

**Comment by tidyui** [comment]
Which template are you using, `BasicWeb` or `Blog`? One thing to note is that the templates are only example projects, and the views supplied to render blocks are only provided as an example and not a part of Piranha CMS as a framework.

With that said, all blocks should of course have **ViewTemplates** in the templates... I'll close your issue in this repo and open new issues in the template repos.

Regards
