### ISSUE TITLE
Ability to specify allowed page/post types in PageField and PostField.

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#386]
This originated from #357. Content admins should not see other types.

Ideally, a generic mechanism to supply parameters to fields is preferred.

**Comment by tidyui** [comment]
Beside that this is a tricky one to implement, one of the questions here is **where** should this configuration be stored. In many cases, a Post/Page Type is a structural blueprint of information, not a functional blueprint. For example, the same Page Type could be used to implement both a News Archive **and** a Product Listing (in terms of content). If this is case, does the config really apply to the Page Type or to the current instance of the Page?

**Comment by tidyui** [comment]
I will close this in favor of #1233 which would solve this issue.
