### ISSUE TITLE
Adding information text for a region

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#388]
This refers to the comments in #355. This feature would be helpful to send content editors some instructions on how to edit the specific region, where it's used and so on.

**Comment by tidyui** [comment]
Yes! This will be implemented for `5.2`. It's already fully implemented in the **labs** manager, due for 6.0 release, but I will lift the features over to the current manager. Here's an example Page Type I'm using in the labs project.

    /// <summary>
    /// Test page
    /// </summary>
    [PageType(Title = "Test page")]
    public class TestPage : Page<TestPage>
    {
        public class HeaderRegion
        {
            [Field(Options = FieldOption.HalfWidth, Placeholder = "Mandatory title")]
            public StringField Title { get; set; }

            [Field(Title = "Sub title", Options = FieldOption.HalfWidth, Placeholder = "Optional sub title")]
            public StringField SubTitle { get; set; }

            [Field(Title = "Background image")]
            public ImageField Background { get; set; }

            [Field]
            public HtmlField Body { get; set; }
        }

        [Region(Position = RegionTypePosition.BeforeBody)]
        [RegionDescription("The Header shows an optional Hero banner on the page. If you leave all fields empty the header will be omitted from the current page.")]
        public HeaderRegion Header { get; set; }

        [Region(Title = "Test Region")]
        [RegionDescription("This is the same region as the header but unpinned.")]
        public HeaderRegion TestRegion { get; set; }
    }

And this is how it gets rendered in that manager interface. As regions are presented slightly different in the current manager it won't look exactly like this, but it will be the same concept.

![skarmavbild 2018-09-24 kl 12 51 52](https://user-images.githubusercontent.com/781266/45948526-a53f8c00-bff8-11e8-9b88-9b21fc53964e.png)

Best regards
