### ISSUE TITLE
Question: How Piranha behaves when fields or page types are removed?

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#389]
Just a few questions about Piranha behaviour when the data model is changed:

1) What happens if a page type field, that has some data provided, gets removed form the model? Will there be any crashes? Will the field's data be removed from the DB?
2) Is it perfectly safe to add fields to already existing page types?
3) What happens if a page type that was instantiated gets removed from the model? Same questions as above.

**Comment by tidyui** [comment]
Hi there! See answers below.

1. The field will **remain** in the database **with its stored value** as Content Types are stored as JSON and there's no foreign key on field level. Removing the obsolete data currently requires manual SQL.
2. Yes, adding fields after the page has been created should not be an issue **EXCEPT** if you reuse the name of the property you removed in your first question and use a different type for the property. This would most likely result in a deserialization issue as the data stored in the field won't match the current type.
3. Removed Page Types doesn't get purged automatically **UNLESS** you call `.DeleteOrphans()` on the type builder after importing types. When the Page Type is deleted from the database **ALL** pages implementing that type will be deleted as well as there's no way for the system to deserialize the information.

Best regards

**Comment by tidyui** [comment]
And as you can see in my second answer, **changing Field Type** for an already existing field will most likely give you an exception.

**Comment by mfronczyk** [comment]
Thanks. I'll close this issue and you can always put this information in the wiki if you think it's worth it.
