### ISSUE TITLE
sqlite - 'database is locked'

### ISSUE THREAD

**Issue by benyoungnz** [PiranhaCMS/piranha.core#390]
Hi All, does anyone else here have an issue with the Piranha cms locking? I have an import from external data source script that uses the api heavily, create pages, folders, media objects etc - it *usually* works well but on occasion i get these locks and the service crashes for no apparent reason

Server is on solid state storage, site usage is very low < 20 visits a day

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.

I'm guessing its the import script, it does a  lot of querying to see if pages/folders/media objects exist before creating it, it is only processing one object at a time so to speak i am not spinning off multiple threads to try and speed it up

Any similar experiences here? anything i can do to tweak sqllite 

Alternatively - ive spent a lot of time with various tools trying to generate exports/dumps and get it into a different format even thought i might be able to get it to mysql with a final resting place on SQL but it's a no go.

Ideally i dont want to have to rebuild the schema/site on sql unless someone has a clever tool for migrating site to site with the API

**Comment by tidyui** [comment]
Well I seen this error message before, but I’m not even sure if it was in Piranha or somewhere else. On the other hand, I’ve never used SQLite in a production scenario either. If I remember correctly, SQLite chooses by itself when it flushed the new data to disc, and with as many read operations as with an import my guess is that the file system gets locked at some point. Maybe there’s some kind of option you can execute on the dbcontext that forces SQLite to flush to disc every write operation. 

Best regards 

Håkan

**Comment by tidyui** [comment]
Is this still a problem for you or did you find a solution for it?

**Comment by benyoungnz** [comment]
Hey sorry, i thought i had replied here- There are still issues with this but to be honest i don't think is something with this CMS. It seems every time i get involved with a sqllite database it causes me no end of issues. 

For the most part it all works, with memory caching on / general performance of the site is great, but as soon as any real load goes into writing to the DB these transaction locks appear.

To put it in perspective we might be talking each run of creating, 1-2 new pages, 1-2 new folders and uploading 10-20 images per folder. There are some reads coming of the db at the same time to check if folders etc exist 

I have refined the processing script that injects the data through your API so it handles things a bit better if it falls over / refined portions of the script to make them more efficient such as the checking if things exist is now checked once at the start and if we add new ones then append to this list along the way etc

At some point ill write a migration script to get it off the sqllite and into a proper SQL database

**Comment by tidyui** [comment]
Allright! We have actually discussed putting together a import/export package so that you can easily copy portions, or an entire site from one instance to another. We've been discussing that an interesting approach would be to install an api-module on both instances and then copy data between them using the API's.

Besides using this to migrate data from development to production, it could also be used in cases where customers would want to have a production environment without a manager interface that is totally decoupled from the working instance. Once all changes are made it could be pushed out to the production server.

Anyway, this is only something we've been discussing, so there's currently no timeframe for it.

Regards

**Comment by benyoungnz** [comment]
I would very much +1 that - I had though of a similar approach but just having a quick custom controller to pass data from site 1 > site 2, would have been a 1 one off but having it as a module would  make a lot more sense - as you say great for dev/test > production migrations

**Comment by tidyui** [comment]
Closing this issue.. See #455 for future reference
