### ISSUE TITLE
MarkdownFields not saved on first click

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#392]
There's a bug in the manager interface introduced with the Ajax save of the form causing content in `MarkdownFields` to not be processed on the first Save operation. Relates to #387

**Comment by mfronczyk** [comment]
Just tested it after upgrading to 5.2 and markdown fields are still not saved on the first click. It's actually a serious bug because editors might lose lots of work. Do you see it as well or do you need any help with debugging?

**Comment by tidyui** [comment]
This has been tested and was resolved by adding the following line to the setup of the Markdown editors:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/assets/js/ui.js#L10

Are you sure you've done a "shift reload" of your manager resources so you don't have the old javascript file cached in the browser?

**Comment by mfronczyk** [comment]
Yes, clearing cache helped. 

FYI, asp.net core lets you add version to the asset links (CSS, JS etc) automatically, so when they change, user browser doesn't use the cached version. Can be done like this:

<script src="~/dist/common.js" asp-append-version="true"></script>

By the way, region notes look very good. Thanks for adding it.
