### ISSUE TITLE
24 hour time format?

### ISSUE THREAD

**Issue by PaddySe** [PiranhaCMS/piranha.core#394]
Is there a trick to getting Piranha manager to support 24h time format? When I edit a page and go to settings to change the publish date, and set it to 13:35, as soon as I leave the text field, it will be changed to 01:35.

It's the same with the time picker part of the datepicker. If I change from AM to PM, it's not reflected in the text field.

I think I've located the problem to the ui.js file in Piranha.Manager, but I haven't really learned how to make pull requests in github yet, so I'm hoping someone could help me with this?

The format string for datetimepicker should use capital HH, as in: "YYYY-MM-DD HH:mm", however this will probably present problems for cultures NOT using 24h time format...

**Comment by tidyui** [comment]
Hi there! I’ll try to reproduce it and fix it for the 5.2version that will be released this week! 

Best Regards
