### ISSUE TITLE
Piranha Manager Hyperlink Buttons Width

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#395]
Hello! @tidyui 

Recently I have got to know more about this system and created a project myself. I have been reading the documentation, but since there isn't everything documented (for the newer version), I decided to write an issue here.

As the title says, my problem is with these buttons. Their width (col-sm-3) makes the text (add/remove) go out of the box and it looks ugly. However this is when I use the Half-Width.

When I cloned the solution from github, I was able to change the widths in the manager files. Now I am using just the Blog template and it doesn't have the Manager files, but the thing is that I don't want to include the whole project just for this small change.

Is this a bug, because the Image fields buttons appear normally when the Half-Width option is on?

![2018-10-09 15_22_25-window](https://user-images.githubusercontent.com/32654709/46676157-da8ed100-cbd7-11e8-904a-4107ceaf5df1.png)
![2018-10-09 15_24_38-window](https://user-images.githubusercontent.com/32654709/46676158-da8ed100-cbd7-11e8-9d14-07144064f3be.png)

I think it will be fairly easy to change the widths. Could you add that, please?

Sorry if anything offended you, writing for a first time here and at all in github.

Thank you in advance!

Yours,
Chris

**Comment by tidyui** [comment]
Hi there! Yes the buttons have been changed for the `ImageField` which had the same issue, but it must have been missed for the `PostField` and `PageField`. We'll fix it for the `5.2` release which is due this week!

**Comment by tidyui** [comment]
The fields will be changed to look like this (like the media fields):

<img width="538" alt="skarmavbild 2018-10-09 kl 16 47 25" src="https://user-images.githubusercontent.com/781266/46677526-19765400-cbe3-11e8-85fe-1b020461abb0.png">

Regards

**Comment by tidyui** [comment]
And for the record, if someone is **offended** by you when you report a bug you should consider **NOT** using their project anymore 😂

Regards
