### ISSUE TITLE
Lots of Questions (When you've got time)

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#397]
Hello! @tidyui 

### Important 💯 
**Appreciated**
- Firstly, I just wanted to thank you for the fast response last time (hyperlink buttons). Not that I am abusing this, but I have some questions because I am not really sure how to work out specific things that I am trying to do.

**Documentation**
- Before submitting this issue, I have looked at other issues (open&closed) and did see some useful information, which is not included in the documentation though. Why is that? Not that I am judging you, but until today, I thought the only source of information for Piranha could be found at the Wiki of this repository.

_[The following are connected]_

1. **Migration Error**
Trying to use `MySQL` (or any other database) returns some kind of migration error. I saw a similar issue, but it did not help me.

2. **New Database**
I need to add a `NoSQL` database to my project. I should probably add it in the `Startup.cs` file, but then should I create new controller or model for it?

3. **HTTP Post/Forms/File submission/Ajax**
I need to make an HTTP Post to a database. As I already said, I am using the jQuery plugin for validation, then reCAPTCHA, after which the form is being submitted. That's the part I just cannot figure out. I have watched many tutorials about MVC and ASP.NET, read Microsoft's API, but still not able to make it work.
![2018-10-09 17_48_16-window](https://user-images.githubusercontent.com/32654709/46688565-98748800-cbf5-11e8-9e8f-2accc2b0473c.png)
This is what I've got at the moment. It submits the data, then it shows it as text on a blank page (just to test it). I can use string for name, email and etc. but what do I use for submitting a file? Should I open a FileStream, use Web Client or? I have been trough your files, but the way you do it (asp-for) does not cover my needs. Any help on this? Will be grateful :)

### Less Important

**Manager Access**
- Since it is not included, I wondered how am I able to reach the (localhost)/manager site? Does it get it from Nuget?

**Block Templates**
- `Views/Shared/DisplayTemplates` - What is it for and why is it in that place of the project when you have it on manager view?

**External URL**
- Is there such a field (similar to HtmlField) but allowing you only to put an external URL?

**Validation Scripts**
- Currently I am using `jQuery Validation plugin` for my forms, but I have noticed that there is this file `_ValidationScriptsPartial.cshtml` under the `_Layout.cshtml` and wondered if it could be of any use? Or is is only when you validate the fields through a separate model/controller?

**Image Formats**
- I have manually added image formats. The `.SVG` one is being rendered as a document (which is fine), but I cannot get the dimensions? I don't know much about the vector graphics, just thought I should let you know that the Width/Height columns in the database were empty.

**Not Found**
- Is there another way to have my own "Not found" (Status code: 404) page, **except** using `web.config`? Like including something in the `Startup.cs`?

**GULP**
- I have to compile some `.less` and `.js` files, should I just add the path to every single one of them? You used it only for `.scss` (sass). I know this will increase the performance, but not sure how to do it.

**License**
- I have noticed that on some files you have placed the following comment:
![2018-10-09 17_45_31-window](https://user-images.githubusercontent.com/32654709/46687398-bab8d680-cbf2-11e8-97ff-2a1ecf125647.png)
Is it okay if I remove it? Or at least from my files? Not that familiar with the **MIT** conditions. 

**Unsafe Port**
- Tried to set the application port in launch settings to: `6000`, but it is saying that is unsafe, do you know anything about that? How come you are able to use `5000` but not this one?

**Potential Bug**
- BUG? `Html.DisplayFor(m => m.Blocks)` shows a text block/field as `Piranha.Extend.Fields.TextField` or it displays `&nbsp`.

### Sorry for the long post :(

Thanks in advance again 👍 

Best Regards,
Chris

**Comment by aneff-official** [comment]
EDIT:

For GULP I have found this:
[https://julienrenaux.fr/2014/05/25/introduction-to-gulp-js-with-practical-examples/#Less_Compilation](url)
And for the ports, this:
[https://superuser.com/questions/188058/which-ports-are-considered-unsafe-on-chrome](url)

**Comment by PaddySe** [comment]
I too got an error while the migrations were running on my MySQL database. The error occurs (at least for me) [at this line](https://github.com/PiranhaCMS/piranha.core/blob/5c7e6861d741a39125fce6c702335869f94d39c3/core/Piranha/Migrations/20180531092411_AddMediaVersionExtension.cs#L17).

The problem seems to be that normal quotes (") aren't valid in the MySQL dialect in its default configuration (it uses backticks (`) for this purpose instead), unless you enable the ANSI_QUOTES sql mode in the mysqld.cnf file.

**Comment by aneff-official** [comment]
Thank you again! I will know for future posts now :)

**Migration error**
- The current packages in piranha.core and UseMySQL/SQLServer

For the manager access, I did not say I don't have it. Just wondered how it gets it (Startup). You kinda answered all my questions and I understand for the ones that you can't give support, no worries. 

**Block Templates**
- Well, I have this folder in my project. I use only regions, so my thought is do I really need it after all?

**License**
- I have not included the license comment on my own pages/models, but also I did not touch any source code comments of the type.

**Missing view for TextBlock**
- I think the view was not missing (could be wrong), maybe it is the way it is rendered. You could be calling only the field name, not the actual value

Cheers,
Chris :)

**Comment by tidyui** [comment]
Hi again @aneff-official! 

### Migration error

I can see from @PaddySe comment and #375 that you can get a migration error on MySql, however SqlServer seem highly unlikely since the migrations were created for it and we use it on SQLite & SqlServer almost every day. What version of SqlServer are you running?

### Block Templates

If you only use regions you can remove these `.cshtml` views from your project.

### Missing TextBlock

If you've used the template `dotnet new piranha` I can see there's an issue in that repo (https://github.com/PiranhaCMS/piranha.core.basicweb/issues/6) that the DisplayTemplate is missing. We'll try to fix it for `5.2`

Regards
