### ISSUE TITLE
ImageField data-filter

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#400]
Hi! @tidyui 

**I promise to be quick this time** 👍 

As the title says - I need this `ImageField` to give me the ability to add documents (_svg in my case_). This is why I added this to the `Piranha.Manager/~/ImageField.cshtml`
![2018-10-10 11_24_50-window](https://user-images.githubusercontent.com/32654709/46730677-9c012100-cc80-11e8-9c6d-e6404a7966ae.png)

**Can this be overridden in my project (using blog template)? Maybe in the `Areas/Manager` folder?
Or any other way?**

Thanks in advance

Yours,
Chris

**Comment by tidyui** [comment]
Hi there! Take a look at the docs here https://github.com/PiranhaCMS/piranha.core/wiki/Core-Fields. There already exists `DocumentField`, `ImageField`, `MediaField` and `VideoField` which filters the media library in different ways!
