### ISSUE TITLE
piranha.core Missing Hamburger menu 

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#404]
Is it possible to update piranha.core to include a hamburger menu like in piranha.core.basicweb ?

I'm assuming its a matter of modifying partial menu.cshtml + CSS ?

As a default, it would be nice to have a mobile friendly menu in the piranha.core source.

**Comment by tidyui** [comment]
Hi there! Are you talking about the Example project `CoreWeb` in the repo? If so I think you've already opened an issue on it here :) #302. If it's the same then it hasn't been prioritized as the example in the repo is mainly for testing while developing core functionality. For starting a new project the `templates` will most likely be used.

Regards
