### ISSUE TITLE
Upgrade AspNetCore to the latest version

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#408]
Due to the Denial of Service vulnerability in `Microsoft.AspNetCore 2.1` all packages should be upgraded to the latest version to ensure that applications building on Piranha CMS uses the latest patched versions of the packages.

It is fully possible to upgrade applications to use `Microsoft.AspNetCore.App 2.1.5` and patching the application, but Piranha should **force** users to use the correct versions.

See https://github.com/aspnet/announcements/issues/316 for reference.

**Comment by aatmmr** [comment]
@tidyui will you do the updates for all packages? `piranha-core-mysql` is affected as well. The underlying `Pomelo.EntityFrameworkCore.MySql` package has apparently no reference - I just checked.
