### ISSUE TITLE
Customizable meta-fields?

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#41]
The current verison of Piranha CMS (2.x) has fields for the meta tags `keywords` & `description`. Maybe it would be nice to be able to configurate the meta fields that should be available and have them as a dynamic collection. This could for example configurated like this:

    "SEO" : [
      {
        "Id" : "keywords",
        "Title": "Keywords",
        "Mandatory": false,
        "Max": 128
      },
      {
        "Id": "description",
        "Title": "Description",
        "Mandatory": false,
        "Max": 255
      }
    ]

These fields should also be available when manipulating the model from code, for example:

    var post = api.Posts.GetById(...);

    post.SEO["keywords"] = "Piranha,CMS,Blog,.NET,DotNetCore,MVC";
    post.SEO["description"] = "This is the description for the post";

**Comment by Lucstar** [comment]
Hi Håkan, 
It would be preferable to specify DataAnnotation for validation, in your config if possible. 
https://msdn.microsoft.com/en-us/library/ee256141(VS.100).aspx 

And some config for what UI renderer to use, im thinking of taking ideas from UIHint in Episerver, where you also can build your own dropdowns or whatever... 
http://world.episerver.com/documentation/developer-guides/CMS/Content/Properties/property-attributes/ 

or just the simple one  UIHint("AppSettings")

[UIHint("AppSettings")]
[Display(Name = "Search Engine ChangeFreq")]
public override string SearchEngineChangeFreq { get; set; }

in appsettings: `<add key="SearchEngineChangeFreq" value="always;always|hourly;hourly|daily;daily|weekly;weekly|monthly;monthly|yearly;yearly|never;never" />`

Also would be preferable to have hardcoded properties, maybe use Automapper to change the the post object to your own "CustomPostwithSEO" with inheritance to Post... just brainstorming on the train home. You have probably put a lot of thoughts on this. 

Regards Luc Gosso

**Comment by tidyui** [comment]
Good input on the values configuration for dropdowns, I'll add that for page/block types. The main reason I was thinking about configuring SEO fields on application level and not type level is that I don't really see the point in having different sets of meta keys for different data types, either you support the meta keys or not, but maybe my assumption is wrong about this?

Regards

Håkan

**Comment by tidyui** [comment]
You can see how page types are currently defined here:

https://github.com/PiranhaCMS/piranha.core/wiki/Page-types

/Håkan

**Comment by Lucstar** [comment]
Regarding SEO on applicationlevel: here is my input from experience:

In Episerver CMS it's common to inherit an abstract BaseSearchPage or ISearchPage. For being able to build a proper sitemap.xml as Google wants it, you'll need these properties:

If you don't inherit from this class, you'll output no-index in metatag or does'nt display it in sitemap.xml.

`{
public abstract class BaseSearchIndexable : BasePageModel
    {
        [Display(Name = "Exclude from search indexing",
            Description = "",
            Order = 10000,
            GroupName = "SEO")]
        public override bool ExcludeFromSearch { get; set; }

        [CultureSpecific(true)]
        [Display(Name = "Search Engine Title",
            Description = "",
            Order = 10001,
            GroupName = "SEO")]
        public override string SearchEngineTitle { get; set; }

        [CultureSpecific(true)]
        [Display(Name = "Search engine description",
            Description = "",
            Order = 10002,
            GroupName = "SEO")]
        [UIHint("textarea")]
       public virtual string SearchEngineDescription { get; set; }
        
        [UIHint("AppSettings")]
        [Display(Name = "Search Engine ChangeFreq",
            Description = "",
            Order = 10003,
            GroupName = "SEO")]
        public override string SearchEngineChangeFreq { get; set; }

        [UIHint("AppSettings")]
        [Display(Name = "Search Engine Priority",
            Description = "",
            Order = 10004,
            GroupName = "SEO")]
        public override string SearchEnginePriority { get; set; }

         [CultureSpecific]
        [Display(Name = "Search engine keywords",
            Description = "",
            Order = 10010,
            GroupName = "SEO")]
        public virtual string MetaKeywords { get; set; }

//extra bonusproperty if you somehow have a custom searchengine
         [CultureSpecific]
        [Display(Name = "Include as Best bet",
            Description = "Best bets are custom hits that you can create and display above the organic results list. They are perfect for giving users quick answers to common questions, as well as for messages targeted for specific search terms – your own sponsored links",
            Order = 1000,
            GroupName = "SEO")]
        public virtual bool BestBet { get; set; }
}}`

**Comment by tidyui** [comment]
All of this would actually be doable right now with the current page type support, but with some nicer structure like this:

    public class SEO
    {
      [Field(Title = "Change Freq")]
      public string SearchEngineChangeFreq { get; set; }
      [Field(Title = "Priority")]
      public string SearchEnginePriority { get; set; }
    }

    public abstract class MyPageBase<T> : Page<T> where T : Page<T>
    {
      [Region]
      public SEO SEO { get; set; }
    }

The only thing missing is the **enum** support which I like and will add before the first release!

/Håkan
