### ISSUE TITLE
Not sure how to add a view for a page

### ISSUE THREAD

**Issue by layinka** [PiranhaCMS/piranha.core#410]
Hi,
I am trying to add a new page template.
I created a class i added in the Models folder, and added a route attribute to it to ,to specify the name of the razor view file  Home1.cshtml under the CMS folder).

e.g 

```
[PageType(Title = "Home1 page")]

[PageTypeRoute(Title = "Default", Route = "/home1")] 

public class HomePage : Page<HomePage> 
```

But when i go through  the manager to create a page using this, the page is blank when i preview.

How do i do this?

_P.S i dont know anywhere else to ask this kid of question, if there is, let me know_

**Comment by aneff-official** [comment]
Hello!

I might've misunderstood you, but I think you are missing the fields for the template (if this is the only code used for it). Take a look at these 2 pictures:

![2018-10-17 10_01_27-piranha - microsoft visual studio](https://user-images.githubusercontent.com/32654709/47075170-decc7700-d1f3-11e8-88b2-c200333f4627.png)
![2018-10-17 10_01_53-piranha - microsoft visual studio](https://user-images.githubusercontent.com/32654709/47075171-decc7700-d1f3-11e8-9665-a9728b7dda65.png)

I have added Regions to the model for the template, then I am adding fields to the region (which could be also used by other models).

I am not sure if this is the correct solution, probably the author knows best, but this is how I understand it.

Regards,
Chris

**Comment by layinka** [comment]
Ok, 
Thanks.

But i am not sure if thats it, because here is my complete file

```
[PageType(Title = "Home1 page")]
    [PageTypeRoute(Title = "Default", Route = "/home1")]
    public class HomePage : Page<HomePage>
    {

        



        public class BannerRegion
        {
            [Field]
            public StringField Title { get; set; }
            [Field]
            public ImageField Image { get; set; }
            [Field]
            public TextField Body { get; set; }
        }

        [Region(Title = "Main Content")]
        public MarkdownField Body { get; set; }

        [Region(Title = "Carousel")]
        public IList<BannerRegion> Carousel { get; set; }




        /// <summary>
        /// Gets/sets the page heading.
        /// </summary>
        [Region]
        public Regions.Heading Heading { get; set; }

        /// <summary>
        /// Gets/sets the available teasers.
        /// </summary>
        [Region(ListTitle = "Title")]
        public IList<Regions.Teaser> Teasers { get; set; }

        /// <summary>
        /// Default constructor.
        /// </summary>
        public HomePage() {
            Teasers = new List<Regions.Teaser>();
            Carousel = new List<BannerRegion>();
        }
    }
```

And moreover in the class StandardPage that came with the VS template, they didnt add regions or fields.

I think i just need a way to specify the viewfile to be used. 
Do you know how to do that?

Thats what i thought the **route** was for, if its not , then how do i specify it?

**Comment by aneff-official** [comment]
Hi

Ok. Can you firstly try with more simple thing - comment out everything except the Heading region, so you narrow down the problems. This way you might be able to see if at least that works or not. What is in that file though?

And I think you shouldn't specify the View the way that you want it. In your View (HomePage.cshtml) you should have:

`@model <layinka>.Models.HomePage`

Chris

**Comment by tidyui** [comment]
I think I understand what you're after. You have listed a specific `route` in your Page Type, **but** to handle this route your need an **Action** actually listening to it. The routing of Piranha is just some middleware components passing on the request to Asp.Net Mvc. Make sure you've added an action, like so:

    public class CmsController : Controller
    {
        private readonly Piranha.IApi _api;

        public CmsController(Piranha.IApi api)
        {
            _api = api;
        }

        ...

        [Route("home1")]
        public IActionResult MyHomePage(Guid id)
        {
            return View(_api.Pages.GetById<HomePage>(id));
        }
    }

The action would in this case call the view `MyHomePage.cshtml`.

I hope I understood your question correctly?

Best regards

**Comment by layinka** [comment]
Ok thanks a lot.

Now i get it

**Comment by tidyui** [comment]
Great!

**Comment by RickIsWright** [comment]
I am getting into the game kind of late. Thank you, @tidyui
