### ISSUE TITLE
Is there a hook for after saving a page?

### ISSUE THREAD

**Issue by michaellockwood** [PiranhaCMS/piranha.core#417]
Hi, I've been looking into the hooks but so far have been unable to find a hook for when a page is saved and just wondered if it's something I'm missing or if that feature doesn't exist?

I've tried adding the following in my startup and putting breakpoints in each lambda which does work when I save one of these types:
```
            Piranha.App.Hooks.Alias.RegisterOnAfterSave(model =>
            {

            });

            Piranha.App.Hooks.Category.RegisterOnAfterSave(model =>
            {

            });

            Piranha.App.Hooks.Media.RegisterOnAfterSave(model =>
            {

            });

            Piranha.App.Hooks.MediaFolder.RegisterOnAfterSave(model =>
            {

            });

            Piranha.App.Hooks.Param.RegisterOnAfterSave(model =>
            {

            });

            Piranha.App.Hooks.Site.RegisterOnAfterSave(model =>
            {

            });

            Piranha.App.Hooks.Tag.RegisterOnAfterSave(model =>
            {

            });
```

**Comment by tidyui** [comment]
No you're right, only hooks for the **simple** content models were finished and the others were forgotten over time. I'll add an issue for it for the `5.3` version.
