### ISSUE TITLE
Restore packages failed on site created from piranha project template 

### ISSUE THREAD

**Issue by rashan** [PiranhaCMS/piranha.core#426]
I try to create a new site from the piranha project template but found package restore failed with errors "...error NU1108: Cycle detected."
"...error NU1108:   Piranha -> Piranha (>= 5.2.1)"

- OS : Mac Mojave 10.14.1

<img width="687" alt="screen shot 2018-11-02 at 6 55 13 pm" src="https://user-images.githubusercontent.com/1784589/47918370-65f73b80-ded2-11e8-928b-182b5e8f35d5.png">

**Comment by tidyui** [comment]
This has to do with NuGet. You can’t restore a package to a project with the same name as it thinks you are restoring the project itself, hence the circular ref 😁

Start over with a different project name and you’ll be fine!

Regards
