### ISSUE TITLE
ApplicationService has empty/default data when accessing from non-CMS-routed page

### ISSUE THREAD

**Issue by stamminator** [PiranhaCMS/piranha.core#427]
I am using Piranha as the CMS for a pre-existing site (I used https://github.com/PiranhaCMS/piranha.core.examples as a seed for implementing it — thanks for making that!). On custom pages served through my own routing rather than the `CmsController`'s routes, trying to use `Piranha.AspNetCore.Services.ApplicationService` does not work properly. The data its properties contain does not accurately reflect the data in the CMS. For instance, my Piranha database contains a blog archive with three blog posts, but the `Api` property of the app service is null.

![image](https://user-images.githubusercontent.com/10633170/47971640-77bb1900-e061-11e8-92f2-af8b67057b40.png)

I believe the service is properly configured in `Startup.cs` and my `_ViewImports.cs` is correct. Would you mind taking a look at my repo and seeing what I'm doing wrong? My goal is to have a "latest post" section on my Index.cshtml home page that displays some info about the most recently added blog post. Here's the link to the private repo, which I've just added you as a collaborator on: https://github.com/stamminator/hps-core

**Comment by tidyui** [comment]
Does accessing a blog post directly work as expected or does this throw the same exception?

**Comment by stamminator** [comment]
Blog access routed through `CmsController` works fine. For instance, my blog archive is simply called "Blog", and the `/blog` URL works correctly, as well as any blog posts within it.

**Comment by tidyui** [comment]
Btw, before I have time to get to the bottom of this, try injecting an IApi directly instead! That should do the trick!

Regards

**Comment by stamminator** [comment]
That works! For now, I will inject `Piraha.IApi` directly. Thanks.

**Comment by tidyui** [comment]
That’s no problem! I can probably reproduce it in a isolated project, and if I can’t you can look at mine to compare!
