### ISSUE TITLE
Save drafts and then publish drafts on a set date

### ISSUE THREAD

**Issue by MCNorthwood** [PiranhaCMS/piranha.core#428]
The earlier version of Piranha had the ability to save drafts and then publish it. From an already published page.
Essentially creating a replica of the page that can be edited without having to update right there and then. Having that added again would be a useful tool, especially with the new preview working as it is now and to save a draft of a published page and having the ability to view it in all screen sizes.

**Comment by tidyui** [comment]
Yes, this is a part of issue #289 which mean to handle both unpublished revisions and history revisions of previous versions. We started working on it for `5.3` but decided to postpone it for `6.0` as it will take a lot of work in the manager to really make the feature simple and intuitive.
