### ISSUE TITLE
SAML 2.0 Authentication support - Feature REquest

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#429]
Add support for SAML 2.0 (Azure Active Directory) user authentication ? 
The ability to only allow authenticated users to view content.

https://github.com/jitbit/AspNetSaml

Is a pretty simple / clean way SAML 2.0 implementation.

**Comment by tidyui** [comment]
If you want to limit access for the entire site, can’t you just authenticate on the controllers? If it’s for specific pages maybe it can be done with a filter?

**Comment by CastleSoft** [comment]
I was thinking of creating a new Authenticated Page type or extending existing pages to include "Authentication Require" as an option. 
Then on the view/controller/filter ? To enforce pages with the "Authentication" flag enabled.
Are you planing on allowing authentication required to view pages ?

**Comment by tidyui** [comment]
Yes that feature was present in the old version of Piranha, but in that version we controlled the auth mechanism. In the current version we have no idea of users, how they can authenticated or authorized so it’s a bit trickier.

**Comment by CastleSoft** [comment]
Sorry.. Been off the radar for a bit..
Awesome.. Thank you.

**Comment by tidyui** [comment]
This has been implemented a couple of versions back. Closing the issue
