### ISSUE TITLE
Manager redirect

### ISSUE THREAD

**Issue by mpjones84** [PiranhaCMS/piranha.core#432]
This might be user error, but I cannot seem to log in on the manager screen.  Ive created the following start up, but it appears to redirect to the login page.
Is this an issue, or have I configured it incorrectly?

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Protocols;
using Piranha;
using Piranha.AspNetCore.Identity.SQLServer;
using Piranha.Local;

namespace xx
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<IApi, Api>();
            services.AddMvc(config =>
            {
                config.ModelBinderProviders.Insert(0, new Piranha.Manager.Binders.AbstractModelBinderProvider());
            });
            string conString = Configuration.GetConnectionString("XXX");
            services.AddPiranhaApplication();
            services.AddPiranhaFileStorage();
            services.AddAuthorization();
            services.AddPiranhaEF(options => options.UseSqlServer(conString));
            services.AddPiranhaIdentityWithSeed<IdentitySQLServerDb>(options => options.UseSqlServer(conString));
            services.AddPiranhaManager();
            //services.AddPiranhaMemCache();
            services.AddPiranhaSimpleSecurity(
                new Piranha.AspNetCore.SimpleUser(Piranha.Manager.Permission.All())
                {
                    UserName = "xxx@xxx.xx",
                    Password = "xxxxx"
                },
                new Piranha.AspNetCore.SimpleUser(Piranha.Manager.Permission.All())
                {
                    UserName = "xx@xxxx",
                    Password = "xxx"
                },
                new Piranha.AspNetCore.SimpleUser(Piranha.Manager.Permission.All())
                {
                    UserName = "xx@xxx",
                    Password = "xxxx"
                }
            );

            return services.BuildServiceProvider();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider services)
        {
            var api = services.GetService<IApi>();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            App.Init();

            // Configure cache level
            App.CacheLevel = Piranha.Cache.CacheLevel.Basic;

            var pageTypeBuilder = new Piranha.AttributeBuilder.PageTypeBuilder(api)
            .AddType(typeof(Models.OpportunityPage))
            .AddType(typeof(Models.StandardPage))
            .AddType(typeof(Models.StartPage))
            .AddType(typeof(Models.RegisterPage))
            .AddType(typeof(Models.ContactPage));
            pageTypeBuilder.Build()
                .DeleteOrphans();

          

            if (env.IsEnvironment("Debug"))
            {
                app.UseForwardedHeaders(new ForwardedHeadersOptions
                {
                    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
                });
            }

            // Register middleware
            app.Use(async (ctx, next) =>
            {
                await next();

                if (ctx.Response.StatusCode == 404 && !ctx.Response.HasStarted)
                {
                    //Re-execute the request so the user gets the error page

                    string originalPath = ctx.Request.Path.Value;
                    ctx.Items["originalPath"] = originalPath;
                    ctx.Request.Path = "/home/PageNotFound";
                    await next();
                }
            });

            app.UseStaticFiles();
            app.UsePiranhaSimpleSecurity();
            app.UsePiranha();
            app.UsePiranhaManager();
            app.UseMvc(routes => 
            {
                routes.MapRoute(name: "areaRoute",
                    template: "{area:exists}/{controller}/{action}/{id?}",
                    defaults: new { controller = "Home", action = "Index" });

                routes.MapRoute(
                    name: "default",
                    template: "{controller=home}/{action=index}/{id?}");
            });
        }
    }
}

**Comment by mpjones84** [comment]
Hi.  Thank you for your help, I did wonder about that.  But removing IdentityWithSeed results in the following exeption.

InvalidOperationException: The AuthorizationPolicy named: 'PiranhaRoles' was not found.

**Comment by mpjones84** [comment]
Does anyone know what is expected for services.AddPiranhaIdentityWithSeed.  I am happy to use that over SimpleSecurity.

**Comment by tidyui** [comment]
You get that error because you are still referencing the NuGet package `Piranha.AspNetCore.Identity.SQLServer`. The package contains manager views & controllers for administrating users & roles which need the policy you get the error message about, however when you remove the `AddPiranhaIdentityWithSeed` these policies doesn't get added.

If you want to use AspNet Identity I suggest you remove the following lines from your startup instead.

        services.AddPiranhaSimpleSecurity(
            new Piranha.AspNetCore.SimpleUser(Piranha.Manager.Permission.All())
            {
                UserName = "xxx@xxx.xx",
                Password = "xxxxx"
            },
            new Piranha.AspNetCore.SimpleUser(Piranha.Manager.Permission.All())
            {
                UserName = "xx@xxxx",
                Password = "xxx"
            },
            new Piranha.AspNetCore.SimpleUser(Piranha.Manager.Permission.All())
            {
                UserName = "xx@xxx",
                Password = "xxxx"
            }
        );

Regards

**Comment by mpjones84** [comment]
Perfect, thank you for the quick responses guy.
