### ISSUE TITLE
Is it possible extending entities?

### ISSUE THREAD

**Issue by jromerus** [PiranhaCMS/piranha.core#438]
The legacy version has documented the possibility to [extend entities](http://legacy.piranhacms.org/docs/extend/custom-entities). Is it enabled in core version? This is a very interesting feature because would allow using piranha as a base framework to develop applications with cms embedded.

Regards,
José Enrique

**Comment by tidyui** [comment]
Hi there! The concept is exactly the same in the new version, we're just working on the new documentation. The base concept is the same for both versions which is **create your own DbContext** and **never** inherit the DbContext provided by Piranha. This would complicate migrating to a newer version later on.

A good example on how do to this is to take a look at the project `Piranha.AspNetCore.Identity` which adds its own DbContext with **users**, **roles** and so on, registers itself as a **module**, adds custom **policies**, **admin views** and injects itself into the **manager menu**.

https://github.com/PiranhaCMS/piranha.core/tree/master/core/Piranha.AspNetCore.Identity

Here are some documentation links you will find interesting on extending the manager UI.

### Adding custom css/js resources to the manager
http://piranhacms.org/docs/manager-extensions/custom-resources

### Extending the manager menu
http://piranhacms.org/docs/manager-extensions/manager-menu

You can also add custom partials into the manager (modals and so on) however there's currently no documentation written on it.

    using Piranha;

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        ...

        App.Modules.Get<Piranha.Manager.Module>()
            .Partials.Add("Partials/_MyModal");
        ...
    }

One of the main ideas behind Piranha is to be able to use it like you describe, so if you find anything limiting with the design, make sure you let us know so we can improve.

Best regards

**Comment by tidyui** [comment]
We will try to create a project template for creating a Piranha Module as there are certain aspects that could be nicely packaged.

**Comment by jromerus** [comment]
Hi Hakan, sounds great! I really some prospect in order to evaluate what is most interesting to me, implement the application inside piranha with extensions or embedding cms inside the application using piranha API. The problem with the first approach is that my model is implemented with another orm (xpo), an the problem with the second is that I had to learn how lo render piranha content calling the API (if possible).

Thanks!

**Comment by vector-man** [comment]
@tidyui is there any document now for this feature?

**Comment by tidyui** [comment]
There is a template for creating a module.

~~~
dotnet new piranha.module
~~~

**Comment by barcollin** [comment]
Are the any tutorials that shows how to extend user class and implement the identity module. I tried for some reason my column are not found and doing migrations seems very complicated on this project
