### ISSUE TITLE
Page Preview doesn't work for non-default site

### ISSUE THREAD

**Issue by steelspace** [PiranhaCMS/piranha.core#440]
Page preview looks empty for pages that are not in default site.

**Comment by steelspace** [comment]
#437 #425

**Comment by steelspace** [comment]
Oh, it seems the host name must be set for all sites, even the default one.

**Comment by tidyui** [comment]
Yes, if you want to route multiple sites to the same hostname but use an "url prefix" as identifier, all sites must have a hostname set!

Regards
