### ISSUE TITLE
Page link dialog doesn't show any pages (postgres)

### ISSUE THREAD

**Issue by steelspace** [PiranhaCMS/piranha.core#443]
When trying to add a Page Link in Manager, the modal dialog doesn't display any page to select from. It works with Sqlite but not with EF Postgres provider.

**Comment by tidyui** [comment]
All queries in Piranha is implemented in **Linq** using **Entity Framework**, if there's a problem with certain queries for certain database providers the issue lies within EF and we can't really give support on it.

**Comment by tidyui** [comment]
An idea is always to check with @alperencaliskan who I know is using PostgreSql with Piranha.
