### ISSUE TITLE
Both #444 and #443 are failing - not related to the db provider. 

### ISSUE THREAD

**Issue by steelspace** [PiranhaCMS/piranha.core#445]
Both #444 and #443 are also failing with MySQL provider. (Pomelo)
I am currently testing Piranha as a CMS for a small business customer. I can help with testing and even contributing if possible.

**Comment by steelspace** [comment]
So - this is not related to the database provider. Actually I had two environments with different databases.
The problems described above appears only on newly created instance, so there is only 1 site. Once I added another site, both problems were gone.

**Comment by tidyui** [comment]
I just tested both the above cases in the newly created site as the `TeaserRegion` included in the Template has a `PageField` property and it also works for SQLite. Did this by

* Opening the start page (Home)
* Selecting a word in the first block and linking to the Blog archive page
* Selecting the Teasers region, expanding the first item and opening the page link dialog

If you reproduce these steps @steelspace are you getting database related errors?

**Comment by steelspace** [comment]
This is related to the PageField on the model. This [+] open modal empty modal dialog. With 2 sites I was able to choose (in combo box) the site and then it displayed site's pages. The combo was initially unset.

**Comment by tidyui** [comment]
And if you then delete the extra site @steelspace so you end with one site again. Is everything working like it should?

**Comment by steelspace** [comment]
I am now going to test it locally - there is an error in
```
NullReferenceException: Object reference not set to an instance of an object.
Piranha.Areas.Manager.Models.AliasListModel.Get(IApi api, Nullable<Guid> siteId)
Piranha.Areas.Manager.Controllers.AliasController.List(Nullable<Guid> siteId)
lambda_method(Closure , object , object[] )
```

**Comment by tidyui** [comment]
This is the **only** line in the specified method that can throw a NullPointerException:

https://github.com/PiranhaCMS/piranha.core/blob/version/v5.2/core/Piranha.Manager/Areas/Manager/Models/AliasListModel.cs#L68

And it can only throw an exception in one of these two cases.

1. The site id passed into the method is incorrect
2. There's no site in the database that has `IsDefault` **true**

The first case should not happen through the manager interface, the second case should not happen if Piranha has seeded the database with default data as the created site has `IsDefault` set.

**Comment by steelspace** [comment]
The issue was fixed when I turned on "default site" for one site and then back to the previous one. Let's close the issue and I will continue reporting when I find something.
