### ISSUE TITLE
Multisite scenario does not work for same domain with /XYZ distinguishing

### ISSUE THREAD

**Issue by steelspace** [PiranhaCMS/piranha.core#448]
Multisite works in case there is a different domain name but it doesn't work if it is the same and the distinguishing hostname part is provided by URL.

Steps to reproduce:
1. Create two sites with hostnames - xyz.com/en, xyz.com/de
2. All permalinks are missing /en or /de part
---
Looking in the code - permalink generation only uses slug and/or parent information but not hostname.

**Comment by tidyui** [comment]
Duplicate of #437
