### ISSUE TITLE
Tools for data transfer

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#455]
It would be very useful with tools to transfer data from one database to another, for example migrating content from a development environment to a production server, or completely working in an internal version and then pushing changes to a live site.

**Comment by stefanolsen** [comment]
I have experience from other CMS platforms that have this feature.
You basically export pages, posts and media files to a Zip file from the manager in one environment. Then you go to the manager in another environment and import said file.
This solution will work across different blob and database providers, but as a manual process.
Besides supporting a Piranha XML transfer format, I guess the content importer could also be able to support other formats (e.g. Wordpress or Umbraco) by implementing a `IContentImporter` interface.
