### ISSUE TITLE
i can't write slug persian 

### ISSUE THREAD

**Issue by ramin149** [PiranhaCMS/piranha.core#457]
if field **slug** equilts "تخت-جمشید-شیراز" in page edit/new post and submit form . show message success to me but current page refresh field **slug**  in empty . not insert to database .

**Comment by tidyui** [comment]
Hi there! The default slug generation () only handles western characters. To generate slugs for Persian you will need to register your own slug generation in `Configure()` in `Startup.cs` like 

    App.Hooks.OnGenerateSlug += (str) => {
        var slug = "";

        // Generate slug from title

        return slug;
    };

Best regards
