### ISSUE TITLE
Route of custom page and post types not persisted

### ISSUE THREAD

**Issue by 79it** [PiranhaCMS/piranha.core#465]
I have created a new page archive and post type with route of /galleryarchive and /gallerypost.

When saving both types the route is not persisted to the database causing the default page and post types to be used (which in turns causes an error because the models don't match).
I don't know if I've set it up incorrectly because in the Piranha_Pages and Piranha_Posts tables everything else is appears to be saved apart from the route (which is null).

My GalleryArchive model (based on BlogArchive):

````
namespace Websites.Models
{
    using Piranha.AttributeBuilder;
    using Piranha.Models;

    using Websites.Models.Regions;

    [PageType(Title = "Gallery Archive", UseBlocks = false)]
    [PageTypeRoute(Title = "Gallery Archive", Route = "/galleryarchive")]
    public class GalleryArchive : ArchivePage<GalleryArchive>
    {
        [Region]
        public Hero Hero { get; set; }
    }
}
`````

Running with the website using the latest source code in the master branch I can see that in PageEditService, when calling ````api.Pages.GetById(id)```` the route information is returned correctly.

The route does not appear to be used in the editor.

When saving, again the ````api.Pages.GetById(id)```` has the Route correctly but ````model```` (passed in from the controller) has null for the Route property.

When the AutoMapping is run the Route in ````page```` in updated to be null and this is then persisted to the database

For now I'm working around this issue by running this before the mapping runs in in the Save method in PageEditService:
 ````model.Route = page.Route;```` 
and something similar in PostEditService.

Have I set my models up wrong or have I found a bug?

Thanks

Chris

**Comment by tidyui** [comment]
Hi there! This is actually as intended. The route is **not saved** on content **if**.

1. There is no custom route defined on the page type
2. There is only **one** custom route defined on the page type

Only when you have several routes available will the selected route be stored in the database. Like you've noticed, the route is mapped when the model is transformed in the `ContentService`.

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha/Services/ContentService.cs#L284

Best regards!!

Håkan

**Comment by 79it** [comment]
Hi Håkan,

That makes sense that no route is saved in these scenarios but it doesn't solve the issue of the wrong route being used.

I'm using Razor Pages and without the route being saved in the database instead of galleryarchive.cshtml and gallerypost.cshtml it is using archive.cshtml and post.cshtml.

Thanks

Chris

**Comment by 79it** [comment]
This is quite bizarre - I tried setting a duplicate PageTypeRoute attribute to force the route to be saved and then removed it to try debugging through ```ContentService````.

I can't replicate the problem now so happy to close the issue.

If it occurs again at least I know I have a more reasonable workaround by creating a duplicate PageTypeRoute attribute.

Thanks

Chris

**Comment by tidyui** [comment]
Let me know if you're able to reproduce it later on, I'll see if can reproduce the behavior on my end 👍

/Håkan

**Comment by 79it** [comment]
My code is based on the RazorWeb example you linked to - if I can replicate it again I'll create a sample project that I'll share with you.

Thanks

Chris
