### ISSUE TITLE
Hidden page is visible in menu and sitemap

### ISSUE THREAD

**Issue by joakimmag** [PiranhaCMS/piranha.core#481]
Hi. Great work on the project.

I marked a page as hidden:

![bilde](https://user-images.githubusercontent.com/28116634/50856629-7cff5180-138b-11e9-9adc-c567049ea59d.png)

But the page is still visible.

In navigation:

![bilde](https://user-images.githubusercontent.com/28116634/50856663-94d6d580-138b-11e9-8a24-dd23cd652b88.png)

And in sitemap.xml:

![bilde](https://user-images.githubusercontent.com/28116634/50856684-9f916a80-138b-11e9-83e3-c5ac1a56c2e8.png)

**Comment by tidyui** [comment]
I'm not sure this is a bug, rather unclear of how it's used. **Yes**, the hidden pages are included in the sitemap **but** the item is marked with `IsHidden=true` so you can exclude them from your view. To make it more clear we could exclude them from the sitemap by default and have parameter to include them (with the current `IsHidden` flag).

The second one is a bit trickier, are we 100% sure that pages that are not shown visually (for example I frequently use `IsHidden=true` for the Startpage as I don't want to render it in the menu) shouldn't be accessible in the sitemap.
