### ISSUE TITLE
Default values for field

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#486]
I want to create a new field (checkbox) for all my pages and to be able to disable something. but the field content shouldn't be "disable", thats why i need a default value. Is this possible?

I tried with

[Field(Title = "Feature Enabled", Options = Piranha.Models.FieldOption.HalfWidth)]
public Piranha.Extend.Fields.CheckBoxField Enabled { get; set; } = true;

Any suggestion or do i need to introduce the negative field like "disable"?

**Comment by tidyui** [comment]
Since the `Create()` method 

1. Creates the model
2. Creates all fields for the model

we would need to introduce a `DefaultValue` properties on the `FieldAttribute`

**Comment by pauldbentley** [comment]
I also have the same requirement so this would be useful.

**Comment by tidyui** [comment]
Closing this in favor of #1233 which would enable this functionality.
