### ISSUE TITLE
Portal navigation problem

### ISSUE THREAD

**Issue by Molot12** [PiranhaCMS/piranha.core#490]
If create new page with cyrillic title - navigation not work.

**Comment by tidyui** [comment]
Hi there! The default slug generation is fairly limited in what characters it can translate. For more info, check out the response to #457.

**Comment by Molot12** [comment]
Solution for cyrillic:

`App.Hooks.OnGenerateSlug += (str) => {
                              
                var slug = str.Trim().ToLower();
                bool hierarchical = true;

                // Convert culture specific characters
                slug = slug
                    .Replace("å", "a")
                    .Replace("ä", "a")
                    .Replace("á", "a")
                    .Replace("à", "a")
                    .Replace("ö", "o")
                    .Replace("ó", "o")
                    .Replace("ò", "o")
                    .Replace("é", "e")
                    .Replace("è", "e")
                    .Replace("í", "i")
                    .Replace("ì", "i");

                string[] lat_up = {"A", "B", "V", "G", "D", "E", "Yo", "Zh", "Z", "I", "Y", "K", "L", "M", "N", "O", "P", "R", "S", "T", "U", "F", "Kh", "Ts", "Ch", "Sh", "Shch", "\"", "Y", "'", "E", "Yu", "Ya"};
                string[] lat_low = {"a", "b", "v", "g", "d", "e", "yo", "zh", "z", "i", "y", "k", "l", "m", "n", "o", "p", "r", "s", "t", "u", "f", "kh", "ts", "ch", "sh", "shch", "\"", "y", "'", "e", "yu", "ya"};
                string[] rus_up = {"А", "Б", "В", "Г", "Д", "Е", "Ё", "Ж", "З", "И", "Й", "К", "Л", "М", "Н", "О", "П", "Р", "С", "Т", "У", "Ф", "Х", "Ц", "Ч", "Ш", "Щ", "Ъ", "Ы", "Ь", "Э", "Ю", "Я"};
                string[] rus_low = { "а", "б", "в", "г", "д", "е", "ё", "ж", "з", "и", "й", "к", "л", "м", "н", "о", "п", "р", "с", "т", "у", "ф", "х", "ц", "ч", "ш", "щ", "ъ", "ы", "ь", "э", "ю", "я"};
                
                for (int i = 0; i <= 32; i++)
                {
                    slug = slug.Replace(rus_up[i],lat_up[i]);
                    slug = slug.Replace(rus_low[i],lat_low[i]);
                }
                
                // Remove special characters
                slug = Regex.Replace(slug, @"[^a-z0-9-/ ]", "").Replace("--", "-");

                // Remove whitespaces
                slug = Regex.Replace(slug.Replace("-", " "), @"\s+", " ").Replace(" ", "-");

                // Remove slash if non-hierarchical
                if (!hierarchical)
                    slug = slug.Replace("/", "-");

                // Remove multiple dashes
                slug = Regex.Replace(slug, @"[-]+", "-");

                // Remove leading & trailing dashes
                if (slug.EndsWith("-"))
                    slug = slug.Substring(0, slug.LastIndexOf("-"));
                if (slug.StartsWith("-"))
                    slug = slug.Substring(Math.Min(slug.IndexOf("-") + 1, slug.Length));
                return slug;
            };`
