### ISSUE TITLE
Get latest blog posts of certain page by slug or id as JSON

### ISSUE THREAD

**Issue by clientwestwood** [PiranhaCMS/piranha.core#494]
Trying to get latest blog posts of certain page by slug or id as JSON.

Have anybody succeed doing it?

I am not an advanced dotnet player so please detailed answers are much appreciated.

**Comment by tidyui** [comment]
To return the data as JSON you should add an `ApiController` and return the data from there!

**Comment by clientwestwood** [comment]
Would you elaborate a little bit more?
Thank you for your fast feedback.
