### ISSUE TITLE
ApiController usage in request Pipeline 

### ISSUE THREAD

**Issue by nhaberl** [PiranhaCMS/piranha.core#495]
Hi, 

Just wanted to know if it's possible to use ApiController also.
So I can integrate a seamless Rest API into my website in the same context all the other stuff renders, like routes 

I hope anybody understands what I mean!?

**Comment by tidyui** [comment]
Yes! Piranha is in fact only a couple of middleware components, after that you can run anything you like, MVC, WebApi, Razor Pages and probably everything else that runs on the asp.net core stack!

**Comment by nhaberl** [comment]
Is there any sample maybe? I know what you mean but how can I use the piranha security context for example? 08:09, 31. Jänner 2019, "Håkan Edling" <notifications@github.com>:Closed #495.
