### ISSUE TITLE
Move post from one archive to another

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#499]
Is there an easy way to move one post from one archive to another? I want to split one archive because after some time it handles to many topic and the idea was to create a second archive, but i do not want to copy / paste afterthing by hand.

**Comment by tidyui** [comment]
Moving post from one archive to another is just a matter of changing the field `BlogId` of the post which is `foreign key` to the Id of the Archive Page containing it. However, as **categories** and **tags** are unique per Archive you would need to remap these to taxonomies available in the new Archive. 

Without having tried it, with any luck the categories & tags will be created in the new archive if you just load the moved posts and save them again, like so :)

    var posts = api.Posts.GetAll(blogId);
    foreach (var post in posts)
    {
        api.Posts.Save(post);
    }

Like I wrote, as I haven't actually tried doing it a backup of your database is in order before you get started ;)
