### ISSUE TITLE
Management UI

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#5]
Create Web manager interface for creating and maintaining the CMS data. This MVC application should be put in its own project and the interface should be based on the common standards of `bootstrap` & `jQuery`

**Comment by TheWolfA2** [comment]
Small personal suggestion; font awesome icons would be nice to use for any UI elements.

**Comment by tidyui** [comment]
That's absolutely an option. I tend to use the basic icons from bootstrap during development and then leave the final decision to my UI/UX specialist @NJepop :)
