### ISSUE TITLE
Category fields like

### ISSUE THREAD

**Issue by vdecristofaro** [PiranhaCMS/piranha.core#500]
Hi 

Which is the best option to define a category like field?
Let's say for example that I need to track a "Section"  and a "SubSection" field for a post. Those fields should be selected from a dropdown when adding a post.

I have then created two custom posts, Section and SubSection and added those as fields into the main Post object. However this way when I am searching posts by Section or Subsection it takes really long time.

Is this the right way to achieve this type of design?

**Comment by vdecristofaro** [comment]
From a strictly technical point of view category and tags are exactly what I need. However I did'nt understood how to:
1. use a category for Section and another one for Subsection
2. Pre-build categories so they can be choosen from a dropdown

> Have you added two PostField properties to your posts pointing towards some special posts that are used to define structure within the archive?

Yes exactly.

**Comment by tidyui** [comment]
Both **categories** and **tags** are "self-cleaning" in the way the only used taxonomies are kept. Also they are only intended to be used by the actual editor when writing the content. I would create two custom fields for structuring your posts, like this:

**Fields**

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.Extensions.Configuration;
    using Piranha.Extend;
    using Piranha.Extend.Fields;

    public abstract class StructureField : SimpleField<string>
    {
        protected string _configParam = "";
        public IEnumerable<string> Alternatives { get; set; }

        protected StructureField(string configParam)
        {
            _configParam = configParam;
        }

        public void Init(IConfiguration config)
        {
            var alternatives = config.GetValue<string>(_configParam);

            // Get the current alternatives from config
            if (!string.IsNullOrEmpty(alternatives))
            {
                Alternatives = alternatives.Split(",");
            }

            // Check so our current alternatives hasn't been deleted.
            if (!Alternatives.Contains(Value))
            {
                Value = null;
            }
        }
    }

    [FieldType(Name = "Section")]
    public class SectionField : StructureField
    {
        public SectionField() : base("sections") { }
    }

    [FieldType(Name = "Section")]
    public class SubSectionField : StructureField
    {
        public SubSectionField() : base("subsections") { }
    }

This way you could make the available sections & subsections configurable in your `appsettings.json` like so:

**appsettings.json**

    {
        "sections": "starters,main courses,deserts",
        "subsections": "pasta,poultry,meat,fish"
    }

Here's a simple example on how the `EditorTemplates` could look:

**SectionField.cshtml**

    @model SectionField

    <select name="@Html.ViewData.TemplateInfo.GetFullHtmlFieldName("Value")" class="form-control small">
        <option @(string.IsNullOrEmpty(Model.Value) ? "selected=selected" : "")></option>
        @foreach (var alternative in Model.Alternatives)
        {
            <option value="@alternative" @(Model.Value == alternative ? "selected=selected" : "")>@alternative</option>
        }
    </select>

**SubSectionField.cs**

    @model SubSectionField

    <select name="@Html.ViewData.TemplateInfo.GetFullHtmlFieldName("Value")" class="form-control small">
        <option @(string.IsNullOrEmpty(Model.Value) ? "selected=selected" : "")></option>
        @foreach (var alternative in Model.Alternatives)
        {
            <option value="@alternative" @(Model.Value == alternative ? "selected=selected" : "")>@alternative</option>
        }
    </select>

You then register the fields in `ConfigureServices` and tell the value to be serialized as a string so it's easy to query.

    App.Fields.Register<SectionField>();
    App.Fields.Register<SubSectionField>();
    App.Serializers.Register<SectionField>(new 
        Piranha.Extend.Serializers.StringFieldSerializer<SectionField>());
    App.Serializers.Register<SubSectionField>(new 
        Piranha.Extend.Serializers.StringFieldSerializer<SubSectionField>());

Now **how** you should query and retrieve the data is totally dependent on how cache is set up (or will be set up) for you application. If you for example will be using **Full Cache** it will be very easy to create a performant query.

**Comment by vdecristofaro** [comment]
Actually the one you've suggested was exactly my first experiment. 
However when I try to read posts by section it take a very long time to answer (e.g. 3 seconds to read from a total archives of 3 posts)

This is the code I am using to read

```
[Route( "archives/news/{sectionId}" )]
public IActionResult NewsArchive( string section ) {
    var news = api.Posts
                            .GetAll<NewsPost>()
                            .Where( x => x.Region.Section.Value == sectionId && x.Published.HasValue );
            return View( "NewsList", news );
}

```

Thanks for your prompt help 😃

**Comment by tidyui** [comment]
When you call `api.Posts.GetAll<NewsPost>` **all** NewsPosts will be fetched from the database and transformed into models and **after** that you will perform your Linq query in memory, this of course isn't that effective. Instead perform the query directly on the `IDb` db context.

    var posts = _db.Posts
        .Where(p => p.PostTypeId == "NewsPost" && 
            p.Fields.Any(f => f.FieldId == "Section" && f.Value == section))
        .Select(p => p.Id);

    var news = new List<NewsPost>();
    foreach (var postId in posts)
    {
        news.Add(_api.Posts.GetById<NewsPost>(postId));
    }
    return View("NewsList", news);

Given that you're using **FULL** cache, the call to `api.Posts.GetById` will retrieve the posts from cache and not generate a roundtrip to the database per post. If you can't use full cache (maybe because you have LOT'S of data), please let me know as there are other more advanced ways to achieve the same result.

**Comment by vdecristofaro** [comment]
great! Thank you for everything 👍
