### ISSUE TITLE
Page cache set in config but does not apply to all pages

### ISSUE THREAD

**Issue by MCNorthwood** [PiranhaCMS/piranha.core#501]
Some pages don't add the cache and store to every page, doesn't seem to be any particular reason why it doesn't add it.

Is there perhaps something else that needs to be set perhaps in the project or on the pagetype? When I'm looking through the site it seems to be fine with the posts but just the odd page will not have it set.

**Comment by tidyui** [comment]
Hi there! Can you elaborate a bit, which cache are you talking about? Are you talking about the internal model cache used by the `Api` when loading models or are you referring to the HTTP Cache headers set when retrieving the pages with the browser?

**Comment by MCNorthwood** [comment]
It's the Http Cache headers

**Comment by MCNorthwood** [comment]
Indeed they have normal page types, including the startpage

**Comment by tidyui** [comment]
I sent you a response to your email!

**Comment by MCNorthwood** [comment]
I saw thank you, thanks for your help

**Comment by tidyui** [comment]
I’m closing this issue as it was not related to Piranha.
