### ISSUE TITLE
SelectField crashes 

### ISSUE THREAD

**Issue by clientwestwood** [PiranhaCMS/piranha.core#504]
Hi there,

Created a custom block with a SelectField input.
It successfully render on manager and able to save the page, but after the save both admin and frontend crashes with error below.

Any idea?

Error:
_NullReferenceException: Object reference not set to an instance of an object.
Piranha.Services.ContentService<TContent, TField, TModelBase>.TransformBlocks<T>(IEnumerable<T> blocks)_

Detail:
Piranha.Controllers.CmsController.Page(Guid id) in CmsController.cs
```
        /// <summary>
        /// Gets the page with the given id.
        /// </summary>
        /// <param name="id">The unique page id</param>
        [Route("page")]
        public IActionResult Page(Guid id) {
            var model = api.Pages.GetById<Models.StandardPage>(id); <<< ERROR LINE
            return View(model);
            //return Json(model);
        }
        /// <summary>
```

SpaceBlock.cs
```
using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;
using Piranha.Extend.Blocks;

namespace Piranha.Extend.Blocks
{
    [BlockType(Name = "Space", Category = "Content", Icon = "fas fa-arrows-alt-v")]
    public class SpaceBlock : Block
    {
        [Field]
        public SelectField<Size> Size { get; set; }
    }

    public enum Size
    {
        small,
        normal,
        large,
    }
}
```

SpaceBlock.cshtml
```
@model Piranha.Extend.Blocks.SpaceBlock

<div class="sep sep-size-@Html.Raw(Model.Size)"></div>
```

**Also on ".db" in "Piranha.BlockFields" table while every record has a plain CLRType value this field has a extra stuff on the end like below.**
_Piranha.Extend.Fields.SelectField`1[[Piranha.Extend.Blocks.Size, DemoCMS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]_

**Comment by tidyui** [comment]
Hi there, I’ll see if I can reproduce the behavior. Also about the CLRType field, this is unfortunately how .net translates the name of the type. We’re not to happy about it and will most likely change the implementation in the future.

**Comment by tidyui** [comment]
You need to add the following line to your application `Startup`. I can see that this is totally missing from the docs, it must have gotten lost when we moved it over from GitHub, I'll make sure to update it!

    App.Fields.RegisterSelect<Piranha.Extend.Blocks.Size>();

Also, it's not good standard to add your custom project components into the namespace of an external component. It would be more logical if `SpaceBlock` was located in your applications namespace.

Best regards

**Comment by tidyui** [comment]
http://piranhacms.org/docs/extensions/select-fields

**Comment by clientwestwood** [comment]
Thanks!
