### ISSUE TITLE
Clone/Copy A Site

### ISSUE THREAD

**Issue by clientwestwood** [PiranhaCMS/piranha.core#507]
Hi there!

I know there is no built-in feature to clone a site with pages and posts in it.
Unline #418 I mean hard copy with no string attached to copied pages/posts.

But anybody ever achieve that by playing with database, creating little snippets or anything?

**Comment by tidyui** [comment]
The easiest way to make a hard copy of a page is probably.

1. Load the page through the Api.
2. Set **all** Id fields (Page, Fields, Blocks) to Guid.Empty.
3. Save the page through the Api.

Put this in a loop based on the sitemap and you could copy all pages. What I can add an issue for is the possibility to **add custom buttons** into all pages of the manager. This will give you the possibility to add your own tools doing these kinds of tasks.

Regards

**Comment by clientwestwood** [comment]
@tidyui Would elaborate a little more how to do bullet 1. and 3. ?
