### ISSUE TITLE
Database Lookup fields

### ISSUE THREAD

**Issue by nhaberl** [PiranhaCMS/piranha.core#509]
Would be great to add fields which can Show a list from a foreign datasource (sql, XML and so on)

**Comment by tidyui** [comment]
Interesting, do you have any suggestions on how it would work more in detail? Are you thinking like a Generic Field where the type has methods for fetching data?

**Comment by nhaberl** [comment]
Thought of a generic type or interface as return type of the field like 

Public T Key
Public string Name
Public string description 
...

Where you can add your builder Func <Ilookup,... > or something like that 

I am not that deep in piranha, so this is a pretty rough concept :)

**Comment by tidyui** [comment]
This has been implemented in the form of `DataSelectField<T>`
