### ISSUE TITLE
Slug generation UTF-8 problems

### ISSUE THREAD

**Issue by clientwestwood** [PiranhaCMS/piranha.core#510]
Hi there!

International characters removed (rather than turn to url friendly counterparts like like ç > c, ş > s) if the slug is generated from title of post/page rather than manually entered.

Characters like "ç, Ç, ğ, Ğ, ş, Ş, ü, Ü, ı, İ". Yeah Turkish alphabet! 😄

I know this can be solved by;
- Manually enter each slug rather than relay on auto generation. (Which is very tiresome while creating a site with more than 100 pages.)
- If a slug hook will be implemented in the future like #243 mentioned.

This may be the choice of developer rather then a issue but here goes nothing.

Any ideas?

**Comment by tidyui** [comment]
Hi! This feature is already available. See #457 for reference on how to implement your own Slug generation!

Regards
