### ISSUE TITLE
Newly added Block prevent saving page with unknown error

### ISSUE THREAD

**Issue by clientwestwood** [PiranhaCMS/piranha.core#511]
Hi there!

Created a simple block with 2 fields. ImageField and VideoField.

When added this block on top of a already created page can't save it and get "The server encountered an error processing the request." error.

If remove the block and add it to end of the page it is fine and can save it.
But then when I drag and drop it to top of the page, again get the same error.

Any ideas?

**Edit: Turns out regardless of which any block to be added to top of the page creates this error.**

**Comment by tidyui** [comment]
Hi there, I’ll test to see if I can reproduce!

**Comment by tidyui** [comment]
Hi there, I have tested in a live environment running `5.3.1` and can't reproduce the error. Do you have any custom blocks in your page. The only thing I can come up with is that an error occurs when the client tries to re-order the array indexes for the blocks **after** you insert a new block before your custom one. This would result in the form-data being more or less corrupt when you save the page. 

When adding a block **after** you're custom block it is not re-ordered and maintain all indexes as they were rendered server-side on page load.

**Comment by tidyui** [comment]
The best way to get to the bottom with it is to insert a block at the top of the page and then inspect the **name** of all form elements in any custom blocks below the block you inserted.
