### ISSUE TITLE
Audio Content?

### ISSUE THREAD

**Issue by CrossBound** [PiranhaCMS/piranha.core#512]
I was looking for a way to add audio files to a site that I created from the basic web template. I read in [the docs](http://piranhacms.org/docs/basics/media-files) about different media types, but in the MediaManager class there are only options for Video, Image, or Documents. Is there a way to add support for audio files? In particular I'm wanting audio embedded so that user's can listen to the audio on the site.

**Comment by tidyui** [comment]
We can definitely add core support for audio files in the future. For now you can add the audio types you want to support as Documents. It won’t give you the manager integration you want but you will still be able to upload and use the audio files in your application!

**Comment by 5w33n** [comment]
Hey, 

I wanted this too and did it locally - can probably submit a PR but want to ask first about supported media types, as I'm not too familiar if any of these are particularly bad for mobile etc:

```
            Instance._mediaTypes.Audio.Add(".m4a", "audio/m4a");
            Instance._mediaTypes.Audio.Add(".mp3", "audio/mpeg");
            Instance._mediaTypes.Audio.Add(".ogg", "audio/ogg");
            Instance._mediaTypes.Audio.Add(".oga", "audio/ogg");
            Instance._mediaTypes.Audio.Add(".webma", "audio/webm");
            Instance._mediaTypes.Audio.Add(".wav", "audio/wav");
```
Any thoughts/objections?

**Comment by tidyui** [comment]
Hi there @5w33n. Yes send us a PR! For media types I think the ones with native support on all devices would be `.mp3` and `.wav`. The others can be added manually in the projects!

Regards

**Comment by tidyui** [comment]
Closing this as PR #573 has been merged.
