### ISSUE TITLE
Sending Push notification

### ISSUE THREAD

**Issue by vdecristofaro** [PiranhaCMS/piranha.core#513]
Hi,
we need to implement a custom section on the manager that provide to send push notifications to users. For this to happen we need in someways to hook on the post saving chain, and, when the save has been completed send the push message through Firebase for example.

Does this way works for our needs or there is a better way to handle this requirement?

Thanks a lot

**Comment by tidyui** [comment]
Hi there! Unfortunately the hooks for content (Pages/Posts) are not available in the current release. We're restructuring the service layer for the `6.0` release and in this work these hooks will be implemented.

Regards
