### ISSUE TITLE
Flush cache after changing site host url?

### ISSUE THREAD

**Issue by clientwestwood** [PiranhaCMS/piranha.core#516]
Hi there,

I use site's host feature to create a multi-language site.
It works perfectly and really useful!

My issue is after changing the default site host url, router kind of stuck on old settings so I have to rebuild package.

Is there a easy way to flush cache so built-in router can recognize the new host urls instantly?

**Comment by tidyui** [comment]
Sounds like there's something wrong with the caching in the Site Repository. We will take a look at this for `6.0`.

**Comment by tidyui** [comment]
As this will be redesigned in `7.1` we will have to revisit the issue then
