### ISSUE TITLE
How to handle 404

### ISSUE THREAD

**Issue by clientwestwood** [PiranhaCMS/piranha.core#517]
Hi there!

Is there a not-documented-feature for handling 404 pages?

**Comment by tidyui** [comment]
Hi there! As the request is passed on to the underlying web application (mvc/razor pages), a 404 is handled like in any .NET Core web application. From there you can make the choice if you want to redirect 404's to a hidden page handled by Piranha or a static page in your application. For handling 500's we recommend redirecting to static pages.
