### ISSUE TITLE
Postgress Support

### ISSUE THREAD

**Issue by Lewis-Bass** [PiranhaCMS/piranha.core#523]
It would be nice if there was support for Postgress dbms.

**Comment by tidyui** [comment]
As far as I know you can use Postgres with the standard EF Core context of Piranha. There are some old closed threads about this here at the repo.

Regards

**Comment by tidyui** [comment]
Btw, since I know people using Piranha with Postgres, what errors are you getting?

**Comment by Lewis-Bass** [comment]
No problems. I copied the msql version made a few changes, added npgsql and it is working.

If anybody wants the code let me know.

**Comment by Lewis-Bass** [comment]
Closing the issue
