### ISSUE TITLE
404 when uploading large media items

### ISSUE THREAD

**Issue by CrossBound** [PiranhaCMS/piranha.core#528]
I'm not sure what's causing this, and I'm not seeing an exception get thrown, but for some reason in production, I'm getting a 404 error when I attempt to load a large file. It seems like the cutoff is somewhere around 30MB. Once I go over 30MB I get a 404. It seems to be in the middle of the upload, i.e. one previous attempt spent 60 seconds uploading and then keeled over with a 404.

What's odd is that it works fine in development.
I'm using the Azure file storage option, and from my development workstation it still takes while to get it uploaded to Azure, but it still works without an error. 

In program.cs I've changed the kestral server to KestrelServerOptions.Limits.MaxRequestBodySize = 105000000; I also tried setting a very small (2 sec) KestrelServerOptions.Limits.KeepAliveTimeout value in development to see if I could replicate the issue, but that did not make a difference.

Any ideas? 

I've attached the request & response headers as well as the log file
![404_1](https://user-images.githubusercontent.com/11417093/53688298-a7281c80-3d07-11e9-8fae-c97a43f14634.png)

[bhc_20190302.log](https://github.com/PiranhaCMS/piranha.core/files/2922557/bhc_20190302.log)

[404_request_headers.txt](https://github.com/PiranhaCMS/piranha.core/files/2922558/404_request_headers.txt)
[404_response_headers.txt](https://github.com/PiranhaCMS/piranha.core/files/2922559/404_response_headers.txt)

.

**Comment by tidyui** [comment]
Hi! This is **highly** dependent on your production environment and nothing that is related to Piranha. For instance, I've been deploying applications to Azure App Services for seven years, and in my experience they just cut the connection when the upload size exceeds 30 something mb. The only way to get around these kind of behaviors is probably to get a virtual machine.

I've bypassed the problem in projects by letting customers upload large files to the web server using FTP and then writing a custom add-on that just adds a file in the media directory directly from the FTP-folder. Another cool way of bypassing it would be to add functionality to upload files from a Dropbox account.

Regards

**Comment by tidyui** [comment]
And like you noticed, the problem is not with Azure Storage. The "problem" is that the proxy handling requests to App Services just terminates the connection when the size exceeds a certain limit.

**Comment by tidyui** [comment]
Here's a link that might have a solution for you:

https://blogs.msdn.microsoft.com/azureossds/2016/06/15/uploading-large-files-to-azure-web-apps/

**Comment by CrossBound** [comment]
So what you are saying is that the connection is being severed by the site hosting provider, not Azure and not asp.net core (My site is not hosted on Azure)?

**Comment by CrossBound** [comment]
The solution in the link provided worked, thanks.
