### ISSUE TITLE
Piranha.Azure.BlobStorage (Windowsazure.Storage)

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#532]
Hi

I just noticed that something recently changed with Piranha's updates. I had the following usings:
![2019-03-05 16_36_50-window](https://user-images.githubusercontent.com/32654709/53821089-fd45cb80-3f64-11e9-8dc6-d92c877cdd60.png)

`Microsoft.WindowsAzure.Storage.Table` is something that is missing right now. The alternative to that, is the Windowsazure.Storage NuGet package.

Do you have any plans of including that back in (if it ever was included and I am not wrong)? Because I need all of those, so I can initialise those fields:
![2019-03-05 16_39_05-window](https://user-images.githubusercontent.com/32654709/53821288-5f063580-3f65-11e9-965a-fc0317cee088.png)

Regards,
Chris

**Comment by tidyui** [comment]
Hi there! 

WindowsAzure.Storage has been replaced as it is obsolete! Please see:

https://www.nuget.org/packages/WindowsAzure.Storage/

Best regards

**Comment by tidyui** [comment]
Here's some more info. Piranha.Azure.BlobStorage `5.4.0` & `5.3.1` is dependent on:

* Microsoft.Azure.KeyVault.Core (>= 3.0.1)
* Microsoft.Azure.Storage.Blob (>= 9.4.2)

Piranha.Azure.BlobStorage `5.3.0` and lower is dependent on:

* WindowsAzure.Storage (>= 9.3.2)

`WindowsAzure.Storage` itself includes namespaces for handling both Blob & Table storage which `Microsoft.Azure.Storage.Blob`. If you want to use table storage you need to include the relevant NuGet packages in your application.

Best regards
