### ISSUE TITLE
404 in multisite scenario

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#533]
Normally i set up 404 pages using 

app.UseStatusCodePagesWithReExecute

The controller generates the view but is not connected to cms and cannot decide which sitemap to show etc.

My idea is to setup error pages in piranha manager and execute it when needed. I don't want to have redirects. This makes no sense because the returning response codes are not correct.

Best scenario would be to have each 404 page in the layout (etc.) of the corresponsing site. 

I tried it by setting 
app.UseStatusCodePagesWithReExecute("/errorpages/404")
and creating the same slug in cms. but this does not work.

Any idea?

**Comment by tidyui** [comment]
Hi! I’m assuming that method only re-executes the pipeline **after** itself if it gets a 404 back from the middleware after itself. Have you made sure you add this to the pipeline before you call App.UsePiranha?

Regards

Håkan

**Comment by tidyui** [comment]
Hi again.. I have tested your case without any issues. Since `UseStatusCodePagesWithReExecute` most likely **only** will re-execute middleware after itself I decided to put it **after** static files and authentication but **before** the call to `app.UsePiranha()` since we want the Piranha middleware to run again and resolve the slug of the error page.

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, IApi api)
    {
        ...

        app.UseStaticFiles();
        app.UseAuthentication();
        app.UseStatusCodePagesWithReExecute("/not-found");
        app.UsePiranha();
        app.UsePiranhaManager();

        ...
    }

Regards

**Comment by rengert** [comment]
I have more detailed information yet, but i guess it has nothing to do with the cms.

I have a middleware adding site information to context to be used in meta areas, but. The middleware is called twice ... i guess this is expected but during the second call i cannot call the next line anymore because of a wrong index based call.

await _next.Invoke(context)
