### ISSUE TITLE
SQL Server and web Project Template

### ISSUE THREAD

**Issue by KYoung1974** [PiranhaCMS/piranha.core#535]
I'm new to ASP.NET Core and Identity, is there a guide to setting up the Web site template to user SQL Server instead of SQLite?  Or the best way to have piranha use the Core Identity tables?

**Comment by tidyui** [comment]
Hi there! Yes we have documentation on our site on how to setup Piranha & Piranha.AspNetCore.Identity for SQL Server.

**How to setup Piranha for SQL Server**
http://piranhacms.org/docs/architecture/databases/sqlserver

**How to setup AspNetCore Identity**
http://piranhacms.org/docs/components/authentication/identity-security

Please let us know if you find anything unclear regarding the documentation as we're constantly improving it!

Regards

**Comment by KYoung1974** [comment]
Hi thanks for replying.  I had been over the documentation numerous times and was looking at the different templates and such.  When it actually came time to hook it up to SQL Server, I forgot to change the ConfigBuilder.  

One more quick question, if you don't mind, and I can create a new issue if needed.  What's the best way to integrate Piranha.Identity with AspNetCore.Identity?  I need the ability to have users self register and create a profile and the Identity scaffolding makes that a breeze to setup and extend the user information.  However, I don't see the PiranhaDbContext in the scaffolding wizard.  Is that something that is better suited to pulling in the individual NuGet packages rather than starting with the template?  Or do I need to add a new context?

**Comment by tidyui** [comment]
Hi! Well, all that the Piranha package for Identity does is to use the basic IdentityDbContext:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore.Identity/Db.cs

You can actually use any authentication you want with Piranha, all you need to do is to implement `ISecurity` and register your own service:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore.Identity/IdentitySecurity.cs

The `ISecurity` service is in reality **only** used when logging in to the manager. Now if you decide to write your own user management, the important thing is that you set the correct claims to your admin accounts or they won't be able to access the manager.

http://piranhacms.org/docs/components/authentication

Also there's nothing that keeps you from having Piranha's Identity implementation for admin users, and a second Identity context for your front-web users, the only downside is that you won't be able to see and administrate them from within the manager as they will be created in different contexts.

Regards

**Comment by tidyui** [comment]
Also, if you want to have all users in your own Identity context and handle them all from the manager, just clone the repo and use the `Piranha.AspNetCore.Identity` project as a base for writing your own custom admin views :) It's all up to you!

**Comment by KYoung1974** [comment]
Thanks for the insight.  I'm looking forward to incorporating this into my application.
