### ISSUE TITLE
SQL server connect with web template

### ISSUE THREAD

**Issue by mpadula1990** [PiranhaCMS/piranha.core#537]
I'm trying to connect to SQL server in the template and I can not. I do not have much experience with this, can someone help?
this is my startup.cs:

```
`using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;
using Piranha;
using Piranha.AspNetCore.Identity.SQLite;
using Piranha.AspNetCore.Identity.SQLServer;

namespace MvcWeb
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        /// <summary>
        /// </summary>
        /// <param name="services"></param>
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(config =>
            {
                config.ModelBinderProviders.Insert(0, new Piranha.Manager.Binders.AbstractModelBinderProvider());
            });
            services.AddPiranha();
            services.AddPiranhaApplication();
            services.AddPiranhaFileStorage();
            services.AddPiranhaImageSharp();


            services.AddPiranhaIdentity<IdentitySQLServerDb>(options => options.UseSqlServer("Data Source=./SQLEXPRESS;Initial Catalog=piranha.core;Integrated Security=True;MultipleActiveResultSets=True"));
            services.AddPiranhaIdentityWithSeed<IdentitySQLServerDb>(options => options.UseSqlServer("Data Source=./SQLEXPRESS;Initial Catalog=piranha.core;Integrated Security=True;MultipleActiveResultSets=True"));
                
            


             /*services.AddPiranhaEF(options =>
            options.UseSqlite("Filename=./piranha.mvcweb.db"));
            services.AddPiranhaIdentityWithSeed<IdentitySQLiteDb>(options =>
            options.UseSqlite("Filename=./piranha.mvcweb.db"));*/

            services.AddPiranhaManager();

            services.AddMemoryCache();
            services.AddPiranhaMemoryCache();
        }



        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IApi api)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            App.Init(api);

            // Configure cache level
            App.CacheLevel = Piranha.Cache.CacheLevel.Full;

            // Custom components
            App.Blocks.Register<Models.Blocks.SeparatorBlock>();

            // Build content types
            var pageTypeBuilder = new Piranha.AttributeBuilder.PageTypeBuilder(api)
                .AddType(typeof(Models.BlogArchive))
                .AddType(typeof(Models.StandardPage))
                .AddType(typeof(Models.TeaserPage))
                .Build()
                .DeleteOrphans();
            var postTypeBuilder = new Piranha.AttributeBuilder.PostTypeBuilder(api)
                .AddType(typeof(Models.BlogPost))
                .Build()
                .DeleteOrphans();

            // Register middleware
            app.UseStaticFiles();
            app.UseAuthentication();
            app.UsePiranha();
            app.UsePiranhaManager();
            app.UseMvc(routes =>
            {
                routes.MapRoute(name: "areaRoute",
                    template: "{area:exists}/{controller}/{action}/{id?}",
                    defaults: new { controller = "Home", action = "Index" });

                routes.MapRoute(
                    name: "default",
                    template: "{controller=home}/{action=index}/{id?}");
            });

            Seed.RunAsync(api).GetAwaiter().GetResult();
        }
    }
}

`
```
and the serve return me it:

> 
> An error occurred while starting the application.
> InvalidOperationException: No service for type 'Piranha.IApi' has been registered.
> Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
> 
> Exception: Could not resolve a service of type 'Piranha.IApi' for the parameter 'api' of method 'Configure' on type 'MvcWeb.Startup'.
> Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
> 
> InvalidOperationException: No service for type 'Piranha.IApi' has been registered.
> Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
> Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
> 
> Show raw exception details
> Exception: Could not resolve a service of type 'Piranha.IApi' for the parameter 'api' of method 'Configure' on type 'MvcWeb.Startup'.
> Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
> Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder+<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
> Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
> Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
> Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

in my sql server mananger I do not see the database. Would you have to create it for me?

Tnx!

**Comment by tidyui** [comment]
Hi there! It looks like you've just copied the wrong line twice.. You have at the moment:

    services.AddPiranhaIdentity<IdentitySQLServerDb>(options => options.UseSqlServer("Data Source=./SQLEXPRESS;Initial Catalog=piranha.core;Integrated Security=True;MultipleActiveResultSets=True"));
    services.AddPiranhaIdentityWithSeed<IdentitySQLServerDb>(options => options.UseSqlServer("Data Source=./SQLEXPRESS;Initial Catalog=piranha.core;Integrated Security=True;MultipleActiveResultSets=True"));

When you should have:

    services.AddPiranhaEF(options => options.UseSqlServer("Data Source=./SQLEXPRESS;Initial Catalog=piranha.core;Integrated Security=True;MultipleActiveResultSets=True"));
    services.AddPiranhaIdentityWithSeed<IdentitySQLServerDb>(options => options.UseSqlServer("Data Source=./SQLEXPRESS;Initial Catalog=piranha.core;Integrated Security=True;MultipleActiveResultSets=True"));

Regards

**Comment by mpadula1990** [comment]
thank you, this solved my problem.
