### ISSUE TITLE
FileStorage in debug mode

### ISSUE THREAD

**Issue by haeberle** [PiranhaCMS/piranha.core#538]
Hi team

I'm using FileStorage to save media files. In the debug mode, the FileStorage tries to save the files in the IIS Express folder (C:\Program Files\IIS Express\wwwroot\uploads), in my case I got an UnauthorizedAccessException, which is fine, because I have no permissions to write into this folder. 

I'd like to save the files in the wwwroot folder in my visual project instead of the iisexpess folder. How is that possible ?

**Comment by haeberle** [comment]
In the Startup.cs you can configure the the ConfigureServices with the following lines:

` var path = Path.Combine(HostingEnvironment.WebRootPath, "media\\");
services.AddPiranhaFileStorage(basePath: path, baseUrl: "~/media/");`

it the way to do it at least with VS 2017. I will test it in prod as soon I can delopy the app.

**Comment by tidyui** [comment]
Hi. Did you get it to work or did you need any support on this issue?

Regards

**Comment by haeberle** [comment]
hi tidyui

the solution works for me,
