### ISSUE TITLE
JSON in Heading region of Posts does not follow conventions

### ISSUE THREAD

**Issue by w0ns88** [PiranhaCMS/piranha.core#539]
Hi,

I just found that the `Heading` region  does not follow the lowercased JSON convention but is like so:
```
"regions": {
    "Heading": { <=== Should not be capitalized
        "PrimaryImage": { <=== Should not be capitalized
            "id": "4e83af14-8a97-480a-8ecd-f7112b54fc7e",
            "hasValue": true
        },
        "Ingress": { <=== Should not be capitalized
            "value": "blog 2 teaser"
        }
    }
},
```
As far as I am aware it is only on `Post` objects.

**Comment by tidyui** [comment]
Hi there! I can't reproduce your issue, how are you serializing your data? Also, since Piranha doesn't add any custom JSON serializers anywhere in its code-base I'm having a hard time seeing how this could be a framework behavior.

Best regards

**Comment by w0ns88** [comment]
I'll look into my code again, I may have missed something.

**Comment by w0ns88** [comment]
My apologies, it was an issue in my code.
