### ISSUE TITLE
Custom block with external library?

### ISSUE THREAD

**Issue by w0ns88** [PiranhaCMS/piranha.core#540]
Hi,

I am trying to write a custom block that contains a custom field that uses an external library. The aim is to create a different Rich Text Block using [Summernote ](https://summernote.org/) instead. 

As per your docs, it is quite a straightforward process to add the [custom blocks](http://piranhacms.org/docs/extensions/custom-blocks) and the [custom fields](http://piranhacms.org/docs/extensions/custom-fields), but I have issues initializing Summernote. In which file should I add the `<link>` and `<script>` elements?

If you can help me point me in the right direction I would be grateful.

**Comment by filipjansson** [comment]
I would recommend to add your css/js resources to the manager module, [example can be find here](http://piranhacms.org/docs/manager-extensions/custom-resources).

By doing so you know that the resursers are inserted only once and accessible on all the views in the manager.

BR
Filip

**Comment by w0ns88** [comment]
That's great thanks for the pointers :)
