### ISSUE TITLE
Htmlfield not being rendered correctly

### ISSUE THREAD

**Issue by RamiSh** [PiranhaCMS/piranha.core#541]
I have this simple page with htmlfield in it

```
    [PageType(Title = "Standard page")]
    public class StandardPage  : Page<StandardPage>
    {
        [Region]
        public HtmlField ContentHtml{ get; set; }

    }
```
and in the view I use 
` @Html.Raw(Model.ContentHtml)`

It still shows it as text rather than html element.

**Comment by RamiSh** [comment]
```
@using System.Web;

@Html.Raw(HttpUtility.HtmlDecode(Model.ContentHtml))
```

**Comment by tidyui** [comment]
Hi there! You’re supposed to use @Html.Raw(htmlField). If this prints the html tags as text something else is wrong. How does the data look in the database, have the tags been escaped by mistake for some reason?
