### ISSUE TITLE
Items on BlockGroup does not get serialized

### ISSUE THREAD

**Issue by stefanolsenn** [PiranhaCMS/piranha.core#543]
Hi @tidyui 
I'm trying to create some nested items with the BlockGroup, but the childs/items does not get serialized to json.

**LinkBlock.cs:**
`[BlockGroupType(Name = "Link", Category = "Groups", Icon = "fas fa-audio-description")]
   [BlockItemType(Type = typeof(Link))]`
 `public class LinkBlock : BlockGroup {}`

**Link.cs**
`    [BlockType(Name = "Link", Icon = "fas fa-link", IsUnlisted = true)]`
`    public class Link : Block { ... }`

Then I add some items in the manager, update and publish the page.

**Result**
`{ ... 
   "blocks":[{}] 
   ... 
 }`

What I expected was that the items gets serialized with the page.
Is this the expected behavior?

**Comment by tidyui** [comment]
Hi there @stefanolsenn! What version of Piranha are you using ?

**Comment by stefanolsenn** [comment]
I'm using 5.4

**Comment by tidyui** [comment]
Hi again! Examining the code for the `BlockGroup` base class I can see that the blocks are marked with `[JsonIgnore]` (https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha/Extend/BlockGroup.cs#L24). This should be considered a bug and should be removed!

Best regards

**Comment by stefanolsenn** [comment]
Thank you @tidyui
