### ISSUE TITLE
Manager Views

### ISSUE THREAD

**Issue by daudirsch** [PiranhaCMS/piranha.core#544]
First, great job and thanks for all your hard work.

I'm sure it's user error, but I was attempting to create a custom menu item in the manager  (based on this example http://piranhacms.org/docs/manager-extensions/manager-menu) and the section and the menu item do show.  When I click on the page it routes to "http://localhost:29102/Manager/MyModule/FirstAction" and says:

"No webpage was found for the web address: http://localhost:29102/Manager/MyModule/FirstAction
HTTP ERROR 404"

I have a MyModuleController with a FirstAction which simply returns View().

.The documentation wasn't available yet (http://piranhacms.org/docs/manager-extensions/manager-views).

**Comment by tidyui** [comment]
Hi there! Since it's a 404 error it's a standard MVC error. Without seeing the code my guess is that you controller hasn't been added to the `Manager` area, like so:

    [Area("Manager")]

Again, this is just me guessing :)

**Comment by i-love-code** [comment]
I would 2nd this, as I forgot it too while testing this :)

![image](https://user-images.githubusercontent.com/1737733/55032899-e92f4000-4fdf-11e9-8018-f82c67fea9ac.png)
![image](https://user-images.githubusercontent.com/1737733/55032960-08c66880-4fe0-11e9-92bc-d343ba7822a6.png)

Seems to work with the area attribute and the code in the custom menu example.

**Comment by tidyui** [comment]
I'll make sure I'll add it to the documentation for clarity!

**Comment by daudirsch** [comment]
And BOOM!  That was it.  I figured it was a simple learning curve on my part.  Thanks for the quick response.
