### ISSUE TITLE
Manager Style

### ISSUE THREAD

**Issue by daudirsch** [PiranhaCMS/piranha.core#545]
Just curious if the manager's style (color/fonts) and/or layout be modified to match an existing site?

**Comment by tidyui** [comment]
Hi there! There are not explicit support for theming, but you can add custom stylesheets to the manager which allows you to override any styling you like. See this page for reference:

http://piranhacms.org/docs/manager-extensions/custom-resources

Regards

**Comment by daudirsch** [comment]
Perfect.  Again, thx for your hard work.
