### ISSUE TITLE
DisplayTemplate missing in example for VideoBlock

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#548]
With the latest 'video block' if you add a new Media / video block, it displays the watermark and offers a "+" to add the media. This all works fine.  

When you then update an view the page, the place which should contain the video contains the string below instead:

Piranha.Extend.Fields.VideoField

**Comment by tidyui** [comment]
The error is not really in the block itself, it's due to the fact that the example project doesn't contain a DisplayTemplate for it. I will update the title of the issue

**Comment by CastleSoft** [comment]
Thanks..
