### ISSUE TITLE
Ability to hide title on any page - Enhancement

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#550]
I've been creating a custom page for a while now (as shown below) to add the ability to optionally display the title on a page.

Would it be possible to add to all the core page styles a new property:
"Hide Title"  or "Show Title" to optionally display a title on any page ?

This would save me recreating for new page types etc. And I think it would be handy for others who wish to use a Graphic or other on their page instead of the title string.

`
// --------------------------- 
// Startup.cs 
// --------------------------- 

// Build content types 

   var pageTypeBuilder = new Piranha.AttributeBuilder.PageTypeBuilder(api) 
                .AddType(typeof(Models.BlogArchive)) 
                .AddType(typeof(Models.StandardPage)) 
                .AddType(typeof(Models.StandardPageWithHideTitle))  // ADDED  
                .AddType(typeof(Models.StartPage)); 

// ----------------------------------------------------------- 
//      Views/Cms/PageWithHideTitle.cshtml 
// ----------------------------------------------------------- 

@model cms.Models.StandardPageWithHideTitle 

@{ 
    ViewBag.Title = Model.Title; 
} 

<div class="main"> 
    <div class="container"> 
        <div class="row justify-content-center"> 
            <div class="col-sm-10 page-body"> 
                     @if (!Model.Settings.HideTitle) {             
                               <h1>@Model.Title</h1> 
                     } 
                @Html.DisplayFor(m => m.Blocks) 
            </div> 
        </div> 
    </div> 
</div> 

// -------------------------------------------------------- 
//    Models/StandardPageWithHideTitle.cs 
// -------------------------------------------------------- 

using Piranha.AttributeBuilder; 
using Piranha.Models; 
using Piranha.Extend.Fields; 
using System.Collections.Generic; 

namespace cms.Models 
{ 
    [PageType(Title = "Standard Page with Hide Title")] 
    [PageTypeRoute(Title = "Default", Route = "/hidetitlepage")] 
    public class StandardPageWithHideTitle  : Page<StandardPageWithHideTitle> 
    { 
    [Region] 
    public Regions.Settings Settings { get; set; } 
    } 
} 

// --------------------------------------------- 
// Models/Regions/Settings.cs 
// --------------------------------------------- 

using Piranha.AttributeBuilder; 
using Piranha.Extend.Fields; 
using Piranha.Models; 

namespace cms.Models.Regions 
{ 
    public class Settings 
    { 
        [Field(Title = "Hide Title")] 
        public CheckBoxField HideTitle { get; set; }         

        [Field(Title = "TAG Optional Comment")] 
        public TextField Tag { get; set; }  
    } 
} 

// --------------------------------------------- 
// Controllers/CmsController.cs 
// --------------------------------------------- 

//   AJT 2018-07-23 
/// <summary> 
/// Gets the PageWithHideTitle with the given id 
///  

/// The unique page id 
[Route("hidetitlepage")] 
public IActionResult PageWithHideTitle(Guid id) 
{ 
   var model = api.Pages.GetById<Models.StandardPageWithHideTitle>(id); 
   return View(model); 
} 
`

**Comment by tidyui** [comment]
Hi there! You can achieve this in several ways, here are my two suggestions:

## 1. Add a style region to your pages

You can add a region to your pages containing information about how they should be rendered. This is a good solution if you think you might want more render settings in the future.

    // Region
    public class StyleRegion
    {
        [Field]
        public CheckBoxField HideTitle { get; set; }
    }

    // Page type
    [PageType(...)]
    public class StandardPage : Page<StandardPage>
    {
        ...

        [Region]
        public StyleRegion Styles { get; set; }

        ...
    }

## 2. Several routes/views for your pages

You can also use the routing option on your pages if you want to send the same model to different views. Take a look at this article when I explain this setup from a security perspective for more information.

http://piranhacms.org/blog/techniques-for-securing-pages

    // Page type
    [PageType(...)]
    [PageTypeRoute(Title = "Basic layout", Route = "/page")]
    [PageTypeRoute(Title = "Without title", Route = "/pagenotitle")]
    public class StandardPage : Page<StandardPage>
    {
        ...

        [Region]
        public StyleRegion Styles { get; set; }

        ...
    }

    // Example controller
    public class MyController : Controller
    {
        [Route("page")]
        public IActionResult Page(Guid id)
        {
            return View(...);
        }

        [Route("pagenktitle")]
        public IActionResult PageNoTitle(Guid id)
        {
            return View(...);
        }
    }

Best regards

Håkan
