### ISSUE TITLE
how hide tab element "content" in manager page edit

### ISSUE THREAD

**Issue by MathieuMauron** [PiranhaCMS/piranha.core#551]
hi, some questions for manager, is it possible to hide the content element  ?

![piranha](https://user-images.githubusercontent.com/42377268/55156938-7519a700-515b-11e9-8a3c-731bbc012ffd.jpg)

if yes how ?

**Comment by tidyui** [comment]
Hi there! Yes you just set `UseBlocks = false` in your `PageTypeAttribute`. Take a look at this page for more information!

http://piranhacms.org/docs/basics/how-to-setup-content/page-types

Regards

**Comment by MathieuMauron** [comment]
okay, thanks a lot, i started piranha cms yesterday and its the first time i use a cms. Really nice project and architecture.

**Comment by tidyui** [comment]
Thanks!!! If you want to ask questions, make sure you join our Gitter channel as well!

https://gitter.im/PiranhaCMS/Piranha

Best of luck!
