### ISSUE TITLE
CheckboxField Placehiolder does not get printed

### ISSUE THREAD

**Issue by w0ns88** [PiranhaCMS/piranha.core#552]
Hi,
I have defined two `CheckboxFelds` that should have the placeholder "Student" and "Teacher" as defined here:

```
[Field(Title = "Target Audience", Placeholder = "Student")]
public CheckBoxField Student { get; set; }

[Field(Placeholder = "Teacher")]
public CheckBoxField Teacher { get; set; }
```
What gets printed on the razor page is as follows:
![target-audience](https://user-images.githubusercontent.com/6594130/55237124-af557800-5231-11e9-85c8-e903e293ca10.PNG)

The placeholders are not shown as described in your [checkbox field docs](http://piranhacms.org/docs/basics/standard-fields).

**Comment by tidyui** [comment]
Hi there. There appears to be a bug causing placeholders to only be shown for **pages** and not for posts or sites.
