### ISSUE TITLE
Question - Using piranha core headless in asp.net mvc5

### ISSUE THREAD

**Issue by dotnetshadow** [PiranhaCMS/piranha.core#554]
Hi there,

I understand that piranha core is targeted for netstandard and asp.net core. I thought I read in your documentation that it's headless. Is there a client / api way of accessing content that can be used on an existing asp.net mvc 5 site. The idea being I can create my content using Piranha Core and have the content appear in my asp.net mvc 5 trough api calls

**Comment by tidyui** [comment]
Hi there! Take a look at this issue #546

**Comment by dotnetshadow** [comment]
@tidyui that's awesome thank you, I guess I just need to know how to config the database to connect the api to it

**Comment by tidyui** [comment]
Yes, the DI setup is of course a bit different in MVC 5. As a last resort you can always create the DbContext and Api manually, take a look at how this is done in the test projects.

**Create DbContext manually**

https://github.com/PiranhaCMS/piranha.core/blob/master/test/Piranha.Tests/BaseTests.cs#L54

**Create Api manually**

https://github.com/PiranhaCMS/piranha.core/blob/master/test/Piranha.Tests/Repositories/Params.cs#L202

Regards

**Comment by tidyui** [comment]
However, for some fields to initialize correctly (PageField, PostField and all MediaFields) `IApi` needs to be registered in the serviceContext provided to the repositories.

**Comment by dotnetshadow** [comment]
@tidyui excellent, much appreciated. I'll have a go at that cheers
