### ISSUE TITLE
Tag and Category Services and Repos missing in 6.0

### ISSUE THREAD

**Issue by w0ns88** [PiranhaCMS/piranha.core#556]
I am now upgrading to 6.0 and have noticed that the `CaregoryService`, `CategoryRepository`, `TagService` and `TagRepository` are missing. 

I have had a look at the changelog and it seems they were deleted (by mistake?). The code can be found in PR #529 in the core/Piranha/Api.cs.

**Comment by tidyui** [comment]
Hi there.. No they are not missing, I will add a notice of them in the Changlog. As tags and categories does not exist outside of the Post archive their methods have been moved into the `PostService`. If the normalized SQL-repositories would be replaced with a NoSql-database this would be the logical place to have them as the repository methods would most likely just get all of the available tags in the posts in the specified archive.

**The methods can be found here:**

    api.Posts.GetAllCategoriesAsync
    api.Posts.GetCategoryBySlugAsync
    api.Posts.GetAllTagsAsync
    api.Posts.GetTagBySlugAsync

Best regards
