### ISSUE TITLE
Post save error

### ISSUE THREAD

**Issue by infocrat** [PiranhaCMS/piranha.core#557]
Error occures while saving post:
> Cannot insert duplicate key row in object 'dbo.Piranha_Categories' with unique index 'IX_Piranha_Categories_BlogId_Slug'.

**I am doing the following:**
1) create post
2) save it
3) reopen post and change something
4) trying to save changes

**Comment by tidyui** [comment]
Hi! Could you add the stack trace for the error so I can see where it happens.

Regards

**Comment by infocrat** [comment]
Here it is:

> System.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__180_0(Task<SqlDataReader> result)
>     System.Threading.Tasks.ContinuationResultTaskFromResultTask<TAntecedentResult, TResult>.InnerInvoke()
>     System.Threading.Tasks.Task.Execute()
>     Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary<string, object> parameterValues, CancellationToken cancellationToken)
>     Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

**Show raw extension details**

> System.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Piranha_Categories' with unique index 'IX_Piranha_Categories_BlogId_Slug'. The duplicate key value is (c67c79c8-1afb-4ba8-a27b-c1a5d167c5ed, ).
> The statement has been terminated.
>    at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
>    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
> ClientConnectionId:bf38eecf-7ec2-4b9e-8c2e-3479274f5d6b
> Error Number:2601,State:1,Class:14
> ClientConnectionId before routing:ee463df5-3966-4733-b366-fdb28ddabe99
> Routing Destination:a1dab40852b7.tr27.westeurope1-a.worker.database.windows.net,11038

**DbUpdateException: An error occurred while updating the entries. See the inner exception for details.**
 

> Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
>     Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple<IEnumerable<ModificationCommandBatch>, IRelationalConnection> parameters, CancellationToken cancellationToken)
>     Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync<TState, TResult>(TState state, Func<DbContext, TState, CancellationToken, Task<TResult>> operation, Func<DbContext, TState, CancellationToken, Task<ExecutionResult<TResult>>> verifySucceeded, CancellationToken cancellationToken)
>     Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList<InternalEntityEntry> entriesToSave, CancellationToken cancellationToken)
>     Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
>     Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
>     Piranha.Repositories.PostRepository.Save<T>(T model)
>     Piranha.Services.PostService.SaveAsync<T>(T model)
>     Piranha.Services.PostServiceSyncExtensions.Save<T>(PostService service, T model)
>     Piranha.Areas.Manager.Services.PostEditService.Save(PostEditModel model, out string alias, Nullable<bool> publish)
>     Piranha.Areas.Manager.Controllers.PostController.Save(PostEditModel model)
>     Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>     Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>     Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>     Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
>     Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>     Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>     Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
>     Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
>     Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>     Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
>     Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
>     Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>     Piranha.AspNetCore.SitemapMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
>     Piranha.AspNetCore.StartPageMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
>     Piranha.AspNetCore.ArchiveMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
>     Piranha.AspNetCore.PostMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
>     Piranha.AspNetCore.PageMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
>     Piranha.AspNetCore.AliasMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
>     Piranha.AspNetCore.ApplicationMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
>     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>     Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>     Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by tidyui** [comment]
Hi again. What database are you using and what version of Piranha. I can't reproduce on SQLite or SQL Server with the latest version.

**Comment by tidyui** [comment]
The scenario you're describing is also tested (with SQLite) in the integrations tests with no errors.

https://github.com/PiranhaCMS/piranha.core/blob/master/test/Piranha.Tests/Repositories/Posts.cs#L627

So I'm having a bit of trouble finding what's causing it.

**Comment by infocrat** [comment]
I've found the problem.
When post is created new category is saved. I used cyrillic category title and category's slug was generated as an empty string (issue  #490 ).
So, the function "GetCategoryBySlug" returns null while post updating, and tries to add new category with empty slug again.
Using slug hooks probably solves the issue.
Thank you.

**Comment by infocrat** [comment]
It looks like slug validation is needed.

**Comment by tidyui** [comment]
Yes, like you say it’s not as visible as when the slug for pages/posts are generated incorrectly. We’ll add a check for an empty slug, as this should not be allowed. I’ll add a new issue for this.
