### ISSUE TITLE
IsUnlisted is ignored on the first add-block on a post

### ISSUE THREAD

**Issue by stefanolsenn** [PiranhaCMS/piranha.core#559]
ref: #543 
The code is the same as in the ref.
IsUnlisted property of block, is ignored on the first add-block on a post. See screenshots below:

The link should not be listed here
![notworks](https://user-images.githubusercontent.com/23049696/55397839-6e1dda80-5547-11e9-8364-8435136c3975.png)

But works as intended here on the second add-block
![notworks2](https://user-images.githubusercontent.com/23049696/55397851-7544e880-5547-11e9-8aaf-d99e557001e5.png)

I'm using version 6.0

**Comment by tidyui** [comment]
Deployed and available on NuGet as of version `6.0.1`
