### ISSUE TITLE
Make sure empty slugs are not generated

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#566]
Add empty validation for slugs AFTER title has been converted to slug. In cases where a charset is used that doesn’t work with the default slug generation it’s easy to miss that it fails for categories and tags. See #557 for reference

**Comment by i-love-code** [comment]
I'd be happy to submit something that in general handles URL segments better. For supporting multiple languages, I'd suggest something like https://github.com/thecoderok/Unidecode.NET which provides transliteration from most unicode characters to readable strings.

An example of their functionality:

```
Assert.AreEqual("Bei Jing ", "\u5317\u4EB0".Unidecode());
Assert.AreEqual("Rabota s kirillitsey", "Работа с кириллицей".Unidecode());
Assert.AreEqual("aeoeuoAeOeUO", "äöűőÄÖŨŐ".Unidecode());
Assert.AreEqual("Hello, World!", "Hello, World!".Unidecode());
Assert.AreEqual("'\"\r\n", "'\"\r\n".Unidecode());
Assert.AreEqual("CZSczs", "ČŽŠčžš".Unidecode());
Assert.AreEqual("a", "ア".Unidecode());
Assert.AreEqual("a", "α".Unidecode());
Assert.AreEqual("a", "а".Unidecode());
Assert.AreEqual("chateau", "ch\u00e2teau".Unidecode());
Assert.AreEqual("vinedos", "vi\u00f1edos".Unidecode());
```
