### ISSUE TITLE
PageField Not showing pages to select

### ISSUE THREAD

**Issue by i-love-code** [PiranhaCMS/piranha.core#567]
On the latest of master branch, commit 45b7ba65b009e17e7d9b2112113a2787b9e13124 v6.0.2 I can't explain why but I cannot seem to use a PageField property.

Latest commit:
![image](https://user-images.githubusercontent.com/1737733/55642612-94858500-5796-11e9-9046-3951f6fb4871.png)

Changes:
![image](https://user-images.githubusercontent.com/1737733/55642631-9e0eed00-5796-11e9-959c-bd39885253ae.png)
![image](https://user-images.githubusercontent.com/1737733/55642655-b121bd00-5796-11e9-8a1b-60e73325a37f.png)

It shows on the content type in the hero region, but it doesn't show any pages to select.

https://i.gyazo.com/a8bb76d84ff6c577c77183edb7f892f4.mp4

The site content has the pages you would expect, freshly seeded.

Oddly, this works just fine on another site from a `dotnet new` template using ~v6.0.0

**Comment by tidyui** [comment]
I have tried this in master and I can't reproduce unfortunately.

**Comment by i-love-code** [comment]
Apologies, this one my VS had defaulted to a .NET Core 2.2 site. With 2.2 as the target, a bunch of routes fail to generate. It causes broken experience a few places in the manager, mainly when adding new pages and this modal. I assume it's due to the endpoint routing with 2.2. 

I don't envy your team having to work that out :)

I assume upgrading to 2.2 or 3.0 (I'm assuming 3.0 will be next LTS) will have to happen much later on. Looks like endpoint routing support for routes from external source is in milestone 3.0-preview5 (based on: https://github.com/aspnet/AspNetCore/issues/4221)
