### ISSUE TITLE
Publish/unpublish content does not reflect when CacheLevel=Full

### ISSUE THREAD

**Issue by stefanolsen** [PiranhaCMS/piranha.core#568]
With CacheLevel set to Full, I try to unpublish a page and refresh the URL of that page. The page still appears to be published. If I force a restart of the site, the page appears unpublished.
If I reduce the CacheLevel to Basic, these changes appear immediately.

**Comment by tidyui** [comment]
This seems to be related to #555. The page is unpublished and cleared from cache **but** the sitemap is not removed from cache so it's still visible in the menu. Until a patch is released, performing another change that will update sitemap (like updating a published page or adding a new one) will clear then sitemap from cache.
