### ISSUE TITLE
After upgrade to 6.0.2 my start page throws 404? 

### ISSUE THREAD

**Issue by AlexJPawlak** [PiranhaCMS/piranha.core#571]
Hey!

After I've upgraded Piranha to 6.0.2 my Start page ("/start") request fails to resolve to a website, but 404 content is thrown instead. I have upgraded and made code adjustments, but my local environment targets old database (if that is of any relevance). My Startup code isn't heavily modified, nor isn't "StartPage". What might affect this issue is that my DB has multiple pages of type "StartPage" (did that for my own convenience for some reason :-) ) 

`        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider services, IApi api)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // Initialize Piranha
            App.Init(api);

            // Configure cache level
            App.CacheLevel = Piranha.Cache.CacheLevel.Basic;

            // Build content types
            var pageTypeBuilder = new Piranha.AttributeBuilder.PageTypeBuilder(api)
                .AddType(typeof(Models.BlogArchive))
                .AddType(typeof(Models.StandardPage))
                .AddType(typeof(Models.StartPage));
            pageTypeBuilder.Build()
                .DeleteOrphans();
            var postTypeBuilder = new Piranha.AttributeBuilder.PostTypeBuilder(api)
                .AddType(typeof(Models.BlogPost));
            postTypeBuilder.Build()
                .DeleteOrphans();

            // Register middleware
            app.UseStaticFiles();
            app.UseAuthentication();
            app.UsePiranha();
            app.UsePiranhaManager();
            app.UseHttpsRedirection();
            app.UseMvc(routes =>` 

Any ideas how to troubleshoot it properly would be so welcome, I'm pretty novice when it comes to ASP.NET apps 

Thanks!

Alex Pawlak

**Comment by pkreemer** [comment]
Alex, people might be able to help better if you include your full Startup class - some of it was cut off.

**Comment by AlexJPawlak** [comment]
Hello! 

Thanks, sorry, here's the full Startup.cs

`using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Piranha;
using Piranha.AspNetCore.Identity.SQLServer;


namespace ErmlandWebsite
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(config =>
            {
                config.ModelBinderProviders.Insert(0, new Piranha.Manager.Binders.AbstractModelBinderProvider());
            });
            services.AddPiranhaApplication();
            services.AddPiranhaFileStorage();
            services.AddPiranhaImageSharp();
            //services.AddPiranhaEF(options => options.UseSqlite("Filename=./piranha.db"));
            //services.AddPiranhaIdentityWithSeed<IdentitySQLiteDb>(options => options.UseSqlite("Filename=./piranha.db"));
            
            services.AddPiranhaEF(options => options.UseSqlServer(Environment.GetEnvironmentVariable("DB")));
            services.AddPiranhaIdentityWithSeed<IdentitySQLServerDb>(options => options.UseSqlServer(Environment.GetEnvironmentVariable("DB")));
            services.AddPiranhaManager();
            services.AddPiranhaSimpleCache();

            return services.BuildServiceProvider();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider services, IApi api)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // Initialize Piranha
            App.Init(api);

            // Configure cache level
            App.CacheLevel = Piranha.Cache.CacheLevel.Basic;

            // Build content types
            var pageTypeBuilder = new Piranha.AttributeBuilder.PageTypeBuilder(api)
                .AddType(typeof(Models.BlogArchive))
                .AddType(typeof(Models.StandardPage))
                .AddType(typeof(Models.StartPage));
            pageTypeBuilder.Build()
                .DeleteOrphans();
            var postTypeBuilder = new Piranha.AttributeBuilder.PostTypeBuilder(api)
                .AddType(typeof(Models.BlogPost));
            postTypeBuilder.Build()
                .DeleteOrphans();

            // Register middleware
            app.UseStaticFiles();
            app.UseAuthentication();
            app.UsePiranha();
            app.UsePiranhaManager();
            app.UseHttpsRedirection();
            app.UseMvc(routes =>

            {

                routes.MapRoute(name: "areaRoute",

                    template: "{area:exists}/{controller}/{action}/{id?}",

                    defaults: new { controller = "Home", action = "Index" });

                routes.MapRoute(

                    name: "default",

                    template: "{controller=home}/{action=index}/{id?}");

            });
        }
    }
}
`

**Comment by AlexJPawlak** [comment]
Just realized it's not only affecting pages of type "Start page", but since I use all of them as Start pages, none of them work. Workaround here: use another page type, but I'm wondering why out of sudden all of these died?

**Comment by tidyui** [comment]
Sounds like there’s something wrong with the routing. If you run your application in the console with dotnet run you will get debug printouts every time any of the middleware intercepts a request based on slug and rewrites it.

**Comment by AlexJPawlak** [comment]
Thanks for feedback!

This is so far the output: 
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55397/
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.2.3-servicing-35854 initialized 'Db' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (43ms) [Parameters=[@__siteId_0='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [p].[Id], [p].[ContentType], [p].[Created], [p].[IsHidden], [p].[LastModified], [p].[MetaDescription], [p].[MetaKeywords], [p].[NavigationTitle], [p].[OriginalPageId], [p].[PageTypeId], [p].[ParentId], [p].[Published], [p].[RedirectType], [p].[RedirectUrl], [p].[Route], [p].[SiteId], [p].[Slug], [p].[SortOrder], [p].[Title]
      FROM [Piranha_Pages] AS [p]
      WHERE (([p].[SiteId] = @__siteId_0) AND [p].[ParentId] IS NULL) AND ([p].[SortOrder] = 0)
info: Piranha.AspNetCore.StartPageMiddleware[0]
      Found startpage
  Route: /start
  Params: id=8acc14f5-b746-4544-9aa8-a0fe94c651f8&startpage=true&piranha_handled=true
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 86.9974ms 404
```
It says it "found startpage", says it's handled by Piranha, and startpage=true . 

None of the start pages work for me, even if I delete all I have and leave only one. Any other page type works just Ok. The database is backed by old and new piranha app - both are talking to the same instance. (New one is hosted on my local PC, old one is on Azure Web app) 
Maybe there's something odd in DB ? Do you have a hint how to look up the parameters that were used in SQL Call, or should I just use SQL Profiler? I'd throw the SQL query at db by hand and see what it returns

**Comment by tidyui** [comment]
Test by surfing to /start + the query params shown in the log. Do you reach the controller listening to that route?

**Comment by AlexJPawlak** [comment]
Tried that now, looks as if Start controller never gets hit, or so it would seem to me. 

```
info: Piranha.AspNetCore.PageMiddleware[0]
      Found page
  Route: /start
  Params: id=8acc14f5-b746-4544-9aa8-a0fe94c651f8&startpage=true&piranha_handled=true
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 164.3903ms 404
```
What I might want to explore is to roll back to pre-upgrade, test out if the site works, and then do the update again... Maybe something funky happened that my start controller doesn't get the route? I take it you can't reproduce the issue and it's most likely something specific to my environment?

**Comment by tidyui** [comment]
I’ve upgraded the official PiranhaCMS.org and all templates without issues so it has to be something else. Have you changed .net core runtime version or added any other middleware into the pipeline?

**Comment by AlexJPawlak** [comment]
Sorted out! 

You said you upgraded templates just fine, so I started looking at my items one by one and it turned out I didn't use a "template" you upgraded, but used the "MVCWeb" one available in Examples (not in the templates): 

https://github.com/PiranhaCMS/piranha.core/blob/d969847abf2c487f90b2ab78ecc818a825f6c1fb/examples/MvcWeb/Controllers/CmsController.cs

I've replaced the CmsController file with actual template and it worked just fine :-) https://github.com/PiranhaCMS/piranha.core.templates/blob/master/web/mvc/Controllers/CmsController.cs

I think I'll review and cherry pick other files as well, are these new templates hosted somewhere so I can do a live lookup what they do?
