### ISSUE TITLE
Null-checking a PageField causes a NullReferenceException

### ISSUE THREAD

**Issue by stefanolsen** [PiranhaCMS/piranha.core#572]
In a template I am doing a null-check against a PageField. But if the field is null, this null-check causes an unexpected `NullReferenceException`.
This is on the top of the stack trace:
`Piranha.Extend.Fields.PageField.op_Inequality(PageField field1, PageField field2)`

It looks like the overridden inequality operator is missing a null-check or two.

Version: 6.0.1

**Comment by tidyui** [comment]
The PageField should never be null. Can you perform a field.HasValue instead?

**Comment by stefanolsen** [comment]
It could be because I added the field after a page was created. The `PageField` instance was null, but checking it against null (`pageField != null`) invoked the overridden operator which does not null-check.
I will have a look at it later, and maybe submit a PR.

**Comment by tidyui** [comment]
Adding this to the `6.1` release and closing since it's been merged. Thanks a lot!
