### ISSUE TITLE
Full caching still causes repeated SQL queries

### ISSUE THREAD

**Issue by stefanolsen** [PiranhaCMS/piranha.core#574]
When `CacheLevel` is set to `CacheLevel.Full`, and I open a blog archive it loads everything from the database on first request. This is fine.
But upon refreshing the same archive page, most of the data is fetched from cache, because my code use the Archive and Posts APIs with strong types.
However, the `ArchiveRouter` uses the `GetBySlugAsync` method without a type, effectively avoiding the cache on all requests (because of the `DynamicPage` exception).
I suggest that this call from `ArchiveRouter` gets changed, so it loads a strongly typed `PageBase` object instead. The same goes for similar routing. This would allow full caching of data.

**Comment by tidyui** [comment]
Adding this to the `6.1` release and closing since it's been merged. Thanks a lot!
