### ISSUE TITLE
Concrete classes can't be moq'd

### ISSUE THREAD

**Issue by MCNorthwood** [PiranhaCMS/piranha.core#576]
So the issue is that the IApi interface has changed from having interface properties to concrete classes which can’t be mocked by Moq unless they are virtual. Will it be possible to reference these services by interface in IApi instead of concrete classes?

**Comment by tidyui** [comment]
The repositories injected into the services (which handles data mgmt) can be mocked. As validation and service logic doesn’t need to be duplicated it show provider a simpler mocking than for 5.x

**Comment by MCNorthwood** [comment]
When using Moq you can do it within the ctor which is how it worked before.

Here's a sample with the new async method:

            var _apiMock = new Mock<IApi>();

            _apiMock.Setup(x => x.Pages.GetByIdAsync(It.IsAny<Guid>())).Returns(Task.FromResult(new Piranha.Models.DynamicPage()));

The test is just check that it does not return a null page. However comes back with:

> Message: System.NotSupportedException : Invalid setup on a non-virtual (overridable in VB) member: x => x.Pages.GetByIdAsync(It.IsAny<Guid>())

All I've managed to do is make the compiler happy with the Task.FromResult surrounding the return it however comes back with that because you cannot Mock concrete classes

**Comment by tidyui** [comment]
Hi, I was rather thinking you insert a mock for each of the repositories, like the api is created in the tests?

https://github.com/PiranhaCMS/piranha.core/blob/master/test/Piranha.Tests/Repositories/PageTypes.cs#L204

**Comment by MCNorthwood** [comment]
I've tried mocking it with an InMemoryDatabase, however the way everything is set up I just cannot get it to work because before I was mocking up the interface and what it returned however it's rather impossible because within the ctor of Db it's trying to do a migration

 protected IServiceProvider services = new ServiceCollection().BuildServiceProvider();

        public IDb GetPiranhaContext()
        {
            var options = new DbContextOptionsBuilder<Db>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            return new Db(options);
        }

        public IApi CreateApi(IDb db)
        {
            var factory = new ContentFactory(services);
            var serviceFactory = new ContentServiceFactory(factory);

            return new Api(
                factory,
                new AliasRepository(db),
                new ArchiveRepository(db),
                new MediaRepository(db),
                new PageRepository(db, serviceFactory),
                new PageTypeRepository(db),
                new ParamRepository(db),
                new PostRepository(db, serviceFactory),
                new PostTypeRepository(db),
                new SiteRepository(db, serviceFactory),
                new SiteTypeRepository(db));
        }

The mocking up simply would end up being to much to maintain compared to how it was before

**Comment by tidyui** [comment]
We can add interfaces for the service in the upcoming version. I'll add it as a feature request!

**Comment by MCNorthwood** [comment]
Thank you I do really appreciate it.

**Comment by niem94** [comment]
@MCNorthwood Did you ever get this to work? Ive been fiddling with it most of the evening, and I can't seem to get it to work myself. Would be very helpful if you have some reference code I can have a look at :-)

**Comment by MCNorthwood** [comment]
@niem94 This is the billy basics for Moq. If you use a type just return that page type within Task.FromResult. e.g. Task.FromResult(new BasicPageType(){Title = "Test"})
` 

                 var _apiMock = new Mock<IApi>();

                _apiMock.Setup(x => x.Pages.GetByIdAsync(It.IsAny<Guid>())).Returns(Task.FromResult(new Piranha.Models.DynamicPage()));
                
                var result = await new Index.PageHandler(_apiMock.Object)
                    .Handle(new Index.Query() { Id = Guid.NewGuid() }, CancellationToken.None);

                result.Page.Should().NotBeNull();
`
the Page here is the Dynamic Page which Piranha's IApi in this instance is returning a Dynamic Page. Make sure you pass in the object of the mocked instance through the constructor wherever you are trying to test. I've managed to create a unit test for about most of the methods under the page repo as well as the archive.

**Comment by niem94** [comment]
Thanks!! My problems were mostly with me using razor pages - its a bit different. Your code helped me plenty though, and I can now easily unit test my pages. I was actually really close myself, my problem was that I tried to test fro expectedGuid versus actualGuid, but that proved way more complex than just testing whether a page is returned.

For razor pages the above looks like this:

`  
//Arrange
var mockIApi = new Mock<IApi>();
mockIApi.Setup(x => x.Pages.GetByIdAsync(It.IsAny<Guid>())).Returns(Task.FromResult(new Piranha.Models.DynamicPage()));

//Act
var result = new StandardPageModel(mockIApi.Object).OnGet(Guid.NewGuid());
            
//Assert
Assert.NotNull(result);
`

where StandardPageModel is the code behind for my standardpage.cshtml file.

**Comment by tidyui** [comment]
Great work! If any of you would be interested in writing a blog post about setting Unit Testing with mock for Piranha we're thinking about opening up for guest writers at http://piranhacms.org. Guest writers will be presented with their photo, name, description and website link of their choice!

**Comment by niem94** [comment]
Sounds interesting! I wouldn't mind doing that in the summer. I just need to get through some exams, and get a better understanding of Mock with Piranha first. Would be cool to share a bit more than just using it with Pages :-)
