### ISSUE TITLE
Items on a BlockGroup does not gets serialized on posts, but works on pages

### ISSUE THREAD

**Issue by stefanolsenn** [PiranhaCMS/piranha.core#577]
Hi @tidyui 

So I upgraded to 6.0.2 in the EF package as you suggested, and checked that all the other packages are up to date, and tried again. And it works, yah! But only on a standardpage or a startpage.

It saves the actual blockgroup in the db, but not the children of the blockgroup. So the results are as it were the first time; an empty array when it gets serialized.

The code is same as in issue #543

**Comment by tidyui** [comment]
Thanks for your feedback! Some errors seem to have snuck into the code when it was refactored during the 6.0 development. We’ll take a look and compare the Page & Post Services.

Regards

**Comment by stefanolsenn** [comment]
All good! Thanks for your work, and the quick feedback. It's much appreciated!

**Comment by stefanolsenn** [comment]
Hi @tidyui Any update on this, or any particular way you would recommend as a temporary solution?

**Comment by w0ns88** [comment]
Hi @tidyui it would be great to have the `BlockGroup`  working for version 6.1. Would this be possible to be check soonish at all?

Regards

**Comment by tidyui** [comment]
This has now been fixed in master and will be deployed in `6.1`
