### ISSUE TITLE
Website Documentation PRs

### ISSUE THREAD

**Issue by i-love-code** [PiranhaCMS/piranha.core#578]
Any chance the website itself could be open sourced in order to allow for PRs to improve the documentation on http://piranhacms.org/docs? Some of it is a bit out of date with minor changes and could benefit from active development just submitting PRs for accurate examples/documentation.

Example:
http://piranhacms.org/docs/basics/select-fields

The select field registration appears to be at App.Fields.RegisterSelect<> instead of App.RegisterSelect<> now.

**Comment by tidyui** [comment]
Yes, I’d love that. I will start looking into providing flat file repository implementation after the new manager interface is done. When that is in place it would be much easier to commit data changes to that repository.

**Comment by tidyui** [comment]
This is done! Check out the piranha.core.docs repo!
