### ISSUE TITLE
Using Manager Login - ReturnUrl in LoginModel is allways null

### ISSUE THREAD

**Issue by fdhighhead** [PiranhaCMS/piranha.core#579]
Hi guys, 

its my first issue so excuse me for any mistakes.

Going directly to e.g. "baseUrl/manager/users" the login form shows up.
Adress in Browser is "baseUrl/manager/login?ReturnUrl=%2Fmanager%2Fusers".

Debugging the login process shows that the UserName and Password is passed correctly but the ReturnUrl is allways null. This szenario is in all common Browsers (Edge, Ff, Chrome etc.) the same.

If i use e.g. Postman to test the Post-Request by using either 
"baseurl/manager/login?ReturnUrl=%2Fmanager%2Fusers&UserName=admin&Password=password" 
or
"baseUrl/manager/login?ReturnUrl=%2Fmanager%2Fusers" (UserName and Password as form-data) 
the login process runs as expected...

I used the latest piranha.core master repo to debug the Piranha.Manager component.

Thanks for your good work!
Greetings and have a nice week.

**Comment by pkreemer** [comment]
Are you using https? I think I saw the same symptoms when running just http.

**Comment by tidyui** [comment]
It looks like the view isn’t actually forwarding the LoginUrl to the login action

**Comment by fdhighhead** [comment]
> 
> Are you using https? I think I saw the same symptoms when running just http.

Yes i tried. Same issue.

> 
> 
> It looks like the view isn’t actually forwarding the LoginUrl to the login action

I just tried to forward returnUrl as a hidden field - that worked.

If i get it right, the DefaultIdentity given by Microsoft uses in the Login view the whole LoginModel, not only the string (returnUrl). So i guess there is something wrong?

thank you for your quick answer!

**Comment by tidyui** [comment]
We'll add the `ReturnUrl` to the login view for `6.1`

**Comment by nahojd** [comment]
This seems to have disappeared again in the new manager interface from version 7.0, because ReturnUrl does not work at all. And in [Login.cshtml](https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Areas/Manager/Pages/Login.cshtml) there is no ReturnUrl, nor in Login.cshtml.cs.
