### ISSUE TITLE
Archive page returns 404 when request URL has trailing slash

### ISSUE THREAD

**Issue by stefanolsen** [PiranhaCMS/piranha.core#580]
If I add trailing slashes to all URLs on my site, the BlogArchive page returns 404 (`/posts` works, `/posts/` returns 404).
It looks like the ArchiveRouter breaks up the URL into segments by each slash, and then expects that a second segment be a year.
I would like the routing to support optional trailing slashes, and let me decide whether or not to use those.

**Comment by tidyui** [comment]
Added this to 6.1 and closing as the PR is merged. Thanks!

**Comment by mkarlsson** [comment]
I think your fix might have broken my route. Now I can't have trailing slash in slug, gives a 404. Removing it solves it. This question led me to the answer.
