### ISSUE TITLE
Reference fields should use cached data

### ISSUE THREAD

**Issue by stefanolsen** [PiranhaCMS/piranha.core#588]
As mentioned in #582, I believe the Init methods in PageField, PostField and MediaField could use the cached and typed version of GetByIdAsync(). This way all instances of these field types would avoid a round-trip to the database when data is already in cache.
As it is a breaking change, it should probably go into version 7.0.

**Comment by tidyui** [comment]
Closing this issue as reference fields uses cached Info-models in 7.0
