### ISSUE TITLE
NullReferenceException when creating new page from code

### ISSUE THREAD

**Issue by dankva** [PiranhaCMS/piranha.core#590]
using Microsoft.AspNetCore.Mvc;
    using Piranha;
    using System;
    using System.Collections.Generic;
    
    namespace ResidentalPicker.Frontend.Web.Controllers
    {
        [Area("Manager")]
        [Route("ResidentalPickerManager")]
        public class ResidentalPickerManagerController : Controller
        {
            private readonly IApi _api;
            private readonly IDb _db;
    
            /// <summary>
            /// Default constructor.
            /// </summary>
            /// <param name="app">The current app</param>
            public ResidentalPickerManagerController(IApi api, IDb db)
            {
                _api = api;
                _db = db;
            }
    
            [HttpGet("Index")]
            public IActionResult Index(Guid id)
            {
                return View();
            }
    
            [HttpGet("CreateSingleSite")]
            public void CreateSingleSite(string client)
            {
                var clientSite = _api.Pages.GetBySlug(client);
    
                if (clientSite != null)
                {
    
                    var residentalPickerSite = Models.ResidentalPicker.Create(_api);
                    //var residentalPickerSite = Models.StandardPage.Create(_api);
    
                    residentalPickerSite.SiteId = clientSite.Id;
                    residentalPickerSite.Title = "TestBrf";
                    residentalPickerSite.ContentType = "Pages";
                    residentalPickerSite.SortOrder = 1;
                    residentalPickerSite.MetaKeywords = "Meta Key Words";
                    residentalPickerSite.MetaDescription = "MetaDescription";
                    residentalPickerSite.Created = DateTime.Now;
                    residentalPickerSite.LastModified = DateTime.Now;
                    residentalPickerSite.Published = DateTime.Now;
                    residentalPickerSite.Image = "";
                    residentalPickerSite.Blocks.Add(new Piranha.Extend.Blocks.HtmlBlock { Body = "<p>param baram</p>" });
                    residentalPickerSite.Permalink = "/fastighetsbyran/testbrf";
    
                    _api.Pages.Save(residentalPickerSite);
                }
            }
            
        }
    }

When trying to save a new page through the api (_api) I get an error "NullReferenceException: Object reference not set to an instance of an object." And I really don't know why.

Below is the Stack-info

> Piranha.Repositories.PageRepository.Save<T>(T model)
ResidentalPicker.Frontend.Web.Controllers.ResidentalPickerManagerController.CreateSingleSite(string client) in ResidentalPickerManagerController.cs
+
                _api.Pages.Save(residentalPickerSite);
Microsoft.Extensions.Internal.ObjectMethodExecutor+<>c__DisplayClass33_0.<WrapVoidMethod>b__0(object target, object[] parameters)
Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(object target, object[] parameters)
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Piranha.Manager.ResourceMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Piranha.AspNetCore.SitemapMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
Piranha.AspNetCore.StartPageMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
Piranha.AspNetCore.ArchiveMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
Piranha.AspNetCore.PostMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
Piranha.AspNetCore.PageMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
Piranha.AspNetCore.AliasMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
Piranha.AspNetCore.ApplicationMiddleware.Invoke(HttpContext context, IApi api, IApplicationService service)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by tidyui** [comment]
ClientSite is a page and not a site, meaning that you’re setting the SiteId of the new page to another page Id.

**Comment by dankva** [comment]
Thank you very much!
