### ISSUE TITLE
Can't create new category for blog post in manager

### ISSUE THREAD

**Issue by expectedsemicolon** [PiranhaCMS/piranha.core#594]
When I attempt to add a new item/post to a blog archive in the manager (6.0.2), the UI doesn't allow me to enter a new category, I can only choose an existing category from the dropdown. This is true in the site I'm working on as well as a fresh BlogTemplate. If I create a blog post programmatically in my own code or the /seed action in the example, it creates a new category for the new blog post without issue. 

I searched recent issues, and the only thing close was #557, but that's fixed, and the behavior is different (I don't get an error -- it just ignores whatever is typed for Category).

Thanks much, and sorry if I'm just missing something in the UI.

**Comment by tidyui** [comment]
Just type the new category name in the text box/select and hit enter!

Regards

**Comment by expectedsemicolon** [comment]
Thanks, man! Had trouble finding the [any key](https://en.wikipedia.org/wiki/Any_key).
