### ISSUE TITLE
Support for horizontal block groups 

### ISSUE THREAD

**Issue by niem94** [PiranhaCMS/piranha.core#599]
I am missing the feature to create blocks inside of blocks. Preferably with the possibility of having nested blocks inside of nested blocks and so on.

This would allow us to create more freedom for the content administrators, and to create more generic blocks, that could be fitted together as seen fit. Obviously it should be possible to constrain which blocks should be allowed inside of other blocks.

I know there are the blockgroups, but their purpose seems different. Correct me if i am wrong.

I would love to develop this feature in the summer, with some guidance, as that would teach me alot about piranha, and hopefully let me contribute more in the future.

**Comment by tidyui** [comment]
HI there! Blocks is feature that is intended 100% for non technical content editors. I’m having a hard time visualizing how the complexity you’re describing could be generically presented in an easy way.

Perhaps we could approach this from the another perspective. What specific problems are you trying to solve and what kind of content are you trying to create that you feel you can’t with the current content model.

Regards

**Comment by niem94** [comment]
What i want is seperate layout blocks like a ColumnBlock or a ContainerBlock, which i then want to be able to insert my other blocks into. I dont want my other blocks to be restricted to a certain layout or content upfront, as i want to reuse blocks on different sites.

Imagine two columns with a image on one side and text on the side. If i want to do this with blocks, i need to make either a ImageWithTextBlock, that has the columns and everything in it, or (not possibly yet) create a TwoColumnBlock which can have nested blocks. I can then put in my ImageBlock and TextBlock on whatever side i like. I would also be able to allow more blocks through constraints so i would be able to fx put another TwoColumnBlock (would create 4 columns in total) or a VideoBlock in it.

I do not think this will necessarely increase complexity for the content administrators, if done correctly, and with care for which blocks one allow to be nested. My idea is that it could be done in a similiar way to how ApostropheCMS implemented this. See midpage (https://docs.apostrophecms.org/apostrophe/tutorials/getting-started/layout-widgets). I used that before learning the .Net way and trying out PiranhaCMS. It was really cool, and in my opinion very easy to use.

**Comment by tidyui** [comment]
Great, now I know what you're after in terms of functionality. In `7.0` the **default** layout for block groups will be a master/detail view like this.

![Skärmavbild 2019-04-26 kl  12 45 37](https://user-images.githubusercontent.com/781266/56802818-59b8bf00-6821-11e9-8c1f-cc87db1b03bb.png)

We've also discussed including other layout options for block groups, like **horizontal** (columns) and **vertical** (flow). This in conjunction with another feature that we've had on our wishlist is being able to specify `MaxItems` and `MinItems` on list regions & block groups.

With this in place, you could easily create a block group for what you're after, something like this.

    
    [BlockGroupType(Name = "Columns", Category = "Content", Icon = "fas fa-images", 
        Display = BlockDisplayMode.Horizontal, MinItems = 2, MaxItems = 4)]
    public class ColumnBlock : BlockGroup
    {
    }

This would then produce a group with a horizontal column layout that could contain 2-4 blocks. We will probably **not** open up for the possibility of adding block groups into block groups though as we want to keep it simple both for the editor & from a data perspective.

How does this sound?

**Comment by niem94** [comment]
This sounds really good. By the information given here, it does seem solve the problems i am having.
Just to be sure, will the horizontal layout option be a part of 7.0, or will it be in a later release?

**Comment by tidyui** [comment]
Hi! Horizontal layout will be a part on 7.0, we’ll see if we have time to implement maxitems & minitems for the major release though.

Regards

**Comment by tidyui** [comment]
<img width="977" alt="Skärmavbild 2019-04-30 kl  18 03 05" src="https://user-images.githubusercontent.com/781266/56976009-46d02280-6b72-11e9-8c35-e6dad890c98f.png">

**Comment by niem94** [comment]
That is just perfect. It is exactly what i’ve been missing. Great work! 😃

Should i close the issue, or do you usually do that? 😊

**Comment by mrccarvalho** [comment]
Hi!

> Example of horizontal block group with one HtmlBlock and one ImageBlock:

Hi!
Is there possibility to add the ImageGalleryBlock into a column ?
we can add HtmlBlock , ImageBlock, VideoBlock, AudioBlock, Separator.

Thanks

**Comment by tidyui** [comment]
Hi there @mrccarvalho! It's not possible to add a Block Group into a Block Group, that's why it's not visible when selecting which item to add.
