### ISSUE TITLE
Create page in hierarchical position

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#60]
Add contextual buttons in the manager site map to add pages directly to a hierarchical position. This should also calculate the correct hierarchical slug for the page.

**Comment by gyretech** [comment]
Should this default to a particular PageType?

**Comment by tidyui** [comment]
When clicking "Add after" or "Add below" icons a modal should open, preferable in conjunction to the mouse pointer (like a tooltip). This tooltip should show the same available page types like the main "Add" button.

When clicking it takes the user to the Add/Edit view with ParentId and SortOrder pre-filled. This should also trigger the slug to automatically get the hierarchical name calculated when saving!

/Håkan
