### ISSUE TITLE
When uploading to Azure Blob Storage, provide option for default cache control

### ISSUE THREAD

**Issue by AlexJPawlak** [PiranhaCMS/piranha.core#600]
Hey there!

A suggestion you might want to implement:
When Azure Blob storage is in use to store media files, provide a setting for cache control - it's not set up by Azure service, but can be pushed with configuration change. See more details here:

https://social.technet.microsoft.com/wiki/contents/articles/25528.azure-blob-storage-and-effective-use-of-cache-control-property.aspx

You might want to implement a default setting for cache control (say 1 month) and expose this setting to be modified willingly?

**Comment by tidyui** [comment]
Good idea! However, since it’s so cheap, it’s still my recommendation that you put Azure CDN in front of Blob Storage and let the CDN worry about the expiration. Plus you get better throughput at the same time 😁

http://piranhacms.org/blog/setting-up-piranha-for-azure-cdn

**Comment by AlexJPawlak** [comment]
I was happy to use this chance to spin up another Azure function with blob trigger to get the job done ;-) 

Feel free to close it,  I guess I'll add CDN in the end to my endpoint :-)
