### ISSUE TITLE
Manual User Validation

### ISSUE THREAD

**Issue by mpjones84** [PiranhaCMS/piranha.core#601]
I have a few users added to the site, I have created a rest api for one of the pages, how would I add validation to that api.

Ideally id like to check against the SimpleUser objects added during startup.

**Comment by tidyui** [comment]
Hi there! Piranha doesn't have any special authorization mechanism so basic mvc behavior applies, i.e:

    // This will prohibit all unauthorized users to access the controller
    [Authorize] 
    [ApiController]
    public class MyApiController : Controller
    {
        // Checks that the current user has the specified policy
        [Authorize(Policy = "PolicyName")] 
        public IActionResult<...> MyAction(...)
        {
           ...
        }

        // This allows unauthorized users even though the controller is authorized
        [AllowAnonymous] 
        public IActionResult<...> MyOtherAction()
        {
            ...
        }
    }

Best regards

**Comment by mpjones84** [comment]
Thanks, I just wondered if I could access the SimpleUser objects added during start up, if not I can move these out to somewhere accessible to both.

Appreciate your quick response.
