### ISSUE TITLE
Passing Data from Manager to All Pages

### ISSUE THREAD

**Issue by TiKevin83** [PiranhaCMS/piranha.core#607]
I've been digging around the manager backend in a test site and learning how to add new kinds of regions, for instance I set up a "slide" Region to start pages, which each start page can render into a unique slideshow.  However, in the menu I wanted to add an external "login" area, with the different login options being constant across all pages.  I read the documentation on [Manager Views](http://piranhacms.org/docs/manager-extensions/manager-views) but I could use some examples of building a custom module like that in action.  I'm not seeing how it would let me pass the data from there to each page.

**Comment by tidyui** [comment]
Hi there! Could you provide some more information as I'm not really sure what you want to achieve. Do you want to:

* Add other forms of login/authentication to your application that local users?
* Specify per page if the user should be logged in to be able to see it?

Or do you just want to pack functionality into a redistributable module that should contain manager components?

Regards

**Comment by TiKevin83** [comment]
I'm trying to build an external login section in the menu partial of the layout.  But I'd like the list of links to external logins to be editable in the manager backend and be constant across every page, so that they don't have to be set up for each page.

**Comment by tidyui** [comment]
Aha! Now I know what you're trying to do. For this you should probably set a `SiteType` for your site. It's just like a `PageType` or `PostType` where you can create different regions, but you then assign it to your site for adding Site Global content.

http://piranhacms.org/docs/basics/how-to-setup-content/site-types

How this helps!

Best regards

**Comment by TiKevin83** [comment]
Neat,
I had some fumbles figuring out that SiteTypeAttribute missing a title referred to setting the Attribute [SiteType(Title= "X")] but I think I've set up what I was looking for.  Now that I can add regions to the global site, how do I access that data from a view?

**Comment by tidyui** [comment]
You can access it from the `ApplicationService`, see the bottom of this article:

http://piranhacms.org/docs/basics/application-service

Best regards

**Comment by TiKevin83** [comment]
That did it!  Thanks!
