### ISSUE TITLE
External URL menu items - Feature request

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#612]
When integrating with existing pages / sites, it would be nice to be able to add an external URL as a menu item in piranha. And be able to move it up/down like existing pages.

This would allow flexibility when adding say a 3rd party shopping cart/e-commerce/customer code pages to the pirahnacms menu

ie.     home   about  shop  contact  

Where the 'shop' is a url not a pirahnacms page.

Maybe a new "External Page" type ? With just the external URL / menu name as properties ?

**Comment by tidyui** [comment]
Hi there, if you open the `Settings` for a page you can set `Redirect` and `RedirectType` for the page. The redirect will then be used when rendering the menu.

<img width="572" alt="Skärmavbild 2019-05-10 kl  14 30 35" src="https://user-images.githubusercontent.com/781266/57527602-6284b700-7330-11e9-9467-bbd0fa550789.png">

Best regards

**Comment by CastleSoft** [comment]
Ahh. Thanks, will give it a shot.
