### ISSUE TITLE
[Bug] Two imagefields on one page aren't updating right

### ISSUE THREAD

**Issue by patrickdemooij9** [PiranhaCMS/piranha.core#614]
Currently I have a BlockGroup. The Block under it has 1 imagefield. Adding the first block with the image seems to work fine, but when I add another item and try to add another image, the image input just stays empty. The image input of the first imagefield changes to the image I just tried to upload. However when I reload it's all fine again. It seems like the first imagefield is being used for showing the input.
I can show how to reproduce it with steps if that's needed.

**Comment by tidyui** [comment]
We might release a 6.1.1 patch and then we can see if we can fix this. This error doesn’t exist in the new manager that will be released in 7.0

**Comment by tidyui** [comment]
Closing this issue as it is fixed in 7.0
