### ISSUE TITLE
Can't login with credentials shown in the templated home page

### ISSUE THREAD

**Issue by rossdonald** [PiranhaCMS/piranha.core#616]
I am trying to evaluate Piranha but the admin login doesn't work.

I made a new project from the template as described here 
http://piranhacms.org/docs/introduction/getting-started/project-templates

It runs and says
"You can log into the admin panel at ~/manager with the default credentials admin / password"

Those credentials give no error but stays on the same login page asking for username and password. Trying a different username shows a red error message. I browsed the SQlite db and there is an admin user in the users table.

I tried adding a test user but it doesn't create in the SQLite
```
services.AddPiranhaSimpleSecurity(
new Piranha.AspNetCore.SimpleUser(Piranha.Manager.Permission.All())
{
	UserName = "test",
	Password = "test"
}
);
```
Any ideas how to login?

**Comment by tidyui** [comment]
Hi there! The project templates doesn't actually use `SimpleSecurity`, they use `Identity`, so adding a user that way won't affect the login unless you've changed it. One issue that can occur is if you create the template, which by default is setup for SQLite, change it to use SqlServer but you forget to change Identity package as the migrations are different for SQLite and SQLServer.

Regards

**Comment by tidyui** [comment]
I can see now in your issue that you're using SQLite and have verified the user in the database. One issue I've experienced in the past is that there's a stray Identity login cookie lurking around in the browser from another login in another application, i.e Identity thinks the user is authenticated but then the claims doesn't match the manager so you're redirected back to the login view. Have you tried clearing your browser cache before logging in?

**Comment by rossdonald** [comment]
Yes it was the login cookie from another app that I have been building on localhost. I've setup some custom host names for development so the cookies don't conflict. thanks for the help.
