### ISSUE TITLE
Is there a way to make a reference to a region within another region, inside the manager ?

### ISSUE THREAD

**Issue by Harksa** [PiranhaCMS/piranha.core#619]
Hello, thanks for creating and updating Piranha !

I have a question that probably seems a bit tricky. I have created two custom regions that are in aIList in the same page. Both regions are very basic but the second region contains a dropdown list and I want to make a reference to the IList of the first region.

The end result I want, in the html page i,s a list of columns displaying different elements each.

Thanks in advance for your help!

**Comment by tidyui** [comment]
Hi there @Harksa! There's no built in functionality for cross-referencing items in different regions or blocks. It would be easier to implement such functionality in the upcoming manager (`7.0`) as the manager is using Vue.js. This means you could get access the entire page model being edited from your custom field or block.

**Comment by Harksa** [comment]
Hi, thank you for your response!
I am looking forward for this release 😄

**Comment by tidyui** [comment]
Closing as the question has been answered.

**Comment by Harksa** [comment]
Hello @tidyui , could you provide a small exemple on how to do so, please ?
Like for example having the text inside a text block duplicated inside another one ?
Thanks again.
