### ISSUE TITLE
Media card view in the manager

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#62]
The media library now shows folders and uploaded assets in a folder-like manner, much like the file explorer. It would however be nice to have the option to view the media library in a more card based view with large thumbnails for all of the uploaded assets.

**Comment by tidyui** [comment]
This will most likely be done together with #199.

**Comment by dannykay1710** [comment]
This would definitely be something I'd be interested in - most images in the CMS I'm migrating from are using the file names straight from the camera!
