### ISSUE TITLE
Getting archive by category isn't populating category property

### ISSUE THREAD

**Issue by MCNorthwood** [PiranhaCMS/piranha.core#620]
So in 6.1 I am doing this
`result.News.Archive = await _api.Archives.GetByIdAsync(request.Id, request.Page, request.Category.Value);`
and then under Archive, the Category is not populating, so I'm trying to pass the id onto the view and it's not there so when it loads more posts it's loading all of them instead of more of the same category. I think it may be the same case when you try bring them back with the base class although I currently can't confirm that.

On a side note, there seems to be no way to update the blog page to specifying the archive type. So you get the type of the post back instead of dynamic as I delete the orphans. I do know how I can get around this but there isn't an easy way to move posts from one blog page to another is there? So I would suggest perhaps in the settings of the post being able to change blogs if there is another one (I can split this request into another if you think it's a good idea)

**Comment by tidyui** [comment]
Hi there! I'll try to get some tests in place to verify your error. However it seems strange as http://piranhacms.org uses `6.1` and both categories and tags are populated. Regarding updating the Blog Page I successfully updated the Blog Archive for PiranhaCMS without issues by just updating the base class from:

    public class BlogArchive : ArchivePage<BlogArchive>

to:

    public class BlogArchive : ArchivePage<BlogArchive, BlogPost>

As the class name of the Archive hasn't changed there's no problem in updating it's base class. If you however have used your archive page for several archives with different post types you can always create a wrapper model for your archive pages:

    public class MyArchiveWrapper<T> where T : PostBase
    {
        public MyArchivePage Page { get; set; }
        public PostArchive<T> Archive { get; set; }        
    }

Then you can return archives of different types to your views depending on what you want to load.

**Comment by MCNorthwood** [comment]
Thanks for the quick response, what I have is currently
`public class NewsPage : ArchivePage<NewsPage>`
which only has two post types that use it and is the only archive. When I got the posts back as DynamicPosts the .Archive didn't have category populated.

So I'm first getting

`result.News = await _api.Pages.GetByIdAsync<NewsPage>(request.Id)`

then for the category part
`result.News.Archive = await _api.Archives.GetByIdAsync(request.Id, request.Page, request.Category.Value);`

and I put a watch on it and it bring back 15 posts, CurrentPage is 1, TotalPages is 2 and TotalPosts is 25 and the category is null. The type of the Archive is PostArchive<DynamicPost>

**Comment by tidyui** [comment]
The "problem" with using `Archives.GetByIdAsync` is that it returns an archive of `DynamicPost` objects. As of version `6.0`, dynamic models are no longer cached as the service layer is no longer responsible for model transformation. This means that posts will be loaded from the database every time instead of being fetched from cache. The following statements will end up fetching the post models from cache:

    _api.Archives.GetByIdAsync<PostInfo>(request.Id, request.Page, request.Category.Value);
    _api.Archives.GetByIdAsync<PostBase>(request.Id, request.Page, request.Category.Value);
    _api.Archives.GetByIdAsync<YourPostType>(request.Id, request.Page, request.Category.Value);

The first will return `PostInfo` models which is a lighter model **without** regions & blocks. `PostBase` means that models will be removed as their typed class (in your case one of your two Post Types). `YourPostType` means that you specify that you only want posts of a certain type.

It's extremely weird that your posts is not returning a category as the `ArchiveService` will end up calling `api.Posts.GetByIdAsync`, so if you're not getting any categories at this stage, you shouldn't get any if you load the post detail page.

**Comment by MCNorthwood** [comment]
So I'm trying it out with the new way from your docs although I think I'm doing it wrong?

` public class NewsArchive<T> : ArchivePage<NewsArchive<T>, T> where T : PostBase`

I think in your example in the docs it didn't have the <T> `ArchivePage<NewsArchive, T>` but the compiler complains otherwise. Would it be better doing it like `public class NewsArchive : ArchivePage<NewsArchive, PostBase>` this then?

Also what about flipping one post to another blog. I can simply go into the database and copy the blogId into the post to move them. But would it be a possible implementation to add?

**Comment by tidyui** [comment]
After discussion the bug has been confirmed that `ArchiveService` is not setting Category property on the `PostArchive` model.

**Comment by i-love-code** [comment]
@tidyui Any chance of this fix getting into a 6.X version? I'm running into the same issue, but with the Tag property. It appears you fixed that too in this commit.
