### ISSUE TITLE
Adding description property to Fields

### ISSUE THREAD

**Issue by w0ns88** [PiranhaCMS/piranha.core#621]
Hi @tidyu,

It would be awesome to add a description to a Field so that, in the manager, when hovering over the title, the description would be shown in a tooltip for example.

It would be added like the title property like so:

```
[Field(Title="Title", Description="This field contains the title of the block")]
public StringField Title { get; set; }
```

**Comment by tidyui** [comment]
Hi! The fields

* `CheckBoxField`
* `DateField`
* `NumberField`
* `StringField`
* `TextField`

all supports the `Placeholder` property on the `FieldAttribute`. For checkboxes this is shown as the label next to the actual checkbox, for the others the value is used as placeholder in the input field.

**Comment by w0ns88** [comment]
I feel a placeholder should be concise, I was more thinking of adding a larger description (for some of our fields a whole paragraph would be needed).
