### ISSUE TITLE
Suggestion - preview changes before saving a published page

### ISSUE THREAD

**Issue by morkonom** [PiranhaCMS/piranha.core#622]
A preview button that would save a temporary page for viewing would be a nice feature. Previewing changes to already published pages isn't very meaningful if you have to save the page first.

I see something like this mentioned in #428 - perhaps this is already in the works for 7.0? In that case - sorry for the duplicate.

**Comment by tidyui** [comment]
Hi there! Yes this ties into #289, but the suggested solution there is that you can save a draft/working copy of an already published page and then preview that draft. When you're finished working on the new version of the page you update the published version, but I think this fills the same purpose!

**Comment by Tojno** [comment]
I second that. This is really a show-stopper for us.

**Comment by tidyui** [comment]
Revisions including drafts will be included in 7.0. Functionality for browsing and restoring a previous revision will come in a 7.x release.

Regards

**Comment by tidyui** [comment]
Implemented for `7.0`
