### ISSUE TITLE
Struggling to Model a Slider with Slides

### ISSUE THREAD

**Issue by runxc1** [PiranhaCMS/piranha.core#623]
So I have a site listing puppies for sale,  each with a Name, picture, birth date etc.   I'd like to create a slider block that can be put on a page that will show each of the puppies.   I am struggling to model this as the Block type doesn't seem to have any IList Fields.   Is the only way to accomplish this to create a specific Page Type and add a Region to it?

**Comment by tidyui** [comment]
Hi there! Yes you can create a `BlockGroup` for this. The documentation is unfortunately a bit lacking on this point, but the syntax looks something like this:

    [BlockGroupType(Name = "Slider", Category = "...", Icon = "...")]
    [BlockItemType(Type = typeof(SliderItemBlock)]
    public SliderBlock : BlockGroup
    {
    }

    [BlockType(Name = "Slider Item", IsUnlisted = true, Category = "...". Icon = "...")]
    public SliderItemBlock : Block
    {
       ...
    }

The `SliderBlock` is the group containing the items. The `BlockItemType` attribute specifies that **only** blocks of this type can be added into the group, remove the attribute and all blocks (except groups) can be added to the group.

The `SliderItemBlock` is the block that should be added to the slider group. The property `IsUnlisted` means that the block won't be available when adding blocks to the page at root level, it will only be visible when adding blocks to the group.

Best regards
