### ISSUE TITLE
MvcWeb Example Navbar

### ISSUE THREAD

**Issue by TiKevin83** [PiranhaCMS/piranha.core#624]
I noticed the duplicate desktop and mobile navbars in the example MvcWeb project.  My fork has an updated example using a single responsive navbar if you'd like to take a look for a pull request.

**Comment by tidyui** [comment]
Sounds great! I think it's the same solution atm in the template projects as well. https://github.com/PiranhaCMS/piranha.core.templates

**Comment by i-love-code** [comment]
It is the same as the template projects. Would love to see the project templates use a consolidated navbar. When I built a project based off the MVC Blog template, I spent time doing the same updates to consolidate the navbar.

**Comment by TiKevin83** [comment]
I added the pull request.  I was actually looking to do it for the razor pages example but that didn't seem to build right when I loaded it up as it uses .net core 2.1 while the rest of the project is on 2.2, so I jumped back and set it up on the MvcWeb example.

**Comment by tidyui** [comment]
Ah, yes the master branch is in some transformation since we're working on the `7.0` release and we haven't updated the Razor example yet.

**Comment by tidyui** [comment]
Merged into master
