### ISSUE TITLE
Published Page Id Null Reference

### ISSUE THREAD

**Issue by karan8794** [PiranhaCMS/piranha.core#630]
Hiii... I got Undefined Id while Save Or Update any page like Teaser Page or Standard Page or Blog Archive.
I had installed Piranha Packages to create a CMS pages. i had also created  HTML pages and CMS Controller as like as in Piranha.
Still I am facing error like this while i am saving the page.
I can't understand from where i can resolve this.
Please Help me,if anyone knowing about it.

![error](https://user-images.githubusercontent.com/50948151/58244531-64a73680-7d70-11e9-9db2-3f4f3d848992.png)

**Comment by tidyui** [comment]
Hi there! Have you sorted this out. It looks like something is not working in the javascript responsible for saving the page as your URL contains `undefined`

**Comment by tidyui** [comment]
Closing this due to lack of response. If you need more help please open a new issue.

Best regards
