### ISSUE TITLE
how to set and debug Piranha.Manager as startup project

### ISSUE THREAD

**Issue by zareiramin** [PiranhaCMS/piranha.core#631]
Hi,

How we can start Piranha.Manager directly from VS? I'm asking this because i'm changing/developing code base of Piranha.Manager and need to debug it directly (without running MvcWeb).

**Comment by tidyui** [comment]
Hi there! You would have to change the project type as it is a class library and then add all of the necessary startup code, content types you want to test with and so on.

Best regards

**Comment by zareiramin** [comment]
Dear tidyui,

Since **Pianha.Manager** is refrenced by **Piranha.AspNetCore.Identity** we can not change it's project type to dotnetcore to run it as web application. So we can not run **Pianha.Manager** directly :(.

Also merging Piranha.Manager with MvcWeb is not possible because of the same issue.

What do you suggest?

Best Regards,
Ramin

**Comment by tidyui** [comment]
I don’t see why you need to do this in the first place? The idea with the manager is that you include it in the end application. If you reference the project and compile in debug you can still set breakpoints in the manager even though it’s not the startup project?

**Comment by zareiramin** [comment]
Because i need to restart application to make changes apply, like small changes in views of Prianha.Manager. And this is so time consuming and cumbersome. While any change to views of MvcWeb applies with reloading page and doesn't need to restart application.

**Comment by tidyui** [comment]
For view development, copy the manager view folder to the same location in MvcWeb while developing. When you’re done, copy the updated files back to the manager project.

Best regards
