### ISSUE TITLE
How can i add a page that requires a user login (not part of the manager)

### ISSUE THREAD

**Issue by Lewis-Bass** [PiranhaCMS/piranha.core#632]
I would like to add a new page that requires the user to login with a specfic role. I can create the role and the user using the manager. I just dont know how to add a new page with the security being required.

**Comment by tidyui** [comment]
Hi there! Check out our latest blog post which has some tips and tricks for this!

http://piranhacms.org/blog/techniques-for-securing-pages

Regards

**Comment by tidyui** [comment]
Closing as question has been answered
