### ISSUE TITLE
Is it possible to have a IList<T> (Collection region) within a region?

### ISSUE THREAD

**Issue by stefanolsenn** [PiranhaCMS/piranha.core#633]
The current functionality for displaying a collection as a region is as simple as adding a IList<T> on a page:
```
public class StartPage : Page<StartPage>
{
        [Region(ListTitle = "Title")]
        public IList<Slide> Slides { get; set; }
}
```

What I need to archive is storing a StringField with the list of Slides. So something like this:
```
public class HeroRegion
{
        public IList<Slide> Slides { get; set; }
        public StringField StringField { get; set; }
}
```
```
public class StartPage : Page<StartPage>
{
        [Region] 
        public HeroRegion HeroRegion { get; set; }
}
```

**Comment by tidyui** [comment]
Hi there! Given the current data structure this is not possible to achieve. Regions doesn’t exist in the database and the id/name of the region is merely used a grouping mechanism when retrieving the fields. 

The scenario you’re describing can however be achieved with block groups.

Regards

**Comment by tidyui** [comment]
Closing this as it can’t be done given the current data structure
