### ISSUE TITLE
Page ordering past depth of 5

### ISSUE THREAD

**Issue by jgreene** [PiranhaCMS/piranha.core#636]
The tree ordering component appears to be using nestable which has a default level of 5.  Users have complained of this and so I overrode it locally to default to 100 with the below.

```
     $('.dd').nestable({
            maxDepth: 100,
            group: 1
     });
```

**Comment by kvelineni** [comment]
@tidyui   while i tried to update my solution with PIrhana 7.0 alpha1  prerelease, i am getting the following error
![image](https://user-images.githubusercontent.com/52752828/60982408-ad558780-a2fd-11e9-8f7a-9b999f899355.png)

does the binders namespace moved from pirhana.Manager namespace (the 61.0 version of Pirhana Manager has Binders namespace in it)

please help to fix this

**Comment by tidyui** [comment]
Hi there! You can see the startup code for 7.0 alpha1 here:

https://github.com/PiranhaCMS/piranha.core.templates/blob/master/blog/mvc/Startup.cs#L35

Please do not comment on closed issues, open a new issue instead.

Best regards

**Comment by kvelineni** [comment]
well my question is :

1) is there a Nuget package called "Pirhana.core" ?
2) Pirahana.Manager version 6.1.0 contains Binders Namaespace in it, where
as  Pirhana.Manager version 7.1.0 alpha1 doesnot contain Binders namespace
in it.  where can i find Binders namespace?

> 3) changes that you made to fix Max page depth for issue
> https://github.com/piranhaCMS/piranha.core/issues/636 is under which dll
> (it Pirhana.Manager)????



 can you please respond to above questions as soon as possible

Thanks & Regards
Kiran

**Comment by tidyui** [comment]
1. No
2. ModelBinders are not used in 7.0 as ModelBinding is used when models are sent to the server as Form Data. 7.0 uses Vue.js and sends all models as Json, that’s why the new startup does some Json configuration instead of adding binders.
3. https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/assets/src/js/piranha.pagelist.js#L43

**Comment by kvelineni** [comment]
Hi Hakan,

Good Afternoon !

After upgrading to below versions from 6.1.0
Piranha 7  alpha2,
Piranha.AspNetCore 7 alpha2,
Phirana.Manager 7 alpha2

i am getting attached error , can you please take a look and help me in
fixing the issue

Thank you for your support in advance !
