### ISSUE TITLE
Drag n Drop for moving media assets between folders

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#64]
Add drag n drop support for moving media assets into/out of folders.

**Comment by LucGosso** [comment]
would be cool to have asset pane to the right side on page edit. with drag n drop functionality, even dnd to wysiwyg

**Comment by tidyui** [comment]
I agree @LucGosso! I think @NJepop who is in charge of the UI/UX actually drew some wild ideas including that, which I later bluntly discarded in favor of more technical stuff :)
