### ISSUE TITLE
Custom scripts and styles aren't added anymore for the manager

### ISSUE THREAD

**Issue by Harksa** [PiranhaCMS/piranha.core#648]
I was playing around with the latest version of PiranhaCMS downloaded directly here (commit #aac1d97) and I discovered that custom scripts and styles aren't added anymore with those lines of codes : 

```csharp
var module = App.Modules.Get<Piranha.Manager.Module>();
module.Scripts.Add("~/js/Test.js");
module.Styles.Add("~/assets/css/StyleSheet.css");
```
Those lines were added in the configuration method, inside the startup.cs. The test was made directly inside the MvcWeb example provided.

Is there a new way to add them or is something broken ?

**Comment by tidyui** [comment]
It’s probably just missing from the new Layout! Thanks for noticing!
