### ISSUE TITLE
Pages position isn't updated 

### ISSUE THREAD

**Issue by Harksa** [PiranhaCMS/piranha.core#649]
While I was playing around with the latest commit, I noticed that whenever I change a page position inside the managers/page view, it is not updated.
Also, I can't had a page as a child of another page anymore as well.
Finally, the little popup for the icons aren't displayed as well as the space added when you hover them with the mouse.

I guess you already knew those bugs but I just wanted to make sure you did.

The new manager still look promising so far !

**Comment by i-love-code** [comment]
Agreed, I think the state of the `master` branch is a bit of an in between state between v6 and v7 of the manager. A number of things don't work (some overlapping with what you mentioned):

1. Adding pages as children of another page (or reordering)
2. Getting to the editing interface of a post
3. Users/Roles/etc Sections of Manger (appears to be role related)
4. I'm not even prompted to login to the manager, I'm just instantly shown the screen (I believe causes no. 3 above, as you're not in the correct role for anything)

**Comment by Harksa** [comment]
While we are it, we can actually go to "~/manager" and see a pretty weird page (I do like it though, it's artistic 😄 ).

**Comment by i-love-code** [comment]
Yeah, I think the default /manager page is being used as a testing ground for front-end interface markup/component testing. Everything is static, but you can tell they're mocking all the UI there for ease of testing.

**Comment by tidyui** [comment]
The master branch is the **development** branch, and like you noticed we have a lot of loose ends we’re working on before 7.0 is finished, this is why we haven’t released an alpha package yet. For example, the api endpoints for moving pages & media isn’t implemented.

And the default page for the the manager area is like you figured out just a test page for the different controls used.
