### ISSUE TITLE
Piranha.Azure.BlobStorage

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#652]
Hi

I am having the following issue:

![2019-06-05 17_01_39-HoltDoctors - Microsoft Visual Studio](https://user-images.githubusercontent.com/32654709/58972495-94652e00-87b5-11e9-9533-360dcea7b8fd.png)

I think I have got all the needed Microsoft packages. Could it be because the library WindowsAzure got split and you have older references in that NuGet Package? Any ideas?

Chris

**Comment by i-love-code** [comment]
Mind sharing your full packagereference section of the csproj?

Example:
```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
    <PackageReference Include="Piranha" Version="6.1.0" />
    <PackageReference Include="Piranha.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Piranha.AspNetCore.Identity.SQLite" Version="6.1.0" />
    <PackageReference Include="Piranha.AspNetCore.Identity.SQLServer" Version="6.1.0" />
    <PackageReference Include="Piranha.AttributeBuilder" Version="6.1.0" />
    <PackageReference Include="Piranha.Azure.BlobStorage" Version="6.1.0" />
    <PackageReference Include="Piranha.ImageSharp" Version="6.0.0-rc1" />
    <PackageReference Include="Piranha.Local.FileStorage" Version="6.1.0" />
    <PackageReference Include="Piranha.Manager" Version="6.1.0" />
    <PackageReference Include="Piranha.Data.EF" Version="6.1.0" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="4.5.0" />
  </ItemGroup>
````

**Comment by aneff-official** [comment]
Yes, of course:

```
<ItemGroup>
    <PackageReference Include="Mailjet.Api" Version="1.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.1" />
    <PackageReference Include="Microsoft.Azure.Storage.Blob" Version="10.0.3" />
    <PackageReference Include="Microsoft.Azure.Storage.Common" Version="10.0.3" />
    <PackageReference Include="MyCouch" Version="7.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="NGeoKDBush" Version="1.0.1" />
    <PackageReference Include="Piranha" Version="6.1.0" />
    <PackageReference Include="Piranha.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Piranha.AspNetCore.Identity.MySQL" Version="6.1.0" />
    <PackageReference Include="Piranha.AttributeBuilder" Version="6.1.0" />
    <PackageReference Include="Piranha.Azure.BlobStorage" Version="6.1.0" />
    <PackageReference Include="Piranha.Data.EF" Version="6.1.0" />
    <PackageReference Include="Piranha.ImageSharp" Version="6.1.0-rc1" />
    <PackageReference Include="Piranha.Local.FileStorage" Version="6.1.0" />
    <PackageReference Include="Piranha.Manager" Version="6.1.0" />
</ItemGroup>
```

**Comment by i-love-code** [comment]
I am seeing that `Piranha.Azure.BlobStorage` uses a 9.X.X version of `Microsoft.Azure.Storage.Blob`, and you seem to have a 10.X installed. It's possible that there's a breaking change there.

Are you using Azure's blob storage directly elsewhere in code? If not, you could uninstall the Microsoft.Azure.Storage packages.

If you are, see if it's possible to downgrade to the highest 9.X.X version of them.

**Comment by aneff-official** [comment]
I am using it elsewhere and I may not be able to downgrade, unfortunately. Thanks for trying to help though :)

I will wait for @tidyui to see this

**Comment by i-love-code** [comment]
Sounds good, yeah per https://github.com/Azure/azure-storage-net/blob/master/Blob/BreakingChanges.txt Azure storage's repo:

`Namespace change from Microsoft.WindowsAzure.Storage.* to Microsoft.Azure.Storage.*, required for SxS with pre-9.4 versions of the library.`

And I can confirm that the StorageCredentials in Piranha.Azure.BlobStrage are using the old namespace of `Microsoft.WindowsAzure.Storage`. I assume a new version of Piranha.Azure.BlobStorage would need to be released to allow for the 10.x version of Microsoft's blob storage library.

**Comment by tidyui** [comment]
Hi there! We’re a little pressed for time working on the new manager interface, but if you send a PR with the upgrades to the 6.1 branch we can release an update for the NuGet package

**Comment by aneff-official** [comment]
Hi!

Not really sure who you meant, but if you want I can try doing the update. I am a bit unsure when touching someone else's files though.

Should I clone `piranha.core` update the package there on that branch then?

Thank you,
Chris

**Comment by aneff-official** [comment]
I had some issues with pushing on your `version/v6.1` branch.

It was saying "Permission denied for user.." and I ended up doing something messy from the UI in GitHub. Can you tell me if you see the change, because it offers me to open a pull request?

**Comment by aneff-official** [comment]
![2019-06-06 10_31_35-MINGW64__c_Sources_NewTestPiranha6_piranha core_core_Piranha Azure BlobStorage](https://user-images.githubusercontent.com/32654709/59022827-73005280-8846-11e9-8bdf-c10733e2aa14.png)

**Comment by tidyui** [comment]
Hi! You can’t push directly to another persons repo. You need to send a pull request from your fork!

Regards

**Comment by aneff-official** [comment]
Hi!

Sorry, didn't know that, although it sounds logical! Will open the pull request any moment. Is it a problem that my branch is different from the one that you've asked?

Regards

**Comment by tidyui** [comment]
Deployed to NuGet. `Piranha.Azure.BlobStorage` version `6.1.1`
