### ISSUE TITLE
How to setup site structure like MvcWeb example site?

### ISSUE THREAD

**Issue by quachnguyen** [PiranhaCMS/piranha.core#664]
![image](https://user-images.githubusercontent.com/128512/59336651-2971a500-8d29-11e9-81d6-b0a5ede9cfa9.png)

Hello everyone, 

I've been researching this CMS framework since yesterday, and setup it on localhost, I tried to create the structure like sample mvc site but not success,  Could someone can help me to create the structure like that, I would like to do this from scratch and by /manager instead of running seed functionality 

The second question is, how can I localize as above structure such as: 

http://yetanothercms.com/vi
http://yetanothercms.com/en 

Please advice

**Comment by tidyui** [comment]
Hi there! The `master` branch is our development branch. Since we currently are a bit delayed it contains the work-in-progress for version `7.0`. When the new version is done you will have a second button with the option `Add site` where you can add the second site with the slug/prefix your suggesting.

If you want to create the structure you mention right now I suggest you start a project from one of the project templates available on NuGet which uses the currently released version `6.1`.

http://piranhacms.org/docs/introduction/getting-started/project-templates

Best regards

**Comment by quachnguyen** [comment]
Hello @tidyui 

Thank you for your quick response, I pulled the code from GIT and installed the template as well, there is a strange. 

The Sample MVC site is running on PIRANHA CMS Version 7.0.0. But the website that I created from template is running on PIRANHA CMS Version 6.1.0 

Is there any wrong from beginning? 

Thank you 
Quách

**Comment by tidyui** [comment]
Hi. The templates are build from the **currently released** version, which is `6.1.0`. The master branch of the of this repository is our **development branch** which contains the not yet released or finished `7.0` version. You can find the source code of the released stable version in its branch `version/v6.1`

https://github.com/PiranhaCMS/piranha.core/tree/version/v6.1

Regards

**Comment by quachnguyen** [comment]
Hello @tidyui  

here is my site: 

![image](https://user-images.githubusercontent.com/128512/59343742-ba9b4880-8d36-11e9-939f-e30116ecd178.png)

Could you tell me how could I create the structure like above? 

I installed the template as bellow command line: 

> dotnet new -i Piranha.Templates

And Create a new website in coffee folder 

> dotnet new piranha.web
> dotnet restore
> dotnet run

I have no idea to create the structure like above, If there is no way, I have to use an example structure for my new site, do you have any suggestion? 

Thanks & Regards,

**Comment by tidyui** [comment]
In either versions, to create different structures for different sites you will do the following.

1. Create one **site** for each language version of your site
2. Set the correct **culture** for your language sites
3. Set the correct **hostname** for your language sites

If I would set this up for `PiranhaCMS.org` for example it would look like:

**Default Site**
    Culture: en-US
    Hostnames:

**Swedish Site**
    Culture: sv-SE
    Hostnames: piranhacms.org/se,www.piranhacms.org/se

The **main difference** between `6.1` and `7.0` is that in `7.0` you see **ALL** of sites at the same time (like in your screenshot). In `6.1` and earlier you see just one site and then switch active site from the site dropdown in the **page list** view.

Regards

**Comment by quachnguyen** [comment]
Thanks for your reply, I'm going to check it 

Regards,
