### ISSUE TITLE
Default page redirect to page not found page

### ISSUE THREAD

**Issue by quachnguyen** [PiranhaCMS/piranha.core#665]
Hello team, 

The Default Site(/) link leads to page not found page when I select it 

![image](https://user-images.githubusercontent.com/128512/59344475-5c6f6500-8d38-11e9-8edd-4f3c72c04330.png)

The Sites in left menu doesn't work, It becomes http://localhost:5000/manager/aliases and when I open the url http://localhost:5000/manager/sites, It redirects to 404 

I guess this is bug in sample site, please advice 

Notice: The sample site is running on PiranhaCMS version 7.0 
Regards, 
Quách

**Comment by tidyui** [comment]
Hi again. The master branch is in **development** and not yet released. If you want to use a stable version, please check the other branches or create a new project from NuGet.

Regards
