### ISSUE TITLE
[QUESTION] Sort archive posts

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#672]
Hi there

![2019-06-18 12_48_43-Window](https://user-images.githubusercontent.com/32654709/59679739-8c4eba80-91c7-11e9-88c0-c542e19caeb0.png)

If you see the above image, you would notice that this is in the manager view, on an archive page. I have known this functionality for a while, but now I need to use something similar to this; display all posts for a certain category (or a tag) without refreshing the page.

I have been going through your manager projects, just to see how you did it and I could grasp the idea, but unfortunately couldn't find it.

While this can be something easy to do, I am stuck with it. I can wait with that, if you have higher priorities (like the new release).

Cheers,
Chris

**Comment by tidyui** [comment]
Hi there! I'm guessing that you want to implement the same kind of behavior in your front-end application. This view in the manager basically loads **all** posts, and when changing category in the dropdown a simple `javascript` just loops through the rows in the table and puts `display:none` on all rows that doesn't contain the selected category in the specified column.

This is of course pretty old school and there are much better ways to achieve the same functionality, for example in the new `7.0` manager we're binding and filtering this view with `Vue.js`.

**Comment by aneff-official** [comment]
Thank you. I am not sure how to achieve the same if not using **Vue/React/Angular**.

This is also pretty close to something else that I needed - lazy loading posts (instead of loading all of them and then hiding them).

**Comment by tidyui** [comment]
I think this is the javascript function that sorts the table:

    function(table, status, type, category, search) {
        $.each($(table).find("tr"),
            function(i, e) {
                // Skip the first row as this is the table header
                if (i > 0) {
                    var row = $(e);
                    var show = true;

                    if (status != "" && !row.hasClass(status))
                        show = false;
                    if (type != "" && type != row.data().posttype)
                        show = false;
                    if (category != "" && category != row.data().category)
                       show = false;
                    if (search != "") {
                        if (!row.first("td").text().toLowerCase().includes(search))
                            show = false;
                    }

                        if (show)
                            row.show();
                        else row.hide();
                    }
                });
        }
    }

As you can see it searches and filters several different things, where most of them are added as data-attributes to the row. It also has a free text search of the post title which is located in the first cell of each row.

Regards
