### ISSUE TITLE
Url rewrite with an alias

### ISSUE THREAD

**Issue by roly445** [PiranhaCMS/piranha.core#673]
I have just been using the CMS to create a site and I am using aliases to help with the routing.
I have just looked over the codebase and I can't seem to find a way to keep a Url once its redirected.
Am I missing something?

**Comment by tidyui** [comment]
As the `AliasMiddleware` just performs a standard redirect to the target url it is handled as a new request and the previous Url is not accessible. If you have any ideas on how to pass along the original url in a good way we always accept PR:s. Also, the `AliasMiddleware` is very lightweight and totally pluggable, so you can just remove it and add your own middleware for handling aliases if you want to treat the differently :)

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore/AliasMiddleware.cs

Best regards

Håkan
