### ISSUE TITLE
7.0 (2019-06-21 pull) - Feature request

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#674]
An "iFrame" block would be a nice feature to embed content external to the engine on a page.

Or expand the current "content" toolbar to allow "source code" for the end user to embed an iFrame tag into the content.

**Comment by tidyui** [comment]
Hi! As Piranha is a content framework that can be used in any context (serving a web **or** a completely different type of application) we try not to add anything that is very web-specific into the core library.

However, we are more than willing to create a contrib repository geared towards web components where everyone can add suggestions, fields & blocks that would enhance its use in web applications.

**Comment by tidyui** [comment]
Closing this issue for now as it doesn't align with the core function of Piranha. Might create a new repository later when we have time!
