### ISSUE TITLE
Cannot edit / add blog item

### ISSUE THREAD

**Issue by JustinK1973** [PiranhaCMS/piranha.core#677]
Latest version of code does nothing when clicking on Add or Edit a blog item. No errors, no network requests.

![PiranhaError](https://user-images.githubusercontent.com/30580723/60063113-17d3c880-973f-11e9-95f8-4e3f7dcc8954.jpg)

**Comment by tidyui** [comment]
Post edit isn’t implemented yet. As it in essence is almost identical to page edit we’re waiting until everything else is 100% before we implement it 😁
