### ISSUE TITLE
Ability disable Manager interface?

### ISSUE THREAD

**Issue by robearlam** [PiranhaCMS/piranha.core#681]
Hi,

Is there a simple way to disable the manager interface in Production environments?

Thanks,
Rob

**Comment by tidyui** [comment]
Yes! Don't include the NuGet-package `Piranha.Manager` and remove the lines in `Startup.cs` than initializes it!

Best regards

Håkan

**Comment by tidyui** [comment]
And if you want to keep it in development you can keep the NuGet package reference and just add the initialization of the manager inside of:

    if (env.IsDevelopment())
    {
        ...
    }

**Comment by robearlam** [comment]
Yes I would like to keep it in development environment and remove from Production. I tried wrapping the calls in startup.cs and it didn't work as expected when setting ASPNETCORE_ENVIRONMENT=Production.

Firstly I wrapped the call in Configure() as so

```
if (env.IsDevelopment())
{
    app.UsePiranhaManager();
}
```

But that has no effect, the management interface was still accessible.

Next I did the same for the ConfigureServices method (you can't change the signature on the method to inject IHostingEnvironment so need to set it to a private prop in the constructor instead, which is fine, and I ended up with:

```
if(Environment.IsDevelopment())
{
    services.AddPiranhaManager();
}
```

However then when I run the site I can't access any page and I get the following error in the Console: **The AuthorizationPolicy named: 'PiranhaAliases' was not found**

**Comment by tidyui** [comment]
Yes I just tried it myself and you are right. The problem here is how MVC automatically scans through all classes derived from `Controller`. The controllers gets added either way, but the policies hasn't been created which causes the error.

Another way to go about it would be to remove the **area initialization** of mvc if you're not using it for other purposes, i.e. remove the following lines:

    routes.MapRoute(name: "areaRoute",
        template: "{area:exists}/{controller}/{action}/{id?}",
        defaults: new { controller = "Home", action = "Index" });

**Comment by robearlam** [comment]
I dont have the **area initialization** route defined in my startup and am still getting the error, you can see my full class here......

```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Piranha;
using Piranha.AspNetCore.Identity.SQLite;
using Piranha.AttributeBuilder;
using PiranhaBlog.Web.Models;

namespace PiranhaBlog.Web
{
    public class Startup
    {
        public IHostingEnvironment Environment { get; }

        public Startup(IHostingEnvironment env)
        {
            Environment = env;
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(config =>
            {
                config.ModelBinderProviders.Insert(0,
                    new Piranha.Manager.Binders.AbstractModelBinderProvider());
            });

            services.AddPiranha();
            services.AddPiranhaApplication();
            services.AddPiranhaFileStorage();
            services.AddPiranhaImageSharp();

            if(Environment.IsDevelopment())
            {
                services.AddPiranhaManager();
            }

            services.AddPiranhaEF(options =>
                options.UseSqlite("Filename=./wwwroot/data/piranhaBlog.db"));
            services.AddPiranhaIdentityWithSeed<IdentitySQLiteDb>(options => 
                    options.UseSqlite("Filename=./piranha.db"));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IApi api)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // Initialize Piranha
            App.Init(api);

            // Configure cache level
            App.CacheLevel = Piranha.Cache.CacheLevel.Full;

            var pageTypeBuilder = new Piranha.AttributeBuilder.PageTypeBuilder(api)
                .AddType(typeof(Models.PiranhaBlogArchive));
            pageTypeBuilder.Build()
                .DeleteOrphans();

            var postTypeBuilder = new Piranha.AttributeBuilder.PostTypeBuilder(api)
                .AddType(typeof(Models.PiranhaBlogPost));
            postTypeBuilder.Build()
                .DeleteOrphans();

            var siteTypeBuilder = new SiteTypeBuilder(api)
                .AddType(typeof(PiranhaBlogSite));
            siteTypeBuilder.Build()
                .DeleteOrphans();

            // Register Middleware
            app.UseStaticFiles();
            app.UseAuthentication();
            app.UsePiranha();

            if (env.IsDevelopment())
            {
                app.UsePiranhaManager();
            }

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=home}/{action=index}/{id?}");
            });
        }
    }
}

```

**Comment by tidyui** [comment]
Hi! As long as the NuGet-package is available you need to call `UsePiranhaManager` and `AddPiranhaManager` due to the fact the MVC registers controllers based on convention. What we want is a way to restrict access to it production.

The simplest and fastest way I can think of is to add a custom `Middleware` in production that just checks if the path of the request starts with `manager` then it returns a `404`. This should effectively block out the manager.
