### ISSUE TITLE
How to execute example "razorweb"

### ISSUE THREAD

**Issue by won5572** [PiranhaCMS/piranha.core#682]
Example "mvcweb" run well. but, I can not build and run example "razorweb".
I got this message that was "can not found Piranha.Manager.Binders namespace".           
How can I fix it?

services.AddMvc(config =>
            {
                config.ModelBinderProviders.Insert(0, new Piranha.Manager.Binders.AbstractModelBinderProvider());
            });

**Comment by tidyui** [comment]
Hi! We haven't had time to update the Razor Pages example project for the `7.0`version yet!

**Comment by won5572** [comment]
Hi! I understood. Thanks for your reply.
