### ISSUE TITLE
[QUESTION] Language support

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#684]
Hello

Following the commits, I am not sure if possible, but since you are translating the manager view into multiple languages I wouldn't want to waste the opportunity to ask/help you if we could add translations for Bulgarian (BG) language into this?

I think it will certainly help new users who don't know English that well.

Cheers,
Chris

**Comment by tidyui** [comment]
Hi there! The translation project for the manager where you can contribute is located here:

https://crowdin.com/project/piranhacms

There’s no real though about the languages that are available, we just clicked “add the most commonly used languages” 😁 We’re more than happy to add Bulgarian if you’re willing to contribute!

**Comment by aneff-official** [comment]
Hi there!

Thank you and of course! Count me in, but I am guessing that this won't happen on github?

**Comment by tidyui** [comment]
You submit your translations on **crowdin** on the link I gave you previously and the system sends a PR automatically back to the repository!

**Comment by tidyui** [comment]
And now I've added **Bulgarian** to the Crowdin project!

**Comment by aneff-official** [comment]
That's great!

I will surely have done progress by the end of the weekend :)

**Comment by aneff-official** [comment]
Done:
https://crowdin.com/project/piranhacms/bg#

**Comment by kttary** [comment]
> And now I've added **Bulgarian** to the Crowdin project!

Can you add Bahasa Indonesia pls? I would like to contribute

**Comment by tidyui** [comment]
@kttary We've added Indonesian to our Crowdin account!

**Comment by kttary** [comment]
After translate some .resx file, i cannot find 'Read More' string. Which resx file contain this string?

<img width="1679" alt="Screen Shot 2021-01-07 at 18 45 12" src="https://user-images.githubusercontent.com/39557649/103884387-7c842780-5119-11eb-92be-577becf13453.png">

**Comment by tidyui** [comment]
@kttary This screenshot is of our public website, this is not a part of the Piranha packages. The only parts of Piranha that is translatable is the backend manager-portal for content administrators.

**Comment by kttary** [comment]
In my site, if i add a block linked to the page or post somewhere in my home page the button Read more is coming. It is like default button containing hyperlink to the complete page or archive..

**Comment by tidyui** [comment]
All of the rendered `HTML` is located in your project and is for you to translate or change anyway you see fit. The "read more" links for linked content would be located in the display templates `PageBlock.cshtml` and `PostBlock.cshtml`.

Best regards

**Comment by kttary** [comment]
now i see that

**Comment by kttary** [comment]
> All of the rendered `HTML` is located in your project and is for you to translate or change anyway you see fit. The "read more" links for linked content would be located in the display templates `PageBlock.cshtml` and `PostBlock.cshtml`.
> 
> Best regards

And don't forget display template for 'Archive.cshml'

Best regards

**Comment by mike7ang1rdz** [comment]
could you create a copy of Spanish I would like to translate it to es-MX.  español-Mexico
