### ISSUE TITLE
Documentation for Custom Block groups

### ISSUE THREAD

**Issue by Nhawdge** [PiranhaCMS/piranha.core#687]
Hey, I see that the [documentation page for custom block groups](http://piranhacms.org/docs/extensions/custom-block-groups) isn't quite ready yet, but I was wondering if there was a (public) project using it that I could see how to properly implement it? 

Thanks!

**Comment by tidyui** [comment]
Hi there and sorry for the late reply! We are working on updating the official site and the documentation and we will post documentation for Block Groups shortly. Which version are you using

**Comment by tidyui** [comment]
This has been added to the documentation.
