### ISSUE TITLE
Manager Login Page Branding/Styling

### ISSUE THREAD

**Issue by asys-bstz** [PiranhaCMS/piranha.core#688]
Hi, the Login Page template doesn't respect any resources injected into the manager (which is reasonable; docs: http://piranhacms.org/docs/manager-extensions/custom-resources), however it doesn't offer any other ways to extend it. Our use-case currently is just to change the logo for a client.

#359 is about a similar case, but the solution (injecting styles) only works for branding inside the actual manager, not the login page.

What would be the best way to achieve custom branding? Overriding the login page with a custom one?

**Comment by tidyui** [comment]
This is a bug. Registered stylesheets should be included in the login view as well. However, at the moment you can solve it just like you described, by overriding the Login view with a local version.

Regards

**Comment by asys-bstz** [comment]
Thanks for the quick reply and fix for 7.0!
