### ISSUE TITLE
Add Identity With Seed doesn't always create a sysadmin user

### ISSUE THREAD

**Issue by dannykay1710** [PiranhaCMS/piranha.core#691]
Tested with Piranha 6.1.0

I'm configuring Piranha in the `Startup.cs` classes `ConfigureServices` method but have come across some weird behaviour.

When you call `services.AddPiranhaIdentityWithSeed<IdentitySQLServerDb>()` with an `Action<IdentityOptions>` as the `identityOptions` parameter it doesn't seem to create a default username and password.

The database seems to be created, but there is nothing added to the `Piranha_Users` table or any other Identity related table.

Whereas if you do not provide an identity options and stick with the default value of `null` , it creates the username and password just fine and allows you to login to the manager

**Comment by tidyui** [comment]
Hi! When calling `AddPiranhaIdentityWithSeed` without specifying a seed the default seed `DefaultIdentitySeed `. The default seed adds a test user with the credentials `user` / `password`. This password however is **so utterly useless**, and only intended for testing purposes, that if you replace the default IdentityOptions with your own, the basic setup for password strength will most likely reject it.

So the solution would be, that if you specify your own production `IdentityOptions` you should also specify your own seed that adds the default admin user with a far better password!

Best regards

**Comment by dannykay1710** [comment]
Now you have said that it seems so obvious, but for whatever reason I just couldn’t see it.

Thanks
