### ISSUE TITLE
Adding columns and content to page causes Null exception on MVC sample blog main page

### ISSUE THREAD

**Issue by JustinK1973** [PiranhaCMS/piranha.core#700]
Add new page/post add Column, add content to column and publish

NullReferenceException: Object reference not set to an instance of an object.
AspNetCore.Views_Cms_Archive.ExecuteAsync() in Archive.cshtml
                    @Html.Raw(GetFirstHtmlBlock(post).Body)

Works without the columns and just adding content

![2019-07-15_17-18-41](https://user-images.githubusercontent.com/30580723/61200430-ad51ef00-a724-11e9-9f08-bc07e6104078.jpg)

**Comment by tidyui** [comment]
Hi there! The method `GetFirstHtmlBlock` is just an example method for how an archive could be rendered located in the view.

    Func<Piranha.Models.DynamicPost, Piranha.Extend.Blocks.HtmlBlock> GetFirstHtmlBlock = (post) => 
    {
        foreach (var block in post.Blocks)
        {
            if (block is Piranha.Extend.Blocks.HtmlBlock)
            {
                return (Piranha.Extend.Blocks.HtmlBlock)block;
            }
        }
        return null;
    };

As the method returns null if **no** Content blocks can be found the archive will throw a `NullPointerException`. I agree the method could be made smarter, but as it's just an example we will have to look at it when we have the time!

Best regards

Håkan

**Comment by JustinK1973** [comment]
Thanks.

I am spending more time playing with it daily and trying to get head around the full architecture.

So far very impressed with it and the speed is fantastic

Justin

Regards
Justin King

________________________________

**Comment by JustinK1973** [comment]
Created pull request
