### ISSUE TITLE
The value "Piranha.Extend.Fields.StringField" is not of type

### ISSUE THREAD

**Issue by gyretech** [PiranhaCMS/piranha.core#701]
So we are getting this error:

`The value "Piranha.Extend.Fields.StringField" is not of type "App.Web.Models.ProjectFeature" and cannot be used in this generic collection.`

```
    [PostType(Title = "Portfolio Item Post", UseBlocks = false)]
    [PostTypeRoute(Title = "Default", Route = "/portfolioItemPost")]
    public class PortfolioItemPost : Post<PortfolioItemPost>
    {
        public PortfolioItemPost()
        {
            RelatedPosts = new List<PostInfo>();
        }

        [Region(SortOrder = 1, Title = "Heading")]
        public PageHeading Heading { get; set; }

        [Region(SortOrder = 2, Title = "Project Info")]
        public ProjectInfo ProjectInfo { get; set; }

        [Region(SortOrder = 3, Title = "Project Features", ListTitle ="Feature")]
        public IList<ProjectFeature> ProjectFeatures { get; set; }

        [Region( Title = "Solution & Result", SortOrder = 4)]
        public SolutionResult ProjectSolutionResult { get; set; }

        public List<PostInfo> RelatedPosts { get; internal set; }
    }


    public class ProjectFeature
    {
        [Field]
        public StringField Feature { get; set; }
    }
```

**Comment by tidyui** [comment]
Hi there! Single Field Regions are not supported by the deserializer. Instead of the following:

    [Region(SortOrder = 3, Title = "Project Features", ListTitle ="Feature")]
    public IList<ProjectFeature> ProjectFeatures { get; set; }

    public class ProjectFeature
    {
        [Field]
        public StringField Feature { get; set; }
    }

use this:

    [Region(SortOrder = 3, Title = "Project Features", ListExpand = false)]
    public IList<StringField> ProjectFeatures { get; set; }

For reference see http://piranhacms.org/docs/basics/how-to-setup-content

Best regards!
