### ISSUE TITLE
Download media without GUID in filename

### ISSUE THREAD

**Issue by fdhighhead** [PiranhaCMS/piranha.core#703]
Hey Guys, 
is it possible to remove the GUID from the filename when downloading a specific file?
If not, it would be a nice addition for a future release.

Thanks a lot for your work!
Just released a page for a voluntary organization with piranha and they are very happy about it - Devs and Users ;-)

Greetings,
Robert

**Comment by filipjansson** [comment]
Hi!

If you are using local file storage, you can solve this by adding this to the CmsController (or other controller) to serve the file with its original filename.

```
[Route("media/download/{id}")]
public IActionResult Download(Guid id)
{
    var media = api.Media.GetById(id);
    return File(media.PublicUrl, media.ContentType, media.Filename);
}
```
Example usage in your view
`<a href="@Url.Action("Download", new { id = media.Id })">Download @media.Filename</a>`

But if you are using Azure Blob storage, or other storage provider, you made need to download the bytes to the application before returning it.
Or maybe someone else has a better solution for situations like that?

**Comment by fdhighhead** [comment]
Okay, 
sounds like a simple solution for a single file, something with routing i did to secure specific media.

Would it be possible to implement this into the "direct-link-generator" of the Manager? 
So if you insert a link, select a media and than this route is inserted?

e.g. now:
![grafik](https://user-images.githubusercontent.com/49428499/61282188-2ac83e80-a7bb-11e9-9567-184a52cd4c35.png)

in future the url would be with the code snippet above:
"/media/download/d111b44e-aa14-4253-828c-0e0ebe4a2a38"
and then the link in the post/page returns the file as described above.

**Comment by tidyui** [comment]
Hi there! The solution would be to implement your own FileStorage service as the service is responsible for returning the URL to the client, you can see the implementation here for the default Local file provider:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Local.FileStorage/FileStorage.cs#L60

Regards

**Comment by fdhighhead** [comment]
So i will write my own FileStorage service.
Thank you a lot to you both and for your quick answers!
Have a nice week! :)
