### ISSUE TITLE
Dropdown in menu

### ISSUE THREAD

**Issue by Bidou44** [PiranhaCMS/piranha.core#711]
I'm currently evaluating your project and find out that it was not possible to add a menu with sub menus in the root site menu (at least with the administration interface), can you confirm this?

For example, I want a menu named Countries at the top and then some countries as sub items (drop down), each item pointing to a specific page.

Or did I miss something? If it's missing and would not be to complicate to add, I could try to do a pull request if you can give me some advise how to implement it... Thanks.

**Comment by tidyui** [comment]
The answer is rather that there's multiple ways of achieving this depending on your goal:

## 1. Multiple Sites
If you want to provide several site structures for different countries you can add a separate site for each country and then loop the available sites in your Layout to create the country menu.

## 2. Information Pages for different countries
If you just want a global context menu pointing to pages within the site structure you can add a `SiteType` for your site which would hold a list of regions containing a `StringField` (name) and `PageField` (the target page). See information here:

http://piranhacms.org/docs/basics/how-to-setup-content/site-types

## 3. Root level structure
If you want your countries to be the root level of your site, create the different countries as Pages with a redirect to the first subpage of itself (i.e the start page of the country). The country menu in the Layout would be the first level in the sitemap, the regular menu would be the child items of the active country.

Best regards

**Comment by Bidou44** [comment]
Thank you for the quick response!

To be sure that you understood correctly what Im trying to achieve, it's something similar to this: https://onholidaysagain.com/. Hovering the menu "Destinations" opens a menu (which can itself contain submenus, etc.). So it's like recursive.

Reading your answer again, I understand that

1) Its not possible to do with the manager (admin interface)
2) I have to implement it myself in code
3) Point 3. of your answer is what would the best fit my requirements.

Im right?

**Comment by tidyui** [comment]
No it’s fully possible to manage the structure in the manager with all of the above options! If you want a global menu like that in the header the easiest solution would be to:

1. Create a page in the root called destinations and set it to hidden so it’s not rendered in the regular menu.
2. Call GetPartial on the site map with the destinations page as root in your layout page and just render the submenu!

Best regards

**Comment by Bidou44** [comment]
Thank you for the support, will try that :)

**Comment by baibhavs** [comment]
Hi, I am new to piranha cms. I am trying to create dorpdwon menu as mention above. Can you please guide or any kind code snippet will be great if you can provide

**Comment by Bidou44** [comment]
@baibhavs unfortunately I was not successful so I cannot help you further. A code sample would be good for me too....

**Comment by RickIsWright** [comment]
It's a little late for this reply. But, I know people are going to ask again. Here's the github link: [](https://github.com/PiranhaCMS/piranha.core/issues/816)[https://github.com/PiranhaCMS/piranha.core/issues/816](url)
