### ISSUE TITLE
can not add new post ,I add the archive page but the add  new item not opened i used the seed also used new page same thing happen

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core#712]

**Comment by tidyui** [comment]
Hi there! Which version of Piranha are you using?

**Comment by haidersafaa** [comment]
i use 7.0.0

**Comment by tidyui** [comment]
Ok, thanks for the heads up! 7.0 is still in alpha but we’ll make sure to fix it for the next release.

**Comment by tidyui** [comment]
Which alpha are you using btw, 1 or 2?

**Comment by haidersafaa** [comment]
can you give me URL for last stable version

**Comment by tidyui** [comment]
If you’re using source code please use the 6.1 branch. If you’re using packages the available templates also reference this version.

**Comment by tidyui** [comment]
This is working in master, closing
