### ISSUE TITLE
need to add Survey

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core#713]
we need to add Survey to piranha , can we use it without using external code

**Comment by tidyui** [comment]
Hi there! Piranha is a CMS framework which means that almost all data structures you add will need some custom code. Depending on how you choose to implement it the amount of code will vary.

For starters, take a look at the different content types available to see if you can use what’s already available.

http://piranhacms.org/docs/basics/how-to-setup-content

Best regards
