### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by Mikechiwu** [PiranhaCMS/piranha.core#725]
I am using v.6.1.1.

I notice the Hidden page checkbox doesn't work if caching is used.
It would work if I set CacheLevel to None for the page to be hidden on the navbar.

The BlogPost page Title and content doesn't get updated on the website when CacheLevel is set to Full.  Have to set CacheLevel to Basic to be able to update BlogPost page Title and content.

Are these two issues able to get it to work on CacheLevel Full?

Thanks

**Comment by tidyui** [comment]
Hi, I have verified the bug in `6.1` and will double check the behavior in `7.0`
