### ISSUE TITLE
Create organization and prefix reservation for nuget.org

### ISSUE THREAD

**Issue by bruno-garcia** [PiranhaCMS/piranha.core#735]
While likely the wrong place to raise this, please route me if needed.

I'd like to suggest reserving the prefix `Piranha` on nuget.org.
I've recently did it and [wrote about it here](https://blog.sentry.io/2018/08/22/sentry-dotnet-nuget-package-prefix-reservation/).

Also, I suggest creating an org (also sort of new on nuget.org). Perhaps adding another core member (but factor?) to the org too.

**Comment by tidyui** [comment]
Thanks for the tips! We've taken the necessary steps!

**Comment by bruno-garcia** [comment]
Great! hopefully helpful.
Correction: I meant bu**s** factor. Not but factor lol
