### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by goranhell** [PiranhaCMS/piranha.core#739]
Can't use swedish letters in the username. No fault handling for that.

**Comment by tidyui** [comment]
Hi there! The methods for adding Identity takes in two optional parameters for configuring the behavior, like usernames and password strength! Take a look at the documentation here for reference:

http://piranhacms.org/docs/components/authentication/identity-security

Best regards

**Comment by goranhell** [comment]
Sorry for delay...
In IdentityModuleExtensions in the Piranha.AspNetCore.Identity project I added
options.User.AllowedUserNameCharacters = "abcdefghijklmnopqrstuvwxyzåäöABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖ0123456789-._@+";
in the SetDefaultOptions method.
This allowed me to use swedish characters in the username.
