### ISSUE TITLE
Manager stays empty in production

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#742]
After upgrading to 7 i noticed that the manager is not working anymore.
The content area stays empty, the error message in console says:
Invalid dropzone element

In local environment everything seems to be fine. I already started investigation and see the code requesting data for the page list for example. so something seens to be wrong with the html?

Sorry for involving you at this early stage of investigation but i dont want to loose time, maybe someone of you have had the same before.
I will update the thread as soon as I know more about
Thanks

**Comment by rengert** [comment]
Has something do to with my security & performance settings, as soon as removed, the manager is working.

**Comment by tidyui** [comment]
Hi! You closed the issue, it would be interesting if you would share what was causing the error!

Regards

**Comment by rengert** [comment]
I have no final result yet, but i know already it is my csp header.
Fortunately the headers in my application are separated for frontend and manager, so i was able to remove it for the manager only.

**Comment by rengert** [comment]
Firefox is my new friend, Firefox told me that the security settings blocked an eval call. 
Well, the issue seems to be located in the signalr file. Not sure but the only eval i was able to find in this short time.
https://github.com/PiranhaCMS/piranha.core/blob/cfb19981ac2505bb858662e5b8f46fd52fd96df5/core/Piranha.Manager/assets/dist/js/signalr.min.js#L1377

I have updated my csp header. Let me if this can be "fixed". The code itself references the "csp" issue, but i am not sure if the code block in the catch block should make it working. Thats why i dont know if it is really the issue. But the try / catch is maybe the issue why my chrome was not telling my about.

**Comment by tidyui** [comment]
Ok. Problem is that the `signalr` file that produces the error is a bit out of our hands since it is the official singalr file from Microsofts distribution.
