### ISSUE TITLE
Region Title on IList<MyType> causes "Sequence contains no matching element"

### ISSUE THREAD

**Issue by RedSerenityDev** [PiranhaCMS/piranha.core#743]
When I add `[Region(Title = "My Title", ...)]` to `public IList<MyType> MyTypes {get;set;}`, it will cause a LINQ exception when trying to add an item to the list in the Manager.

It looks like the manager requests `/manager/api/content/region/page/TeaserPage/My%20Title` instead of `/manager/api/content/region/page/TeaserPage/MyType`.

This can be reproduced in the MvcExample project by adding **Title = "My Title"** to any of RegionAttributes of the IList<..> types in a page.

This is happening on the latest 7.0-rc1.

**Comment by tidyui** [comment]
Thanks! Workaround until next release is to not add custom titles for List regions.
