### ISSUE TITLE
Posting Forms

### ISSUE THREAD

**Issue by steelspace** [PiranhaCMS/piranha.core#746]
Is there a preferred way, how to handle custom form posting (from the user perspective, not in manager)?
Or, should I just add my own controller/action etc?
Is there any example?

**Comment by tidyui** [comment]
If you don't want to loose context of **which** page in the structure you're actually posting to you should route to your permalink with the additional `action` or `parameters` after it. This is described in the section **Advanced Routing** in the docs.

http://piranhacms.org/docs/architecture/routing/advanced-routing

Best regards
