### ISSUE TITLE
Sites in 7.0 missing features in prod

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#747]
I am testing 7.0 with my page and i noticed a behavior, i have no idea how to fix, because in only occures in the production environment.

I am unable to use site:
1. the add site button is disabled (not so important)
2. the custom tabs in the management overlay of a site does not contain the custom tab.

I analyzed the data transfered an see there is different:
The json does not contain the id of the sitetype but the following:
"typeId":"{{ siteType.id }}

3. the delete button is not available (not so important)

Any ideas? I tested with all accounts including the sys admin, so the permissions configured should be not the problem.

**Comment by tidyui** [comment]
Hi there! The behaviors you describe are all a part of a previous pre-release of `7.0` when those features where not implemented. Are you sure you have the same versions of the packages in both development and production?

Regards

**Comment by rengert** [comment]
Ah, i see, i guess we can close this if this was know in the previous release. Sorry my mistake :) Next deployment is planned for day after tomorrow.

**Comment by rengert** [comment]
we've cloned the production to test the new version. well ... no, but i believe it has something to do with our security settings or the database. now the delete button is there ... so better ... the new site button is there ... so almost perfect ... but the tabs in the overlay are still missing and we see a 404 in network tab and saving site is following by

![image](https://user-images.githubusercontent.com/6323357/63195003-bf031b00-c071-11e9-9ca8-0a3f2cc6ac6e.png)

but we are still investigating. but the frontend is not effected, so everything stored in the properties of the custom site model is still present. so thanks for this stability ;)

**Comment by tidyui** [comment]
Have you tried updating to the official package? Did you resolve this issue?
