### ISSUE TITLE
How Can I Contribute to Documentation

### ISSUE THREAD

**Issue by CrossBound** [PiranhaCMS/piranha.core#753]
If I want to help with the documentation... how can I do that?

**Comment by tidyui** [comment]
That’s awesome, and we’d really appreciate that! What do you think would be the best way to do this? Should we just set up a contribution group in admin and add people to it so they can log into the manager, or should we create a wiki-like documentation where you just contribute to the documentation directly on the public website?

Regards

**Comment by CrossBound** [comment]
If you go the manager route I suspect you lose the control of being able to review/approve changes, which makes me think the wiki route would be better. What's the downside of the wiki option?

**Comment by tidyui** [comment]
We're currently rebuilding the official website and we will aim for turning the documentation into Markdown based content with wiki-style in-front edit for contributions. We hope to incorporate GitHub sign-on for documentation contribution!

Regards

**Comment by vfabregat** [comment]
I use this issue to make another question. The official website its open source? It has a few things that I want to check how it's resolved by piranha. I searched in the repos without success.

**Comment by tidyui** [comment]
Hi there @vfabregat We haven’t made the code for the current website public, mostly because we didn’t have the time clean up the credentials for different services. We are currently working on a completely new website which we will make available when it’s done!

**Comment by DaveEmmerson** [comment]
I found something, so just tweeted at you; then I saw this issue :)

**Comment by lgoudriaan** [comment]
Sounds good!

ps. this is related to #578

**Comment by tidyui** [comment]
Documentation repo now opened here:

https://github.com/PiranhaCMS/piranha.core.docs

We are working on lifting over all of the available docs. If you encounter a missing or empty page we just haven't gotten started on that yet!
