### ISSUE TITLE
Add a view, to show posts filtered by type/category

### ISSUE THREAD

**Issue by mspasiuk** [PiranhaCMS/piranha.core#755]
I have an BlogArchive, with two postType, on my archive page, I get the post using PostBase as follows
```
[Route("archive")]
        public async Task<IActionResult> Archive(Guid id, int? year = null, int? month = null, int? page = null,
            Guid? category = null, Guid? tag = null)
        {
            var model = await _api.Pages.GetByIdAsync<BlogArchive<PostBase>>(id);
            model.Archive = await _api.Archives.GetByIdAsync<PostBase>(id, page, category, tag, year, month);

            return View(model);
        }
```
With the above code, on my Archive view, I render the two post types.
I need two more views (listed on sitemap as will be menu options) to show posts from the same archive, but filtered by PostType.
How can I do that?
For sure I can do something like 

` var model = await _api.Pages.GetByIdAsync<BlogArchive<MyPostType>>(id);
            model.Archive = await _api.Archives.GetByIdAsync<MyPostType>(id, page, category, tag, year, month);`

How to route properly to my razor view?

**Comment by mspasiuk** [comment]
I finally did it, but for sure is not the best way. 
I believe there is another way where I can receive the Guid of the archive properly and retrieve the posts.
Here my code
On CmsController

```
 [Route("only-one-post-type")]
        public async Task<IActionResult> ArchiveBySpecificPostType(Guid id, int? year = null, int? month = null, int? page = null,
            Guid? category = null, Guid? tag = null)
        {
            var sites = await _api.Sites.GetAllAsync();
            var site = sites.First();
            var model = await _api.Posts.GetAllBySiteIdAsync<MyPostType>(site.Id);
          
            return View(model);
        }
```

**Comment by tidyui** [comment]
Like you say, specifying the `PostType` on `Archives.GetByIdAsync<T>(...)` will filter out the archive to only include a single post type. For routing you can add **multiple** routes to a post type, for example.

    [PageType(...)]
    [PageTypeRoute(Title = "Default", Route = "/archive")]
    [PageTypeRoute(Title = "Only PostType One", Route = "/archive-one")]
    [PageTypeRoute(Title = "Only PostType Two", Route = "/archive-two")]
    public MyArchivePage : ArchivePage<MyArchivePage>
    {
        ...
    }

These different actions can the load the archive either as `PostBase` or a specific type to filter the archive.

**Comment by mspasiuk** [comment]
thanks for replying! 
And the sitemap? If I add another archive, (with different route) the archive is different. (I did not receive same guid on the controller)
I need the view listed on the sitemap, there will be menu options.

**Comment by tidyui** [comment]
The id passed into the action is always the **Page Id**. When getting the page your can find the **SiteId** on the Page model.

Regards
