### ISSUE TITLE
7.0 manager interface includes links when user is not authorized

### ISSUE THREAD

**Issue by CrossBound** [PiranhaCMS/piranha.core#756]
In the manager interface, even when the user that is logged in does not have the correct permissions it still shows all the menu items. If you click on a menu item you are not authorized for it takes you back to the login page. It would be much better for the links to never show up in the menu if the user is not authorized. This prevents questions from coming up such as " Why can't I access foo / bar ".

I propose the menu be dynamically generated based on the logged in user's authorized modules.

**Comment by tidyui** [comment]
Hi there, the intended functionality is like you describe. There seems to be a bug in the menu rendering where it forgets to adjust the items for the current user. Until this fix is included in the next release it can be fixed by putting the following view:

**_Menu.cshtml**

    @using Piranha.Manager
    @using Microsoft.AspNetCore.Authorization
    @inject ManagerLocalizer Localizer
    @inject IAuthorizationService Auth
    @{
        var menu = await Menu.Items.GetForUser(User, Auth);
    }

    <nav class="navbar navbar-left fixed-top navbar-dark bg-dark">
        <a class="navbar-brand" href="~/manager" tabindex="-1"></a>
        <ul class="navbar-nav">
            @foreach (var group in menu)
            {
                <li class="nav-item nav-header"><span class="navbar-text">
                    <i class="@group.Css"></i>@Localizer.Menu[group.Name]
                </span></li>
                @foreach (var item in group.Items)
                {
                    <li class="nav-item@(ViewBag.MenuItem == item.InternalId ? " active" :"")">
                        <a href="@Url.Content(item.Route)" class="nav-link" tabindex="-1">
                            <i class="@item.Css"></i>@Localizer.Menu[item.Name]
                        </a>
                    </li>
                }
            }
            <li class="nav-item nav-header">
                <a class="navbar-text" href="~/manager/logout">
                    <i class="fas fa-power-off"></i>@Localizer.Menu["Logout"]
                </a>
            </li>
        </ul>
    </nav>

in the the folder `~/Areas/Manager/Shared/Partial/`

Best regards
