### ISSUE TITLE
TinyMCE - Edit Source Code Toolbar button

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#758]
The TinyMCE has the "code" plugin included, but it's missing from the toolbar.

`plugins: [
                "autoresize autolink code hr paste lists piranhaimage piranhalink"
            ],`

Would it be possible to add the plugin to the toolbar?

`toolbar: "code | bold italic | bullist numlist hr | alignleft aligncenter alignright | formatselect styleselect | piranhalink piranhaimage"`

Any position would be fine, it allows users to tweak the content on a page with some css/html snippets which come in handy.

![pir1](https://user-images.githubusercontent.com/740215/63396519-a9dc1280-c40a-11e9-9d82-00218d020a22.png)
![pir2](https://user-images.githubusercontent.com/740215/63396524-ad6f9980-c40a-11e9-9981-0417fd3b499c.png)

**Comment by tidyui** [comment]
Hi! There’s an issue for this #262. This issue is for adding a good code editor that you can toggle between and not the code modal from TinyMCE as we find that one rather limited.

If you want to include the code editor in TinyMCE you can do this in your projects.

Best regards
