### ISSUE TITLE
TinyMCE - Toolbar Table Support

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#759]
Another suggestion for the TinyMCE editor. Modify the plugins to include table as shown:

`plugins:["autoresize autolink code table hr paste lists piranhalink piranhaimage"]`

then add the table to the "toolbar" list as shown: 

`toolbar:"code | table | bold italic | bullist numlist hr | alignleft aligncenter alignright | formatselect | piranhalink piranhaimage"`

Once these changes are made to piranha.min.js the resulting images are:

![pir5](https://user-images.githubusercontent.com/740215/63397293-6cc54f80-c40d-11e9-9eec-4b98cba4341b.png)
![pir3](https://user-images.githubusercontent.com/740215/63397294-6cc54f80-c40d-11e9-8ab3-b865a04228f8.png)
![pir4](https://user-images.githubusercontent.com/740215/63397295-6cc54f80-c40d-11e9-8def-0b35499f1eba.png)

**Comment by tidyui** [comment]
Hi there. The editor setup should be customized in the projects to include the desired feature. I’m working on updating the docs on how this is done in 7.0

Regards
