### ISSUE TITLE
Add category model

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#76]
Add category model with:

* Title
* Slug
* PrimaryImage
* Description
* Archive settings

Categories will mainly be used for classifying and generating archives for posts.

**Comment by gyretech** [comment]
Any additional specs on "Archive settings"?

**Comment by tidyui** [comment]
Hi! Almost all of the code for Posts/Categories/Tags/Archives are done in a backup branch but will not be lifted into the new codebase until `4.1` release. The `4.0` release will only include Pages.

**Comment by gyretech** [comment]
When will 4.1 be released?

**Comment by tidyui** [comment]
As soon as 4.0 is released the work with 4.1 will begin.

**Comment by tidyui** [comment]
Category model, repository & integration tests in place. Admin UI needs to be added.
