### ISSUE TITLE
Separator and other elements not rendering correctly

### ISSUE THREAD

**Issue by mortware** [PiranhaCMS/piranha.core#769]
With a fresh install, I tried adding the elements to a new page:

- Separator
- Columns
- Gallery

All display strangely. For instance, the separator displays a GUID. The gallery and columns display 
`System.Collections.Generic.List'1[Piranha.Extend.Block]`
https://imgur.com/a/yj06b9Z

**Comment by tidyui** [comment]
We have issue for this in the Piranha.Templates repository. There are some default display templates missing.

**Comment by jbolt1236** [comment]
Hey I see that this issue was closed. What was the answer to fixing it? Getting same error on all of the above.

**Comment by jbolt1236** [comment]
Can you link the associated issue?

**Comment by jbolt1236** [comment]
Link to associated issue in Piranha.Templates repository. https://github.com/PiranhaCMS/piranha.core.templates/issues/3
