### ISSUE TITLE
Setting Properties on a Block

### ISSUE THREAD

**Issue by daudirsch** [PiranhaCMS/piranha.core#773]
First off, thank you for all of the hard work on this project.  As I have just begun to look into the details of the project I hope I'm not asking a duplicate question.  Is there a way to set properties on a block such as "style" or "class"?  A simple example would be assigning a class for an HTML block or image block via the manager.  Another example would be to set the background color of a column.

Thanks in advance.

**Comment by tidyui** [comment]
Hi there! There are no such default settings, instead the idea is to create your own blocks to fit your own needs. Here's an example on how you could extend the `HtmlBlock` to add a `CssClass` field to it.

**FormattedHtmlBlock.cs**

    using Piranha.Extend.Blocks;
    using Piranha.Extend.Fields;

    namespace MyApp.Models
    {
        [BlockType(Name = "Formatted Content", Category = "Content", Icon = "fas fa-paragraph", Component = "format-html-block")]
        public class FormattedHtmlBlock : HtmlBlock
        {
            public StringField CssClass { get; set; }
        }
    }

**Custom Javascript**

    /*global
        piranha
    */

    Vue.component("format-html-block", {
        props: ["uid", "toolbar", "model"],
        data: function () {
            return {
                body: this.model.body.value
            };
        },
        template:
            "<div>" +
            "  <div class='form-group'>" +
            "    <label>Css Class</label>" +
            "    <input class='form-control' type='text' v-model='model.cssClass.value' />" +
            "  </div>" +
            "  <div class='html-block'>" +
            "    <html-block v-bind:uid='uid' v-bind:toolbar='toolbar' v-bind:model='model'></html-block>" +
            "  </div>" +
            "</div>"
    });

As you can see, both the **block** and the Vue **component** uses the basic HtmlBlock and adds an extra field to it.

Please note that the current manager styles will not present this correctly as the css-classes for blocks where a bit to restrictive. We will change this in `7.0.2` of the manager which will be released this week.

Best regards

**Comment by daudirsch** [comment]
Cool, that's what I was doing for other custom blocks.  I wasn't sure if that was "best practice" for adding properties to the core Blocks (HTML, image, etc).   Thanks for the response!
