### ISSUE TITLE
Piranha database

### ISSUE THREAD

**Issue by zakwillis** [PiranhaCMS/piranha.core#776]
Hi guys, how are you doing? I am working on quite an old version of Piranha 5.3.0..., so this may not be an issue. 

Please don't take offence at what I say.

However, I looked at your database structure and noticed there are no primary keys on the database. I guess if you are caching the data on site startup, this is not so bad but heap tables are bad if data is constantly added and deleted.

A second point is, I know coders do this, the database should really be in a SQL Server Project. I realise, older .Net/Entity Framework lets people do code first but it is not best practice.

I am happy to take these tasks on in due course, but am busy at the moment or I can drop an example SQL Project up shortly for you to commit/push?

**Comment by tidyui** [comment]
Hi there!

The database has **primary keys**, **foreign keys** and **indexes**, all created by Entity Framework in the migrations. We have however seen issues from other users of these indexes not persisting when exporting/restoring data between databases. These issues have had nothing to do with the migrations, but rather with how the databases has been restored.

In regards to Code First we have chosen this approach for the simplest possible setup on multiple platforms, Piranha is in no way limited to SQL Server. This goes in line with Microsofts official documentation on EF Core which recommends the use of Migrations if the model layer is the source origin of the Schema.

Best regards

Håkan

**Comment by zakwillis** [comment]
Hi Hakan, yeah, I kind of thought this. Once you go for multi-platform, maintaining this sort of thing becomes harder. Oracle Data Modeler is a great free tool for database interoperability and managing data models, but not sure it covers SQLLite. Perhaps one solution is to let some people add extra database repositories to help validate things like database consistency. The main reason this is an issue in the SQL World is if data is dropped, edited and readded, over time, you get heaps/fragmentation.

I am not a fan of code first, and indeed use Dapper for all Data Access unless I am onsite with clients, but again, I understand why you did it.

Many thanks.

**Comment by tidyui** [comment]
however, as you can change data repositories you could actually write a repository layer in dapper instead. I’m planning on writing one for file based JSON storage for example!

**Comment by zakwillis** [comment]
I will take a look at your data access/repository layer. The only thing I imagine is, all of your code, joins is in LINQ to Entities, wrapped inside Entity Framework. Once you take that route, there is no real benefit to using Dapper as the same join logic would need to be pushed to the database layer and then you get divergence of business logic. I will start to look into your code more anyway to see if I can help in the future.

**Comment by tidyui** [comment]
All LINQ queries are inside the EF repositories, the service layer calls a clean Api. So another repository layer could have a completely different Schema, for example if you were using a NoSql database!

**Comment by zakwillis** [comment]
Hi again. It is worth noting that although Dapper does have a Linq to entities capability, it isn't what Dapper is for. Dapper is more about letting you take advantage of SQL. One such example is returning multiple recordsets from one pass. Anyway, I will take a look at your code when I upgrade to your later version. Happy Friday.
