### ISSUE TITLE
PageField only shows links from the default site.

### ISSUE THREAD

**Issue by lgoudriaan** [PiranhaCMS/piranha.core#777]
I currently have a multi-site setup and when I try to select a page in my second (not default site). It shows only the pages from the default site.

It also would be nice to switch between sites in the PageField, just like the copy page function.

**Comment by tidyui** [comment]
We have verified it for the `PageField`, however in the `PostField` you can select both `Site` and `ArchivePage`

**Comment by lgoudriaan** [comment]
Oops my bad, I will edit the title.

**Comment by lgoudriaan** [comment]
Thanks for the quick fix and release!
