### ISSUE TITLE
Post model

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#78]
Add post model for publishing not placed in a specific position in the sitemap. Posts should support the same kind of content as pages but should be grouped by their category.

**Comment by gyretech** [comment]
Please clarify "not placed in a specific position". Also do we need PostTypes?

**Comment by tidyui** [comment]
See my comment on #76

**Comment by tidyui** [comment]
Post model, repository & integration tests in place. Admin UI needs to be added.
