### ISSUE TITLE
Links in the template

### ISSUE THREAD

**Issue by pauldbentley** [PiranhaCMS/piranha.core#780]
Hi, I am building a site which has social links (Facebook, Twitter etc) I'd like them to be in the CMS so the content editor can add which ever links they like.

Where would be a good place to store this?  I was initially thinking in a SiteContent class?  And that they would be a `List<SocialLink>` or similar so they can add as many as they like?

**Comment by lgoudriaan** [comment]
I have created a new site type with a social region in it. I think it really depends on your needs.

**Comment by tidyui** [comment]
Like @lgoudriaan wrote, it totally depends! If your social link should be **the same** for all pages, for example in the Site Footer you should put them on the Site. If they should share direct links to specific items in the site maybe they should be put on a different level.

**Comment by pauldbentley** [comment]
Yes they will be the same across all pages in the site footer, so as suggested I've put an `IList<SocialLink>` region on my `SiteContent`.

In my footer partial I'm then using:

`var siteContent = await WebApp.Site.GetContentAsync<DefaultSite>();`

Is this a good way of doing it?  I've put a few other properties on my `DefaultSite` so find I'm calling `GetContentAsync` in quite a few places.
