### ISSUE TITLE
Confirm deleting site

### ISSUE THREAD

**Issue by pauldbentley** [PiranhaCMS/piranha.core#783]
Have a confirmation box when deleting a site - or maybe implement a "Danger Zone" pattern like when deleting a github repository where you have to confirm the site name before deleting.

**Comment by pauldbentley** [comment]
The manager also allows deleting the default site, maybe this shouldn't be allowed?

**Comment by tidyui** [comment]
Well that depends. The `DbContext` seeds the Default Site if no sites exists, but there's not really any obligation to keep that site as the data evolves.

**Comment by pauldbentley** [comment]
> Well that depends. The `DbContext` seeds the Default Site if no sites exists, but there's not really any obligation to keep that site as the data evolves.

Yes that's true, ignore my comment then.

**Comment by tidyui** [comment]
Clicking delete will open the following confirmation in the modal footer.

![Skärmavbild 2019-09-03 kl  13 22 32](https://user-images.githubusercontent.com/781266/64169358-f1708e80-ce4d-11e9-822d-a1a5017a7a75.png)

**Comment by pauldbentley** [comment]
> Clicking delete will open the following confirmation in the modal footer.
> 
> ![Skärmavbild 2019-09-03 kl 13 22 32](https://user-images.githubusercontent.com/781266/64169358-f1708e80-ce4d-11e9-822d-a1a5017a7a75.png)

Perfect
