### ISSUE TITLE
Custom TinyMCE for specific region

### ISSUE THREAD

**Issue by pauldbentley** [PiranhaCMS/piranha.core#789]
It is possible to have a different TinyMCE configuration for a specific region?

My use case is I would like a region with a `HtmlField` but to restrict the allowed functions i.e. just have bold and italic for example.

But when adding a `HtmlBlock` I want all the functions available.

**Comment by tidyui** [comment]
Currently it's the same initialization for all Tiny MCE editors. You could easily add your own block for a simpler HTML-field as the structure is quite simple:

    Vue.component("html-field", {
        props: ["uid", "toolbar", "model"],
        data: function () {
            return {
                body: this.model.value
            };
        },
        methods: {
            onBlur: function (e) {
                this.model.value = e.target.innerHTML;
            }
        },
        computed: {
            isEmpty: function () {
                return piranha.utils.isEmptyHtml(this.model.value);
            }
        },
        mounted: function () {
            piranha.editor.addInline(this.uid, this.toolbar);
        },
        beforeDestroy: function () {
            piranha.editor.remove(this.uid);
        },
        template:
            "<div class='field html-field' :class='{ empty: isEmpty }'>" +
            "  <div contenteditable='true' :id='uid' spellcheck='false' v-html='body' v-on:blur='onBlur'></div>" +
            "</div>"
    });

As you can see the component calls `piranha.editor.addInline()` for setting up the editor. Here you could call your own `javascript` method that sets up the editor in a completely different way.

Best regards

**Comment by pauldbentley** [comment]
Excellent, thanks for the response.  This will do exactly what I need.

**Comment by tidyui** [comment]
Awesome! And for the record I meant **field** and not block. The code I provided is also for the HtmlField
