### ISSUE TITLE
BlockDisplayMode.Vertical component

### ISSUE THREAD

**Issue by pauldbentley** [PiranhaCMS/piranha.core#791]
I notice there isn't a `block-group-vertical` component when using `BlockDisplayMode.Vertical`.  Are there plans to implement this?  I'm developing a `BlockGroup` class and the vertical layout would work really well for it.

**Comment by tidyui** [comment]
Hi! Yes we didn’t have time to implement it before release. We’ll look at it for a future release of the manager!

**Comment by pauldbentley** [comment]
> Hi! Yes we didn’t have time to implement it before release. We’ll look at it for a future release of the manager!

Great thanks!

I'm spotting a few little things with the block-group, mainly regarding getTitle() returning [Not Implemented] - shall I continue to raise issues?  I didn't want to bombard you!

**Comment by tidyui** [comment]
As Block Groups can't be positioned within other Block Groups there's no reason for implementing `getTitle()` for groups. They are inherited from `Block` which has the default implementation of `[Not Implemented]`.

Regards

**Comment by pauldbentley** [comment]
Sorry, I mean when adding `Blocks` to a `BlockGroup`.  I have created a simple `BlockGroup` and added some content, quote, separator, audio, image and video and this is what is displayed:
![Capture](https://user-images.githubusercontent.com/5243982/64534739-eade8d00-d30d-11e9-8981-77f07a4eabba.PNG)

Image does show the file name, as does Audio and Video, but not when you go back into the editor after you have saved.

**Comment by tidyui** [comment]
Allright, I follow you now. Could you split this into a separate issue for the default title implementations!

Best regards

**Comment by tidyui** [comment]
We will not be able to squeeze in the vertical component in `SR3`, but as the component `blockgroup-vertical` is called it can be registered in the client project. We will let you know when we have an implementation for this, or in the meantime you can add it yourself if you want.

Regards
