### ISSUE TITLE
Default title implementations in BlockGroup

### ISSUE THREAD

**Issue by pauldbentley** [PiranhaCMS/piranha.core#800]
When adding `Blocks` to a `BlockGroup`, the titles are displayed as `[Not Impletemented]` for some `Blocks`.

![64534739-eade8d00-d30d-11e9-8981-77f07a4eabba](https://user-images.githubusercontent.com/5243982/64603919-0c488300-d3b9-11e9-8693-aa9fe6c1b725.png)

Separated from #791

**Comment by Neteklab** [comment]
Also need to override GetTitle( ) in the inherited block:

```
   public class Slide: Piranha.Extend.Block{

      public StringField Title{ get; set; }
      ...
      public override string GetTitle( )=> Title.Value;
   }

```
