### ISSUE TITLE
List Category posts

### ISSUE THREAD

**Issue by lfontaine974** [PiranhaCMS/piranha.core#804]
Hi,

What is best possibility to get all category with at least one post please ? 

Thanks

**Comment by tidyui** [comment]
Hi there!

Categories and Tags are cleaned every time a post is saved to ensure that only used taxonomies are kept in the database!

**Comment by lfontaine974** [comment]
Ok thanks but from a view or partial view how to get all categories please ?

**Comment by lfontaine974** [comment]
I want to avoid to list each post to have categories list :)

**Comment by tidyui** [comment]
Hi! The PostService has a method for getting all categories for an archive!

    await api.Posts.GetAllCategoriesAsync(...)

**Comment by lfontaine974** [comment]
Thanks very much !!! Very good. :)

var category = await Api.Posts.GetAllCategoriesAsync(Model);
foreach (var c in category)
{
...
}

**Comment by lfontaine974** [comment]
Thanks it ok now !
