### ISSUE TITLE
Possible to add fields to a BlockGroup?

### ISSUE THREAD

**Issue by Svsk** [PiranhaCMS/piranha.core#805]
Hi! First off; I love this project! I have only recently started using it, so I am still a bit green.

Is it possible to add fields to a `BlockGroup`? For instance I want to have a set of `ColumnBlock`s in a row with a background image. It would be ideal to be able to set the background on the `BlockGroup`. 

I tried creating a custom `BlockGroup` and adding a field to it in version 7.0.0. It seemed to work in the sense that I was able to edit the value in the manager, but upon save it threw an exception stating missing required parameter `Name`.

Thanks!

**Comment by tidyui** [comment]
You should be able to add global fields to groups. We will verify the functionality and get back to you after that.

Best regards

Håkan

**Comment by tidyui** [comment]
We have verified the bug. The problem is when creating a new block group that has a global field, the Id property of the field is not set correctly causing a NullPointerException when saving the model.
