### ISSUE TITLE
TinyMCE has licensing issues - Move it into a separate module and use a different default editor

### ISSUE THREAD

**Issue by 121GWJolt** [PiranhaCMS/piranha.core#815]
TinyMCE currently requires a license to host it on anything other than an LGPLv3-compatible use case. Therefore, its inclusion in anything without the  [expensive self-hosting license](https://www.tiny.cloud/pricing/) has a legal risk attached to it. Potential alternatives include [Trumbowyg](https://alex-d.github.io/Trumbowyg/) and [Summernote](https://summernote.org/), both of which are MIT-licensed.

**Comment by tidyui** [comment]
I have created a feature-branch for this and started working on it:

https://github.com/PiranhaCMS/piranha.core/tree/features/editor-restructuring

I have moved `TinyMCE` from the manager into its own package and also added a package for `Summernote` as an example. It's not complete, but I have added basic image library integration for the `Summernote` editor. The example `MvcWeb` uses the TinyMCE package and the `RazorWeb` example uses the Summernote package

**Comment by 121GWJolt** [comment]
Editor loads and I like the interface a lot. Media plugin loads for me too.

For saving I propose possibly hooking into [this function](https://summernote.org/deep-dive/#onfocus-onblur-onblurcodeview) or [this function](https://summernote.org/deep-dive/#onchange) and changing the signature of the addInline method to have a callback for saving the model posted to it. Callback could pass one parameter containing the string value of Summernote's contents.

**Comment by tidyui** [comment]
I have gone through licensing terms and taken precautions. What this means is that I've added the correct "Powered by Tiny" link on all editors when active. As fas as `LGPL` this license does not prohibit usage in closed commercial software at all when components are used as a library. The only thing `LGPL` tries to control is that if you make changes or modifications to the library, these changes are also to be considered `LGPL`. I am 100% sure that it's not a problem using `LGPL` components in closed source software as we in fact used this license for the old legacy version of Piranha for many years before switching to `MIT`.
