### ISSUE TITLE
How to create dropdown menu?

### ISSUE THREAD

**Issue by baibhavs** [PiranhaCMS/piranha.core#816]
Hi I new piranha . I want to create dropdown menu. I have create multiple page under abroad study
and structure as shown in screenshot. When I hover over abroad study i want drop-down menu to be opened.At present abroad study is only appearing in navbar . Please let me know do is it supported or i have to customize code?
![image](https://user-images.githubusercontent.com/20481221/65278166-1e5cbb00-db49-11e9-86b8-0a9b555d77b1.png)

**Comment by tidyui** [comment]
Hi there! I’m assuming that you’ve started your project with one of the templates available as they only render the first level in the sitemap.

First off, Piranha is a headless CMS, meaning that the code you get from the template is just an example, just like when you create a new MVC application in Visual Studio.

Secondly, the sitemap used to render the menu in the template is a recursive structure. Each item has an Items property that holds the children and can be used to render a dropdown menu.

I’ll try to provide an example for you 😁

Regards

**Comment by mrccarvalho** [comment]
Hi ! A few days ago I had the same need as you.
I'm working on an example.
I hope this helps you!

![piranhacmsMultiLevelMenu](https://user-images.githubusercontent.com/22612587/65320249-5986da80-db99-11e9-81c0-1cde3ddb7c8f.png)

Bests regards

**Comment by ulfetalhussaini** [comment]
Thanks @mrccarvalho , it was very helpful to me.

**Comment by RickIsWright** [comment]
Thanks @mrccarvalho.

**Comment by RickIsWright** [comment]
I discovered the best way to navigate the menu is by creating a recursive function that looks for the parentMenu.Items.Count > 0 to continue recursion, or create the single menu item if it has no children. 
a simple 7 line recursive function seems to do the trick.
