### ISSUE TITLE
How to add custom form/pages like cantact us?

### ISSUE THREAD

**Issue by baibhavs** [PiranhaCMS/piranha.core#817]
I am evaluating piranha cms. I am trying to create basic business website using it.I need to create few customs forms/page like contact us, feedback etc? How can I add them?

**Comment by tidyui** [comment]
You can post back to any page instance, take a look at the docs here:

http://piranhacms.org/docs/architecture/routing/advanced-routing

However it's up to you how you save the data. Piranha only handles content. We have an open issue created by other users on creating a generic Form Builder, maybe that is something you'd like to collaborate on. 

https://github.com/PiranhaCMS/piranha.core/issues/628

Best regards

Håkan

**Comment by sea-4** [comment]
+1 on the form builder :-)

**Comment by axunonb** [comment]
> http://piranhacms.org/docs/architecture/routing/advanced-routing

The new link:
https://piranhacms.org/docs/application/advanced-routing
