### ISSUE TITLE
Add GenericBlock

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#820]
Add support for rendering "Generic Blocks", i.e where the fields are just rendered using the view components for the fields. This also requires that blocks are exported completely different through the manager Api as blocks does not contain meta-data for fields.

**Comment by tidyui** [comment]
This should probably consist of two parts. First some way to mark the BlockType that it should be serialized as a generic block, like a `GenericBlockAttribute`, and secondly a `Vue` component `generic-block` that can be registered as the component for the block. This way it would be possible to create custom block components the uses the generic serialization model if desired.

**Comment by tidyui** [comment]
As support for .NET Core `2.2` ends in December we have to push this feature to `8.1` and focus on migrating to .NET Core `3.0`.

**Comment by psandgren** [comment]
Nice work! Speeds up development a lot!
