### ISSUE TITLE
How could we add a different type of archive page from the page main blog when you click on a category?

### ISSUE THREAD

**Issue by Rabehoavy** [PiranhaCMS/piranha.core#824]
Hi,

How could we add a different type of archive page from the page main blog when you click on a category?

Thank you

**Comment by tidyui** [comment]
Are you using MVC or Razor Pages?

**Comment by Rabehoavy** [comment]
MVC

**Comment by tidyui** [comment]
You could do it like this for example. 

    [Route("archive")]
    public async Task<IActionResult> Archive(Guid id, int? year = null, int? month = null, 
        int? page = null, Guid? category = null, Guid? tag = null)
    {
        var model = await _api.Pages.GetByIdAsync<Models.BlogArchive>(id);
        model.Archive = await _api.Archives.GetByIdAsync(id, page, category, tag, 
            year, month);

        if (model.Archive.Category != null)
        {
            return View("CategoryArchive", model);
        }
        return View(model);
    }

**Comment by Rabehoavy** [comment]
Thanks
