### ISSUE TITLE
Implement Post views count

### ISSUE THREAD

**Issue by mspasiuk** [PiranhaCMS/piranha.core#825]
What is the best way to save in a post property the view count for that post?
I need to create on my home a "Top Viewed Posts" section and list the first 5.

My first approach was to create a field on my post model class
```
 [Field]
  public NumberField Views { get; set; }
```
and then in the controller do something like

 ```
[Route("aroute")]
public async Task<IActionResult> GetMyPost(Guid id)
 {
        var model = await _api.Posts.GetByIdAsync<MyPost>(id);
         _ = model.MyRegion.Views.Value == null ? model.MyRegion.Views.Value = 0 : model.MyRegion.Views.Value = model.MyRegion.Views.Value + 1;
        await _api.Posts.SaveAsync(model);

        return View(model);
  }

```

**Comment by tidyui** [comment]
Hi there! Personally I wouldn't store it in a field on the post for the following reason.

1. You're solution includes a save operation (with model transformation) each time the post is accessed.
2. Every time the post is saved it is purged from cache, meaning that caching is effectively disabled for posts.
3. Querying the data includes complex join operation as it is stored on a field of a normalized model.

Instead, for optimal performance I would add an application specific `DbContext` with a entity that would look something like this:

    public class PostViews
    {
        public Guid PostId { get; set; }
        public DateTime Created { get; set; }
    }

Then getting the data would be a simple matter of performing a `Count` on the number of rows for a specific `PostId`. You could of course have **one single row** with the count, but the you have to handle the fact that you have the possibility of several server threads updating the value at the same time.

Also, I would expose the method for updating the statistics via an `ApiController` that you call from `Javascript` in the client after the page is rendered to minimize the amount of operations that has to be done before presenting the page to the user.

Best regards
