### ISSUE TITLE
BlockGroup fields are not initialized on load

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#836]
This means that when adding new fields to existing Block Groups the fields are not initialized when loading an existing group.

**Comment by monsieurberry** [comment]
Hi Håkan!

Is this why my page doesn't save when my Custom BlockGroup has a field on it?

I get a console error in the browser...

Uncaught TypeError: Cannot set property 'visible' of undefined
    at piranha.min.js:formatted:32301

Cheers!

Adam

**Comment by tidyui** [comment]
If you’re getting the error saving an existing block that you’ve added fields to but not if you create a new block it’s this error.

To verify, create a new page and add the block group to it. If it saves ok then it’s the above error

**Comment by monsieurberry** [comment]
Thanks Håkan,

I tried with an existing block group and the field doesn't show at all.

I then created a new page and added the block group. The field then showed and - but the page wouldn't save correctly and I got the console error as outlined above. Perhaps its something wrong with my setup of the Block and BlockGroup...

When I expand out the console error it takes me to the following JS and its on the `e.style.visible = !0` line where it seems to be failing...

piranha.notifications = new Vue({
    el: "#notification-hub",
    data: {
        items: []
    },
    methods: {
        push: function(e) {
            e.style = {
                visible: !1,
                "notification-info": "info" === e.type,
                "notification-danger": "danger" === e.type,
                "notification-success": "success" === e.type,
                "notification-warning": "warning" === e.type
            },
            piranha.notifications.items.push(e),
            setTimeout(function() {
                e.style.visible = !0,
                e.hide && setTimeout(function() {
                    e.style.visible = !1,
                    setTimeout(function() {
                        piranha.notifications.items.shift()
                    }, 200)
                }, 5e3)
            }, 200)
        }
    }
}),

My Block Group class is as follows

[BlockGroupType(Name = "Destination Group", Category = "DigiRooms", Icon = "fas fa-map-marker-alt")]
    [BlockItemType(Type = typeof(FeaturedDestinationBlock))]
    public class FeaturedDestinationBlockGroup : BlockGroup
    {
        public StringField Title { get; set; }
    }

and my Block class is as follows...

[BlockType(Name = "Destination", Category = "DigiRooms", Icon = "fas fa-map-marker-alt", Component = "featured-destination-block")]
    public class FeaturedDestinationBlock : Block
    {
        public StringField Title { get; set; }
        public StringField DestinationSlug { get; set; }
        public DateField ArrivalDate { get; set; }
        public DateField DepartureDate { get; set; }
        public NumberField NumberOfProperties { get; set; }
        public StringField LinkText { get; set; }
        public ImageField Image { get; set; }
    }

The Block works fine independently of the Block Group.

The Group also works if I comment out the Title field, but not with it included

I feel like I followed the docs 100% but I still must be missing something

Many Thanks

Adam

**Comment by monsieurberry** [comment]
Håkan please ignore the above - I solved the issue by updating Piranha.Manager to 7.0.4

Cheers

Adam
