### ISSUE TITLE
Application startup exception: Editor config editorconfig.json not found!

### ISSUE THREAD

**Issue by hrvoje-grabusic** [PiranhaCMS/piranha.core#842]
Hi,

A minor issue after following the getting started instructions the app doesn't run.
dotnet new piranha.web
dotnet restore
dotnet run

> Application startup exception: Editor config editorconfig.json not found!

After creating that [file](http://piranhacms.org/docs/components/html-editor) everything works.

Very nice Clean CMS :)

**Comment by tidyui** [comment]
Thanks! I'll take a look at it, it must be missing from the template package!

**Comment by tidyui** [comment]
Fixed now in the template repository. Will be available next service release. Thanks! https://github.com/PiranhaCMS/piranha.core.templates/issues/5
