### ISSUE TITLE
Add a field with tags

### ISSUE THREAD

**Issue by lfontaine974** [PiranhaCMS/piranha.core#848]
Hi,

Is it possible to add in manager an other field like tags ? 

Have you an example ?

Thanks

**Comment by tidyui** [comment]
Hi there! Could you clarify a bit what you want to achieve, I’m not following you.

Regards

**Comment by lfontaine974** [comment]
I just want to add a new field in a region or in main content of a post. In this field, I want to save Town tag (ex : Paris, New-York...) to have a localisation tag.

**Comment by tidyui** [comment]
Hi again! This can be implemented in an infinite amount of ways, so it's hard to give one answer to it. First off some basic questions.

1. Should this field use the tags of the existing Archive or should it be a distinct set of tags.
2. If it should be a new set of tags, should these work like the existing ones (i.e choose existing or add new), or should they be a predefined set of tags for the users to select from.

If you want the user to select from a set of pre-defined tags the simplest solution is to use a `SelectField<enum>` to let the user select. This however means that new tags means the web needs to be redeployed as the enum has to be updated.

A simple mid-way solution is that you add a `Param`, like so:

    await api.Params.SaveAsync(new Param
    {
        Key = "MyTagParam",
        Value = "Paris;New-York;London"
    });

The field could then load this param, split the value into a collection and use them as select options. If the used adds a new param you just update the param value.

The most complex solution is of course to add your own database context and tables for storing these tags much like the built-in solution does.

**Comment by lfontaine974** [comment]
It's exactly your example for a field with a distinct set of tags. I will have a set of 24 tags only.

Where can I must add Param please ? 

Thanks

**Comment by lfontaine974** [comment]
And if I want to add a new set of tags, should these work like the existing ones (i.e choose existing or add new), what is the solution ? In this solution, it will be possible to add many tags for a post or page. Thanks so much !!!

**Comment by tidyui** [comment]
How they should work is completely up to you, whether you want the used to be able to select several "Countries" or what you're using it for. Please note that even after adding a `Param` with the raw data you will still need to implement a custom `Field` for this, and a `Vue.js` component for rendering the field in the manager.

http://piranhacms.org/docs/extensions/custom-fields

Regards

**Comment by lfontaine974** [comment]
Ok but with the first solution enum, where can I add the param please ?

**Comment by tidyui** [comment]
As this was rather fun, here's my simple solution (which can probably be improved on) 😀. This field allows for **one** selected tag at a time and as such works very much like the Post Category.

**Custom Field And Serializer (full source code)**

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Piranha;
    using Piranha.Extend;
    using Piranha.Models;

    namespace MyWebApp.Models.Fields
    {
        [FieldType(Name = "Custom Tag", Component = "custom-tag")]
        public class CustomTagField : IField
        {
            /// The selected value. This will be stored in the database.
            public string Value { get; set; }

            /// The previously created options from other posts.
            public IList<string> Options { get; set; } = new List<string>();

            // The title when used in a list region.
            public string GetTitle()
            {
                return Value;
            }

            // Initializes the field
            public async Task Init(IApi api)
            {
                // Get the options param
                var param = await api.Params.GetByKeyAsync("CustomTagFieldOptions");

                if (param != null)
                {
                    // We found the param, let's split the string value and assing
                    // to options if it's not empty.
                    if (!string.IsNullOrEmpty(param.Value))
                    {
                        Options = param.Value.Split(';', options: StringSplitOptions.RemoveEmptyEntries).OrderBy(s => s).ToList();
                    }
                }
                else {
                    // No existing param, let's create it.
                    param = new Param
                    {
                        Key = "CustomTagFieldOptions"
                    };
                }

                // Check that the selected value exists in the options,
                // if it doesn't, let's add it
                if (!string.IsNullOrEmpty(Value) && !Options.Contains(Value))
                {
                    Options.Add(Value);
                    Options = Options.OrderBy(s => s).ToList();

                    param.Value += $";{ Value }";
                    await api.Params.SaveAsync(param);
                }
            }
        }

        public class CustomTagFieldSerializer : ISerializer
        {
            // When we serialize, ONLY store the selected option
            public string Serialize(object obj)
            {
                if (obj is CustomTagField)
                {
                    return ((CustomTagField)obj).Value;
                }
                throw new ArgumentException();
            }

            // Create a new field from the given string
            public object Deserialize(string str)
            {
                return new CustomTagField
                {
                    Value = str
                };
            }
        }
    }

**Vue.js component for rendering the field**

    Vue.component("custom-tag", {
        props: ["uid", "toolbar", "model", "meta"],
        mounted: function () {
            var self = this;

            $("#" + self.uid).select2({
                tags: true,
                selectOnClose: true,
                placeholder: piranha.resources.texts.addTags
            });
            $("#" + self.uid).on("change", function() {
                var item = $(this).find("option:selected").text();
                self.model.value = item;
            });
        },
        template:
            "<select class='form-control' :id='uid' v-model='model.value'>" +
            "  <option :value='item' v-for='item in model.options'>{{ item }}</option>" +
            "</select>"
    });

**Startup.cs**

            // Register the field
            App.Fields.Register<MyWebApp.Models.Fields.CustomTagField>();
            // Register the serializer
            App.Serializers.Register<MyWebApp.Models.Fields.CustomTagField>(new Models.Fields.CustomTagFieldSerializer());
            // Add the script with the manager component, change to where your js file is located
            App.Modules.Get<Piranha.Manager.Module>().Scripts.Add("~/assets/js/custom-tag.js");

Enjoy and make something awesome!!!

Regards

**Comment by tidyui** [comment]
Answer now also available here as a blog post:

http://piranhacms.org/blog/creating-a-custom-tag-field
