### ISSUE TITLE
Paging archive page by months 

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core#852]
Hi 
I need to made paging archive page by months

**Comment by tidyui** [comment]
This is supported if you route to an archive page with

    mydomain.com/myblog/year/month

For example:

    http://piranhacms.org/blog/2019/10

**Comment by tidyui** [comment]
You can see the complete set of routing options if you take a look at **Archive Middleware** here:

http://piranhacms.org/docs/architecture/middleware

Regards

**Comment by haidersafaa** [comment]
thanks a lot
