### ISSUE TITLE
Cannot choose route for page

### ISSUE THREAD

**Issue by mikaellindemann** [PiranhaCMS/piranha.core#856]
According to http://piranhacms.org/docs/basics/how-to-setup-content/page-types, adding multiple PageTypeRoute attributes on a page type should cause the manager settings to enable switching between the different routes.

```csharp
[PageType(Title = "Standard page")]
[PageTypeRoute(Title = "Default Page", Route = "/page")]
[PageTypeRoute(Title = "Title Page", Route = "/titlepage")]
public class StandardPage  : Page<StandardPage>
{
}
```

I cannot seems to get this activated, and looking through the manager code since the v7 transition, it doesn't seem like there has been support for it at all in the manager.

Piranha will currently just use the first declared PageTypeRoute in the file.

If I downgrade to v6.1, the dropdown for routes show up.

**Comment by tidyui** [comment]
Thanks! We’ve had a couple of things that just was forgotten during the rewrite of the manager.
