### ISSUE TITLE
posts archive by slog

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core#859]
hi 
I used archive  like Route("archive") in mvc i want to get last 20 post by slog

**Comment by tidyui** [comment]
Hi there! The method `GetByIdAsync` in `api.Archives` has an **optional parameter** `pageSize` which determines how many posts should be returned. If this parameter is omitted it uses the default config param `config. ArchivePageSize` which can be set from the manager interface.
