### ISSUE TITLE
Add paging in manager archive view

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core#860]
we have a Blog archive page it have more than 4000 posts (transferred by script from other cms ) it very slow load cause it load all the 4000 posts, we made Archive page size
 to 12 but it load all posts

**Comment by tidyui** [comment]
The manager view is simply not designed for 4000 posts as there’s no paging in the manager. I’ll update the title and add it as a feature request.

**Comment by haidersafaa** [comment]
thanks for your reply but can we made solution from our site >

**Comment by tidyui** [comment]
Not without replacing the manager archive component in your local application.

Regards

**Comment by haidersafaa** [comment]
also if you have a lot off images in manager

**Comment by tidyui** [comment]
Hi! There has already been a PR merged for performance optimization for the media view for `7.1`, see #845
