### ISSUE TITLE
HTTP Error 500.35

### ISSUE THREAD

**Issue by carthax12** [PiranhaCMS/piranha.core#861]
Out of the box installation of Piranha on a brand new ASP.Net Core MVC website.  It works perfectly running from my local machine.

I post it to my website (smarterasp.net is the host), and then run it. 

I get an error stating:

HTTP Error 500.35 - ANCM Multiple In-Process Applications in same Process 

Nothing shows in the IIS logs on the hosting control panel.

Any thoughts?

**Comment by tidyui** [comment]
Hi there! It’s not an error we’ve seen or had reported before, however we deploy all of our projects on Azure Web Apps. Post a message in our Gitter channel and check if someone else has had similar experiences publishing to other hosting providers.

Best regards
