### ISSUE TITLE
Using Piranha's media handler in custom manager views

### ISSUE THREAD

**Issue by Nauvran** [PiranhaCMS/piranha.core#862]
Im looking for a way to add the media handler to some custom views, to try and keep the theme and flow of work.
In general just being able to re-use Piranha elements in custom views would be nice.
Thanks in advance.

**Comment by tidyui** [comment]
Hi there! When logged in to the manager it's very simple to reuse the different components. We have purposely designed every part as it's own self container `Vue` application, for example:

## Open the media picker modal and pick an asset

    piranha.mediapicker.open(function(d) { 
        // Do something with the selected asset
        console.log(d) 
    });

The open method also has parameters for filtering the modal and which folder to open.

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/assets/src/js/piranha.mediapicker.js

### Open the preview modal for an asset

    piranha.preview.open(id);

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/assets/src/js/piranha.preview.js

Best regards

**Comment by tidyui** [comment]
And we are currently working on updating and restructuring the documentation. All of these elements will be covered in detail!

**Comment by Nauvran** [comment]
Awesome!
Thanks for the help
