### ISSUE TITLE
override the seed and use database directly 

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core#863]
Hi
I need to override the seed and use database directly cause i transferred data from other CMS it note easy to add this data to seed class

**Comment by tidyui** [comment]
Hi! Are you talking about the seed of example data in the template projects or the basic seed in the core library? The **core** seed method only makes sure that all of the **system config params** exist in the database and adds **one default site** to the database if the site table is empty.

**Comment by haidersafaa** [comment]
thanks for your replay 
Dear we used piranha.core-v.6.1.1 and use the mvcweb example

**Comment by tidyui** [comment]
The seed of the templates project is completely optional - you have an option when you start the project the first time if you wish to seed example data or go straight to the manager.

**Comment by haidersafaa** [comment]
after we publish to iis and upload to sql server our database we received this error 
Database 'piranha' already exists. Choose a different database name.

**Comment by tidyui** [comment]
Did you solve this issue?
