### ISSUE TITLE
Routing for 2+ segments in url

### ISSUE THREAD

**Issue by gyfke** [PiranhaCMS/piranha.core#865]
Is it possible to handle urls like site.com/blog/subblog/blogpost?
I use MvcWeb example, created subblog under exising Blog archive and created a blog post in subblog. And when try to open blog post I've got 404 error

![routing](https://user-images.githubusercontent.com/15141774/67133821-4b1ef380-f217-11e9-8778-b4ba3f4f43e6.png)

**Comment by tidyui** [comment]
Hi this only affects archive pages as child pages! See issue #699.
