### ISSUE TITLE
Localization not work in Manager when use nuget package

### ISSUE THREAD

**Issue by martinhla** [PiranhaCMS/piranha.core#866]
Hi! I create new project with command: `dotnet new piranha.web` when i changed culture in Startup.cs with this code: 
`var cultureInfo = new System.Globalization.CultureInfo("de");
 System.Globalization.CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
 System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;`
but texts in piranha manager is still in english. 

Then i tried download full Piranha solution and changed culture in example project MvcWeb and now texts is in german language. Why localization not work when Piranha is install via nuget? Am i missing something? Thank you for help.

Martin

**Comment by tidyui** [comment]
For the German localizations to kick in you have to use `de-DE` as culture info.

Best regards

**Comment by martinhla** [comment]
I already tried and localizations is still in English.
There is my test project: [TestPiranha.zip](https://github.com/PiranhaCMS/piranha.core/files/3748165/TestPiranha.zip)
Can you look in to it please?

Martin

**Comment by tidyui** [comment]
I have confirmed the issue, there's something wrong with how the package is built and distributed, we're looking into it.

**Comment by tidyui** [comment]
This has been resolved and deployed in `Piranha.Manager.Localization 7.0.5`

Best regards
