### ISSUE TITLE
Login fails on MS Edge browser

### ISSUE THREAD

**Issue by timheuer** [PiranhaCMS/piranha.core#868]
Logins are failing on the Microsoft Edge (the chrome-based one) browser experience.  Login just keeps re-routing to login page.

**Comment by tidyui** [comment]
Btw, did you try the old "turning it on and off again" test? Since Piranha just uses basic `ASP.NET Core Identity` we've had issues in the past where stray cookies from previous logins have caused the manager login to fail.

**Comment by timheuer** [comment]
just cleared some cache and now it works 🤷‍♂

**Comment by i-love-code** [comment]
I've definitely experienced this before when I run multiple versions of the template on the same port/etc.

I believe it keeps cookies/etc from sessions on previous template tries and as @tidyui mentioned they often just make it refresh the login page because it failed.
