### ISSUE TITLE
Saving with Summernote when still in code view fails

### ISSUE THREAD

**Issue by timheuer** [PiranhaCMS/piranha.core#869]
When saving HTML content in code view in Summernote, if you stay in code view it does not save the contents...you must switch to non-code mode and it will save:

1) Create post
2) switch to code view
3) paste a bunch of HTML
4) save post
EXPECT: It saves and renders
ACTUAL: It tells you it saves but really only saves the ```<p><br/></p>``` default text
If you toggle code view again (to get the preview) then it will save

**Comment by tidyui** [comment]
Seems to be a general Summernote issue that has been closed but not fixed (https://github.com/summernote/summernote/issues/94). We'll see if we can provide a workaround.
