### ISSUE TITLE
Does not work on Azure App Service Linux

### ISSUE THREAD

**Issue by timheuer** [PiranhaCMS/piranha.core#870]
Piranha does not work when deployed to Azure App Service Linux.  Read operations are fine, but write operations fail with the logs showing SQLIte database is locked.

**Comment by tidyui** [comment]
We usually do not recommend SQLite for production environments, but it’s still weird as we have over 600 integration test on SQLite which are being executed on Linux & Mac OS X with Travis for every commit. It would be very interesting to know what’s the difference between the scenarios.

Did you push the local database up to Azure or did it create the database in Azure? Could it be as simple as access rights on the db file it it was pushed to production?

**Comment by tidyui** [comment]
I get the same result when I try to deploy without an existing database. The database-file is created but stays at `0 bytes` and the data seed fails with `Database locked`. I have tried setting the different `cache` settings through the connection string without any effect. Not really sure what's going on. File mode seems to be ok on the created file as well.

**Comment by timheuer** [comment]
@tidyui I *think* this might be an issue with how App Service Linux is mounted for files.  We are looking at this with the App Service team.  I think having a warning on docs for where you deploy might be a good temporary 'resolution' here for this project.

See:

- https://stackoverflow.com/questions/42722855/sqlite-3-on-windows-share-cifs-access-from-ubuntu-nobrl-risk
- http://sqlite.1065341.n5.nabble.com/How-to-make-SQLite-run-safely-on-CIFS-mounted-file-system-td37415.html
- https://sqlite.org/faq.html#q5

**Comment by tidyui** [comment]
Hi again @timheuer Did you find out if the issue here was related to file system mounting in Azure?

**Comment by timheuer** [comment]
Yes we think that’s the cause here. Not totally confirmed but likely. 

-th

**Comment by timheuer** [comment]
Closing this.  SQLite + App Service Linux in current form is not compatible.  Recommend that putting a remark for this config so users know in advance this is not a recommended config.

**Comment by tidyui** [comment]
Ok, thanks for the info! We’re currently reworking the docs and we’re adding a section about hosting!
