### ISSUE TITLE
Add client side validation for manager forms

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#872]

**Comment by yiqi0110-glitch** [comment]
Hey all, I was wondering if there is any documentation on how to implement this into code. Thanks!

**Comment by tidyui** [comment]
@filipjansson Could give some details on how this is implemented in the manager and when there's time write something about it in the docs!

**Comment by tidyui** [comment]
@yiqi0110-glitch As this is a closed old issue, could you please open a documentation issue for it at this repository https://github.com/PiranhaCMS/piranha.core.docs. @filipjansson when the issue has been opened, let's comment there instead
