### ISSUE TITLE
Can we make piranha play nice with swashbuckle?

### ISSUE THREAD

**Issue by Bored0ne** [PiranhaCMS/piranha.core#876]
This basically means that all controller methods must have a [httpPost] or put or get or delete attribute on them.

Ambiguous HTTP method for action - Piranha.Manager.Controllers.MediaApiController.DeleteFolder (Piranha.Manager). Actions require an explicit HttpMethod binding for Swagger 2.0

**Comment by tidyui** [comment]
Absolutely! We can probably make this happen for the `7.1` release.
