### ISSUE TITLE
DateField saves time of day (sort of) when using Datepicker

### ISSUE THREAD

**Issue by nahojd** [PiranhaCMS/piranha.core#877]
When I use a DateField on a Page, I would expect it to only save the selected Date, and leave the time empty, or rather as 00:00:00. This does indeed seem to be the case when I type in the date manually, but when I select the date with a date picker a time of day gets saved.

The time saved is somewhat correlated to the current time of day, but not quite, at least not when there are multiple DateFields on one page. Consider the following Page type:

```csharp
[PageType(Title = "TagePage for dates")]
public class TestPage : Page<TestPage>
{
	[Region]
	public TestDates DateRegion { get; set; }

	public class TestDates {
		[Field]
		public DateField TestDate { get; set; }

		[Field]
		public DateField AnotherTestDate { get; set; }

		[Field]
		public DateField ThirdTestDate { get; set; }
	}
}
```

When I created a new page of this type, and selected the date 2019-10-01 with the datepicker, and saved the page (at 15:04 CEST), the following dates were saved:

<table>
<tr><td>TestDate</td><td>2019-10-01 13:04:00</td></tr>
<tr><td>AnotherTestDate</td><td>2019-10-01 13:04:00</td></tr>
<tr><td>ThirdTestDate</td><td>2019-10-01 13:04:00</td></tr>
</table>

So, the current time of day was save (but in UTC instead).

I then edited the page, and selected 2019-10-02 for all of the dates instead. After a save the page contained the following dates:

<table>
<tr><td>TestDate</td><td>2019-10-02 13:04:00</td></tr>
<tr><td>AnotherTestDate</td><td>2019-10-02 13:04:00</td></tr>
<tr><td>ThirdTestDate</td><td>2019-10-02 00:00:00</td></tr>
</table>

So, the previous times were kept, except for the last one, where the time was set to 00:00:00.

A third attempt, with the dates 2019-10-01, 2019-10-02 and 2019-10-03 resulted in the following values being saved:

<table>
<tr><td>TestDate</td><td>2019-10-01 14:04:00</td></tr>
<tr><td>AnotherTestDate</td><td>2019-10-02 14:04:00</td></tr>
<tr><td>ThirdTestDate</td><td>2019-10-03 01:00:00</td></tr>
</table>

And now all times were incremented by one hour...

I can't for the life of me figure out the logic in these seemingly random changes to the time, but I have confirmed that these values are indeed being sent to the backend in the call to `/manager/api/page/save`, so the error is not on the server side, but rather in the Datepicker.

At first I thought that this could be fixed by just axing the time part of the DateTime on the server side when the date is saved, but there seems to be an additional problem around midnight.

For my fourth and last attempt, I changed the system clock to 00:30, and proceeded to set all the dates to 2019-10-01 (again using the datepicker). This resulted in the following values:

<table>
<tr><td>TestDate</td><td>2019-10-01 12:04:00</td></tr>
<tr><td>AnotherTestDate</td><td>2019-10-01 12:04:00</td></tr>
<tr><td>ThirdTestDate</td><td>2019-09-30 23:00:00</td></tr>
</table>

Well, the time of day for the first two dates decreased by an hour, but for the last one we even got the wrong date!

I think something is seriously wrong with the date picker, and that it would be better to just use `<input type="date">`.

**Comment by tidyui** [comment]
I can’t tell you the logic behind it either, as the bottom line is that the time shouldn’t be saved at all 😁 As for your last test when the date was wrong my guess is that the js-component maybe formats time zone into the date and on conversion to server time an hour was subtracted and made the date jump back to the previous date. Again just guessing as I’ve never ran into the issue!

**Comment by nahojd** [comment]
Obviously you don't edit dates during the småtimmar enough. :-)
But as I said, the times are posted to the save method just as they are saved, so even if the time component was ignored, the date would still be wrong for the last one. Unless maybe if it was converted back to local time, but that's always tricky.
