### ISSUE TITLE
Support for SVG images

### ISSUE THREAD

**Issue by CrossBound** [PiranhaCMS/piranha.core#879]
I've added SVG as an image type but the manager will not let me upload it. Is there a way around this?
``` csharp
            // add supported image type
            Piranha.App.MediaTypes.Images.Add(".svg", "image/svg+xml");
```

![image](https://user-images.githubusercontent.com/11417093/67626180-67212700-f80d-11e9-95b2-5e5d19cfb14b.png)

**Comment by tidyui** [comment]
I haven’t tried it myself but it looks like the external imagesharp component can’t handle svg images. I’ll take a look at if there’s any updates on their library or if maybe skiasharp handles svg.

**Comment by mikaellindemann** [comment]
I don't see why SVGs should be handled by the image cropper - most browsers are able to render them just fine in any resolution.

**Comment by tidyui** [comment]
I’ll have check the code why it’s failing. My guess is that the content is added as an image so it uses the current image component to verify that it is an image which fails. We would probably need to extend the registration of image types so you can specify if it should be cropped or not.

**Comment by tidyui** [comment]
So the problem is the following line in the code. When an image is uploaded it tries to create an Image object from it to get the dimensions of it:

    _processor.GetSize(bytes, out width, out height);

As `ImageSharp` doesn't support opening `svg` files it throws an exception. So in order to support it we need to be able to bypass image processing for certain added image types.

**Comment by tidyui** [comment]
This will be release in `7.1` you can now add a media type that doesn't support processing with:

~~~ csharp
Piranha.App.MediaTypes.Images.Add(".svg", "image/svg+xml", false);
~~~

All calls for getting a resized version of the image will return the original URL.

**Comment by kttary** [comment]
> ```cs
> svg
> ```

where do you put this line of code?

**Comment by tidyui** [comment]
In the `Configure` method in `Startup.cs` after `App.Init()` has been called. https://piranhacms.org/docs/master/content/media

Regards

**Comment by kttary** [comment]
it keep saying

Failed to upload media. Image cannot be loaded. Available decoders:
- JPEG : JpegDecoder
- BMP : BmpDecoder
- PNG : PngDecoder
- GIF : GifDecoder
- TGA : TgaDecoder

**Comment by tidyui** [comment]
Which version are you using of Piranha? I haven't tested this for a while, I'll have to double-check so that our external dependency `ImageSharp` hasn't removed support for `.svg` in some upgrade.

**Comment by kttary** [comment]
Piranha 8.4.1

**Comment by tidyui** [comment]
@kttary Can you verify that you have set the **third** optional parameter to `false` when adding `svg` images, like so:

~~~ csharp
Piranha.App.MediaTypes.Images.Add(".svg", "image/svg+xml", false);
~~~

If not the file will be opened with `ImageSharp` to determine width & height, and `.svg` images is not supported by `ImageSharp`.

**Comment by kttary** [comment]
Yes i follow your comment on oct 28 2019.

**Comment by tidyui** [comment]
I **can't** reproduce your issue. I have done the following.

1. Create a new web project with `dotnet new piranha.razor`
2. Add the line above directly below `App.Init(api);` in `Configure()` in `Startup.cs`
3. Restore, build and run the application
4. Seed some test data for the template
5. Login to the manager and navigate to the media library
6. Drop a test `.svg` image in the upload panel

The file uploads correctly and I can open it and look at the details and preview (see screenshot).

<img width="1481" alt="Skärmavbild 2021-01-28 kl  15 33 24" src="https://user-images.githubusercontent.com/781266/106153199-9516b900-617e-11eb-86ad-3ee96333fb09.png">

**Comment by kttary** [comment]
Got it work now. Problem with my browser i think
