### ISSUE TITLE
Creating new Page Types

### ISSUE THREAD

**Issue by ecnerwal1234** [PiranhaCMS/piranha.core#884]
Not sure if this is the best place to add this. I'm trying to follow the documentation on creating new page types. I Tried the markdown page in the docs but get a viewbag.title error.  

I have also tried to create a news archive following the archive page type docs and get model.archive error 

I'm very new to dotnet core and am sure it's just my lack of experience, but I feel like i need to add stuff to the cmscontroller but not really sure what and where.

Thanks!

**Comment by tidyui** [comment]
Hi there! The approaches are **slightly** different depending whether you're using `MVC` or `Razor Pages`. The `.cshtml` examples in the docs are written for MVC where the **model** is the PageModel, but in Razor Pages the **model** is actually the RazorPage class which **contains** a model object.

How did you create your project, are you using MVC or Razor Pages?

Regards

**Comment by tidyui** [comment]
Hi again! Take a look at this article in the documentation in the section "A Real World Example"

http://piranhacms.org/docs/basics/how-to-setup-content/page-types

This has an example of adding a new page type with routing, adding a controller handling the request and an example view for rendering it.

If anything is unclear in the documentation please let us know!

Regards

**Comment by tidyui** [comment]
Hi again! Did you find the information you were looking for?

**Comment by dinukasal** [comment]
I think the new documentation about page types should be in this https://piranhacms.org/docs/content/pages

**Comment by tidyui** [comment]
Hi there @dinukasal This issue is really old and has nothing to do with the current documentation. If you feel anything is missing in the docs for Pages, please open a new issue for this.

**Comment by tidyui** [comment]
@dinukasal And remember that issues regarding the documentation should be created in the repository https://github.com/PiranhaCMS/piranha.core.docs

Best regards

**Comment by dinukasal** [comment]
Hello @tidyui 
Thanks, will follow that.
