### ISSUE TITLE
Field title not showing

### ISSUE THREAD

**Issue by ecnerwal1234** [PiranhaCMS/piranha.core#887]
I have a field in a region and the title does not show when there is only one field in the region, when I added a second field both titles started showing.

**Comment by tidyui** [comment]
Hi there! Just to clarify, are you talking about showing `ListTitle` for a collection region?

Best regards

**Comment by ecnerwal1234** [comment]
Here is the region i have set up.
```
public class ComplexRegion
        {
            [Field(Title = "News Release Date", Placeholder = "Give me a date!")]
            public DateField ReleaseDate { get; set; }

            //[Field(Title = "Just a Test", Placeholder = "Check me out!")]
            //public CheckBoxField  CheckboxTest { get; set; }

        }
```
![1field](https://user-images.githubusercontent.com/6483075/68023879-ee8fef80-fc7e-11e9-9084-56d8b8b2d111.PNG)

when i uncomment the second field the titles show.
![2fields](https://user-images.githubusercontent.com/6483075/68023886-f0f24980-fc7e-11e9-90cb-fe4cf4f468cb.PNG)

**Comment by tidyui** [comment]
Hi! The problem is that complex regions with a single field is not allowed. You can read more about this here in “Single field regions”.

http://piranhacms.org/docs/basics/how-to-setup-content

As these regions doesn’t have field attributes they are not shown.
