### ISSUE TITLE
paging and sorting in media

### ISSUE THREAD

**Issue by ulfetalhussaini** [PiranhaCMS/piranha.core#890]
In media if we have large sets of images (more than 1000 image) it load all images without paging and there is no sorting (to get the last image) so it is difficult to find and choose the last image we added..

**Comment by tidyui** [comment]
There will be an update in 7.1 for increasing performance for large sets of files. In regards to paging and sorting, the media view supports hierarchical folder structures to avoid having thousands of files in the same folder. Isn’t this a better solution than just adding paging to a folder? Also, if the view is fast enough, maybe good search functionality is better that sorting and paging ad you want minimal amount of clicks for finding the asset you’re looking for.

**Comment by haidersafaa** [comment]
we used the WordPress  and i see it good to take from their interface for this usage ,they show last images (filtered by limit let say 10), if there folders they show it also there is filter and by months and by file type in top of view media  
you can see it here
https://easywpguide.com/wordpress-manual/media-library/
https://easywpguide.com/wordpress-manual/media-library/viewing-a-file-in-the-media-library/

**Comment by tidyui** [comment]
Closing this as we're releasing an updated version of the media library in `8.1`, see #1024 for more details.
