### ISSUE TITLE
Oauth2 and inline editor

### ISSUE THREAD

**Issue by AdamJacks** [PiranhaCMS/piranha.core#894]
Is Piranha Core capable of using Oauth2?

I haven't been able to find anything related to inline editing of HTML content in Piranha Core, is this possible?

**Comment by tidyui** [comment]
Hi there! Authentication is completely pluggable by implementing a custom service implementing the `ISecurity` interface (http://piranhacms.org/docs/extensions/authentication). We provide a package for `ASP.NET Identity` which can most certainly be configured for OAuth (http://piranhacms.org/docs/components/authentication/identity-security).

In regards to inline editing, are you referring to in-front editing of the content?

**Comment by AdamJacks** [comment]
@tidyui Yes, I am referring to in-front editing of content.

Thank you for the speedy reply!

**Comment by tidyui** [comment]
We currently don't have any components for this, but if you're using `Vue.js` you could reuse the components included in the manager although this is undocumented at the moment.

**Comment by AdamJacks** [comment]
I'm afraid I wont be using Vue.js, thank you anyway!
