### ISSUE TITLE
Blazor / WASM options?

### ISSUE THREAD

**Issue by AlexJPawlak** [PiranhaCMS/piranha.core#897]
Hello!

Do you think it would be possible to run a contained hosting with .NET Core Blazor app? Or is not a suitable technology choice for this? Ideally I'd love to host Piranha off Azure Storage account as static website with web assembly, so I don't have to maintain webapp/SQL in the backend of it? Looks like a big task in terms of architecture, but I'm not sure whether this would fit or is technically rational. Thanks for great product otherwise!

**Comment by tidyui** [comment]
I haven’t looked into it, but rebuilding the manager as Blazor would be a big task, and even if done the content data has to be persisted somewhere and not in client memory, so some form of api backend with some form of storage would be needed anyway.

We are actually looking into setting up a hosted Piranha-as-a-service that would provide manager and api access for the data. Then you would only have to worry about the client application which could pretty much be built in any technology and be hosted anywhere.

If you have some other thoughts please comment as we love to hear all possible use cases!
