### ISSUE TITLE
Preview does not work

### ISSUE THREAD

**Issue by CrossBound** [PiranhaCMS/piranha.core#898]
I'm not sure what I'm missing but there is no documentation on Preview pages and I can't figure out how to make it work. I have the route working for pages and the preview comes up... but it doesn't respect changes that have been saved. The changes have to actually get "published" before the preview will show them. I assume the point of "preview" is to be able to see the changes you have made before actually publishing... I'm not sure what I'm missing. Can you point me in the right direction?

**Comment by CrossBound** [comment]
P.S. No errors are being thrown that I know of... the data just won't change after hitting "Save" unless I published it.

**Comment by tidyui** [comment]
Hmmm. Just to clarify:

If you save a draft for a page and then open preview, do you see the changes? Is it the preview that doesn’t work at all or is it the auto update function when you have preview open and **then** save the draft.

Regards

**Comment by tidyui** [comment]
I have an idea here! Have upgraded your project from an older version of Piranha that didn’t support preview of drafts? Then it might just be the case that you don’t have any code that handles this case in your application.

As the preview will call your front-end application for rendering the preview you are actually responsible for doing it. All of this is of course included in the templates when you create a new application, but if you’ve upgraded an older version it might be missing. Take a look at the controllers for the template project for reference.

https://github.com/PiranhaCMS/piranha.core.templates/blob/master/web/mvc/Controllers/CmsController.cs#L53

Best regards

**Comment by CrossBound** [comment]
I did not build this from a template but instead built it from scratch. 

I must say, this is very confusing because there is no documentation anywhere about this other than simply following along from the template. For anyone like me that is not using the template it would be helpful if there was a guide somewhere.

I was able to fix the problem by adding the `bool draft = false` parameter to my action method, as is shown in your template that you linked to.

**Comment by tidyui** [comment]
Yes, good point! We’ll add this to the new documentation!

**Comment by tidyui** [comment]
Content will be added to these pages:

https://github.com/PiranhaCMS/piranha.core.docs/blob/master/src/03.%20Application/01.%20Services/02.%20ModelLoader.md

https://github.com/PiranhaCMS/piranha.core.docs/blob/master/src/03.%20Application/03.%20Previewing.md
