### ISSUE TITLE
Database access from custom module

### ISSUE THREAD

**Issue by chybyk** [PiranhaCMS/piranha.core#900]
Hello,
At First i am not very experienced in Entity Framework.
I'm trying to create my own table in a database for my custom module and I get an exception saying that I don't have such a table. Should I create it manually or create a separate database for my DBContext?

As an example, I used _data/Piranha.Data.EF_ & _Piranha.AspNetCore.Identity_.

Thanks.

**Comment by tidyui** [comment]
Hi there! Our recommendation is always that you create your own `DbContext` for your custom tables, and never extend the one provided by Piranha. This will keep the code separated and will ensure smooth upgrades in the future.

As for exactly how you should design your `DbContext` with your tables in the best way for your application the best resource for this is to check out the docs for EF Core:

https://docs.microsoft.com/en-us/ef/core/

Best regards

**Comment by chybyk** [comment]
Thanks for the answer.
It turns out that the best practice is to create a separate database for your modules. And never try to change _core_ database?

**Comment by tidyui** [comment]
You can have your custom tables in the same database, but preferably in its own DbContext. The problem with modifying the core context is when updating piranha and merging your custom migrations with possible new migrations on the core context.

Note that this hasn’t anything to do with piranha, but is rather general Entity Framework functionality.

Best regards

**Comment by chybyk** [comment]
Thank you for the detailed explanation :)

By the way, I ran into the issue of creating my own migrations for my custom DBContext(i have the same _'missing table'_ exception), if you already have one. Do you have an example of working with multiple DBContexts?

Best regards.

**Comment by chybyk** [comment]
Iresolve my issue with migrations - **_Database.EnsureCreated_** for my custom DBContext did his job and it worked!

Best regards, thanks for the help and guidance :)
