### ISSUE TITLE
Error changing user password when password does not meet Identity requirements

### ISSUE THREAD

**Issue by Forester-** [PiranhaCMS/piranha.core#907]
Reproducing steps:
1. Create new project from templates
    > dotnet new piranha.web
2. Build and run project
3. In browser navigate to /manager, have got login page
4. Use admin/password, enter to Manager
5. Navigate to Users in Manager, click on admin
6. Enter new password "qqq" (without quotes), confirm it, click Save
7. Got notification **Success: The user has been saved**
8. Click Logout, got login page
9. **Can't enter to /manager, nether "password", nor "qqq", nor empty password is accepted**

As I see the cause is new password does not meet Identity requirements (IdentityModuleExtensions.SetDefaultOptions, options.Password.RequiredLength = 6). After user saving PasswordHash column in Piranha_Users table is empty.

For reset admin/password account it needs to delete all records from Piranha_Users table and re-run project. Admin account will be re-created on project start.

**Comment by tidyui** [comment]
Thanks for your input! This has been fixed and will soon be released in 7.1, see #883.

Regards
