### ISSUE TITLE
In the new template 7.1.0 have some problem using SQLServer

### ISSUE THREAD

**Issue by AllPIM** [PiranhaCMS/piranha.core#918]
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.2.7/System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll

Application startup exception: System.InvalidOperationException: The AuthorizationPolicy named: 'PiranhaApiMedia' was not found.

   at 
Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)

**Comment by tidyui** [comment]
Hi there! The logical reason for getting this error message would be that you have installed the package `Piranha.WebApi` without adding the following line to `ConfigureServices`.

~~~ sharp
services.AddPiranhaApi(); 
~~~

Best regards

Håkan

**Comment by AllPIM** [comment]
Thanks ! It's OK !
