### ISSUE TITLE
Error creating from template (cycle detected)

### ISSUE THREAD

**Issue by OrlandoF** [PiranhaCMS/piranha.core#921]
Hi,

Here the issue found trying to setup the project for the first time.

dotnet restore
C:\Users\...\piranha\piranha.csproj : error NU1108: Cycle detected.
C:\Users\...\piranha\piranha.csproj : error NU1108:   piranha -> Piranha (>= 7.1.0).

How to reproduce:
- Follow steps from http://piranhacms.org/docs/introduction/getting-started/project-templates
1- dotnet new -i Piranha.Templates
2- dotnet new piranha.web
3- dotnet restore => error above
Environment:
 dotnet --version
3.0.100

Expected:
download all packages.

**Comment by tidyui** [comment]
Hi there! Your project can't be named `Piranha` when restoring a package with that name. This is a built in limitation in `.NET`.

Best regards!

**Comment by OrlandoF** [comment]
Hi.

Thanks for the quick response.
