### ISSUE TITLE
Editing complex block

### ISSUE THREAD

**Issue by psandgren** [PiranhaCMS/piranha.core#929]
Would be nice to have a way to edit complex blocks in an old fashion way, like block group properties. Writing components for every block is somewhat difficult.
For example:
![image](https://user-images.githubusercontent.com/1876684/69735929-d0a89400-1131-11ea-854b-a8865bb8658d.png)

**Comment by tidyui** [comment]
Yes, we have issue for it here #820 which is planned for 8.1, i.e after the version for .net core 3.1 has been released!

**Comment by tidyui** [comment]
We initially planned it for 7.1 but ran out of time!
