### ISSUE TITLE
Manager resources doesn't work behind a reverse proxy

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#934]
If the manager is run behind a reverse proxy and the proxy isn't forwarding scheme to the application resources links are rendered incorrectly. This is due to the following line in the `_Layout.cshtml` of the manager.

<base href="@(new Uri(new Uri(Url.ActionContext.HttpContext.Request.Scheme + "://" + Url.ActionContext.HttpContext.Request.Host.Value), Url.Content("~")).ToString())" />

**Comment by gyfke** [comment]
Hello
Thanks for great major update
But I'm still having this issue with nginx+https. It seems that it was fixed 1.5 hours after Piranha.Manager 8.0.0 was released :-)
When this fix expect to be released?

**Comment by tidyui** [comment]
Thanks for noticing. This was actually committed **before** `8.0` was released so it was supposed to be released in that version. However it seems we must have made en error in packaging the NuGet-packages because the released version doesn't seem to contain the fix! We'll get back with when we can get this released.

However there are several issues with solutions on how to fix this for nginx by forwarding scheme to the web-server, I'll see if I can locate them.

Regards

**Comment by tidyui** [comment]
There are some solutions in our Gitter channel.. Here's a suggestion:

That's what I was thinking and that's why I am curious about version. I assume it is pre 8 we're talking about - I cannot tell by the screens.

~~~ csharp
app.UseForwardedHeaders(new ForwardedHeadersOptions { 
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto });
~~~

Is the code to add in startup.cs to fix it. Additional settings might be required in reverse proxy to forward it too.

There's more info in the Gitter history about this!
