### ISSUE TITLE
Update uploaded media assets

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#94]
There needs to be an option to update the uploaded file for a media asset in the manager.

**Comment by CrossBound** [comment]
I would have to agree with this... at the very least it would be nice to be able to rename/move it between folders

**Comment by tidyui** [comment]
Hi! This is old functionality. 

To update the file, simply click the name of the file to open the preview modal and from there click "Update file".

To move the file, simply drag it to the folder your want to move it to.

Regards
