### ISSUE TITLE
page parameter in ArchiveModel.OnGet is always null

### ISSUE THREAD

**Issue by vjacquet** [PiranhaCMS/piranha.core#942]
The pagination does not work in a blog generated with Piranha.blog.razor because the page parameter is always null.
With razor page, "page" is a route value set with the path to the page therefore the binding tries to bind the string "/Archive" instead of the query string parameter "3".

There is at least 2 possible way to fix this
1. add the attribute "[FromQuery]" before the page parameter: `public async Task OnGet(Guid id, int? year = null, int? month = null, [FromQuery] int? page = null, Guid? category = null, Guid? tag = null)`
2. rename the parameter to something else (pagenum ?) in the signature of the method and in the `IntegratedMiddleware`. 

I notice that `ArchiveRouter` set to the querystring both page and pagenum.

**Comment by tidyui** [comment]
Yes I think you’re right, somewhere along the line we ran into the naming issue and added the pagenum param. However we seem to have forgot it in the upgrade process to 8.0. We’ll try to fix it for the next release!

**Comment by ikhwanhayat** [comment]
Hi.. Is this issue fixed? I am still experiencing this problem. I see that `pagenum` is added in the middleware but seems not being used in `ArchiveModel.OnGet`?

**Comment by tidyui** [comment]
The bug was fixed long, but if you’re referring to the new templates the example code is missing, see https://github.com/PiranhaCMS/piranha.core.templates/issues/29

**Comment by ikhwanhayat** [comment]
I'm new to Piranha and still getting the hang of things. Should I override the ArchivePage in my own project? I am referring to this file https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore/Models/ArchivePage.cs

Seems that things work if I replace the parameter "page" with "pagenum" instead.

**Comment by j-bbr** [comment]
I ran into this problem recently with the last stable Nuget Package of piranha (8.42 I think). I also noticed that the problem is fixed on the Roadmap but while that's not released or for people who can't upgrade right away I just wanted to leave the temporary fix suggested by @ikhwanhayat here:

```
public class ArchivePageWithFixedPagination : ArchivePage<StandardArchive, Piranha.Models.PostInfo>
    {
        public ArchivePageWithFixedPagination(IApi api, IModelLoader loader) : base(api, loader) { }

        public override Task<IActionResult> OnGet(Guid id, int? year = null, int? month = null, int? pageNum = null, Guid? category = null, Guid? tag = null,
            bool draft = false) =>
            base.OnGet(id, year, month, pageNum, category, tag, draft);
    }
```
The model on the page template must be replaced with that as well of course, and the whole thing can be removed once version 9 is released
