### ISSUE TITLE
Blog Template Setup Page Assets

### ISSUE THREAD

**Issue by i-love-code** [PiranhaCMS/piranha.core#945]
Assets in the updated .NET Core 3.1 template appear to be referencing asset links on the new website that no longer exist.

![image](https://user-images.githubusercontent.com/1737733/70632286-254d1400-1bf4-11ea-834c-75ea9da45d6e.png)

Missing assets:
![image](https://user-images.githubusercontent.com/1737733/70632301-2aaa5e80-1bf4-11ea-8998-92f7c9f10393.png)

I assume it's just related to the new website being launched today.

**Comment by tidyui** [comment]
Thanks for noticing so fast. I totally forgot about those files and just deleted them 😫 I have to come up with an alternate design faster than lighting 😂

**Comment by tidyui** [comment]
Ok, so the blog setup page is probably "kind of" like it was before. I'm going to keep the issue open until I've fixed the web template as well.

**Comment by tidyui** [comment]
Resolved.. Again, thanks for noticing!
