### ISSUE TITLE
No button to add new blog post

### ISSUE THREAD

**Issue by RishkoPavel** [PiranhaCMS/piranha.core#948]
Hello, when I try to add a new post to a page like a blog. Then I just don’t have a button to do this. (But there is a button if this blog was created using your seeds)
![image](https://user-images.githubusercontent.com/47470737/70786645-d17a3080-1d95-11ea-8192-f53184f53810.png)

**Comment by tidyui** [comment]
Hi there! Can you share your `Startup` / `PageType` for the Blog. Have you imported your post types during application startup?

**Comment by filipjansson** [comment]
I believe I happen to stumble upon the same issue yesterday.
If you create a new archive page and save/publish it, you need to reload the page for the Add button to be visible.

**Comment by tidyui** [comment]
Ok, please verify if this was your issue @RishkoPavel in which case we'll file this as an issue.

**Comment by tidyui** [comment]
I have verified @filipjansson bug and we will try to fix this for `8.1`. Until then, reload page after it's been created
