### ISSUE TITLE
AccountController appears to be missing

### ISSUE THREAD

**Issue by gizmohd** [PiranhaCMS/piranha.core#95]
Was trying to figure out the user management... and there doesnt seem to be any?  no way to log in/out of the site?

**Comment by gizmohd** [comment]
i would be happy to help integrating the Basic Authentication into the site.

**Comment by tidyui** [comment]
Another good idea would be to actually include the `SignIn` and `SignOut` methods in the `ISecurity` api and the let the SimpleSecurity be created with the HttpContext as an argument. This way it could be configured as a **scoped** service and be injected into the account controller for the manager.

**Comment by tidyui** [comment]
The current source code now have updated `ISecurity` interface, claims based security for the manager and a `SimpleSecurity` module included which can be used for development scenarios.
