### ISSUE TITLE
Postgresql integration

### ISSUE THREAD

**Issue by erdemkara** [PiranhaCMS/piranha.core#951]
I appreciate your efforts, it's a very clean job. Will the project have a postgresql integration?
Greetings from Istanbul.

**Comment by filipjansson** [comment]
Hi @erdemkara!
We do have a repository for a [PostgreSQL provider for Piranha](https://github.com/PiranhaCMS/piranha.core.postgresql).
This repository is mostly maintained by the community.

BR
Filip

**Comment by erdemkara** [comment]
Thanks @filipjansson , I saw this yesterday. I think this package is compatible with version 7.0. I'il try it soon. 
I'll also try with the original nuget postgresql package.
Thank you.

**Comment by tidyui** [comment]
Hi! The repo has been upgraded to .netcore 3.1 and piranha 8, but we don’t have access to publishing the package

**Comment by tidyui** [comment]
I'm closing this issue as there is an open issue in the PostgreSQL repo!
