### ISSUE TITLE
Use ImageGallery in custom page?

### ISSUE THREAD

**Issue by firedog** [PiranhaCMS/piranha.core#952]
I am new to Piranha and in the process of trying it out and have implemented a custom page (inheriting from Page\<T\>). In my custom page I have created an inner class holding a few properties (StringFields and CheckBoxFields) and then exposed this as a Region and it all shows up in the manager and works as expected.

I have also tried to include an image gallery by adding a property holding an ImageGalleryBlock. But this never shows up! I have tried using both UseBlocks = true and UseBlocks = false in the PageTypeAttribute (but I really wouldn't like the content creators to be able to use arbitrary blocks for this page as it is a strictly formatted details page that will have a fixed structure).

Are you supposed to be able to use blocks this way (i.e. reuse a specific block in your custom pages)?

If so, how do you do it?

I'm using Piranha 8.0.0 on .NET Core 3.1

**Comment by tidyui** [comment]
Hi there! Blocks can't be used as regions, they are accessible from the manager when adding new blocks to the main content area (if `UseBlocks` is true).

Regards

**Comment by firedog** [comment]
Hi and thanks for the quick reply!

So if I understand you correctly I can not reuse the image gallery block in my custom page unless I have UseBlocks = true and then I can't control which blocks or how many of them a content creator is using. Right?

**Comment by tidyui** [comment]
That is correct. But in essence you could achieve the same functionality with the following region:

~~~ csharp
[PageType(Title = "My Page", UseBlocks = false)]
public class MyPage : Page<MyPage>
{
    [Region]
    public IList<ImageField> Gallery { get; set; }
}
~~~

**Comment by firedog** [comment]
I have implemented your suggestion and it works well. I took the view code from the image gallery block and made some minor changes and incorporated that into my custom page view. From a site visitor viewpoint it is perfect!

The only problem I see is that the interaction in the manager when creating the page is somewhat clunkier than what the image gallery block offers. The image gallery block is a very intuitive and slick component for the content creator so that is why I would like to use it in my "fixed-structure" page.

Are there any technical reasons as to why you can't reuse a block in this way or is it simply that no one has thought of it or has had the need to do it?

Anyway, for me I consider the problem solved and I'm closing the issue. 

Thank you very much for your assistance and a great product!

**Comment by tidyui** [comment]
Hi! There's a technical difference in the sense that regions can't have custom view components in the way blocks can, they are only treated as a "group of fields" where the fields have view components. 

This said, it would still be fully possible to allow for different rendering scenarios of **List Regions** in the future, so you could use the "Master/Detail" list view of the gallery block group. If you want you could create an issue for this feature! Also, it would be possible to add a custom `ImageField` which displays the image in the same way the `ImageBlock` does. The current fields for media are much less visual as regions are more often composed of many different regions and your want to get an overview over all of the data.

Regards
