### ISSUE TITLE
WebApi login problem

### ISSUE THREAD

**Issue by erdemkara** [PiranhaCMS/piranha.core#957]
Hello,
When I make the following call with Postman, I am directed to the login page. I don't understand Auth logic. I think we need a token, but where?

/api/sitemap

**Comment by tidyui** [comment]
The WebApi just uses the same authentication mechanism as the manager, I.e that the user has certain claims. How you choose to handle security is up to you as it differs very much from application to application. One example could like you say be to send a token and the handle it in a middleware component before the request reaches the controller.

**Comment by tidyui** [comment]
Also, if you take a look at the source code for the WebApi you’ll see that the complexity is very low as all logic is encapsulated in services. This way you can easily expose the functionality you want through your own custom api.

**Comment by erdemkara** [comment]
Thanks Hakan,
I got what I wanted using a JWTToken.
Startup.cs example

`            services.AddAuthentication().AddCookie(options =>
            {
                options.AccessDeniedPath = new PathString("/manager/login/");
                options.LoginPath = new PathString("/manager/Login/");
                options.SlidingExpiration = true;
            }).AddJwtBearer(options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateAudience = true,
                    ValidAudience = "app.erdem",
                    ValidateIssuer = true,
                    ValidIssuer = "app.erdem",
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(
                        Encoding.UTF8.GetBytes("xxx"))
                };

                options.Events = new JwtBearerEvents
                {
                    OnTokenValidated = ctx =>
                    {
                        //Gerekirse burada gelen token içerisindeki çeşitli bilgilere göre doğrulam yapılabilir.
                        return Task.CompletedTask;
                    },
                    OnAuthenticationFailed = ctx =>
                    {
                        Console.WriteLine("Exception:{0}", ctx.Exception.Message);
                        return Task.CompletedTask;
                    }
                };
            });;
            services.AddPiranhaApi();`

AccountController.cs

`using System;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Piranha.Models;
using Piranha.AspNetCore.Identity.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Configuration;

namespace inSightBlog.Controllers
{
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    [ApiController]
    public class AccountController : ControllerBase
    {
        private readonly UserManager<Piranha.AspNetCore.Identity.Data.User> _userManager;
        private readonly SignInManager<Piranha.AspNetCore.Identity.Data.User> _signInManager;
        private readonly ILogger _logger;
        private readonly IConfiguration _configuration;

        public AccountController(
          UserManager<Piranha.AspNetCore.Identity.Data.User> userManager,
          SignInManager<Piranha.AspNetCore.Identity.Data.User> signInManager,

          ILogger<AccountController> logger, IConfiguration configuration)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _configuration = configuration;
        }

        [HttpGet]
        [Route("api/account/getvalue")]
        [Produces("application/json")]
        public ActionResult GetValue()
        {
            //TODO: User bilgilerine erişim
            /*var e = User.Identity.Name;
            var c = _userManager.GetUserAsync(HttpContext.User);
            var user = _userManager.FindByIdAsync(b);*/
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var cd = _userManager.Users.FirstOrDefault(u => u.Id.ToString() == userId);
            return Ok(cd);
        }
        public class userVm{
            public string UserName {get; set;}
            public string Password {get; set;}
        }
        [HttpPost]
        [AllowAnonymous]
        [Route("api/account/token")]
        public async Task<ActionResult> Token([FromBody]userVm model)
        {
            var result = await _signInManager.PasswordSignInAsync(model.UserName, model.Password, false, lockoutOnFailure: false);
            if (result.Succeeded)
            {
                var appUser = _userManager.Users.SingleOrDefault(r => r.UserName == model.UserName);
                var token_ = GenerateToken(model.Email, appUser);
                return Ok(token_);
            }
            throw new ApplicationException("INVALID_LOGIN_ATTEMPT");
        }
        private string GenerateToken(string userName, Piranha.AspNetCore.Identity.Data.User user)
        {
            var someClaims = new Claim[]{
                new Claim(JwtRegisteredClaimNames.UniqueName,userName),
                new Claim(JwtRegisteredClaimNames.Email,user.Email),
                new Claim(ClaimTypes.NameIdentifier,user.Id.ToString()),
                new Claim(JwtRegisteredClaimNames.NameId,Guid.NewGuid().ToString())
            };

            SecurityKey securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("xxxxxxxxxxxxx"));
            var token = new JwtSecurityToken(
                issuer: ""app.erdem",
                audience: "app.erdem",
                claims: someClaims,
                expires: DateTime.Now.AddDays(365),
                signingCredentials: new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256)
            );

            return new JwtSecurityTokenHandler().WriteToken(token);
        }
    }
}`
