### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by j209** [PiranhaCMS/piranha.core#962]
Hi
Does piranha support rtl cultures(arabic,hebr,...)?
And can we extend piranha with [blazor](https://github.com/aspnet/Blazor) ?

**Comment by tidyui** [comment]
The only part of Piranha that is written for western languages is the slug generation, but this can easily be customized in your application to work just the way you need it to. In regards to Blazor, the core of Piranha is just a NetStandard Api that can be used by any framework, you can even use it as a headless CMS and just get the content from an WebApi. The manager interface however is an ASP.NET Core application and needs to run on a web server.

Regards
