### ISSUE TITLE
Tag / Catagory Filter using empty slug for startpage

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core#968]
I am using an "empty" slug for the startpage to generate the canonical url correctly without the need to check, if it is the startpage.
 As i want to setup a very simple bog with startpage as the only archive, but supporting tag filtering and category filtering i am unable to make it working by default. I have checked the integrated middleware class and the middleware is unable to find the page because the segments array is not empty, but there is no slug matching. because "/" is not checked.

Well, i just need an advice what could be the correct strategy ... 

1) define a second page "search", but load the archive from the startpage
2) define a slug for the startpage but render slug depending on the startpage flag (needs to be copied to my model)
3) define parameter as query strings instead of url segement

Thanks for any feedback.

**Comment by tidyui** [comment]
Hi there! As you’ve noticed the archive routing does not work with an empty slug. If you for example look at the blog template which has the archive as it’s start page you can see that the default route for the unfiltered archive is:

    /

When filters are applied, the slug of the archive is used, ie:

    /blog/category/...

Here, blog is just the slug of the archive, so you could name it any way you want, for example “search”.

Regards

**Comment by rengert** [comment]
Thanks for the quick response, exactly what i mentioned.
The solution is working, but this would change the urls of the posts.
Ok, i think i can live with it. Many thanks.
