### ISSUE TITLE
upgrade from 7 to 8

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core#970]
what we need to upgrade to 8 without loosing content ?

**Comment by tidyui** [comment]
If you’re using SQLServer, MySQL or PostgreSQL there shouldn’t be any problem. If you’re using SQLite for production we are as lost as you are as Microsoft has changed the underlying components and databases doesn’t seem to be compatible.

Regards

**Comment by haidersafaa** [comment]
thanks it very helpful

**Comment by tidyui** [comment]
Any more questions on this, or can I close the issue?

**Comment by haidersafaa** [comment]
thank a lot
