### ISSUE TITLE
Manager page is getting 404 error

### ISSUE THREAD

**Issue by recepyahyazade** [PiranhaCMS/piranha.core#971]
I cloned latest master branch and set  startup "examples/MvcWeb" project as default and run project.

Project is running on localhost:5000.

When I write url localhost:5000/manager or localhost:5000/manager/login or localhost:5000/admin, I am getting 404 error. What is the manager URL or what I am missing?

I am using VS 19 latest version. And I did not change any line of code.

![image](https://user-images.githubusercontent.com/44996593/71750943-05271280-2e8b-11ea-9664-fc3556e9aaa0.png)

**Comment by tidyui** [comment]
Hi there @recepyahyazade It's not reproducible in my environment, but on the other hand I'm running `VS Code` on Mac. Maybe you can verify if it works by running it from the command line first. Open your command prompt, navigate to the folder and type:

~~~ bash
dotnet build
dotnet run
~~~

When the application is running, go to `http://localhost:5000/manager`.

@filipjansson could you try it on your machine running `VS 2019`?

**Comment by recepyahyazade** [comment]
Yes, i also tried command line running. This very wierd case :) I have been trying to run manager since 2 days but no luck. I cant find any solution.

**Comment by tidyui** [comment]
Well I doubt that @filipjansson will be able to reproduce the issue, and given the fact that no one has ever reported this issue it has to be something to something on your local machine.

The best way is if you start the application from the command prompt, when it’s started, make a number or line breaks in the console so you can easily find the start of the request. Then access the manager in your browser and copy the output from your command prompt here. Also open the inspector in your browser and check if you get any redirects, server errors or just a plain 404.

Regards

**Comment by recepyahyazade** [comment]
CMD output:

![image](https://user-images.githubusercontent.com/44996593/71763882-574f4e80-2ef2-11ea-99f7-dc0df8e3f161.png)

Chrome console:

![image](https://user-images.githubusercontent.com/44996593/71763888-70f09600-2ef2-11ea-816e-af88ce8756ba.png)

**Comment by recepyahyazade** [comment]
After two days later, it is working now, without no change. 

Actually I changed some of .csproj that include `Microsoft.AspNetCore.App` and revert them and rebuild all projects and now it is working. 
Sorry for your time. But I still dont understand the reason.

**Comment by tidyui** [comment]
Well given the screenshots it wasn’t hitting the manager area at all, like the routing hasn’t been mapped

**Comment by maartendebal** [comment]
I have the same issue. Changing the run configuration to x64 for all projects fixed it.

**Comment by thientd87** [comment]
I get this error when running project first time. Anyone can help?
<img width="885" alt="Screen Shot 2022-03-03 at 11 11 10 AM" src="https://user-images.githubusercontent.com/7514574/156494884-c4d68587-959e-4097-b57c-8d72881ca67a.png">

**Comment by thientd87** [comment]
> Looks like the database is completely empty and doesn’t contain any sites, which is weird as there should always be a default site seeded in the database.

@tidyui : I create another issue here for more detail. There is data in DB. i debuged.
https://github.com/PiranhaCMS/piranha.core/issues/1833
