### ISSUE TITLE
viewing child page in the header

### ISSUE THREAD

**Issue by ulfetalhussaini** [PiranhaCMS/piranha.core#973]
Hi..
how can i view child page(about me) inside the dropdown menu when i click on the parent page (blog) in the header  ?

![a](https://user-images.githubusercontent.com/38277711/72055069-35334300-32db-11ea-99cc-42aa368b42a3.jpg)

**Comment by tidyui** [comment]
The default templates doesn't have any built in support for dropdown menus so you'll have to add it in your application. All our templates use Bootstrap 4, so the latest documentation applies: https://getbootstrap.com/docs/4.4/getting-started/introduction/

Apart from that, When using Dropdown menus I personally don't think it's a good idea to have content on the root node as navigation tends to get messy and complicated if the item should both expand on click and navigate on click. Also, for clarity I also personally think it's good practice to **not** have the start page as a dropdown, instead add dropdown pages to the siblings.

Best regards

**Comment by tidyui** [comment]
Hi again @ulfetalhussaini Did I understand your question correctly? Do you need more information or can we close this issue?

**Comment by ulfetalhussaini** [comment]
yes, you can close it.
the solution in  #816 issue was helpful to me.
thankyou.

    <ul class="justify-content-center navbar-nav mr-auto">
                @foreach (var item in WebApp.Site.Sitemap)
                {
                    if (!item.IsHidden && item.Items.Count == 0)
                    {
                        <li class="nav-item  @(item.Id == WebApp.PageId ? "active" : "")">
                            <a class="" href="@item.Permalink">@item.MenuTitle</a>
                        </li>
                    }

                    if (!item.IsHidden && item.Items.Count >= 1)
                    {
                        <li class="nav-item dropdown  @(item.Id == WebApp.PageId || item.HasChild(WebApp.PageId) ? "active" : "")">
                            <a class="" data-toggle="dropdown" href="@item.Permalink">@item.MenuTitle</a>
                            <ul class="dropdown-menu" >
                                @foreach (var subitem in item.Items)
                                {
                                    <a href="@subitem.Permalink">@subitem.MenuTitle</a>

                                }
                            </ul>
                        </li>

                    }
                }
            </ul>
