### ISSUE TITLE
Doubt adding new posts

### ISSUE THREAD

**Issue by rodolfoduarte** [PiranhaCMS/piranha.core#974]
Hello,

When adding posts,
How can I add a dynamic table with data from my database?

Any idea?

I can do it in static pages, but I dont know how to do in post.cshtml.

That's my future blog: http://rodolfoduarte-002-site7.ftempurl.com/

Great job anyway! Thanks in advance.

Rodolfo Duarte

**Comment by tidyui** [comment]
Hi there. You need to clarify a bit, are you talking about:

1. How you should render your Archive page according to the provided example?
2. How you add custom data to your post that is not in the CMS?
3. How you enable a HTML Table Editor in the WYSIWYG editor?

Best regards

**Comment by rodolfoduarte** [comment]
The archive page is fine, that's what I want.
My posting pages are an example of hard code that I added directly to the post.cshtml file.
I have some data in a table from my database, I want to add this data to the posting pages as a table. The data can be changed on the database and it should sync with the posting dinamicaly.

Sorry about my english,

I hope you got it

Thanks in advance

**Comment by rodolfoduarte** [comment]
> 
> 
> Hi there. You need to clarify a bit, are you talking about:
> 
>     1. How you should render your Archive page according to the provided example?
> 
>     2. How you add custom data to your post that is not in the CMS?
> 
>     3. How you enable a HTML Table Editor in the WYSIWYG editor?
> 
> 
> Best regards

Do you work as freelancer sometimes? It would be a pleasure if you make a litle customization on my project.

**Comment by tidyui** [comment]
Sorry for the late response. Do you need more input on this issue? Regarding your last question I don't have the time to do freelance work, all consultancy I do at my day time job at [byBrick](https://www.bybrick.se/interface-en/home/).

Best regards
