### ISSUE TITLE
add Regions show it in manager

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core#978]
hi   thanks for your great work 
i need to add header and footer Regions should only i add it to template (as i see in documents ) or should add code to manager 
what the step by step way to made this goal 
regards

**Comment by tidyui** [comment]
Hi there! If you are referring to site header & footer the recommendation is that you add these into a `SiteType`. Take a look at the docs here, and if it's unclear, please add an issue to the documentation so we can improve it, this way it's beneficial for everyone!

http://piranhacms.org/docs/content/sites

**Comment by r4g-jon** [comment]
Hi @tidyui 

I was thinking it might be worth adding a FAQs to the documentation with some examples on how to create things like footers. I've got a few code snippets and can type them up if you like? It might also be worth thinking about a forum too?

Thanks
Jon

**Comment by tidyui** [comment]
Examples and additions to the documentation is always appreciated! You can find the source files for the Docs in this repo:

https://github.com/PiranhaCMS/piranha.core.docs

I'll move this issue there and reopen it for reference.

Regards
