### ISSUE TITLE
Tag issues with different versions

### ISSUE THREAD

**Issue by wiruzman** [PiranhaCMS/piranha.core#988]
I think it would be nice to tag different issues with version numbers to see if the issue is related to the issues others have. Sometimes you can get some knowledge just reading the  issues and maybe out of date.

**Comment by tidyui** [comment]
You mean so you can see which version they were implemented/fixed in?

**Comment by tidyui** [comment]
Closing this as all implemented issues are in fact marked with both milestone and project when they were released.
