### ISSUE TITLE
Extension methods for PiranhaServiceBuilder in Piranha.AspNetCore.Identity

### ISSUE THREAD

**Issue by IvanTsel96** [PiranhaCMS/piranha.core#999]
Hi, guys. I have started using your CMS of version 8.0.2 and now I need to use my custom IdentitySeed to set default values in database. But I can not find extension method for PiranhaServiceBuilder. Now I am using your extension method for IServiceCollection. 

My question is why have not you created extension method for PiranhaServiceBuilder with two generic-arguments where one implements Db<T> and second implements IIdentitySeed?

**Comment by tidyui** [comment]
Like you say this extension method seems to be missing from the new `PiranhaServiceBuilder`, however it's still available directly on the `IServiceCollection`. Until it's added I suggest you remove identity from the options and add it outside of `AddPiranha`, like this:

~~~ csharp
services.AddPiranha(options =>
{
    // Don't add identity here
    // options.UseIdentityWithSeed<T>(...);
});

// Add identity directly on the IServiceCollection
services.AddPiranhaIdentityWithSeed<T, TSeed>(...);
~~~

Best regards

**Comment by IvanTsel96** [comment]
Perfect!
Yes, I am using this solution already.

Thanks for your fast answer.
